### ISSUE TITLE
how to specify a generated file in //go:embed directive so that the embedsrc section is automatically filled

### ISSUE THREAD

**Issue by asv** [bazelbuild/bazel-gazelle#1007]
### What version of gazelle are you using?

bazel-gezelle 0.23.0

### What version of rules_go are you using?

rules_go 0.26.0

### What version of Bazel are you using?

3.5.0

Thanks for the quick implementation of //go:embed support in rules_go / gazelle!

I have following question: how to specify a generated (by another bazel rule) file in the // go:embed directive so that the embedsrc section is automatically generated? When trying to just specify the target name, gazelle prints error **pattern incidents_list.html: matched no files**.

**Comment by asv** [comment]
hmm, I added a **visibility** attribute to my targets that generate files and gazelle no longer fails. however the **embedsrc** section is not generated, and if added it is erased unless **# keep** is specified.

**Comment by asv** [comment]
a small example:

```golang
var (
	//go:embed incidents_list.html
	incidentsHTML     string
	incidentsTemplate *template.Template

	//go:embed settings.html
	settingsHTML     string
	settingsTemplate *template.Template
)
```

```starlark
load("//tools/mjml_runner:def.bzl", "mjml_compile")
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

mjml_compile(
    name = "incidents_list.html",
    src = "incidents-list.mjml",
    visibility = ["//visibility:public"],
)

mjml_compile(
    name = "settings.html",
    src = "settings.mjml",
    visibility = ["//visibility:public"],
)

go_library(
    name = "email",
    srcs = ["html.go"],
    embedsrcs = [
        ":incidents_list.html",  # keep
        ":settings.html",  # keep
    ],
    importpath = "scm.infinet.ru/nms/next/pkg/martin/templates/email",
    visibility = ["//visibility:public"],
)
```

**Comment by jayconrod** [comment]
Gazelle should be able to match embed patterns against files it knows about in the current Bazel package. Those include:

* Static files in the same directory.
* Static files in subdirectories that don't contain build files or .go files.
* Generated files mentioned in `out` or `outs` attributes of other targets in the build file.

These `mjml_compile` targets don't have `out` or `outs` attributes, so Gazelle doesn't know what files they'll produce since it doesn't evaluate Starlark.

I think the best way to handle this is exactly what you're doing: add the targets explicitly with a `# keep` directive.

**Comment by asv** [comment]
Thanks, Jay. I got it!

**Comment by echyam** [comment]
I have a similar situation: I have a bazel rule that generates a file (with an `out` attribute), so I have included it with `# keep`.  
When I run gazelle, it adds the generated file to `embedsrcs` and returns no errors, but when I run `bazel build ...`, it says 1 input file does not exist. Is there an extra step I'm missing?  Relevant code and output posted below.

versions:
go 1.16.2
io_bazel_rules_go v0.26.0
bazel_gazelle v0.23.0
bazel 3.7.0

```
// vars.go

//go:embed releases
var release_data embed.FS

//go:embed user-data.tpl
var user_data_templ string
```
```
// BUILD.bazel
load("@io_bazel_rules_go//go:def.bzl", "go_embed_data", "go_library", "go_test")
load("//user_data:rule.bzl", "user_data")

go_library(
    name = "go_default_library",
    srcs = [
        "manifest.go",
        ...
    ],
    embedsrcs = [
        "releases/*.yaml",
        "user-data.tpl",  # keep <-- this is the generated file
    ],
    visibility = ["//visibility:public"],
    deps = [... ],
)

user_data(
    name = "user_data_template",
    out = "user_data.tpl",
    ...
)
```
```
$ bazel run //:gazelle
INFO: Analyzed target //:gazelle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.983s, Critical Path: 0.73s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
```
```
$ bazel build --jobs 1 ...
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets...
ERROR: /xxx/pkg/release/BUILD.bazel:3:11: GoCompilePkg pkg/release/go_default_library.a failed (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src pkg/release/ami.go -src pkg/release/manifest.go -src pkg/release/release.go -src ... (remaining 59 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src pkg/release/ami.go -src pkg/release/manifest.go -src pkg/release/release.go -src ... (remaining 59 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: /xxx/.cache/bazel/_bazel_eyam/4a5bb56fefe178e87f0604296e5213be/sandbox/linux-sandbox/1490/execroot/__main__/pkg/release/release.go:10:12: could not embed user-data.tpl: no matching files found
INFO: Elapsed time: 1.014s, Critical Path: 0.74s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

**Comment by echyam** [comment]
For anyone who finds this, there was an issue with my custom bazel rule that it specified the output using `attr.string` instead of `attr.output`.  Workaround would be to either include the target `:user_data_templ` in `embedsrcs` or use `# keep` with the generated file and update the bazel rule to properly specify its output.
