### ISSUE TITLE
language/go: `embedsrcs` not being generated for nested directories

### ISSUE THREAD

**Issue by jacobfoard** [bazelbuild/bazel-gazelle#1013]
### What version of gazelle are you using?
0.23.0

### What version of rules_go are you using?
0.26.0

### What version of Bazel are you using?

4.0.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
macOS 11.2.3 amd64

### What did you do?

Given this small files as `main.go`

```go
package main

import (
	"embed"
	"fmt"
	"io"
)

//go:embed config/*
var config embed.FS

func main() {
	reader, err := config.Open("config/config.yaml")
	if err != nil {
		panic(err)
	}

	bytes, err := io.ReadAll(reader)
	if err != nil {
		panic(err)
	}

	fmt.Println(string(bytes))
}
```

and with this as `config/config.yaml`

```yaml
dev: true
```

running `go run main.go` properly prints out: `dev: true` as one would expect.

But when trying to use gazelle to generate a BUILD file `gazelle -repo_root . -go_prefix github.com/jacobfoard/demo` it prints out `gazelle: /Users/jacobfoard/go/src/github.com/jacobfoard/demo/main.go:9:2: pattern config/*: matched no files`

and generates this BUILD file

```bazel
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "demo_lib",
    srcs = ["main.go"],
    importpath = "github.com/jacobfoard/demo",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "demo",
    embed = [":demo_lib"],
    visibility = ["//visibility:public"],
)
```

### What did you expect to see?
I would expect the yaml file to be added into `embedsrcs`

```bazel
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "demo_lib",
    srcs = ["main.go"],
    embedsrcs = ["config/config.yaml"],
    importpath = "github.com/jacobfoard/demo",
    visibility = ["//visibility:private"],
)

go_binary(
    name = "demo",
    embed = [":demo_lib"],
    visibility = ["//visibility:public"],
)
```

I was able to generate the file above by modifying the check for `matched` in the [embedResolver](https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/embed.go#L166-L169)
```go 
for i < len(er.files) {
	p := er.files[i].path

	if er.files[i].isDir {
		p += "/"
	}

	matched, _ := path.Match(embed.path, p)
	advance(matched)
}
```

**Comment by jayconrod** [comment]
Took a quick look at this but didn't have time to fix it today.

It's more complicated than just adding a slash to the directory. The `advance` function skips an entire directory if the directory itself doesn't match. It should walk through the contents of the directory, too.

**Comment by jacobfoard** [comment]
I figured as much, which is why I didn't open a PR with the simple fix. Thanks for looking into it!
