### ISSUE TITLE
Gazelle attempts to download host workspace when Bazel symlink_prefix is set

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/bazel-gazelle#1017]
### What version of gazelle are you using?

v0.23.0

### What version of rules_go are you using?

v0.27.0

### What version of Bazel are you using?

4.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

I ran gazelle with no args.

### What did you expect to see?

I expected gazelle to update all BUILD files.

### What did you see instead?

Gazelle errors and tries to download the module listed in gazelle:prefix for every file import.

```
gazelle: finding module path for import github.com/simple-circle/simc/erp: 
go: downloading github.com/simple-circle/simc v0.0.0-20210321083719-16fa07b8a3e6
go get github.com/simple-circle/simc/erp: github.com/simple-circle/simc@v0.0.0-20210321083719-16fa07b8a3e6: 
verifying module: github.com/simple-circle/simc@v0.0.0-20210321083719-16fa07b8a3e6: 
reading https://sum.golang.org/lookup/github.com/simple-circle/simc@v0.0.0-20210321083719-16fa07b8a3e6: 
        410 Gone
	server response:
	not found: github.com/simple-circle/simc@v0.0.0-20210321083719-16fa07b8a3e6: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/gopath/pkg/mod/cache/vcs/fbc9dd191b3049772f5fcb0588392007dcb95eab8b664b148a9ec316b09b0860: exit status 128:
		fatal: could not read Username for 'https://github.com': terminal prompts disabled


gazelle: finding module path for import github.com/simple-circle/simc/base/db/pg_test: 
go: downloading github.com/simple-circle/simc v0.0.0-20210321083719-16fa07b8a3e6
go get github.com/simple-circle/simc/base/db/pg_test: github.com/simple-circle/simc@v0.0.0-20210321083719-16fa07b8a3e6: 
verifying module: github.com/simple-circle/simc@v0.0.0-20210321083719-16fa07b8a3e6: 
reading https://sum.golang.org/lookup/github.com/simple-circle/simc@v0.0.0-20210321083719-16fa07b8a3e6: 
        410 Gone
	server response:
	not found: github.com/simple-circle/simc@v0.0.0-20210321083719-16fa07b8a3e6:
invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /tmp/gopath/pkg/mod/cache/vcs/fbc9dd191b3049772f5fcb0588392007dcb95eab8b664b148a9ec316b09b0860: 
exit status 128:
		fatal: could not read Username for 'https://github.com': terminal prompts disabled

<continues for every import>
```

After `bazel clean --expunge`, gazelle worked again.

**Comment by jschaf** [comment]
After running all tests in the repo, gazelle fails again with the same error. Running `bazel clean` is enough to fix gazelle.

**Comment by jschaf** [comment]
Root cause was these two lines in `.bazelrc`

```
build --symlink_prefix=dist/
build --experimental_no_product_name_out_symlink
```

Removing those config lines allows gazelle to run successfully. I'll leave it open to decide how you'd like to handle this bug.

**Comment by jayconrod** [comment]
It sounds like what's happening here is with these options, Bazel's symbolic links don't start with the "bazel-" prefix. Gazelle looks for that prefix and avoids visiting those directories.

I don't think it's feasible for Gazelle to interpret bazelrc files, so I'll close this issue.

As a workaround, you can use a directive like `# gazelle:exclude dist` to skip those directories explicitly.
