### ISSUE TITLE
Building bazel-gazelle from source failing: no such package @com_github_google_go_cmp//cmp

### ISSUE THREAD

**Issue by Michaelhobo** [bazelbuild/bazel-gazelle#1020]
### What version of gazelle are you using?

n/a

### What version of rules_go are you using?

0.27.0

### What version of Bazel are you using?

4.0.0

### What operating system and processor architecture are you using?

WLinux (WSL on Windows 10), x86-64

### What did you do?

Cloned a fresh bazel-gazelle repo, and the test `//walk:walk_test` passes. I made a few seemingly-harmless changes in https://github.com/bazelbuild/bazel-gazelle/compare/master...Michaelhobo:bazelignore 

Now, `bazelisk test //walk:walk_test` fails with ` BUILD file not found in directory 'cmp' of external repository @com_github_google_go_cmp. Add a BUILD file to a directory to mark it as a package. and referenced by '//testtools:testtools'`

### What did you expect to see?

Some bazel test output

### What did you see instead?

```bash
~/repos/bazel-gazelle$ bazelisk test //walk:walk_test
ERROR: /home/michaelhobo/repos/bazel-gazelle/testtools/BUILD.bazel:3:11: no such package '@com_github_google_go_cmp//cmp': BUILD file not found in directory 'cmp' of external repository @com_github_google_go_cmp. Add a BUILD file to a directory to mark it as a package. and referenced by '//testtools:testtools'
ERROR: Analysis of target '//walk:walk_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.230s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by jayconrod** [comment]
I can confirm Gazelle builds from source at `master` (`5b8616dbb7dad825c61ffbb12ea9f75622568657`) on macOS amd64.

Does it build without your change? Gazelle is used to generate build files in its own `go_repository` dependencies, so if a bug prevents it from generating build files, you'd see this message.

Does it build using regular Bazel, not Bazelisk? I wouldn't expect that to make a difference, but maybe.

Is this specific to WLinux?

**Comment by Michaelhobo** [comment]
Yea, it builds and passes test on master for me too, so I don't believe it's WLinux-specific.

My changes touch //walk and //walk_test, and don't have any BUILD file changes (only imports changed are go standard library imports). Yet, bazel build //testtools passes on master, and fails on my change, which I rebased on master. What could be causing that?

My change is stacked right on top of master:

```bash
$ git log
commit 6c45824b37c09a713b95aef6809e404494f89202 (HEAD -> bazelignore, origin/bazelignore)
Author: Michaelhobo <callmemikeh@gmail.com>
Date:   Fri Dec 25 02:59:50 2020 +0000

    Respect .bazelignore

commit 5b8616dbb7dad825c61ffbb12ea9f75622568657 (bazelbuild/master, master)
Author: Jay Conrod <jayconrod@google.com>
Date:   Fri Mar 19 17:59:43 2021 -0400

    language/go: don't let 'go mod download' edit go.sum (#1015)
```

bazelisk (version=4.0.0) and system bazel (version=3.4.1) both fail.

**Comment by Michaelhobo** [comment]
| Does it build without your change? Gazelle is used to generate build files in its own go_repository dependencies, so if a bug prevents it from generating build files, you'd see this message.

Oh, after reading your comment a bit more, I think I understand what you mean. It seems like Gazelle is being run during a bazel build - that's the part I didn't realize. I started commenting out different things in my change, and I'm getting different errors that actually point to my code now.
