### ISSUE TITLE
Add -print0 to make gazelle scripting friendly

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel-gazelle#1028]
### What version of gazelle are you using?

v0.22.2

### What version of rules_go are you using?

v0.24.7

### What version of Bazel are you using?

4.0

### What did you expect to see?

We would love to use gazelle in pre-commit-hook to update build files automatically. When doing so, we need to know which build file is rewritten and needs to be added to the staging area for committing.

We propose to add `-print0` flag for `-mode=fix`. When set, let gazelle print the names of rewritten files separated with '\0' (like other Unix tools,) then the output could be piped to `xargs -r0 git add`.

**Comment by jayconrod** [comment]
Sorry to take so long to get to this.

In general, I'm hesitant to expand the user interface of Gazelle; none of the maintainers have much bandwidth to support new features.

Is there another way this problem can be solved? What about using `-mode=diff`, then applying that patch?

**Comment by ashi009** [comment]
> Sorry to take so long to get to this.
> 
> 
> 
> In general, I'm hesitant to expand the user interface of Gazelle; none of the maintainers have much bandwidth to support new features.
> 
> 
> 
> Is there another way this problem can be solved? What about using `-mode=diff`, then applying that patch?

Already tried, but it's not working well with git. 

The patch gazelle generated is not acceptable by `git apply`, which assumes `git diff` generates that. Hence, after applying it with `patch` I still need to find a way to get the list of changed files. So back to square one.

I already have a 10-line-ish patch for this. But still waiting for the CLA approval to upload it.
