### ISSUE TITLE
fix up "the importpath attribute on go_binary is deprecated"

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel-gazelle#103]
It would be cool if gazelle could fix up the deprecation warning "importpath attribute on go_binary is deprecated".

**Comment by jmhodges** [comment]
Oh, this seems to be that gazelle needs to fix this up on `go_test` calls, too, but the deprecation warnings on those say "go_binary" in their text, too (for obvious reasons).

**Comment by jayconrod** [comment]
Thanks for reminding me about this. Was waiting until after rules_go 0.9.0 and gazelle 0.9 were both tagged. Now that that's happened, this should be an easy fix.

**Comment by jmhodges** [comment]
Thanks!
