### ISSUE TITLE
go_repository "replace" parameter doesn't work as expected

### ISSUE THREAD

**Issue by Nickersoft** [bazelbuild/bazel-gazelle#1045]
### What version of gazelle are you using?
0.23.0

### What version of rules_go are you using?
0.27.0

### What version of Bazel are you using?
4.0.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
macOS Catalina, Intel Core i9

### What did you do?
Recently, my project [ODict](https://github.com/TheOpenDictionary/odict) has begun failing because a transitive dependency of the Bleve Go library, `github.com/willf/bitset`, has been renamed to `github.com/bits-and-blooms/bitset` and Gazelle doesn't add this library as a dependency in the BUILD file it generates. So I added the following to the `go_repository` definition for the repo:

```python
    maybe(
        go_repository,
        name = "com_github_bits_and_blooms_bitset",
        importpath = "github.com/willf/bitset",
        replace = "github.com/bits-and-blooms/bitset",
        sum = "h1:NotGKqX0KwQ72NUzqrjZq5ipPNDQex9lo3WpaS8L2sc=",
        version = "v1.1.10",
    )
```

### What did you expect to see?
I expected the path to resolve, the dependency to be added, and my project to build.

### What did you see instead?
I continued to receive:

```
        /private/var/tmp/_bazel_tnickerson/0019a6bf008320198a79ef1cd374261c/sandbox/darwin-sandbox/286/execroot/odict/external/com_github_couchbase_vellum/fst.go: import of "github.com/willf/bitset"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
```

The generated BUILD file does not include this dependency, despite `github.com/willf/bitset` being import by `fst.go`:

```
go_library(
    name = "vellum",
    srcs = [
        "automaton.go",
        "builder.go",
        "common.go",
        "decoder_v1.go",
        "encoder_v1.go",
        "encoding.go",
        "fst.go",
        "fst_iterator.go",
        "merge_iterator.go",
        "pack.go",
        "registry.go",
        "transducer.go",
        "vellum.go",
        "vellum_mmap.go",
        "writer.go",
    ],
    importpath = "github.com/couchbase/vellum",
    visibility = ["//visibility:public"],
    deps = ["@com_github_blevesearch_mmap_go//:go_default_library"],
)
```

Interestingly enough, this error goes away when I don't use `maybe`, but I need to because I have other Bazel projects that use this repo and want to prevent duplicate rule definitions. Even when I don't use `maybe`, the build passes for ODict but the failures continue when building ODict from other Bazel projects.

**Comment by robfig** [comment]
I think Gazelle notices `go_repository` declarations and indexes them. Try the `# gazelle:repository` WORKSPACE directive to directly inform it. 

(Search for details on the README: https://github.com/bazelbuild/bazel-gazelle/) 

Please reopen if you're still having difficulty. Thanks
