### ISSUE TITLE
Proposal: Move expression merging into an interface

### ISSUE THREAD

**Issue by eric-skydio** [bazelbuild/bazel-gazelle#1072]
# Context
For an internal custom Gazelle plugin, we recently wanted to have Gazelle merge dicts with string key and value pairs. Unfortunately, Gazelle doesn't understand those today, and there is no way for us as an plugin author to provide custom merging/sorting logic for this case. Looking through the codebase, it's clear that even adding that capability internally would require a pretty significant amount of modification to many parts of the code, because there's no clear abstraction layer for the concept of merging a field. #1063 is a result of similar pains around controlling sorting, #1036/#1037 for merging of glob expressions, and #1051 around PlatformStrings with custom keys. I'm sure I would find more if I looked past the first page of issues.

This proposal aims to introduce a new interface for custom merging and sorting behavior that can be used _both_ by internal Gazelle functionality (like PlatformStrings) _and_ by external rule authors who want custom behavior.

# Proposal
This proposal defines a new interface
```go
interface Merger{
	Merge(other bzl.Expr) bzl.Expr
}
```

When `Merge` is invoked, it is responsible for returning a Starlark expression that contains the result of merging its data into the previously-existing expression provided as `other`. Note that `other` can be nil, if no previous attr with this name existed.

While anyone is free to implement this interface, Gazelle itself would provide three implementations encapsulating _current_ merging behavior.

```go
type SortedStrings []string
type UnsortedStrings []string
type go.PlatformStrings ...
```

For compatibility with existing behavior, `rule.SetAttr(...)` will, if provided with a `[]string`, immediately convert it into a `SortedStrings` or `UnsortedStrings` based on the name of the attr, following current rules. The go plugin will continue to explicitly provide `PlatformStrings` to `SetAttr`.

At the time rules are merged, any attr that is marked as mergeable _must_ implement the `Merger` interface, and merging the attr will simply be done by invoking that function, which is responsible for handling `#keep` comments. No later sorting will be performed, nor will Gazelle ever parse or care about the contents of the returned `bzl.Expr`.

A few use cases:
1. A plugin that wants to sort the merged lists for some attribute, even if it's not named "srcs" or "deps", can immediately do so by simply casting to a `SortedStrings` before calling `SetAttr()`
2. A plugin that wants to work with string lists, but wants different/custom sorting logic can implement their own version of SortedStrings on top of UnsortedStrings.
3. A plugin that wants to work with some other Skylark construct (dicts, lists of numbers, lists of tuples, etc) can implement a Merger and pass that object to SetAttr. If other plugins want the same functionality, it can be upstreamed to Gazelle itself.

I may or may not have the time to implement this, but wanted consensus on the direction before submitting a PR.

**Comment by eric-skydio** [comment]
Pinging @jayconrod for design feedback, I'm willing to sink some implementation effort into this but want a :+1: first.

**Comment by linzhp** [comment]
> At the time rules are merged, any attr that is marked as mergeable must implement the Merger interface

Does this mean all existing plugins that define rules with mergeable attributes need to be updated?

**Comment by eric-skydio** [comment]
No,  since SetAttr would automatically handle PlatformStrings and []string by converting them to the new internal mergeable representations. Since those are the only types currently merged, that should cover all existing code.

**Comment by linzhp** [comment]
The desgin looks good to me. I can review your pull request

**Comment by eric-skydio** [comment]
As a revision, it may make sense to instead perform that fallback at the time of rule merging rather than when `SetAttr` is called, to more closely match existing behavior.

**Comment by com6056** [comment]
@eric-skydio did you happen to get a PR going for this feature? would love to have this, I also have a need to support merging selects outside of just platforms
