### ISSUE TITLE
label.Parse fails on labels with hyphens in the repository name

### ISSUE THREAD

**Issue by facundominguez** [bazelbuild/bazel-gazelle#1082]
### What version of gazelle are you using?

v0.23.0

### What version of rules_go are you using?

v0.27.0

### What version of Bazel are you using?

4.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

nixos x86_64

### What did you do?

```go
lbl, err := label.Parse("@stackage-exe//tasty-discover:tasty-discover")
if err != nil {
    log.Fatal(err)
}
```

### What did you expect to see?

I expected the label to be parsed since hyphens are accepted in repository names by bazel. 
https://github.com/bazelbuild/bazel/issues/11837
https://github.com/bazelbuild/bazel/commit/e574d558da17cfd0f818e7a937a07926aa270069

### What did you see instead?

```
gazelle: label parse error: repository has invalid characters: "@stackage-exe//tasty-discover:tasty-discover"
```

**Comment by robfig** [comment]
Thanks for the issue report. I believe this can resolved by a simple change to //label/label.go. Are you interested in putting up a PR?

**Comment by facundominguez** [comment]
I have a workaround that is good enough for my use case, but I offer to test a newer bazel-gazelle when there is fix.
