### ISSUE TITLE
Extra `data = glob("testdata/**")` added even if testdata is not used

### ISSUE THREAD

**Issue by rHermes** [bazelbuild/bazel-gazelle#1116]
### What version of gazelle are you using?
v0.24.0

### What version of rules_go are you using?
v0.29.0

### What version of Bazel are you using?
4.2.1

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

I have a directory with a `testdata` in it, which is only used through Go's `embed` functionality. Gazelle adds a `data = glob("testdata/**")` to the `go_test` rule, thinking that I need the files at runtime, but I do not, as they are all listed in the
`embededsrcs` directive.

### What did you expect to see?
As I don't use `testdata` for anything, I expected it to not appear as a `data` directive.

### What did you see instead?
It appears

### EXTRA

I see that this is done at: https://github.com/bazelbuild/bazel-gazelle/blob/3ea1d64d6fe943dac06c341f9a265472bb99acd7/language/go/generate.go#L531 but I'm unsure of it should be added that if a embeded directive covers all the posibilities, it should be removed? Or a directive can be created that would allow it to be ignored?

**Comment by rHermes** [comment]
There is no problem in including it, I just thought it would be a strong indication if the testdata directory was embeded. I'm not to familiar with bazel, so I don't know if there is any overhead to copying the testdata into the test containers?

**Comment by robfig** [comment]
These rules do not produce any containers, so those details would depend on how you generate them. If you include the "runfiles", then it would have to copy data files which it would not otherwise copy, which would be overhead. But probably it's not substantial, unless your test data has very many files or is very large. If you put only the binary into the container, then there should be no impact at all.

**Comment by peter-cardenas-ai** [comment]
maybe instead we could configure a way to disable this behavior? imo it seems confusing that we add it as a data dependency but it's actually not used, especially when gazelle is meant to keep the srcs and deps clean and up to date.

**Comment by peter-cardenas-ai** [comment]
another strange thing is that this happens with `-index=lazy` and `-r=false` but not with `-index=true` and `-r=true` (default)
