### ISSUE TITLE
Unable to build go package that links static .a archive

### ISSUE THREAD

**Issue by glukasiknuro** [bazelbuild/bazel-gazelle#1120]
### What version of gazelle are you using?
0.24.0

### What version of rules_go are you using?
0.29.0

### What version of Bazel are you using?
4.2.0

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Linux, amd64

### What did you do?
Repro: https://github.com/glukasiknuro/gazelle-gozstd-issue

Reproduction steps are described in README in above repo, in short:

This is a simple binary that imports `github.com/valyala/gozstd`

Using gazelle to generate go_repository and then building binary with bazel finishes with an error:
```
gcc: error: ./libzstd_linux_amd64.a: No such file or directory
```

Workaround seems to be to statically create BUILD file to properly include `.a` file: https://github.com/glukasiknuro/gazelle-gozstd-issue/blob/master/external/gozstd.patch

The go files contain those stanzas, but looks like those files are not included in dependencies of `go_library` so cannot be found during linking: https://github.com/valyala/gozstd/blob/master/libzstd_linux_amd64.go#L6
```
#cgo LDFLAGS: ${SRCDIR}/libzstd_linux_amd64.a
```

### Question
What's the recommended way going forward here?
- Supporting such use cases in bazel-gazelle
- Using patch whenever this library is needed
- Checking BUILD file into the zsd library

Found somewhat similar issue reported for `confluent-kafka-go`: https://github.com/bazelbuild/bazel-gazelle/issues/773

**Comment by robfig** [comment]
Copying the resolution from the Bazel Slack (https://bazelbuild.slack.com/archives/C01HMGN77Q8/p1641343903028700):

Generally Gazelle will only work with cgo if everything is in the same directory. I had this problem  with imagick - you can see a working build here: https://github.com/yext/imagick/commit/7827fa8f4380225e8aad21bf1c7ac81ebbab40f7

A reproducer was here: https://github.com/bduffany/gozstd/tree/bazelify, and it was solved by this general BUILD approach:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

cc_library(
    name = "libzstd",
    srcs = select({
        "@io_bazel_rules_go//go/platform:android_amd64": ["libzstd_linux_amd64.a"],
        "@io_bazel_rules_go//go/platform:android_arm": ["libzstd_linux_arm.a"],
        "@io_bazel_rules_go//go/platform:android_arm64": ["libzstd_linux_arm64.a"],
        "@io_bazel_rules_go//go/platform:darwin_amd64": ["libzstd_darwin_amd64.a"],
        "@io_bazel_rules_go//go/platform:darwin_arm64": ["libzstd_darwin_arm64.a"],
        "@io_bazel_rules_go//go/platform:freebsd_amd64": ["libzstd_freebsd_amd64.a"],
        "@io_bazel_rules_go//go/platform:ios_amd64": ["libzstd_darwin_amd64.a"],
        "@io_bazel_rules_go//go/platform:ios_arm64": ["libzstd_darwin_arm64.a"],
        "@io_bazel_rules_go//go/platform:linux_amd64": ["libzstd_linux_amd64.a"],
        "@io_bazel_rules_go//go/platform:linux_arm": ["libzstd_linux_arm.a"],
        "@io_bazel_rules_go//go/platform:linux_arm64": ["libzstd_linux_arm64.a"],
        "@io_bazel_rules_go//go/platform:windows_amd64": ["libzstd_windows_amd64.a"],
        "//conditions:default": ["UNSUPPORTED_PLATFORM"],
    }),
    hdrs = [
        "zdict.h",
        "zstd.h",
        "zstd_errors.h",
    ],
)

go_library(
    name = "gozstd",
    srcs = [
        "dict.go",
        "doc.go",
        "gozstd.go",
        "libzstd_darwin_amd64.go",
        "libzstd_darwin_arm64.go",
        "libzstd_freebsd_amd64.go",
        "libzstd_linux_amd64.go",
        "libzstd_linux_arm.go",
        "libzstd_linux_arm64.go",
        "libzstd_windows_amd64.go",
        "reader.go",
        "stream.go",
        "writer.go",
    ],
    cdeps = [":libzstd"],
    cgo = True,
    copts = ["-O3"],
    importpath = "github.com/valyala/gozstd",
    visibility = ["//visibility:public"],
)
```
