### ISSUE TITLE
embedsrcs ignores directories with BUILD files

### ISSUE THREAD

**Issue by uhthomas** [bazelbuild/bazel-gazelle#1133]
### What version of gazelle are you using?

v0.24.0

### What version of rules_go are you using?

v0.29.0

### What version of Bazel are you using?

4.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Tested on MacOS and Linux.

### What did you do?

Assuming the directory structure

```
cmd/something
├── BUILD.bazel
├── data
│   ├── BUILD.bazel
│   ├── something.txt
│   ├── some_other_thing
│   │   ├── some_other_thing.txt
└── main.go
```

and with `main.go`

```go
package main

import "embed"

//go:embed data
var content = embed.FS

func main() {}
```

Gazelle won't generate an `embedsrcs` for the "data" directory.

```sh
❯ bazel run //:gazelle
gazelle: cmd/something/main.go:5:2: pattern data: matched no files
```

### What did you expect to see?

`embedsrcs` should be generated.

### What did you see instead?

Gazelle doesn't generate `embedsrcs` for directories with BUILD files.

**Comment by andyliuliming** [comment]
we need this too.

**Comment by achew22** [comment]
I don't think this can actually be done automatically. By making the directory that you want to include have a `BUILD` file, bazel wouldn't be able to reach into the directory using something like `glob`. It would require synchronizing a `filegroup` or something in the inner directory which is not going to be something that's completely standardized between projects (some will want direct file enumeration vs `exports_files` vs `filegroup` vs custom type'd target, etc.). If you have a need for this, move the targets that you defined in `data` up a level into the `cmd/something/BUILD` file and then refer to the files in the inner directory as `data/something.txt`.

If you feel really strongly about this and would like to pick one of those implementations and contribute it as a patch, let's open another issue and discuss the way it would be done.

**Comment by uhthomas** [comment]
The new `subpackages` function may be helpful?

https://github.com/bazelbuild/bazel/pull/14780

Design doc: https://docs.google.com/document/d/13UOT0GoQofxDW40ILzH2sWpUOmuYy6QZ7CUmhej9vgk/edit#heading=h.5mcn15i0e1ch
