### ISSUE TITLE
error building com_github_prometheus_common: undefined types

### ISSUE THREAD

**Issue by amalucelli** [bazelbuild/bazel-gazelle#1140]
### What version of gazelle are you using?

`v0.24.0`

### What version of rules_go are you using?

`v0.29.0`

### What version of Bazel are you using?

`4.2.1`

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

- `linux/amd64`
- `darwin/adm64`

### What did you do?

Tried to upgrade `gazelle` to `v0.24.0` and `rules_go` to `v0.29.0`, but I'm getting an error when it tries to build the dependency `com_github_prometheus_common` in a `build` action for a `go_binary` or `go_image` target.

I found a similar issue described here https://github.com/bazelbuild/rules_go/issues/2998.

I think this is more related to `gazelle` than `rules_go` because if I try to use `gazelle` with `v0.23.0` everything works out, only when I use the latest I get this error.

Here is the `go_repository` that I have declared for that dependency:

```go
    go_repository(
        name = "com_github_prometheus_common",
        importpath = "github.com/prometheus/common",
        sum = "h1:RyRA7RzGXQZiW+tGMr7sxa85G1z0yOpM1qq5c8lNawc=",
        version = "v0.10.0",
    )
```

And this is the Go version I'm using:

```go
go_register_toolchains(version = "1.16.5")
```

### What did you expect to see?

No build errors.

### What did you see instead?

```go
external/com_github_prometheus_common/expfmt/openmetrics_create.go:171:19: metric.Counter.Exemplar undefined (type *io_prometheus_client.Counter has no field or method Exemplar)
external/com_github_prometheus_common/expfmt/openmetrics_create.go:239:7: b.Exemplar undefined (type *io_prometheus_client.Bucket has no field or method Exemplar)
external/com_github_prometheus_common/expfmt/openmetrics_create.go:305:12: undefined: io_prometheus_client.Exemplar
external/com_github_prometheus_common/expfmt/openmetrics_create.go:448:41: undefined: io_prometheus_client.Exemplar
```

**Comment by msiebuhr** [comment]
I've been running into a similar issue - from what I can figure out, Bazel is actually downloading the wrong version of https://github.com/prometheus/client_model v0.2.0:

If I `go mod vendor` and look at the downloaded repository, I get a rather sparse looking thing that matches upstream:

```console
# Let's see what go.sum says about it
% grep prometheus/client_model go.sum 
github.com/prometheus/client_model v0.0.0-20180712105110-5c3871d89910/go.mod h1:MbSGuTsp3dbXC40dX6PRTWyKYBIrTGTE9sqQNg2J8bo=
github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90/go.mod h1:xMI15A0UPsDsEKsMN9yxemIoYk6Tm2C1GtYGdfGttqA=
github.com/prometheus/client_model v0.2.0 h1:uq5h0d+GuxiXLJLNABMgp2qUWDPiLvgCzz2dUR+/W/M=
github.com/prometheus/client_model v0.2.0/go.mod h1:xMI15A0UPsDsEKsMN9yxemIoYk6Tm2C1GtYGdfGttqA=
# Download and get a rough look at what's there
% go mod vendor 
% tree vendor/github.com/prometheus/client_model 
vendor/github.com/prometheus/client_model
├── go
│   └── metrics.pb.go
├── LICENSE
└── NOTICE
```
But bazel/gazelle downloads something completely different for me:

```console
# Gazelle has set up v0.2.0 with matching sum...
% grep client_model -C 3 deps.bzl
        version = "v1.11.0",
    )
    go_repository(
        name = "com_github_prometheus_client_model",
        importpath = "github.com/prometheus/client_model",
        sum = "h1:uq5h0d+GuxiXLJLNABMgp2qUWDPiLvgCzz2dUR+/W/M=",
        version = "v0.2.0",
    )
# But something very different-looking is on disk:
% tree /home/msi/.cache/bazel/_bazel_msi/21c5c7000294153c36b1e8fe67103839/external/com_github_prometheus_client_model
/home/msi/.cache/bazel/_bazel_msi/21c5c7000294153c36b1e8fe67103839/external/com_github_prometheus_client_model
├── BUILD.bazel
├── CONTRIBUTING.md
├── cpp
│   ├── metrics.pb.cc
│   └── metrics.pb.h
├── go
│   ├── BUILD.bazel
│   └── metrics.pb.go
├── go.mod
├── go.sum
├── LICENSE
├── MAINTAINERS.md
├── Makefile
├── metrics.proto
├── NOTICE
├── pom.xml
├── python
│   └── prometheus
│       ├── client
│       │   ├── __init__.py
│       │   └── model
│       │       ├── __init__.py
│       │       └── metrics_pb2.py
│       └── __init__.py
├── README.md
├── ruby
│   ├── Gemfile
│   ├── lib
│   │   └── prometheus
│   │       └── client
│   │           ├── model
│   │           │   ├── metrics.pb.rb
│   │           │   └── version.rb
│   │           └── model.rb
│   ├── LICENSE
│   ├── Makefile
│   ├── prometheus-client-model.gemspec
│   ├── Rakefile
│   └── README.md
├── setup.py
├── src
│   └── main
│       └── java
│           └── io
│               └── prometheus
│                   └── client
│                       └── Metrics.java
└── WORKSPACE
```

**Comment by amalucelli** [comment]
I found the reason for the error, and the solution is just changing the order of the dependencies being loaded. This is required as the `0.24.0` introduced a lot of new dependencies.

This is even described in the release page, I just missed it for some reason: https://github.com/bazelbuild/bazel-gazelle/releases/tag/v0.24.0.

How it was in my configuration:

```go
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()
load("//:go.bzl", "go_deps")
# gazelle:repository_macro go.bzl%go_deps
go_deps()
```

What I changed to make it work:

```go
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
# First our dependencies, later gazelle ones.
load("//:go.bzl", "go_deps")
# gazelle:repository_macro go.bzl%go_deps
go_deps()
gazelle_dependencies()
```

**Comment by bviswana101** [comment]
@amalucelli i am running into the same issue,  Only difference is rules_go is at 0.30.0

WORKSPACE loads
`load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")`

and, i have moved `gazelle_dependencies` down below all other `go_repository`

but still seeing the same error. Any help?
