### ISSUE TITLE
Gazelle generates wrong deps from a bazelized git_repository repos

### ISSUE THREAD

**Issue by tigersoldier** [bazelbuild/bazel-gazelle#1143]
### What version of gazelle are you using?

0.24.0

### What version of rules_go are you using?

0.29.0

### What version of Bazel are you using?

4.2.1-homebrew

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS Intel

### What did you do?

I made a repository to showcase this issue: https://github.com/tigersoldier/gazelle-bugs

If I replace

```starlark
go_repository(
    name = "com_github_tigersoldier_gazelle_demo",
    importpath = "github.com/tigersoldier/gazelle-demo",
    sum = "h1:Mafq8JTThXQWLmd3GDDVwniPv90p0lTV5Iuc8KRFOoI=",
    version = "v0.0.0-20211206203318-4d00bfc2e984",
)
```

with 

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "com_github_tigersoldier_gazelle_demo",
    branch = "main",
    remote = "ssh://git@github.com/tigersoldier/gazelle-demo",
)
```

NOTE: I'm not using `git_repository` from gazelle. I'm using the one from Bazel.

Then run `bazel run //:gazelle`

### What did you expect to see?

No change

### What did you see instead?

The deps in `repo/BUILD.bzl` is changed from `"@com_github_tigersoldier_gazelle_demo//lib"` to `"@com_github_tigersoldier_gazelle_demo//lib:go_default_library"`

**Comment by robfig** [comment]
I don't believe that Gazelle indexes all dependency BUILD files. It relies on naming convention, and allows you to make individual overrides for specific rules using `# gazelle:resolve`. I wasn't part of that design decision, but I would guess that it would take too long to index everything (and it already takes too long on my work repo!). 

In my experience, this approach has worked fine -- our work repo has hundreds of dependencies, and I haven't found it necessary to deviate from the naming convention or missed the ability to index their rules specifically. 

If your particular need is to avoid `go_default_library`, you can set `go_repository(...., build_naming_convention="import")`
See https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.md#go_repository-build_naming_convention

Please feel free to reopen if there is a real, specific scenario that this won't handle for you. Thanks
