### ISSUE TITLE
Mirroring dependencies

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel-gazelle#1145]
I'm trying to both improve our dependency download reliability and startup times for fresh CI workers.

To achieve that, I'd like to rehost all our dependencies on a local mirror that we own.  git_repository is well known to be slower than http_archive with Bazel, so this should help with both.  This needs to be automated to succeed.

We are using `bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=repositories.bzl%go_repositories -prune=true` to generate the imports today.

I'm gearing up to write a python script to parse repositories.bzl, download artifacts, upload them, then update the .bzl file.  I think Gazelle would be a better home for this logic than another post step.  Thoughts?

**Comment by sluongng** [comment]
gazelle supports GOPROXY so you can just setup any go proxy implementation and then set GOPROXY value there.

Read https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/go_repository.bzl#L92 to see how go_repository is being downloaded by bazel.

Also https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/go_repository_cache.bzl may help if you wana set up caches for CI.
