### ISSUE TITLE
How to work with local replace ?

### ISSUE THREAD

**Issue by wenerme** [bazelbuild/bazel-gazelle#1148]
### What operating system and processor architecture are you using?

macOS, amd64

### What did you do?

structure

- git root
  - commons
    - WORKSPACE
    - go.mod
  - app
    - WORKSPACE
    - go.mod

in `app/go.mod`

```
replace wener.me/commons => ../commons
```

in WORKSPACE

```
local_repository(
    name = "commons",
    path = "../commons",
)
```

### What did you expect to see?

A proper way to work with local repo

### What did you do instead?

in BUILD, replace all used import path

```py
# gazelle:prefix wener.me/micros
# gazelle:resolve go wener.me/commons/errorx @commons//errorx
# gazelle:resolve go wener.me/commons/nilx @commons//nilx
# gazelle:resolve go wener.me/commons/fxs/routines @commons//fxs/routines
# gazelle:resolve go wener.me/commons/protox @commons//protox
# gazelle:resolve go wener.me/commons/ulidx @commons//ulidx
# gazelle:resolve go wener.me/commons/fxs @commons//fxs
# gazelle:resolve go wener.me/commons/buildx @commons//buildx
gazelle(
    name = "gazelle",
    args = [
        "-known_import=wener.me",
        "-proto=disable",
    ],
)
```

New to bazel , don't know how to handle or mapping these, gazelle do not support path replace, but should provide a way to work with path replacement ?

**Comment by wenerme** [comment]
`gazelle:repository` seems works.

**Comment by chandraaditya** [comment]
@wenerme can you give an example of how it should be used?
