### ISSUE TITLE
problem with go_proto_compiler 

### ISSUE THREAD

**Issue by mashail** [bazelbuild/bazel-gazelle#1156]
### What version of gazelle are you using?
0.24.0

### What version of rules_go are you using?
0.29

### What version of Bazel are you using?
4.2.1

### Does this issue reproduce with the latest releases of all the above?
yes

### What operating system and processor architecture are you using?
macos arm64

### What did you do?
SE

### What did you expect to see?
successful build.

### What did you see instead?
```
[build] Loading: 
[build] Loading: 0 packages loaded
[build] Analyzing: 1424 targets (2 packages loaded, 0 targets configured)
[build] ERROR: /private/var/tmp/_bazel_mashail/fb982e585f10475d9912cf6de83e1539/external/com_github_envoyproxy_protoc_gen_validate/BUILD:17:11: no such package '@com_github_envoyproxy_protoc_gen_validate//vendor/github.com/lyft/protoc-gen-star': BUILD file not found in directory 'vendor/github.com/lyft/protoc-gen-star' of external repository @com_github_envoyproxy_protoc_gen_validate. Add a BUILD file to a directory to mark it as a package. and referenced by '@com_github_envoyproxy_protoc_gen_validate//:go_default_library'
[build] ERROR: Analysis of target '//bazel:pgv_plugin_go_reset_plugin_' failed; build aborted: Analysis failed
[build] INFO: Elapsed time: 0.253s
[build] INFO: 0 processes.
[build] FAILED: Build did NOT complete successfully (6 packages loaded, 1012 targets configured)
[build] FAILED: Build did NOT complete successfully (6 packages loaded, 1012 targets configured)
[build] 
task: Failed to run task "build": exit status 1

```

`//bazel:pgv_plugin_go` is a custom plugin and it's defined like this:
```
load("@io_bazel_rules_go//proto:compiler.bzl", "go_proto_compiler")

go_proto_compiler(
    name = "pgv_plugin_go",
    options = ["lang=go"],
    plugin = "@com_github_envoyproxy_protoc_gen_validate//:protoc-gen-validate",
    suffix = ".pb.validate.go",
    valid_archive = False,
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_envoyproxy_protoc_gen_validate//validate:go_default_library",
        "@com_github_golang_protobuf//ptypes:go_default_library_gen",
    ],
)
```

We are plugging it like this:
```
# gazelle:go_grpc_compilers @io_bazel_rules_go//proto:go_grpc,//bazel:pgv_plugin_go
```

Every thing is working perfectly, once we upgrade gazelle from 0.23 to .24 we get this error!!! could do not figure out why gazelle 0.24 is resolving `com_github_envoyproxy_protoc_gen_validate` in a vendor mode!!

**Comment by blico** [comment]
The build error you shared indicates a problem with `@com_github_envoyproxy_protoc_gen_validate`. Could you share your repo's `go_repository` rule definition for `com_github_envoyproxy_protoc_gen_validate`?

**Comment by mashail** [comment]
> `com_github_envoyproxy_protoc_gen_validate`

Sorry for the late reply, Here you go:

```
    go_repository(
        name = "com_github_envoyproxy_protoc_gen_validate",
        importpath = "github.com/envoyproxy/protoc-gen-validate",
        sum = "h1:qcZcULcd/abmQg6dwigimCNEyi4gg31M/xaciQlDml8=",
        version = "v0.6.7",
    )
```

**Comment by mashail** [comment]
@blico

**Comment by mashail** [comment]
I am going to close the issue. I figured it out the issue was calling `go_repository` was after `gazelle_dependencies`. So, I just changed the order and it worked
