### ISSUE TITLE
[proto] Unable to properly find the list of embedded targets when the native rule is overridden

### ISSUE THREAD

**Issue by lbcjbb** [bazelbuild/bazel-gazelle#1162]
### What version of gazelle are you using?

`v0.24.0`

### What version of rules_go are you using?

`None`

### What version of Bazel are you using?

`None`

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

`Linux` / `amd64`

### What did you do?

I created a macro to override the `go_library` rule and I run `gazelle` to update a `BUILD` file for a `.proto` file which import another `.proto` file.

To highlight the issue, we can use this minimal setup below:

- An empty `WORKSPACE` file
- `BUILD` file

```skylark
# gazelle:prefix github.com/lbcjbb/test
# gazelle:map_kind go_library my_go_library //:my.bzl
```

- `my.bzl`

```skylark
load("@io_bazel_rules_go//go:def.bzl", "go_library")

my_go_library = go_library
```

- `a/a.proto`

```proto
syntax = "proto3";

package test;
option go_package = "github.com/lbcjbb/test/a";
```

- `b/b.proto`

```proto
syntax = "proto3";

package test;
option go_package = "github.com/lbcjbb/test/b";

import "a/a.proto";
```

And execute this command below inside this directory:

```sh
$ gazelle update
```

### What did you expect to see?

- No warnings from `gazelle`
- A `b/BUILD.bazel` with a `go_proto_library` rule with a `deps` attribute containing the `//a` label.

### What did you see instead?

- This warning below:

```
gazelle: multiple rules (//a:a_go_proto and //a) may be imported with "a/a.proto" from //b:b_go_proto
```

- No `deps` attribute for the `go_proto_library` rule in `b/BUILD.bazel`. 

All the other rules in `a/BUILD.bazel` and `b/BUILD/bazel` files are correctly added.

**Comment by blico** [comment]
@lbcjbb I cannot reproduce the issue with the steps you provided. Could you share the entire contents of your BUILD.bazel files before and after running Gazelle?

**Comment by lbcjbb** [comment]
I have no BUILD.bazel before running Gazelle, and after I have:

- `a/BUILD.bazel`

```
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("//:my.bzl", "my_go_library")

proto_library(
    name = "a_proto",
    srcs = ["a.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "a_go_proto",
    importpath = "github.com/lbcjbb/test/a",
    proto = ":a_proto",
    visibility = ["//visibility:public"],
)

my_go_library(
    name = "a",
    embed = [":a_go_proto"],
    importpath = "github.com/lbcjbb/test/a",
    visibility = ["//visibility:public"],
)
```

- `b/BUILD.bazel`

```
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("//:my.bzl", "my_go_library")

proto_library(
    name = "b_proto",
    srcs = ["b.proto"],
    visibility = ["//visibility:public"],
    deps = ["//a:a_proto"],
)

go_proto_library(
    name = "b_go_proto",
    importpath = "github.com/lbcjbb/test/b",
    proto = ":b_proto",
    visibility = ["//visibility:public"],
)

my_go_library(
    name = "b",
    embed = [":b_go_proto"],
    importpath = "github.com/lbcjbb/test/b",
    visibility = ["//visibility:public"],
)
```

**Comment by blico** [comment]
Strange, so I can only reproduce on Linux, not MacOs. 

Also, if I run `gazelle update /b` the BUILD.bazel file gets generated correctly, it is only when running `gazelle update` where I see the warning.

Given this issue likely has to do with `map_kind` I think @robfig might be the best person to take a look.

**Comment by alexeagle** [comment]
I have this problem as well, I tried to use `map_kind` to wrap `go_proto_library` with a macro https://github.com/aspect-build/bazel-examples/blob/main/write_source_files/go_proto_library.bzl that checks in the .pb.go source files, but then Gazelle doesn't recognize it as the built-in kind - I assume due to https://github.com/bazelbuild/bazel-gazelle/blob/5b8616dbb7dad825c61ffbb12ea9f75622568657/language/go/kinds.go#L175-L179
