### ISSUE TITLE
Generic question about compatibility between go_repository and Go vet

### ISSUE THREAD

**Issue by fandw** [bazelbuild/bazel-gazelle#1178]
### What version of gazelle are you using?
v0.22.3

### What version of rules_go are you using?
rules_go-v0.25.1

### What version of Bazel are you using?
4.1.0-bd3243f705b1d9afb853a7d94d17992f8a055261

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
Ubuntu Focal (U20), x86_64

### What did you do?
I'm using bazel/gazelle to pull in some external git repositories. For example:

```
go_repository(
    name = "com_github_pkg_errors",
    importpath = "github.com/pkg/errors",
    sum = "h1:iURUrRGxPUNPdy5/HRSm+Yj6okJ6UtLINN0Q9M4+h3I=",
    version = "v0.8.1",
)
```

My go file would just import github.com/pkg/errors like normal. 

### What did you see instead?
Problem comes when I run go vet on my file. It would complain that no such package exists under GOROOT or GOPATH. This repo is located in my bazel cache. `~/.cache/bazel/.../external/com_github_pkg_errors`
Is there a way for go vet to be compatible?

**Comment by achew22** [comment]
Unfortunately `rules_go` does not work in a way compatible with `go vet` and never can work this way for structural reasons. We have a parallel system called [`nogo`](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst) that provides similar functionality that makes these checks part of the compiler which should prevent any vet-able issues from ever getting into your codebase (it just won't compile with them).

**Comment by fandw** [comment]
@achew22 other than go vet, is `rules_go` compatible with other popular analyzers such as 
https://pkg.go.dev/honnef.co/go/tools/unused and https://pkg.go.dev/honnef.co/go/tools/cmd/staticcheck ?
