### ISSUE TITLE
language/proto: Missing dependencies with `go_package` grouping

### ISSUE THREAD

**Issue by nickgooding** [bazelbuild/bazel-gazelle#1219]
### What version of gazelle are you using?

v0.25.0

### What version of rules_go are you using?

v0.31.0

### What version of Bazel are you using?

5.0, 5.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Mac OS 12.3, x86_64-apple-darwin21.1.0

### What did you do?

Using Gazelle to generate `proto_library` and `go_proto_library` targets using `gazelle:proto package` and `gazelle:proto_group go_package` directives with Proto files that share a Proto package, but have separate Go packages. I've pushed a simple reproduction of the issue here: https://github.com/nickgooding/bazel-gazelle-1219-repro

### What did you expect to see?

- Generated `proto_library` and `go_proto_library` targets should be generated with appropriate `deps`
- Generated `proto_library` and `go_proto_library` targets should be buildable

### What did you see instead?

- Generated `proto_library` and `go_proto_library` targets are missing `deps` for `proto_library`/`go_proto_library` targets that belong to the same Proto package but have different Go packages
- Generated `proto_library` and `go_proto_library` targets fail to build due to the missing dependencies

---

Using `git bisect`, it appears that 6bbfc47 is the commit where these dependencies stopped being generated. A similar issue, bazelbuild/bazel-gazelle#1157 was raised regarding per-file Proto mode, but the fix for that does not appear to have resolved the issue when using `go_package` grouping.

**Comment by wyattanderson** [comment]
I can confirm that we're facing the same issue, introduced by the same commit, and that @nickgooding's PR fixes the issue for us. Thanks!
