### ISSUE TITLE
bazel.build link is broken for v0.25

### ISSUE THREAD

**Issue by tim-chaplin-dd** [bazelbuild/bazel-gazelle#1224]
The link in the `WORKSPACE code` section for v0.25 at https://github.com/bazelbuild/bazel-gazelle/releases is broken:

https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.25.0/bazel-gazelle-v0.25.0.tar.gz

> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> \<Error>
> \<Code>NoSuchKey\</Code>
> \<Message>The specified key does not exist.\</Message>
> \</Error>

The github.com link works.

**Comment by meteorcloudy** [comment]
https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.25.0/bazel-gazelle-v0.25.0.tar.gz is now available
