### ISSUE TITLE
importpath set only to package name, rather than full path (due to proto go_package option)

### ISSUE THREAD

**Issue by ixdy** [bazelbuild/bazel-gazelle#124]
I'm attempting to update kubernetes/kubernetes to a more recent version of rules_go, and due to the warnings about `importpath` deprecation, decided to update gazelle as well, from 31ce76e3acc34a22434d1a783bb9b3cae790d108 to 683e26c7a735ee7539ef4e2ec1d9f4351e2b98b2.

Gazelle removes the `importpaths` outside `vendor/`, and correctly preserves most of the `importpath`s in `vendor/`, but a number are rewritten to include only the package. For example, some of the incorrect diffs look like
```diff
diff --git a/vendor/github.com/libopenstorage/openstorage/api/BUILD b/vendor/github.com/libopenstorage/openstorage/api/BUILD
index 2f7f752a40..24627d375e 100644
--- a/vendor/github.com/libopenstorage/openstorage/api/BUILD
+++ b/vendor/github.com/libopenstorage/openstorage/api/BUILD
@@ -13,7 +13,7 @@ go_library(
         "api.pb.go",
         "status.go",
     ],
-    importpath = "github.com/libopenstorage/openstorage/api",
+    importpath = "api",
     visibility = ["//visibility:public"],
     deps = [
         "//vendor/github.com/golang/protobuf/proto:go_default_library",
diff --git a/vendor/google.golang.org/grpc/grpclb/grpc_lb_v1/messages/BUILD b/vendor/google.golang.org/grpc/grpclb/grpc_lb_v1/messages/BUILD
index 06ab31fa94..63e7ea975d 100644
--- a/vendor/google.golang.org/grpc/grpclb/grpc_lb_v1/messages/BUILD
+++ b/vendor/google.golang.org/grpc/grpclb/grpc_lb_v1/messages/BUILD
@@ -9,7 +9,7 @@ filegroup(
 go_library(
     name = "go_default_library",
     srcs = ["messages.pb.go"],
-    importpath = "google.golang.org/grpc/grpclb/grpc_lb_v1/messages",
+    importpath = "messages",
     visibility = ["//visibility:public"],
     deps = ["//vendor/github.com/golang/protobuf/proto:go_default_library"],
 )
```

full diff: [importpath-diff.txt](https://github.com/bazelbuild/bazel-gazelle/files/1709418/importpath-diff)

Note that kubernetes/kubernetes is a little weird, in that we have a `staging/` directory which is really vendored code (intended for other kubernetes/ repos), but we symlink to these directories from `vendor/` to make go happy. Gazelle basically handles these correctly, though we have a [post-gazelle sed](https://github.com/kubernetes/kubernetes/blob/2172a2a806c4a93dfa31f4560615998630018cf6/hack/update-bazel.sh#L48-L49) to fix the `importpath`s. I don't think that's affecting what's happening here, though, since these packages are incorrectly filled even without the sed, and it's affecting some of the normal vendored dependencies too.

**Comment by ixdy** [comment]
It seems like there may be a strong correlation between there being a `.proto` / `.pb.go` file and these incorrect `importpath` attributes.

**Comment by ixdy** [comment]
Yeah, this appears to be directories that have a `.proto` file that specify `go_package` that isn't fully qualified. For example, `vendor/github.com/libopenstorage/openstorage/api/api.proto` has
```proto
option go_package = "api";
```

It seems like gazelle is now using this verbatim instead of trying to resolve to the full path?

**Comment by ixdy** [comment]
oh neat, the recommended value for `option go_package` has changed over time: https://github.com/golang/protobuf/issues/139

**Comment by jayconrod** [comment]
Thanks for investigating and fixing this. I didn't know about the package name form. I wish there were better documentation for this on golang/protobuf.
