### ISSUE TITLE
fix-update: Custom extension flags cannot influence Loads() or Kinds()

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel-gazelle#1275]
The `.RegisterFlags()` / `.CheckFlags()` API exists to allow extensions to offer custom behavior via flags.  Currently, there is no way that these flags may influence the return value(s) of the `.Loads()` and/or `.Kinds()` API due to the fact that `.CheckFlags` is called after `.Loads()` and `.Kinds()`.  

### What version of gazelle are you using?

master

### What version of rules_go are you using?

0.27

### What version of Bazel are you using?

4.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

**Comment by sluongng** [comment]
If i read this correctly, it would potentially allow us to load go_repository from a different place? Or is there some other intention behind this?
