### ISSUE TITLE
Java or Kotlin gazelle plugin?

### ISSUE THREAD

**Issue by gonzojive** [bazelbuild/bazel-gazelle#1276]
We would like to use something like gazelle for Java and Kotlin (JVM) code.

Does something exist like this?

What would be tricky about implementing a gazelle plugin for those languages?

I suspect we will eventually write something ourselves, so even design ideas would be useful in this issue thread.

**Comment by achew22** [comment]
Have you looked at rules_jvm's [gazelle plugin](https://github.com/bazel-contrib/rules_jvm/tree/main/java/gazelle)?

**Comment by gonzojive** [comment]
The latest in Kotlin gazelle support is https://github.com/aspect-build/aspect-cli/tree/main/gazelle/kotlin, which is [now linked in the README.md](https://github.com/bazelbuild/bazel-gazelle/pull/1590).
