### ISSUE TITLE
"inconsistent definition for type pflag.parseFunc during import" after switching to gazelle in this repo

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel-gazelle#130]
I've followed https://github.com/bazelbuild/bazel-gazelle#running-gazelle-with-bazel to prepare for the removal of gazelle in https://github.com/bazelbuild/rules_go.

I did a `bazel clean` and a `bazel build //...` and now get go build errors:
```
ERROR: <path>/BUILD.bazel:3:1: GoCompile src/go/.../cmd.a failed (Exit 1)
src/go/.../cmd/connect.go:32:2: inconsistent definition for type pflag.FlagSet during import
	struct { Usage func(); SortFlags bool; pflag.name string; pflag.parsed bool; pflag.actual map[pflag.NormalizedName]*pflag.Flag; pflag.orderedActual []*pflag.Flag; pflag.sortedActual []*pflag.Flag; pflag.formal map[pflag.NormalizedName]*pflag.Flag; pflag.orderedFormal []*pflag.Flag; pflag.sortedFormal []*pflag.Flag; pflag.shorthands map[byte]*pflag.Flag; pflag.args []string; pflag.argsLenAtDash int; pflag.errorHandling pflag.ErrorHandling; pflag.output io.Writer; pflag.interspersed bool; pflag.normalizeNameFunc func(*pflag.FlagSet, string) pflag.NormalizedName } (in "github.com/spf13/cobra")
	struct { Usage func(); pflag.name string; pflag.parsed bool; pflag.actual map[pflag.NormalizedName]*pflag.Flag; pflag.formal map[pflag.NormalizedName]*pflag.Flag; pflag.shorthands map[byte]*pflag.Flag; pflag.args []string; pflag.argsLenAtDash int; pflag.exitOnError bool; pflag.errorHandling pflag.ErrorHandling; pflag.output io.Writer; pflag.interspersed bool; pflag.normalizeNameFunc func(*pflag.FlagSet, string) pflag.NormalizedName } (in "k8s.io/client-go/tools/clientcmd")
src/go/.../cmd/connect.go:32:2: inconsistent definition for type pflag.parseFunc during import
	func(*pflag.Flag, string) error (in "github.com/spf13/cobra")
	func(*pflag.Flag, string, string) error (in "k8s.io/client-go/tools/clientcmd")
2018/02/14 15:08:21 error running compiler: exit status 1
```

there is no use of `pflag.FlagSet` in connect.go, neither is there in the whole source code. Any ideas for how to debug this?

**Comment by jayconrod** [comment]
I don't have enough information to reproduce this. Is there a repo or PR I could look at?

I tried running Gazelle and building `//vendor/github.com/spf13/cobra:go_default_library` in k8s.io/client-go, and that worked.

**Comment by ensonic** [comment]
I'll compare the generated BUILD files tomorrow.

**Comment by jayconrod** [comment]
I was able to reproduce this with some hep.

The problem is that there are two versions of the library `github.com/spf13/pflag`. When you compile a package in Go, some type information from imported libraries is stored in the output archive file. If you've ever taken apart an archive file, this is that `__.PKGDEF` file. In this case, the compiler is seeing different type information for the same transitive dependency from two direct dependencies. Specificially:

* `@com_github_spf13_cobra//:go_default_library` depends on `@com_github_spf13_pflag//:go_default_library`.
* `@io_k8s_client_go//tools/clientcmd:go_default_library depends on @io_k8s_client_go//vendor/github.com/spf13/pflag`.

This issue should be fixed when #131 is fixed. Gazelle will set `importmap` attributes on `go_library` rules within the vendor directory, which will give those packages unique names as far as the compiler and linker are concerned.

**Comment by ensonic** [comment]
#131 is marked as fixed, but I still get this issue. So I've also tried git HEAD instead of 0.10.0
Here is some data:

`io_k8s_client_go/tools/clientcmd/BUILD.bazel`
pulls in `"//vendor/github.com/spf13/pflag:go_default_library"`
and has `importpath = "k8s.io/client-go/tools/clientcmd",`

`io_k8s_client_go/vendor/github.com/spf13/pflag/BUILD.bazel`
has `importpath = "github.com/spf13/pflag"`

`com_github_spf13_cobra/BUILD.bazel`
pulls in `"@com_github_spf13_pflag//:go_default_library"`
and has itself uses `importpath = "github.com/spf13/cobra"`

`com_github_spf13_pflag/BUILD.bazel`
als has `importpath = "github.com/spf13/pflag",`

From your last comment, I was expecting that the vendored dep `"//vendor/github.com/spf13/pflag:go_default_library"` would have a distinct import-path?

When I search for the new annotation
> find . -name "BUILD.bazel" -exec grep -Hn "# gazelle:importmap_prefix" {} \;
I don't find it used at all.

Is there any way I can override or annotate things to guide it?

**Comment by jayconrod** [comment]
Are you seeing `importmap` attributes after running a new version of Gazelle? Here's what I'm seeing on the vendored pflag library:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ...
    importmap = "vendor/github.com/spf13/pflag",
    importpath = "github.com/spf13/pflag",
    visibility = ["//visibility:public"],
)
```

You probably won't need to set `gazelle:importmap_prefix` explicitly. It's automatically set inside vendor directories.

**Comment by ensonic** [comment]
Args, bazel was caching the old version (lesson learned alwas change sha256 to "" when bumping the version). I) also had to switch to git-HEAD for rules-go. 
Now I get the importmaps and it builds!
