### ISSUE TITLE
Gazelle command not found on Windows

### ISSUE THREAD

**Issue by adam-kov** [bazelbuild/bazel-gazelle#1309]
### Versions

|Name|Version|
| --- | --- |
|Gazelle|`0.26.0`|
|rules_go|`0.34.0`|
|Bazel|`5.2.0`|

### Does this issue reproduce with the latest releases of all the above?
All of the above is the latest of releases at the time of writing this. *(2022.07.27)*

### What operating system and processor architecture are you using?
Windows 10, 64-bit x86

### What did you do?
I followed the [Gazelle README setup for Bazel](https://github.com/bazelbuild/bazel-gazelle#running-gazelle-with-bazel), then I ran the command `bazel run //:gazelle` in the root of a repo where I tried to set up Go and Node.js - although I got stuck with Go.

[My GitHub repo can be found here](https://github.com/n00pper/bazel-go-node-test)

### What did you expect to see?
I expected Gazelle to create a BUILD.bazel file in the `go/services/core`.

### What did you see instead?
This was the command output:
```bazel
INFO: Analyzed target //:gazelle (84 packages loaded, 8741 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
  bazel-bin/gazelle.exe
INFO: Elapsed time: 17.216s, Critical Path: 16.16s
INFO: 57 processes: 15 internal, 42 local.
INFO: Build completed successfully, 57 total actions
INFO: Build completed successfully, 57 total actions
/bin/bash: C:\Users\xxxxx\xxxxxxxxxxx\zu4tg5ct\execroot\com_github_n00pper_bazel_go_node_test\bazel-out\x64_windows-fastbuild\bin\gazelle: command not found
```
The `bazel-*` folders are generated and there are these files in the `bazel-out\x64_windows-fastbuild\bin` folder:
- `gazelle`
- `gazelle-runner.bash`
- `gazelle.exe`
- `gazelle.exe.runfiles_manifest`

At the moment I'm not even sure I'm using Gazelle correctly, so any clarification is appreciated.

**Comment by DragunasVilius** [comment]
I'm getting the same problem. Any solution?

**Comment by gjycn** [comment]
I encountered the same problem, the same Gin Hello World project, under Windows 11, but it was normal under WSL. Based on the prompt information, I guessed that it was a file extension issue.

```bash
grep: C:\\Users\\xxxx\\_bazel_xxxx\\jik7kwyi\\execroot\\__main__\\bazel-out\\x64_windows-fastbuild\\bin\\gazelle.runfiles_manifest: No such file or directory

C:\\Users\\xxxx\\_bazel_xxxx\\jik7kwyi\\execroot\\__main__\\bazel-out\\x64_windows-fastbuild\\bin\\gazelle: warning: could not locate GOROOT used by rules_go

grep: C:\\Users\\xxxx\\_bazel_xxxx\\jik7kwyi\\execroot\\__main__\\bazel-out\\x64_windows-fastbuild\\bin\\gazelle.runfiles_manifest: No such file or directory

error: could not locate gazelle binary
```

There is only the "gazelle. exe. runfiles_manifest" file in this folder, and there is no "gazelle. runfiles_manifest" file.

I suggest using this tool on Linux until it improves support for Windows.

<html>
<body>


Name | Version
-- | --
Gazelle | 0.27.0
rules_go | 0.39.0
Bazel | 6.0.0

**Comment by bshashank** [comment]
The issue seems to be with the custom `find_runfiles` function implemented in `gazelle.bash.in`

I was able to work around the problem via: https://github.com/bshashank/bazel-gazelle/commit/3dc2f476cb18078508cfd85bd05de6c790fd85a2

(but this is still un-tested on other platforms)

**Comment by albertocavalcante** [comment]
Just for reference:

I was having the same issue on Windows even after `v0.33.0`.

```sh
C:\dev\workspace\chromed>bazel run //:gazelle
INFO: Analyzed target //:gazelle (100 packages loaded, 12313 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
  bazel-bin/gazelle.exe
INFO: Elapsed time: 27.579s, Critical Path: 1.85s
INFO: 9 processes: 9 internal.
INFO: Build completed successfully, 9 total actions
INFO: Running command line: bazel-bin/gazelle.exe
/bin/bash: line 1: C:\Users\alber\_bazel_alber\pvqfizta\execroot\_main\bazel-out\x64_windows-fastbuild\bin\gazelle: command not found
```

It happens I am running on an Windows 11 machine with WSL2 setup, and Gazelle relies on the locally `bash.exe` which [Bazel on Windows](https://bazel.build/configure/windows#using-bazel-without-bash) talks about.

So when WSL2 is setup, a `bash.exe` is created at `C:\Windows\System32`, which makes Bazel resolves to this, which actually runs in the WSL host and not the local Windows machine.

```sh
$ where bash
C:\Windows\System32\bash.exe
C:\Program Files\Git\usr\bin\bash.exe

```

To fix this, make sure to set `BAZEL_SH` to either `Git Bash` or `MSYS2 bash`.
