### ISSUE TITLE
[feature request] Remove leftover targets.

### ISSUE THREAD

**Issue by blorente** [bazelbuild/bazel-gazelle#1311]
### What version of gazelle are you using?

v0.23.0, since later versions gave me issues with `x/errors`. I can imagine it repros with later versions as well.

### What version of rules_go are you using?

v.0.33.0

### What version of Bazel are you using?

```
Bazelisk version: development
Build label: 5.2.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:11:09 2022 (1654618269)
Build timestamp: 1654618269
Build timestamp as int: 1654618269
```

### Does this issue reproduce with the latest releases of all the above?

I couldn't get latest gazelle to run, but I can imagine it reproduces.

### What operating system and processor architecture are you using?

macOS, arm64.

### What did you do?

This minimal repro (https://github.com/blorente/standalone-repros/tree/gazelle-rename-repro) represents a case where someone in our team had managed to get stuck by moving go files around. The target `//lib:badlib` is a leftover target from before splitting `lib` into 2 and renaming it.

### What did you expect to see?

Gazelle's behaviour is as expected (it leaves `//lib:badlib` alone, assuming it's an intentional target), but I was wondering: **Is there a way to tell gazelle to remove spurious targets?**

### What did you see instead?

Things I've tried and didn't work:
- Using `gazelle fix`. It didn't address this particular case.
- Using the `# gazelle:go_naming_convention go_default_library` directive, maybe hypothesising that it would remove everything that is not a `go_default_library`.

Has anyone dealt with this?

**Comment by achew22** [comment]
Unfortunately there is no good way to determine what we can safely remove without breaking the build. As a trivial example of this, we don't know if 3rd parties who depend the repo in question are depending on the targets we are considering deleting. As a result, we bias toward not breaking your build and include the instructions in our [README](https://github.com/bazelbuild/bazel-gazelle/blame/master/README.rst#L796):

> Existing rules of the old kind will be ignored. To switch your codebase from a builtin kind to a mapped kind, use [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer).

I'm going to leave this issue open if you've got any more thoughts on the topic I'd love to hear what you think. I've not buildozed in a while, but it is pretty straight forward. I expect something like:


```sh
bazel query //...:go_default_library | xargs buildozer delete
```

would get you squared away.

**Comment by blorente** [comment]
Yeah my issue was more related to "given that I'm in a bad state by moving code around (https://github.com/blorente/standalone-repros/tree/gazelle-rename-repro), is there a way to detect that `//lib:badlib` is a bad target and delete it using Gazelle?

For our customers, they'd like to touch BUILD files as little as possible. The person who ran into this didn't know that the `//lib:badlib` target was still around, they assumed that Gazelle would nuke everything that wasn't `# keep` before running.

That makes me think: Would there be space for such a mode? Something like `gazelle destructive-rebuild`, that has the semantics: "Regenerate rules, deleting everything that is not generated now or # kept"

I think that kind of "burn everything and rebuild from scratch" could be useful for someone who doesn't want to deal with BUILD files, and thus works really hard to stay in the happy path.

**Comment by achew22** [comment]
Can you help me understand how the proposed `gazelle destructive-rebuild` feature be different than 

```
find . | grep /BUILD$ | xargs rm
```

If there are any rules that are hand rolled (not generated by Gazelle) there is no way to detect that they are hand rolled and should be preserved or if they are lingering from old configurations.

**Comment by blorente** [comment]
The main difference would be that gazelle would respect # keep comments in targets that users want to keep, and would delete the rest.

I'm not sure how # keep is processed, but as far as I understand, there would be a conceptual difference between targets the users want to keep (via #keep), and the other ones.

**Comment by achew22** [comment]
Unfortunately, as you point out, there are a lot of risks. Combining that with the fact that it's a relatively uncommon operation so my will to write a perfectly generalized solution is [quite low](https://xkcd.com/1205/). If this is something you'd like to make an effort into doing this, I'd be very happy to review. I do want to warn that it would need to be right 100% of the time without adding support for any new conceptual artifacts, which I hypothesize is going to be a tall order.

The only theory I've got is some kind of `gazelle undo` where it goes and deletes everything as it would be generated right now followed by a `gazelle update` to generate the new targets, but I think that would fall flat on `# keep` annotated targets. 🤷

**Comment by blorente** [comment]
Sorry for the late reply. I agree that, if the invariant of "Gazelle never breaks the build" is to be kept, this seems next to impossible.
I was planning on working on this myself, but if it's unlikely to get merged then another, more ad-hoc solution is probably best for us.
Thank you for taking the time to answer!
