### ISSUE TITLE
Don't use select in srcs

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#134]
Currently, Gazelle identifies platform-specific source files using file name suffixes (e.g., `foo_linux_amd64.go`) and build tags (e.g., `// +build linux,amd64`).

It's important that we don't attempt to build packages that are only imported by platform-specific sources that wouldn't get compiled for the target platform. Building the wrong packages causes errors and wastes resources.

That said, there's actually no need to exclude platform-specific *sources* at analysis time. The compiler wrapper in rules_go also checks build constraints at execution time, so this early exclusion is redundant (even though it saves us a little time).

In some cases (particularly when `goos` and `goarch` are set on a `go_binary` rule), sources that should be included are excluded by `select` expressions. There's no way to evaluate these expressions correctly in the presence of `goos` and `goarch` attributes. We should avoid using them when they're not necessary.

**Comment by afking** [comment]
This fixed selection of source files however dependencies `deps = []` for go rules are still selected and fail on goos/goarch attributes.

**Comment by jayconrod** [comment]
@afking Unfortunately, there's no practical way to fix that within rules_go or Gazelle. Attributes like `goos` / `goarch` on `go_binary` don't affect the configuration, so `select` may pick the wrong thing. If we produce flat `deps` lists instead, we end up building all dependencies, including packages that are unbuildable on the target platform.

**Comment by steeve** [comment]
There is also the issue of CGo files (`.c`) being built regardless it seems ?

**Comment by jayconrod** [comment]
@steeve That should not be happening. Could you file an issue on rules_go with steps to reproduce?

Gazelle should include .c files if there is at least one .go file with `import "C"` and the .c files may be built on at least one platform.

rules_go should filter those files for the target platform based on tags and filename suffixes before attempting to compile them.

**Comment by steeve** [comment]
I think `gazelle` successfully skips `.c` files if no `import "C"` is found, however, should this file be tagged, the `.c` file is still built by CGo

**Comment by jayconrod** [comment]
@steeve We pass the full set of `go_library` sources to the cgo builder for codegen. For each .c file, it checks tags for the target platform. It copies the file if the tags match and creates an empty file if not. We compile the copied / empty files with `cc_library`.

If there's a case where a .c file should not be matched but is compiled anyway, please file a bug.
