### ISSUE TITLE
Documentation on how to add a new language to Gazelle

### ISSUE THREAD

**Issue by achew22** [bazelbuild/bazel-gazelle#136]
Would you be willing to put together a little document on all the places that one would need to modify in order to get Gazelle to output build files for another language?

**Comment by jayconrod** [comment]
[Design.rst](https://github.com/bazelbuild/bazel-gazelle/blob/master/Design.rst) is the closest thing I have to this right now.

What languages are you thinking about?

Ideally, Gazelle can be restructured a bit so additional languages can be plugged in without too much hassle. I'm happy to describe what would need to be changed to add a new language today, but it would be better to figure out a framework that will work for lots of languages in the future.

**Comment by achew22** [comment]
I was thinking about adding support for `rules_typescript`.

> Ideally, Gazelle can be restructured a bit so additional languages can be plugged in without too much hassle.

Yes, that would be ideal. It seems that the majority of the code in Gazelle would be reusable, I would just need to add a new indexer that can understand the rules_typescript naming convention and write a scanner that is able to read import statements from `.ts` files. I'm also willing to accept a subset of typescript as the target language just to get things off the ground in the first iteration.

Do you have any plans to add support for Gazelle as a framework?

**Comment by achew22** [comment]
Friendliest of pings

**Comment by jayconrod** [comment]
Sorry for the delay. I haven't forgotten, but perf took a long time. I'll write this up this week.

**Comment by achew22** [comment]
Perf is also killing me. Could you please not do it till next week? No need to stress
