### ISSUE TITLE
map_kind should apply equally to all rules regardless of pre-existing state

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/bazel-gazelle#1391]
The current behaviour around `map_kind` and existing rules is quite subtle and brittle. Much more so when a `map_kind` is used to just load a rule from another file, and not to rename it (e.g. `# gazelle:map_kind go_binary go_binary //tools/go:def.bzl`), and particularly around targets that gazelle _doesn't_ maintain.

I tried to fix a specific bug, and found that a lot of the behaviour is surprising, so wasn't sure which direction to make the bugfix.

I've pushed pushed a bunch of test-cases showing the current behaviours of `map_kind`. For existing hand-written targets unrelated to gazelle, gazelle will sometimes apply a `map_kind` that wasn't applied before, will sometimes _unapply_ a `map_kind` that _was_ manually applied before, or will sometimes preserve whatever existed before. See the top commit of this branch: https://github.com/illicitonion/bazel-gazelle/tree/map-kind-edge-case-tests

I believe that the correct behaviour should either be:
1. Always apply `map_kind` transformations in all BUILD files gazelle touches (even if that changes existing rules' kinds).
2. For existing rules that gazelle _isn't_ generating, always preserve the target kind that existed before gazelle got involved (which is fiddly, because it may require re-loading a rule kind with a unique new name), and for any rule that gazelle _is_ generating, apply any relevant `map_kind`.

I pretty strongly favour 1. I can't think of cases where you'd want to `map_kind` for gazelle but _not_ for non-gazelle, but if they exist, I think the BUILD file author should rename their manual import to achieve this.

In particular, I believe this test case is incorrect behaviour: https://github.com/bazelbuild/bazel-gazelle/blob/5e06b9479bc41f57d5730962feabf25dda938461/cmd/gazelle/integration_test.go#L2753-L2766 - if gazelle generates a rule, and there's a `map_kind` in scope for it, the `map_kind` _should_ be applied, regardless of what load was present before.

Before I put together a PR fixing my particular bug, I wanted to get people's opinions on what the true behaviour should be here.

**Comment by sluongng** [comment]
Few thoughts:

- I think the commit https://github.com/bazelbuild/bazel-gazelle/commit/9aff2c83e542c8b41f4159f45ab57ca645eec144 should make it into the current Gazelle code. At minimum, we could document current observable behaviors with these new tests. "Fixing" these behaviors could be a separate discussion.

- I agree that (1) is the desirable behavior, at least for the short term being. In my head, I keep having to think about what would/should happen when you run Gazelle over a fairly large monorepo served from a FUSE file system. In this case, each Gazelle should be operating lazily based on the current diff against merge-base commit of the VCS (or a change tracker such as watchman). Under such lazy-gazelle mode, (2) seems to be more desirable. But such a mode does not exist today so (1) is the correct answer for the time being.
