### ISSUE TITLE
Gazelle generates dependency but missing its transitive dependency

### ISSUE THREAD

**Issue by jgao54** [bazelbuild/bazel-gazelle#1411]
### What version of gazelle are you using?

0.28.0

### What version of rules_go are you using?

0.37.0

### What version of Bazel are you using?

6.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

darwin/arm (also hit same issue with linux/x86_64)

### What did you do?

Hit the following gnarly edge case:

Have Go project with following properties:
(1) uses gazelle to generate go_repositories from go.mod
(2) uses go 1.17+
(3) has a target that uses `container_image` rule from `rules_docker`
(4) `go list -m all` returns `github.com/google/go-containerregistry` even though it's not actually used by the project (i.e. not in go.mod/go.sum).

When attempting to build the container_image target, I get following error:

```
ERROR: /private/var/tmp/_bazel_jgao/99d539c2e285762ed014381651bc84f1/external/com_github_google_go_containerregistry/internal/estargz/BUILD.bazel:3:11: GoCompilePkg external/com_github_google_go_containerregistry/internal/estargz/estargz.a [for tool] failed: (Exit 1): builder failed: error executing command (from target @com_github_google_go_containerregistry//internal/estargz:estargz) bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-625e526ca8a8/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_arm64 -src ... (remaining 23 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
compilepkg: missing strict dependencies:
	/private/var/tmp/_bazel_jgao/99d539c2e285762ed014381651bc84f1/sandbox/darwin-sandbox/65/execroot/myworkspace/external/com_github_google_go_containerregistry/internal/estargz/estargz.go: import of "github.com/containerd/stargz-snapshotter/estargz"
No dependencies were provided.
```
The issue is that rules_docker itself depends on `github.com/google/go-containerregistry`; but I have a `deps.bzl` (generated by `bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=deps.bzl%go_dependencies`) in WORKSPACE evaluated prior to rules_docker that also contains `com_github_google_go_containerregistry`. but _not_ go-containerregistry's transitive dependencies; resulting in error above.

Some workarounds are:
1. explicitly declare go_repository in WORKSPACE before calling deps.bzl%go_dependencies
2. move rules_docker before gazelle in WORKSPACE (similar goal as 1.)
3. manually add a go_repository for `com_github_containerd_stargz_snapshotter_estargz` in deps.bzl with # keep comment so that @com_github_containerd_stargz_snapshotter_estargz is generated as an external dep

While these workarounds circumvent the error, it would be nice if this could be solved systematically with gazelle.  I'm not quite sure why `go list -m all` included `github.com/google/go-containerregistry` even though it's unused, yet _not_ its transitive dependencies; but it seem to have something to do with https://go.dev/ref/mod#graph-pruning because prior to Go 1.17 all unused transitive deps used to be listed as well so this was not an issue.

See a minimum repro [here](https://github.com/jgao54/gazelle-issue-repro).

### What did you expect to see?

Build to succeed

### What did you see instead?

Gazelle does not generate all the necessary transitive dep; causing build to fail.

**Comment by aschlosberg** [comment]
I'm experiencing something similar and the only commonality I can find between the failing packages is that they use generics. This may very well be a red herring, and I haven't proven it yet, but wanted to reply in case it turns out to be the solution but I forget to tell you.

**Comment by marksmithson** [comment]
Had a similar issue with rules_docker and go_containerregistry.

In our case go_containerregistry was a transitive dependency of another dependency. You can check if you have any using  `go mod graph | grep containerregistry`

I would have expected the transitive dependencies of  go_containerregistry to have been added by gazelle though.

**Comment by fmeum** [comment]
The proper fix is to migrate to Bzlmod and the `go_deps` extension, which directly consumes `go.mod` and doesn't go through `go list -m all`: https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md#external-dependencies
