### ISSUE TITLE
Directive to set `pure = "on"` by default OR if no cdeps are in transitive dependencies

### ISSUE THREAD

**Issue by malt3** [bazelbuild/bazel-gazelle#1437]
### What version of gazelle are you using?

bazel-gazelle-af021617bef884e1e40afb01b692092a471d9a48 (latest commit)

### What version of rules_go are you using?

v0.37.0

### What version of Bazel are you using?

6.0.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

- 5.15.0-58-generic Ubuntu SMP x86_64 GNU/Linux
- Ubuntu 22.04.1

### What did you do?

I would like to find a way to set [`pure = "on"`](https://github.com/bazelbuild/rules_go/blob/master/go/modes.rst#building-pure-go-binaries) for BUILD files generated by gazelle. This would prevent me and my team from accidentally introducing new cgo dependencies and make go binaries independent from the cc toolchain by default.

### What did you expect to see?

A [directive](https://github.com/bazelbuild/bazel-gazelle#directives) to set `pure = "on"` for `go_binary` rules by default.

### What did you see instead?

I cannot find a way to set this as a default.

**Comment by Sovietaced** [comment]
Have you found a way to workaround this?

**Comment by AFMiziara** [comment]
You can add this to `.bazelrc` file:
```
# Disable CGO dependencies
build --@io_bazel_rules_go//go/config:pure
```

**Comment by alimoli** [comment]
> You can add this to `.bazelrc` file:
> 
> ```
> # Disable CGO dependencies
> build --@io_bazel_rules_go//go/config:pure
> ```
> 
> All available parameters that are exposed to be configured: https://github.com/bazelbuild/rules_go/tree/master/go/config

Thank you for the answer, very useful!
Just out of curiosity @AFMiziara, where is the part in this directive where `pure` is set to `on`?
Is it simply the `:pure` suffix here activating it?

**Comment by AFMiziara** [comment]
Exactly @alimoli !

**Comment by malt3** [comment]
Thanks. That looks great 👍
