### ISSUE TITLE
Can't import "golang.org/x/exp/slices" 

### ISSUE THREAD

**Issue by hulkholden** [bazelbuild/bazel-gazelle#1468]
### What version of gazelle are you using?

v0.29.0

### What version of rules_go are you using?

v0.38.1

### What version of Bazel are you using?

```
Bazelisk version: development
Build label: 6.1.0
Build target: bazel-out/darwin_arm64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Mar 6 17:10:27 2023 (1678122627)
Build timestamp: 1678122627
Build timestamp as int: 1678122627
```

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

macOS Venture 13.2, Apple M2 Max.

### What did you do?

See https://github.com/hulkholden/gazellerepro. I'm trying to import "golang.org/x/exp/slices". If `gazelle_dependencies` appears before `load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")` in my WORKSPACE.bazel, gazelle doesn't seem to generate a BUILD file for the slices subdirectory. This sounds a bit like #104 which is how I figured out to fix the problem by reordering things.

### What did you expect to see?

Successful build OR a useful error message. At the very least it would have been nice to see a warning like "encountered legacy rule in X, flipping to legacy mode" if that's what's going on.

### What did you see instead?

`no such package '@org_golang_x_exp//slices': BUILD file not found in directory 'slices' of external repository @org_golang_x_exp. Add a BUILD file to a directory to mark it as a package. and referenced by '//:gazellerepro_lib'`

**Comment by ramilmsh** [comment]
@hulkholden the issue is that older versions of `golang.org/x/exp` do not contain `/slices`. The simplest way to solve this is to upgrade the package version to the latest

in my case, I've done it with gazelle:

```
gazelle(
    name = "gazelle-golang-org-x-exp",
    args = [
        "golang.org/x/exp@v0.0.0-20230522175609-2e198f4a06a1",
    ],
    command = "update-repos",
)
```

**Comment by Multiply** [comment]
We're experiencing this again since the change in #1582 was reverted in #1615.

Is there a short-term fix, as we need to use the latest version of the slices packages?

**Comment by fmeum** [comment]
@tyler-french Was the downgrade of the `exp` package intentional? I missed it during the review.

**Comment by fmeum** [comment]
@Multiply You could add the contents of the reverted commit as a patch to your `http_archive` for gazelle.

**Comment by Multiply** [comment]
The overall issue for us isn't tied to x/exp, but rather latest version of x/exp updating x/tools as well, from the looks of it.
Seems like we can get by with an x/exp version from just before x/tools got updated to the latest version for now. 🚀

**Comment by tyler-french** [comment]
> @tyler-french Was the downgrade of the `exp` package intentional? I missed it during the review.

It was not. I just ran the releaser. I am a bit concerned because it looks like other deps were also changed.

Maybe there was some mistake I made while rebasing
