### ISSUE TITLE
Use gazelle to change MODULE.bazel

### ISSUE THREAD

**Issue by PandaBlueYellow** [bazelbuild/bazel-gazelle#1474]
Currently, is it possible to use gazelle to automatically update the MODULE.bazel used by bzlmod?
Otherwise, is it possible in future?

**Comment by seh** [comment]
#1404 is pertinent to address the need for changing the _MODULE.bazel_ file at all. @fmeum, take note.

**Comment by fmeum** [comment]
I am in a discussion with @Wyverald about how to do this properly. The current approach is somewhat flawed as auto_use_repo would need to rely on the `go_deps` extension to fix the `go_deps` extension's `use_repo` calls, but that [can fail if the user specified an incorrect `use_repo` call](https://github.com/bazelbuild/bazel/pull/17799).
