### ISSUE TITLE
Error when running `update-repos`: `flag provided but not defined: -repo_config`

### ISSUE THREAD

**Issue by cgrindel** [bazelbuild/bazel-gazelle#1493]
### What version of gazelle are you using?

0.30.0

### What version of rules_go are you using?

NA: Using bzlmod

### What version of Bazel are you using?

6.1.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

MacOS, x86_64

### What did you do?

1. Upgraded `MODULE.bazel` to 0.30.0.
2. Ran `update-repos` command that worked with 0.29.0.
  - [macro declaration](https://github.com/cgrindel/rules_swift_package_manager/blob/main/examples/firebase_example/BUILD.bazel#L31-L36)
  -  [macro impl](https://github.com/cgrindel/rules_swift_package_manager/blob/main/swiftpkg/internal/swift_update_packages.bzl#L71-L77)

### What did you expect to see?

Successful execution.

### What did you see instead?

Received the following error:
```
flag provided but not defined: -repo_config
gazelle: Try -help for more information
```

I double-checked my code to ensure I was not passing `-repo_config`. I noticed in [the code](https://github.com/bazelbuild/bazel-gazelle/blob/4dfcb75883c6ca2441e6ad17173488068adcfb1c/cmd/gazelle/fix-update.go#L88) that the flag is defined for `fix`/`update` and not for `update-repos`. Did this change recently?

**Comment by cgrindel** [comment]
@fmeum Do you have any thoughts on this? I can reproduce this error in two different repositories.

**Comment by cgrindel** [comment]
@seh @fmeum I think that I found the underlying issue. I added [a comment to the commit](https://github.com/bazelbuild/bazel-gazelle/commit/9c4a8d444274b09d67e583cdb80186296d73c54d#r107847801).

**Comment by fmeum** [comment]
This is a regression.

Cc @tyler-french

**Comment by cgrindel** [comment]
I just put up #1501. It adds a simple check for the Gazelle command before adding the `-repo_config` flag.
