### ISSUE TITLE
Add output mode for verification

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#15]
(Migrated from bazelbuild/rules_go#692)

Per discussion in #688, in addition to `-mode=print,fix,diff`, Gazelle should have an output mode where it exits successfully (code 0) if all files are up to date and unsuccessfully (code 1) if there are differences. It may print a list of differing files.

This could be used in a `gazelle_test rule`, which would be useful as a presubmit.

**Comment by ciarand** [comment]
Is this `gazelle_test` thing still a desired goal? The `buildifier_test` equivalent recently (ish) [got support for a no_sandbox field](https://github.com/bazelbuild/buildtools/commit/762712d8ce3ff3aa361b36d50688eb4ab7884637) which is the equivalent of running against the whole repo (while still generating test reports that are readable by CI systems). If I were to open a MR with an equivalent change in this repo would it be considered for merging?
