### ISSUE TITLE
How can I use the go_deps extension to apply patches to a generated dependency?

### ISSUE THREAD

**Issue by aaronmondal** [bazelbuild/bazel-gazelle#1521]
### What version of gazelle are you using?

Custom checkout from commit 23226de, vendored in a bazel registry.

### What version of rules_go are you using?

0.39.1

### What version of Bazel are you using?

6.1.2

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Gentoo x86_64

### What did you do?

I need to patch a transitive cgo dependency. How can I apply a patch to `"an_implicit_dependency_in_need_of_patching"`? In general, how can I override the attributes of dependencies that are generated this way?

```python
# MODULE.bazel
bazel_dep(name = "rules_go", version = "0.39.1")
bazel_dep(name = "gazelle", version = "23226de")
go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")

# Generates ~100 deps. I need to only patch "an_implicit_dependency_in_need_of_patching"
use_repo(
    go_deps,
    "some_primary_dependency_with_many_deps",
)
```

In case this is not possible yet, how can I tell gazelle to skip it when reading `go.mod` and use a provided `bazel_dep` instead?

@fmeum @tyler-french @seh

**Comment by seh** [comment]
Perhaps the `go_deps.module_override` tag's "patches" field would help here, if you can specify the Go module path that leads to the creation of this "an_implicit_dependency_in_need_of_patching" Bazel repository.

**Comment by aaronmondal** [comment]
Ahh that works! What a nice user experience to not have to carry around `deps.bzl` :tada: 

```python
# MODULE.bazel
go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
go_deps.module_override(
    path = "github.com/org/project",
    patches = [
        "@myproject//patches:some_custom_patch.diff",
    ],
    patch_strip = 1,
)
```

@seh Thanks a lot for the help :heart:
