### ISSUE TITLE
Epoch timestamp in diff mode output confuses `git apply`

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel-gazelle#1528]
### What version of gazelle are you using?

v0.30.0

### What version of rules_go are you using?

v0.39.1

### What version of Bazel are you using?

6.1.2

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Debian Linux. x86_64

### What did you do?

Stored the output of `gazelle update -mode=diff` in a file where a change is being made to an existing BUILD file, and then provided the file to `git apply`.

### What did you expect to see?

Patch correctly parsed and applied to the git worktree.

### What did you see instead?

git complains that a new file depends on old contents ([source code](https://github.com/git/git/blob/69c786637d7a7fe3b2b8f7d989af095f5f49c3a8/apply.c#L1778)).

This happens because gazelle outputs the epoch as the modification timestamp for all files. While unified format [spec](https://www.gnu.org/software/diffutils/manual/html_node/Detailed-Unified.html) does not really have any special meaning given to the epoch timestamp, GNU diff does give some special meaning to the epoch timestamp ([doc](https://www.gnu.org/software/diffutils/manual/html_node/Creating-and-Removing.html)). Given this treatment by GNU diff, `git apply` interprets the epoch timestamp as a file creation/deletion event ([source code](https://github.com/git/git/blob/69c786637d7a7fe3b2b8f7d989af095f5f49c3a8/apply.c#L895)). And so, to `git apply`, all files in the diff output of gazelle look like file creation events.

We could file this as a bug in git, but I doubt it will move anywhere because this behavior has been there for some time, and people may have depended on it. It might be more reasonable for gazelle to stop outputting epoch timestamps.

**Comment by fmeum** [comment]
Happy to review a PR that replaces the hard-coded timestamp in https://github.com/bazelbuild/bazel-gazelle/blob/3a1235c298b7dc11fa7ba994db4f92587c1aca79/cmd/gazelle/diff.go#L39 with one that has no special meaning.

**Comment by siddharthab** [comment]
> Happy to review a PR

Sent #1552.
