### ISSUE TITLE
gazelle replaces a define with the verbatim value in the importpath attr

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel-gazelle#153]
I have a BUILD file like this:
```
package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

IMPORTPATH = "github.com/foo/cmd/client"

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = IMPORTPATH,
    visibility = ["//visibility:private"],
    deps = [ ... ],
)

go_test(
    name = "go_default_test",
    size = "small",
    srcs = [
        "main_test.go",
    ],
    embed = [":go_default_library"],
    importpath = IMPORTPATH,
    visibility = ["//visibility:private"],
    deps = [ ... ],
)

load("@io_bazel_rules_docker//go:image.bzl", "go_image")

go_image(
    name = "client",
    base = "@cc_image_base//image",
    embed = [":go_default_library"],
    importpath = IMPORTPATH,
)

go_binary(
    name = "client",
    embed = [":go_default_library"],
)
```

after running `bazel run //:gazelle` the importpath on the go_library (1st rule) is replaces with the real value. I saw from https://github.com/bazelbuild/bazel-gazelle/releases/tag/0.10.0 that importpath is deprecated for go_binary and go_test, but it actually did not remove the attribute there (please note that go-image is-a go_binary).

**Comment by jayconrod** [comment]
Gazelle considers `importpath` to be a *mergeable* attribute, meaning it will modify it when it's different than what Gazelle thinks it should be. For scalar attributes like this, Gazelle will replace whatever's there, even if it's not a string. You can prevent Gazelle from modifying it by adding a `# keep` comment after the attribute or before the rule.

```
go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = IMPORTPATH,  # keep
    visibility = ["//visibility:private"],
    deps = [ ... ],
)
```

`importpath` is deprecated for `go_test` and `go_binary` only. It's still required for `go_library`. Gazelle doesn't recognize `go_image` as a generated rule, so it will ignore that one. #18 is a proposal to tell Gazelle about wrappers that have a similar interface but different kind to rules that Gazelle generates.

**Comment by ensonic** [comment]
I've cleanup the deprectaed use. I think I was configured because it replaced one and did not touch the deprecated ones.

**Comment by pcj** [comment]
FYI workaround for me is to keep a `None` placeholder for the importpath:

```
go_test(
    name = "go_default_test",
    size = "small",
    srcs = ["kv_test.go"],
    embed = [
        ":go_default_library",
    ],
    importpath = None,  #keep
)
```
