### ISSUE TITLE
bazel run gazelle cannot be run with package-dirs args

### ISSUE THREAD

**Issue by pjk25** [bazelbuild/bazel-gazelle#1540]
### What version of gazelle are you using?

0.30.0

### What version of rules_go are you using?

0.39.1

### What version of Bazel are you using?

6.2.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

macos, amd64

### What did you do?

After upgrading gazelle to 0.30.0, passing package-dir args no longer works when running gazelle with bazel (`bazel run gazelle -args subpackage`)

### What did you expect to see?

Should work as before

### What did you see instead?

`gazelle: -repo_config: failed to resolve symlinks: lstat /Users/.../-repo_config: no such file or directory`

This appears to be a side effect of the injection of the `-repo_config` arg as the last arg in the `gazelle-runner.bash`. This causes gazelle to treat `-repo_config` as an additional subdir of the repo_root, and fails. This appears to be a relatively recent change in https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/gazelle.bash.in

**Comment by pjk25** [comment]
This is close to https://github.com/bazelbuild/bazel-gazelle/pull/1501 but no exactly the same

**Comment by fmeum** [comment]
Should be fixed in 0.31.0.
