### ISSUE TITLE
Allow specifying godeps.{gazelle,module}_override with a config file

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel-gazelle#1550]
We have way too many `godeps.{gazelle,module}_override` calls in `MODULE.bazel`, and the size of file keeps growing. As https://github.com/bazelbuild/bazel/issues/14632 is not going anywhere. Is it a good idea to load relevant tags from a config file?

```starlark
go_deps.from_file(
  go_mod = "//third_party/go:go.mod",
  overrides = "//third_party/go:dep_overrides.json",
)
```

And the `dep_overrides.json` could be:

```
{
	"github.com/cloudflare/circl": {
		"patches": [
			"@rules_ll//patches:go_circl_header_fix.diff"
		],
		"patch_strip": 1
	}
}
```

(Though I hate the fact that the existing json module with starlark doesn't support json file comments and trailing commas.)

**Comment by fmeum** [comment]
@ashi009 Could you provide some details on why that file is so large? What are the common types of overrides you need to apply? 

If they concern public modules, have you considered contributing to https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/bzlmod/default_gazelle_overrides.bzl? https://github.com/bazelbuild/bazel-gazelle/pull/1526 will provide a similar capability for `module_override`.

That said, it's definitely possible that this won't be sufficient and some way to segment the file is needed. However, I would first like to give https://github.com/bazelbuild/bazel/issues/17880 a chance before introducing a solution specific to rules_go.

**Comment by ashi009** [comment]
> @ashi009 Could you provide some details on why that file is so large? What are the common types of overrides you need to apply?
> 

A few things:

- patches - bug fixes, security patches, unmerged upstream PRs
- replaces - replace certain modules with our internal log adaptor
- protogen directive - we have lots of internal deps with both proto file and generated go files, and we need to disable the protogen for that

Therefore the file becomes gigantic. In the past, we were able to segment the WORKSPACE in bzl files, which allows us to maintain those in a dedicated go.bzl file, which is then reviewed by go experts for approvals.

**Comment by fmeum** [comment]
I proposed a potential design in https://github.com/bazelbuild/bazel/issues/17880#issuecomment-1574144457. I have a very strong preference for doing this a) in Starlark and b) in Bazel, not individual rulesets. 

Let's try to come up with a good design over at https://github.com/bazelbuild/bazel/issues/17880. If that fails, we can reconsider a Gazelle-specific solution.
