### ISSUE TITLE
Transitive dependency: missing strict dependencies

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel-gazelle#156]
Example repo: https://github.com/prestonvanloon/libp2p-chat/commit/03c458ba28fd4269b0c4fc5a50784119a6b89f5f

**Command**
```
bazel build //chat
```

**Expected**

Chat binary builds

**Actual** 

```
 /home/preston/.cache/bazel/_bazel_preston/7124606768f837af1d78732c4a470bda/external/com_github_gxed_eventfd/BUILD.bazel:3:1: GoCompile external/com_github_gxed_eventfd/linux_amd64_stripped/go_default_library~/github.com/gxed/eventfd.a failed (Exit 1)
2018/03/14 23:07:46 missing strict dependencies:
        external/com_github_gxed_eventfd/eventfd.go: import of github.com/gxed/GoEndian, which is not a direct dependency
Target //chat:chat failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 221.624s, Critical Path: 18.05s
FAILED: Build did NOT complete successfully
```
I have seen issue #123, but I don't think this is related to proto rules. This is a dependency that depends on something else.

Here's [command.log](https://github.com/bazelbuild/bazel-gazelle/files/1813895/command.log) with full output of the above command.

**Comment by jayconrod** [comment]
Changing `github.com/gxed/goendian` to `github.com/gxed/GoEndian` in WORKSPACE fixes this.

This error comes up when a .go file imports a package with an import path that is not provided by any of the libraries in `deps`. In this case, eventfd.go imports `github.com/gxed/GoEndian`, but that repository is declared with the prefix `github.com/gxed/goendian`. All the `go_library` rules generated for that repository will have `importpath` attributes that start with that prefix.

I've filed #157 to automatically correct the case of import paths when they are added or updated in WORKSPACE.

**Comment by prestonvanloon** [comment]
Wonderful, thank you for looking

**Comment by prestonvanloon** [comment]
FYI, these dependencies were created by hand. So i'm not sure that #157 is correct.

gazelle doesn't support gx package manager, as far as I know

**Comment by prestonvanloon** [comment]
I think this is can be considered closed.
The problem was that I didn't maintain the repository importpath case and I was doing these by hand .

I would like to use update-repos with [gx package manager](https://github.com/whyrusleeping/gx) which has a `package.json` list of dependencies.

**Comment by prestonvanloon** [comment]
Created feature request: #158
