### ISSUE TITLE
Do not generate `WORKSPACE` code when running `update-repos` for bzlmod enabled workspaces

### ISSUE THREAD

**Issue by cgrindel** [bazelbuild/bazel-gazelle#1588]
### What version of gazelle are you using?

0.41.0

### What version of rules_go are you using?

0.32.0

### What version of Bazel are you using?

6.3.0

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

MacOS / x86_64

### Feature Request

For rule repositories that build with bzlmod enabled but still support legacy clients, it is necessary to generate a `go_deps.bzl`. In addition to generating the `go_deps.bzl`, running `update-repos` will add code to the `WORKSPACE` to load the `go_deps.bzl`. It would be nice to generate the `go_deps.bzl` without updating the `WORKSPACE`.

I propose adding a flag to `update-repos` called `--bzlmod`. When this flag is present, running `update-repos` with the `-to_macro=go_deps.bzl%my_go_dependencies` flag will generate the `go_deps.bzl`, but not update the `WORKSPACE`. 

For example,

```python
gazelle(
    name = "gazelle_update_repos",
    args = [
        "-from_file=go.mod",
        "-to_macro=go_deps.bzl%my_go_dependencies",
        "-build_external=external",
        "-bzlmod",      # <=== New flag
        "-prune",
    ],
    command = "update-repos",
)
```

If the `-bzlmod` flag is enabled and the `-to_macro` flag is not specified, the Go `update-repos` code will do nothing (i.e., no updates to `WORKSPACE`, no `go_deps.bzl`).

**Comment by cgrindel** [comment]
@fmeum This is related to [this thread](https://bazelbuild.slack.com/archives/C01HMGN77Q8/p1690477265792089). The nuance from the previous discussion is that there is a case when I do want to generate `go_deps.bzl` even when the rule repository builds with bzlmod enabled.

**Comment by cgrindel** [comment]
BTW, I will put up a PR with this feature. However, I wanted to discuss it with the community first.

**Comment by fmeum** [comment]
Instead of a new flag, can we use https://github.com/bazelbuild/bazel-gazelle/blob/d2032781c7d4611ce778360ca345d86a97e06956/config/config.go#L109? We can still generate the `.bzl` file if and only if `-to_macro` is specified even with Bzlmod, but we should not update `WORKSPACE`, just as you mentioned.

**Comment by cgrindel** [comment]
I didn't realize [the -bzlmod flag already exists](https://github.com/bazelbuild/bazel-gazelle/blob/d2032781c7d4611ce778360ca345d86a97e06956/config/config.go#L209). This is exactly what I was proposing. I just need to update the logic.
