### ISSUE TITLE
Map Go imports of WKTs to rules_go

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#159]
Originally reported in bazelbuild/rules_go#1386.

When a WKT is imported in a .proto file, we don't generate a dependency in `go_proto_library`, since the compiler is expected to provide those. The official WKTs are defined in `@io_bazel_rules_go//proto/wkt`.

When a WKT is imported in a .go file, we treat it as a normal Go import. For example, see https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/internal/protostruct/protostruct.go#L19. `github.com/golang/protobuf/ptypes/struct` will be resolved as `@com_github_golang_protobuf//ptypes/struct:go_default_library`. We should resolve it as `@io_bazel_rules_go//proto/wkt:struct_go_proto` instead.

**Comment by jwahlin** [comment]
I'm still getting the "references multiple files" error with the latest version of Gazelle's go_repository rule.
```
src/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go: references multiple files (bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_go/proto/wkt/darwin_amd64_stripped/descriptor_go_proto~/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go and external/com_github_golang_protobuf/protoc-gen-go/descriptor/descriptor.pb.go)
```
I think a go_library is getting created for the external/com_github_golang_protobuf/protoc-gen-go/descriptor/descriptor.pb.go file. No target should be created for this file since a target with the same importpath is already generated by Gazelle, right?

Thanks for your help.

**Comment by jayconrod** [comment]
Reopening. descriptor is another special case that might not have been handled correctly by the fix for this.

**Comment by jwahlin** [comment]
Great, thanks for looking into this.

**Comment by jwahlin** [comment]
Is this corrected for you? I'm still seeing this in my bazel-sandbox/external/com_github_golang_protobuf/protoc-gen-go/descriptor BUILD file:
<pre>load("@io_bazel_rules_go//go:def.bzl", "go_library")

filegroup(
    name = "go_default_library_protos",
    srcs = ["descriptor.proto"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    srcs = ["descriptor.pb.go"],
    importpath = "github.com/golang/protobuf/protoc-gen-go/descriptor",
    visibility = ["//visibility:public"],
    deps = ["//proto:go_default_library"],
)</pre>

The rules_go well_known_types.bzl file is generating a go_proto_library with the same importpath: <pre>github.com/golang/protobuf/protoc-gen-go/descriptor</pre>

I see the same thing with other golang/protobuf protos.  I'm loading the following versions of rule_go and gazelle in my workspace:
<pre>
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "c1f52b8789218bb1542ed362c4f7de7052abcf254d865d96fb7ba6d44bc15ee3",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.12.0/rules_go-0.12.0.tar.gz",
)
git_repository(
    name = "bazel_gazelle",
    commit = "7f30ba724af9495b221e2df0f5ac58511179485f",  # master as of 2018-05-08
    remote = "https://github.com/bazelbuild/bazel-gazelle",
)</pre>

Any suggestions?

**Comment by jayconrod** [comment]
Are you still getting errors about the same library being referenced multiple times in a build or the same file being referenced multiple times in a `go_path`?

The `go_library` rule for `github.com/golang/protobuf/protoc-gen-go/descriptor` should still be generated, but it shouldn't be the target of dependency resolution in any other library, so you shouldn't end up depending on it.

**Comment by jwahlin** [comment]
It seems related to the org_golang_google_genproto dependency. When I add that to my workspace above go_rules_dependencies(), I don't get the error. As soon as I remove it, I see this again:
<pre>
ERROR: /Users/jamie/go/src/git.tcncloud.net/m/lms/BUILD.bazel:11:1: in go_path rule //:path:
Traceback (most recent call last):
        File "/Users/jamie/go/src/git.tcncloud.net/m/lms/BUILD.bazel", line 11
                go_path(name = 'path')
        File "/private/var/tmp/_bazel_jamie/eaca13e5f53a0c8d50578bee4374bf97/external/io_bazel_rules_go/go/private/tools/path.bzl", line 72, in _go_path_impl
                _add_manifest_entry(manifest_entries, manifest_entry_m..., <3 more arguments>)
        File "/private/var/tmp/_bazel_jamie/eaca13e5f53a0c8d50578bee4374bf97/external/io_bazel_rules_go/go/private/tools/path.bzl", line 174, in _add_manifest_entry
                fail("{}: references multiple files (...))
src/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go: references multiple files (external/com_github_golang_protobuf/protoc-gen-go/descriptor/descriptor.pb.go and bazel-out/darwin-fastbuild/bin/external/io_bazel_rules_go/proto/wkt/darwin_amd64_pure_stripped/descriptor_go_proto~/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go)
</pre>

**Comment by jwahlin** [comment]
If you need me to put an example up, let me know.

**Comment by jayconrod** [comment]
Ah, thanks for your comment about `org_golang_google_genproto`. I was able to reproduce, and I think I see what the issue is. I regenerated the build files for that repo before the fix in Gazelle landed, so they have some conflicting deps. I'll put together a PR to regenerate those.

**Comment by jwahlin** [comment]
Do we need to reference these go libraries like this now:
<pre>@io_bazel_rules_go//proto/wkt:duration_go_proto</pre>
instead of this?
<pre>@com_github_golang_protobuf//ptypes/duration:go_default_library</pre>

I'm also depending on grpc-gateway which references the go libraries like this:
<pre>@com_github_golang_protobuf//ptypes/duration:go_default_library</pre>
and that also seems to be causing the "references multiple files" error.

**Comment by jayconrod** [comment]
`@io_bazel_rules_go//proto/wkt` should be considered canonical now. Gazelle will resolve dependencies on WKTs to rules in that directory.

Since Gazelle hasn't been doing this correctly for a while, there are a lot of build files out there which will cause conflicts. I'm not really sure there's a solution for this, other than updating those files.

@achew22 Do you think there would be any issues updating those dependencies? I'm happy to put together a PR tomorrow. This would work rules_go versions since March 1 (0.11.0 or later).

**Comment by jayconrod** [comment]
I thought of a better approach. I'm going to replace the `go_library` rules for WKTs in `@com_github_golang_protobuf` and `@org_golang_google_genproto` with `alias` rules that point to rules in `@io_bazel_rules_go//proto/wkt`.
