### ISSUE TITLE
language/go/generate_test.go TestGenerateResult spuriously passing

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel-gazelle#1593]
### What version of gazelle are you using?

commit fa6d6eab293df1f27ab6e97e3f6a6821e95306d2

### What version of rules_go are you using?

v0.39.1

### What version of Bazel are you using?

bazel 6.3.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

n/a

### What did you do?

1. Modify `language/go/testdata/bin/BUILD.want` to introduce an erroneous `srcs`
2. Run `bazel test //languge/go:go_test`

### What did you expect to see?

A failure.

### What did you see instead?

Success.

Digging in a bit more, the test harness loops through `regularFiles` provided by `walk.Walk`, but all of the files in the runfiles subdirectory are symlinks, thus skipped by `Walk` (as documented).  The end result is a spurious failure.

**Comment by fmeum** [comment]
Nice catch! 

Given that you have already looked into this test in detail, do you have a suggestion for fixing it?

**Comment by shahms** [comment]
Having walk include symlinks-to-files in `regularFiles` would fix it, but seems like a potentially breaking change.

Although, it looks like the `follow` directive is set to a member but not currently *read* anywhere, so that might be a potential avenue.
