### ISSUE TITLE
Enable generating go_test targets per _test.go file in a directory

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel-gazelle#1594]
Similar to #1417, I'd like to add support for generating a distinct go_test target per _test.go file in a directory/package.  This would facilitate, for example, separating tests based on size, execution requirements, etc. without having to manually maintain dependencies or the file as a whole.

I've actually prepared a local patch implementing this behavior for Kythe and am hoping to be able to contribute it upstream.

**Comment by pqn** [comment]
Glad to see #1597 merged. Is there a recommended way to maintain a library of test files in the same directory when using `file` mode? Previously I relied on the `_test.go` suffix to ensure separation from the main library. I can't seem to make a second `go_library` work -- Gazelle then updates all dependency references to this new library, even if I make it `testonly=True` and private visibility.

**Comment by pqn** [comment]
Related: https://github.com/bazelbuild/bazel-gazelle/issues/1365
