### ISSUE TITLE
docs on using gazelle with bzlmod 

### ISSUE THREAD

**Issue by pdeva** [bazelbuild/bazel-gazelle#1622]
all the documentation seems to be around using gazelle with `WORKSPACE` file. there should be some documentation on using it with `bzlmod` and/or to migrate old `WORKSPACE` gazelle code to `bzlmod`

**Comment by fmeum** [comment]
We have https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md. 

If that's what you were looking for, but in a different place, please send a PR adding a link there!
