### ISSUE TITLE
Don't exclude hidden directories

### ISSUE THREAD

**Issue by fxposter** [bazelbuild/bazel-gazelle#164]
If the application depends on packages, which names start with `_` (in my case it's https://github.com/newrelic/go-agent/tree/master/_integrations/nrpkgerrors) - gazelle will just not generate a BUILD file for it.

By looking at gazelle's code I see that such packages are indeed ignored: https://github.com/bazelbuild/bazel-gazelle/blob/257c283f6dd0d177cad931f3e6897f07fed5b41e/internal/packages/walk.go#L173.

Is it possible to find out the reasons for such decision?

**Comment by jayconrod** [comment]
Gazelle skips "hidden" files and directories, i.e., those starting with dots and underscores. This is done for two reasons:

* The Go toolchain also skips these. `go build` ignores hidden files, and `go list` skips hidden packages.
* People take advantage of this fact and sometimes put unbuildable code (test data, examples) in these directories.

It seems `go build` lets you import packages with hidden names though, even if `go list` doesn't report them, so maybe we shouldn't skip them.
