### ISSUE TITLE
Bzlmod: allow build_extra_args in gazelle_override

### ISSUE THREAD

**Issue by casuallyhostile** [bazelbuild/bazel-gazelle#1647]
### What version of gazelle are you using?

0.33.0

### What version of rules_go are you using?

0.41.0

### What version of Bazel are you using?

6.3.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS arm64

### What did you do?

I'm taming gazelle with `bzlmod` and want to pass an `build_extra_args` to `gazelle_override` e.g.

```starlark
go_deps.gazelle_override(
    build_extra_args = ["-exclude=src"],
    path = "github.com/census-instrumentation/opencensus-proto",
)
```
fixing issue like 
https://github.com/census-instrumentation/opencensus-proto/issues/200#issuecomment-622610454

**Comment by fmeum** [comment]
This looks reasonable at least at first glance as this can't be pushed into a directive.

@tyler-french What do you think?
