### ISSUE TITLE
Bzlmod: (feature request) support setting go_env like before

### ISSUE THREAD

**Issue by yckbilly1929** [bazelbuild/bazel-gazelle#1653]
In previous WORKSPACE mode, we can modify go env using
```
gazelle_dependencies(
    go_env={
        "CGO_ENABLED": "0",
        "GOPRIVATE": "gitlab.com/my-private-repo",
    },
)
```

After migrating to bzlmod, we find nowhere to do the same modification, and it was not mentioned in https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md. It blocks us from migrating to bzlmod as we need to set `GOPRIVATE` to access other private repos within the company.

After investigation, it seems like this feature is removed here:
https://github.com/bazelbuild/bazel-gazelle/blob/d8369a6b0d891546948219a064b63a0a12bb2794/internal/bzlmod/non_module_deps.bzl#L39C9-L39C16

Our current workaround is to manually edit the generated `go.env` file under `gazelle~0.33.0~non_module_deps~bazel_gazelle_go_repository_cache`.

**Comment by yckbilly1929** [comment]
It turns out we don't need this at all, running `bazel` command with CGO_ENABLED and GOPRIVATE suffices.

My issue might be related to slow ssh, behind proxy. 🤔

**Comment by fmeum** [comment]
You could also use `--repo_env` if you want to add these values to `.bazelrc`.
