### ISSUE TITLE
Build fails when importing protobuf from another package

### ISSUE THREAD

**Issue by tinkerbeast** [bazelbuild/bazel-gazelle#1659]
### What version of gazelle are you using?

Not using gazelle.

### What version of rules_go are you using?

Not using golang.

### What version of Bazel are you using?

Docker based Bazel -
```
Build label: 6.4.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 19 17:07:43 2023 (1697735263)
Build timestamp: 1697735263
Build timestamp as int: 1697735263
```

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux 6.2.0-36-generic 22.04.1-Ubuntu x86_64

### What did you do?

My directory structure is as follows:
```
├── proto
│   ├── BUILD
│   └── hello.proto
├── src
│   ├── BUILD
│   └── outer.proto
└── WORKSPACE
```
The `WORKSPACE` file loads and `http_archive` for `com_google_protobuf`. The version is "https://github.com/protocolbuffers/protobuf/archive/v3.25.0.tar.gz" which is more or less the latest.

The `proto/hello.proto` file:
```
load("@rules_proto//proto:defs.bzl", "proto_library")
package(default_visibility = ["//visibility:public"])
proto_library(
    name = "hello_proto",
    srcs = ["hello.proto"],
)
```
The `proto/BUILD` file:
```
load("@rules_proto//proto:defs.bzl", "proto_library")
package(default_visibility = ["//visibility:public"])
proto_library(
    name = "hello_proto",
    srcs = ["hello.proto"],
)
```
The `src/outer.proto` file:
```
syntax = "proto3";
import "proto/hello.proto"; // What path to import from?
message OuterMessage {
  HelloRequest req = 1;
  HelloReply resp = 2;
}
```
The `src/BUILD` file:
```
load("@rules_proto//proto:defs.bzl", "proto_library")
proto_library(
    name = "outer_proto",
    srcs = ["outer.proto"],
    deps = ["//proto:hello_proto"],
)
```
### What did you expect to see?

Build go through.

### What did you see instead?
```
src/outer.proto:6:3: "HelloRequest" is not defined.
src/outer.proto:7:3: "HelloReply" is not defined.
Target //src:outer_proto failed to build
```

**Comment by fmeum** [comment]
This doesn't seem to be related to either Gazelle or rules_go. I would recommend asking over at https://slack.bazel.build/.
