### ISSUE TITLE
Respect --symlink_prefix bazel setting

### ISSUE THREAD

**Issue by excavador** [bazelbuild/bazel-gazelle#168]
If configure bazel (tools/bazel.rc) by following option:
```
--symlink_prefix=bazel/
```
gazelle will try to inspect bazel directories.

Need to respect this option in some way.
For start would be enough add option to 'gazelle' run rule.

**Comment by jayconrod** [comment]
I think the best way to ignore these is adding `# gazelle:exclude` directives in your root build file. This will prevent Gazelle from recursing into those directories.

```
# gazelle:exclude bazel
```

There are too many complications around Bazel rc files for Gazelle to parse them and figure this automatically. They can be stored in several different places (some checked in, some not), and flags can be conditional (depending on the configuration).

**Comment by excavador** [comment]
@jayconrod nice workaround, thank you, but would be great to have direct solution.

**Comment by ryanrhee** [comment]
As of now, the `gazelle:exclude` workaround does not stop gazelle from inspecting bazel directories.

**Comment by cpsauer** [comment]
Hey guys!

I made some incremental progress towards this while writing #1384. Saving out mental state here

It seems like a good fix for this issue would involve invoking `bazel info output_base`, in repo.go and walk.go, removing the hardcoding of bazel-out , assuming it's okay to invoke Bazel from within gazelle?
