### ISSUE TITLE
Missing documentation and best practices for bzlmod

### ISSUE THREAD

**Issue by alimoli** [bazelbuild/bazel-gazelle#1715]
I tried to follow the [tutorial](https://bazel.build/external/migration) for the migration from the legacy WORKSPACE (version 6.3.2) to `bzlmod` (enabled by default using version 7.0.0, the version that I am migrating to).

Considering my current environment, a monorepo composed of multiple Go projects using go-modules and docker rules to create build/push the images, I am finding it quite tricky to follow.

First of all, I have the feeling there are no "best practices" for Go projects with Bazel.

_Example_
Should I prefer a design where I have a MODULE.bazel for each project in the monorepo? 
Or should I have one single MODULE.bazel for the entire monorepo at the WORKSPACE level (as suggested in the tutorial)?

Secondly, I am not able to find documentation to adapt gazelle with bzlmod. 

Thank you in advance for your help.

**Comment by fmeum** [comment]
The docs exist, they just aren't sufficiently discoverable: https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md

@tyler-french What do you think, is it time to make the Bzlmod instructions the default?

**Comment by fmeum** [comment]
> Or should I have one single MODULE.bazel for the entire monorepo at the WORKSPACE level (as suggested in the tutorial)?

I would say that a monorepo should really have one `MODULE.bazel` file, just like it had one `WORKSPACE` file.

**Comment by fmeum** [comment]
You are affected by this bug: https://github.com/bazelbuild/bazel/issues/20721

Could you try again with Bazel 7.0.1rc1?

**Comment by fmeum** [comment]
That error means that you need to update the `load` in your top-level BUILD file to be from `gazelle` rather than `bazel_gazelle`. You can of course keep using the old names with `repo_name`.

**Comment by fmeum** [comment]
That failure is expected, you aren't declaring any external dependencies. That is what the `go_deps` extension is for, see https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md#external-dependencies.
