### ISSUE TITLE
gazelle looking for WORKSPACE in bzlmod enabled project

### ISSUE THREAD

**Issue by udf2457** [bazelbuild/bazel-gazelle#1734]
When run as follows:

```
gazelle(
    name = "gazelle-update-repos",
    args = [
        "-from_file=go.mod",
        "-prune",
    ],
    command = "update-repos",
)
```

`gazelle` errors out with:

```
gazelle: loading WORKSPACE file: open /Users/<REDACTED>/WORKSPACE: no such file or directory
make: *** [gazelle-update] Error 1
```

The internet led me to #1588 which makes mention of a `-bzlmod` flag, but [the linked source](https://github.com/bazelbuild/bazel-gazelle/blob/ec1591cb193591b9544b52b98b8ce52833b34c58/config/config.go#L209) states `for internal usage only`.

So what is the correct way of stopping `update-repos` for trying to work with the legacy `WORKSPACE` ?

**Comment by fmeum** [comment]
You should be able to work around this by using https://github.com/bazelbuild/bazel-gazelle/commit/62d7108a26601cb5b9f6a787d79f83527ba865a6 and passing `-bzlmod`.

However, when using Bzlmod, you shouldn't really need `update-repos` for Go repos anymore. What are you using it for?

**Comment by udf2457** [comment]
You're right @fmeum , I eventually stumbled accross [the bit in the docs that says to use go_deps instead ](https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md#specifying-external-dependencies)

I guess I must have got the idea from elsewhere.  Still a bazel noob ! :blush:

**Comment by brentleyjones** [comment]
Would be nice if we could get a release with 62d7108a26601cb5b9f6a787d79f83527ba865a6 in it. I'm trying to use it in a project without a `WORKSPACE` file and it fails on this error.
