### ISSUE TITLE
Gazelle reports "could not merge expression" when using select statements in hdrs or srcs

### ISSUE THREAD

**Issue by hofbi** [bazelbuild/bazel-gazelle#1735]
### What version of gazelle are you using?

`bazel_dep(name = "gazelle", version = "0.35.0")`

### What version of rules_go are you using?

`bazel_dep(name = "rules_go", version = "0.46.0")`

### What version of Bazel are you using?

`7.0.2`

### Does this issue reproduce with the latest releases of all the above?

Yes, thats what we use

### What operating system and processor architecture are you using?

Ubuntu 20.04 x86

### What did you do?

1. I use a select statement in `hdrs` or `srcs` with `@platforms//os:XXX` as key
2. For some platforms such as `@platforms//os:windows`, `@platforms//os:linux`, `@platforms//os:ios`the merge works fine, while for others such as `@platforms//os:qnx` or `@platforms//os:osx` this results in a `could not merge expression` error

### What did you expect to see?

The same behavior as for the other platforms

### What did you see instead?

`could not merge expression` error

**Comment by hofbi** [comment]
Maybe https://github.com/bazelbuild/bazel-gazelle/blob/ec1591cb193591b9544b52b98b8ce52833b34c58/rule/platform.go#L51 is a good starting point, since it looks like the issue happens for all platforms not part of this list.

**Comment by hofbi** [comment]
I still see this issue for Bazel 7.2.1 and Gazelle 0.37.0. Do you think it would be enough adding the missing platforms to https://github.com/bazelbuild/bazel-gazelle/blob/ec1591cb193591b9544b52b98b8ce52833b34c58/rule/platform.go#L51? I can see a depratation message there so not sure if I should add something there?

**Comment by fmeum** [comment]
It's deprecated only for use outside of Go. Feel free to submit a PR to add new platforms!

**Comment by hofbi** [comment]
Created https://github.com/bazelbuild/bazel-gazelle/pull/1853, working on the CLA

**Comment by fmeum** [comment]
@hofbi Could you also submit a commit to rules_go that adds these platforms there? It looks like they don't exist yet and thus result in error messages: https://github.com/bazelbuild/bazel-gazelle/issues/1862#issuecomment-2285821433

**Comment by hofbi** [comment]
@fmeum I came up with https://github.com/bazelbuild/rules_go/pull/4036

**Comment by hofbi** [comment]
https://github.com/bazelbuild/bazel-gazelle/pull/1853 has fixed this
