### ISSUE TITLE
update-repos: accept -build_file_name, -build_file_generation and other options

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#175]
When these options are provided to `update-repos`, it should generate or update `go_repository` rules with the corresponding attributes. For example:

```
$ gazelle update-repos -build_file_name=BUILD.bazel github.com/pkg/errors
```

should create the rule:

```
go_repository(
    name = "com_github_pkg_errors",
    importpath = "github.com/pkg/errors",
    build_file_name = "BUILD.bazel",
    commit = "123456",
)
```

If the rule exists, the `build_file_name` attribute should be changed to match the command line.

This should work for `-from_file` as well.

**Comment by blico** [comment]
👍 

This feature would be useful for us to set the `build_file_proto_mode` attribute.
