### ISSUE TITLE
Transitive Go dependencies not included when using `go_deps.from_file`

### ISSUE THREAD

**Issue by recht** [bazelbuild/bazel-gazelle#1764]
### What version of gazelle are you using?

0.35.0

### What version of rules_go are you using?

0.46.0

### What version of Bazel are you using?

7.1.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

A Go project which imports eg `github.com/matrix-org/dendrite/setup`. This adds `github.com/matrix-org/dendrite v0.13.6` to `go.mod`, but transitive dependencies are not in `go.mod`. This means the project can't build but fails with this:
```
WARNING: /home/joakim/code/MODULE.bazel:43:24: The module extension go_deps defined in @bazel_gazelle//:extensions.bzl reported incorrect imports of repositories via use_repo():

Imported, but not created by the extension (will cause the build to fail):
    com_github_arceliar_phony

Fix the use_repo calls by running 'bazel mod tidy'.
ERROR: Analysis of target '//dendrite' failed; build aborted: module extension "go_deps" from "@@gazelle~//:extensions.bzl" does not generate repository "com_github_arceliar_phony", yet it is imported as "com_github_arceliar_phony" in the usage at /home/joakim/code/MODULE.bazel:43:24
```

That dependency is in dendrite's `go.mod`, but isn't picked up by `from_file` since it only looks at the local `go.mod`. 

As far as I know there's no way to resolve this by only looking at go.mod/go.sum. Pre-bzlmod gazelle used to do a `go list -mod=readonly -e -m json all` to get the correct output, which seems to be the right way to do it, but of course that's much more expensive. It's not obvious if it's possible to just rely on the old gazelle generated `go_repositories` when using bzlmod?

### What did you expect to see?

Not fail

### What did you see instead?

Failure

**Comment by recht** [comment]
I guess the problem is that in this case the dependency is actually a pure bazel dependency on `@com_github_matrix_org_dendrite//cmd/dendrite`. If I add a dummy import then go.mod is updated as expected and everything works.

**Comment by fmeum** [comment]
If this is about a tool dependency, also see https://github.com/bazelbuild/rules_go/blob/master/docs/go/core/bzlmod.md#depending-on-tools. The "dummy import" is the official Go native way of handling this and also works with Bazel as you discovered.
