### ISSUE TITLE
Support for adding `exports_files` targets in a `go_repository`

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel-gazelle#178]
Some Go projects contain regular (non-go source) files that may be needed.  It would be helpful to add an option to the `go_repository` rule that allows specifying a set of these files and adding them to the `exports_files` list of their respective packages.  Most importantly, this would help a project to refer to a project's `LICENSE.txt` (or other licence file), possibly packaging them into a build artifact.

**Comment by jayconrod** [comment]
Sorry for the slow response.

`go_repository` will not support this. For repositories where build files can be mostly generated by Gazelle but need some manual customization, we have two rules: [`git_repository`](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#git_repository) and [`http_archive`](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#http_archive). These are similar to the native rules of the same name, but they allow you to specify a set of pre-generated build files that can be copied into a repository after it's checked out.

The idea is that you would create a repository rule with a command like `gazelle update-repos -kind=http_archive example.com/repo`. Gazelle would add the rule to WORKSPACE and write the build files to `third_party/com_example_repo`. You could hand-edit the build files in that directory and check them in. You could also update them with the same Gazelle command.

This is broadly covered in #56, but I also opened #182, a narrower issue to track this specific functionality.
