### ISSUE TITLE
Add unsupported/non source files as data files

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel-gazelle#179]
Non supported or non source files in a package are discarded. Perhaps we should keep them as `data`. Some packages rely on these files being present in the `GOPATH` at runtime.

**Comment by steeve** [comment]
Actually, this is pretty similar to #178

**Comment by jayconrod** [comment]
I've opened #182 which discusses the plan for this. In general, any repository that requires some modifications to build files that `go_repository` is not capable of should use `git_repository` and `http_archive`. Gazelle needs to be improved to make that workflow more usable.
