### ISSUE TITLE
Passing debug_mode via go_deps to go_repository is not supported

### ISSUE THREAD

**Issue by davidbyttow** [bazelbuild/bazel-gazelle#1805]
It appears that there is no way to pass in `debug_mode` to `go_repository` via `go_deps` with bzlmod. Unless I'm missing something, this makes it difficult to see when things go wrong during BUILD file generation because errors are not reported directly from the `gazelle` command.

https://github.com/bazelbuild/bazel-gazelle/blob/f93e45f142de1a32389f1b8798880e5cf903c432/internal/go_repository.bzl#L372-L374

**Comment by fmeum** [comment]
Happy to review a PR that adds a corresponding attr to the `go_deps` extension. I could see a single attribute that sets `debug_mode` for all repo rules being more ergonomic.

**Comment by davidbyttow** [comment]
Thanks @fmeum. I added a single attribute to config. LMK if you'd like it elsewhere. Seems like it could be extended per module to be less noisy later. https://github.com/bazelbuild/bazel-gazelle/pull/1806
