### ISSUE TITLE
`go_repository_cache` repository rule doesn't handle MacOS arm64 platform

### ISSUE THREAD

**Issue by smocherla-brex** [bazelbuild/bazel-gazelle#1816]
### What version of gazelle are you using?
v0.35.0

### What version of rules_go are you using?
v0.46.0

### What version of Bazel are you using?
6.1.0

### Does this issue reproduce with the latest releases of all the above?
Only tested with latest version of gazelle/rules_go but not Bazel. Does happen with the former though.

### What operating system and processor architecture are you using?
MacOS, ARM64

### What did you do?
We have multiple `go_download_sdk` used in our repo with support for multiple execution platforms like

```
_SUPPORTED_PLATFORMS = [
    ("linux", "amd64"),
    ("darwin", "amd64"),
    ("darwin", "arm64"),
]

for platform in _SUPPORTED_PLATFORMS:
        go_download_sdk(
            name = "go_sdk_{}_{}".format(platform[0], platform[1]),
            version = go_version,
            goos = platform[0],
            goarch = platform[1],
        )
```

With this approach, Gazelle actually fails for us on M1, because we don't use the default `go_sdk` and it gets here https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/go_repository_cache.bzl#L137 and always chooses `darwin_amd64` for the host go sdk to bootstrap gazelle which seems incorrect. This leads to errors like

```
'@com_github_fatih_color//': no such package '@bazel_gazelle_go_repository_tools//': list_repository_tools_srcs: env: /Users/ec2-user/.cache/bazel/769e755687ae21d5b840c4edaea740f0/external/go_sdk_darwin_amd64/bin/go: Bad CPU type in executable
```

It would appear that it should handle the `arm64` architecture too and return the right host go SDK accordingly? I can have a fix PR out for this but would like to know if this is reasonable.

### What did you expect to see?

`go_repository_cache` using the right Go SDK on Mac M1 , when users don't register a default `go_sdk` and explicitly register go_sdk for different platforms. I would expect it to use `go_sdk_darwin_arm64`

### What did you see instead?
It chooses the go sdk for Darwin amd64 platform rather than arm64, leading to the error.

**Comment by fmeum** [comment]
A fix would be very welcome!

**Comment by smocherla-brex** [comment]
Fix PR [here](https://github.com/bazelbuild/bazel-gazelle/pull/1817).
