### ISSUE TITLE
gazelle fails to fetch some repositories loaded with `go_deps.from_file(go_mod = "//:go.mod")` 

### ISSUE THREAD

**Issue by Megakuul** [bazelbuild/bazel-gazelle#1831]
### What version of gazelle are you using?

0.36.0

### What version of rules_go are you using?

0.48.1

### What version of Bazel are you using?

7.2.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

linux, x86_64

### What did you do?

Attempted to fetch the `https://github.com/go-acme/lego/v4` go module by reading it from `go.mod` with the `go_deps` extension.
```
...
go_deps.from_file(go_mod = "//:go.mod")
use_repo(
    go_deps,
    "com_github_go_acme_lego_v4",
)
...
```

### What did you expect to see?

Successful download of the repository.

### What did you see instead?

The following error is emitted:
```
ERROR: An error occurred during the fetch of repository 'gazelle~~go_deps~com_github_go_acme_lego_v4':
   Traceback (most recent call last):
        File ".../external/gazelle~/internal/go_repository.bzl", line 263, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch gazelle~~go_deps~com_github_go_acme_lego_v4: fetch_repo: .../external/rules_go~~go_sdk~go_default_sdk/bin/go .../external/rules_go~~go_sdk~go_default_sdk/bin/go mod download -json -modcacherw github.com/go-acme/lego/v4@v4.17.4: go: github.com/go-acme/lego/v4@v4.17.4 requires go >= 1.22; switching to go1.22.4
go: golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64: verifying module: checksum database disabled by GOSUMDB=off
```

I took a look at the `internal/go_repository.bzl` it mentions. On line `270` I found this code:
```starlark
# Disable sumdb in fetch_repo. In module mode, the sum is a mandatory
# attribute of go_repository, so we don't need to look it up.
fetch_repo_env = dict(env)
fetch_repo_env["GOSUMDB"] = "off"
```

I do not really understand why this is done here, but when I stop it from disabling GOSUMDB like this:
```starlark
# Disable sumdb in fetch_repo. In module mode, the sum is a mandatory
# attribute of go_repository, so we don't need to look it up.
fetch_repo_env = dict(env)
# fetch_repo_env["GOSUMDB"] = "off"
```

It does correctly fetch the repository and continues with the compilation.

So far, I have only experienced this problem with the `github.com/go-acme/lego/v4` repository, maybe it is also related to the use of the go1.22.4 toolchain, but I know too little about it to judge.

**Comment by fmeum** [comment]
I can't reproduce this failure with this setup:

```
# MODULE.bazel
bazel_dep(name = "gazelle", version = "0.36.0")
bazel_dep(name = "rules_go", version = "0.49.0")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(
    go_deps,
    "com_github_go_acme_lego_v4",
)

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.22.5")

# go.mod
module example.com

go 1.22

toolchain go1.22.5

require github.com/go-acme/lego/v4 v4.17.4

# go.sum
github.com/go-acme/lego/v4 v4.17.4 h1:h0nePd3ObP6o7kAkndtpTzCw8shOZuWckNYeUQwo36Q=
github.com/go-acme/lego/v4 v4.17.4/go.mod h1:dU94SvPNqimEeb7EVilGGSnS0nU1O5Exir0pQ4QFL4U=
```

Running `bazel build @com_github_go_acme_lego_v4//...` results in a different error (expected since `go.mod` is incomplete) that does show that the lego repo has been fetched successfully.

Could you share a complete reproducer?

**Comment by Megakuul** [comment]
@fmeum I created a simple example that reproduces the issue: https://github.com/Megakuul/gazelle_issue_1831_reproduce

**Comment by Megakuul** [comment]
After testing around with the reproduce I already located the issue, it is that I did not explicitly download the toolchain 1.22.5 with bazel. I mistakenly assumed that this had already been taken care of/considered by the gazelle extension.
When explicitly downloading the correct toolchain `go_sdk.download(version = "1.22.5")` it works fine.
