### ISSUE TITLE
Feature request: directive to include default attributes

### ISSUE THREAD

**Issue by guoshimin** [bazelbuild/bazel-gazelle#187]
Use case: I want to add an x_defs attribute to all gazelle-generated go_binary targets.

**Comment by guoshimin** [comment]
Found a way to do it without the need for this. Closing.

**Comment by jayconrod** [comment]
For future reference, [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer) is a great tool for batch changes to build files like this.

**Comment by guoshimin** [comment]
Good to know!
