### ISSUE TITLE
Gazelle no such file or directory (windows 11)

### ISSUE THREAD

**Issue by brounnoupegreula-7757** [bazelbuild/bazel-gazelle#1874]
### What version of gazelle are you using?

0.38.0

### What version of rules_go are you using?

0.49.0

### What version of Bazel are you using?

7.3.0

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

windows 11

### What did you do?

i try bazel gazelle with bzlmod : 

MODULE.bazel 

```
bazel_dep(name = "rules_go", version = "0.49.0")
bazel_dep(name = "gazelle", version = "0.38.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.22.6")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(go_deps, "com_github_gofiber_fiber_v3")

```

BUILD.bazel

```
load("@gazelle//:def.bzl", "gazelle")

gazelle(name = "gazelle")
```

and run with this command :

`bazel run //:gazelle`

![image](https://github.com/user-attachments/assets/bd29956a-ef61-40da-8a0c-57e18fef76b6)

i got error like above command gazelle not found, i run inside terminal goland but when i try to check the directory the app is exist 

![image](https://github.com/user-attachments/assets/c08cd1f9-07fe-4680-bf79-45a48e1d0cd6)

look like the the command running inside linux bash but not running /mnt 

how can i fix it?

**Comment by fmeum** [comment]
Could you post the content of the `gazelle-runner.bash` file in that directory?

Are you using MSYS2 to provide `bash`?

**Comment by brounnoupegreula-7757** [comment]
i fix it @fmeum 

gazelle not working with wsl, so i change to git bash and it worked
