### ISSUE TITLE
Directive to resolve dependencies explicitly

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#189]
Gazelle should support a directive that explicitly maps an import path to a label. When Gazelle resolves an import with the same path, it will resolve to the label instead of using the library index. The directive would affect dependency resolution in the directory where it appears and subdirectories. The directive can be used multiple times.

```
# gazelle:use github.com/foo/bar //custom/foo:bar
# gazelle:use github.com/baz/quux //custom/baz:quux
```

**Comment by gwik** [comment]
That would be useful. I have a vendored library that use bazel and have two libraries with the same import path generated by gazelle, a go_proto_library and a go_library.
When running gazelle it complains about "multiple rules".

**Comment by robfig** [comment]
This seems to be implemented as the `# gazelle:resolve` directive.
