### ISSUE TITLE
Update README.md when releasing

### ISSUE THREAD

**Issue by eljobe** [bazelbuild/bazel-gazelle#1953]
### What version of gazelle are you using?

v0.35.0

### What version of rules_go are you using?

v0.50.1

### What version of Bazel are you using?

6.1.1

### Does this issue reproduce with the latest releases of all the above?

Yes (I mean, it's not related to the behavior of the tools. So, I guess.)

### What operating system and processor architecture are you using?

N/A

### What did you do?

I tried to update bazel-gazelle to the latest release (0.39.1) and I had to manually cobble together the right configuration for my WORKSPACE file.

### What did you expect to see?

I expected to open the README.md on this repo and see a copy and pasteable example with the latests release.

### What did you see instead?

And older release.

**Comment by fmeum** [comment]
We try to keep it updated, but might forget. PRs welcome!

Note that WORKSPACE is deprecated and Bzlmod doesn't require a snippet, you just bump the version in `bazel_dep`. I would strongly recommend migrating to Bzlmod (at least for rules_go and gazelle).
