### ISSUE TITLE
gazelle update-repos doesn't support vgo

### ISSUE THREAD

**Issue by dokipen** [bazelbuild/bazel-gazelle#200]
[vgo](https://github.com/golang/go/wiki/vgo) is the next generation of dependency management for go.

I'd like to work on a PR to add vgo lock file support to the update-repos command. Plan:
 * Add vgo support to internal/repos
 * Update documentation with clear indicators that vgo is still not production-ready.

Does this PR have a chance to be accepted?

**Comment by jayconrod** [comment]
This is definitely a feature I'd like to have. I've been planning to work on this, but I haven't had the time to look into exactly what's needed yet.

I'd be happy to accept a PR, perhaps marked experimental or preliminary as you mentioned. internal/repos is the correct place for this.

**Comment by robfig** [comment]
I think these are the two best docs for Go Modules nowadays
https://github.com/golang/go/wiki/Modules
https://tip.golang.org/cmd/go/#hdr-Modules__module_versions__and_more

**Comment by clintberry** [comment]
this is awesome! But I am not entirely sure how to use it yet. Are there any docs on how to use this?

**Comment by clintberry** [comment]
For anyone else that is curious on how to do this manually, you can `gazelle update-repos -from_file=go.mod` Hopefully it can be automated across all go.mod files in every package. Very cool work. Thank you @jayconrod

**Comment by jayconrod** [comment]
@clintberry Yep, that's the right way to do that. I should have updated the documentation earlier, but the section on `update-repos` mentions this now.

> Hopefully it can be automated across all go.mod files in every package.

That should work automatically. Internally, Gazelle copies your go.mod to a temporary directory and runs `go list -m` there. That will list transitive dependencies, even if your dependencies don't have go.mod files.
