### ISSUE TITLE
gazelle update-repos should support pruning unneeded dependencies

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#213]
For example, when importing external repository rules from a lock file, if the `-prune` flag (or something similar) is given, Gazelle should remove `go_repository` rules that no longer have equivalent repos in the lock file.

```
gazelle update-repos -from_file=Gopkg.lock -prune
```

Later, we should also be able to remove repositories that aren't imported by the main repository or transitive dependencies.

**Comment by linzhp** [comment]
> Later, we should also be able to remove repositories that aren't imported by the main repository or transitive dependencies.

To do this as part of `update-repos`, can we assume Bazel rules exist in the main repo? If so, we can run `bazel query deps(//...)` and prune all `go_repository` rules not in the transitive dependency closure.

**Comment by jayconrod** [comment]
> To do this as part of update-repos, can we assume Bazel rules exist in the main repo? If so, we can run bazel query deps(//...) and prune all go_repository rules not in the transitive dependency closure.

Yes we can assume Bazel rules exist in the main repo.

I don't think Gazelle should run `bazel query` or any other Bazel command though. Earlier, it was not possible since Gazelle is commonly invoked by `bazel run`, and that used to hold a global lock on the work space. But still I think it's better not to recursively invoke Bazel. This may interfere with autogazelle, and it will be slow. I also don't want to create the expectation that Gazelle can evaluate Starlark code: we can't update files that require evaluation (e.g., targets declared in macros).

It may be better to ask users to run `bazel fetch //...` first, then do a best-effort emulation of `bazel query`.

**Comment by martin-randall-tanium** [comment]
It look like `-prune` was implemented in #514. Can this issue be closed?

**Comment by jayconrod** [comment]
Yeah this can be closed. I don't think `update-repos` will support listing imports in source files, so `-prune` can only be used with `-from_file`.
