### ISSUE TITLE
Dependency resolution: add special case for gRPC

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#217]
When resolving dependencies for packages under the prefix `github.com/grpc/grpc-go`, Gazelle should prefer libraries in the external repo `@org_golang_google_grpc` over anything in the vendor directory. The gRPC plugin implicitly depends on the external repo, and depending on both will cause conflicts.

**Comment by lucperkins** [comment]
I’m not sure that I can think of a use case, but there may be cases in which users *do* want to use the vendored version. I’d recommend changing Gazelle’s default behavior, as suggested, but also providing a configuration lever so that users can use the vendored version if desired.

**Comment by morozov** [comment]
FWIW, gRPC is not the only case. There's a similar problem with `"github.com/golang/protobuf/"` being resolved to `"//vendor/github.com/golang/protobuf/"` instead of `"@com_github_golang_protobuf//"`.

Unlike gRPC which fails on initialization (`init()`) because of this issue, `protobuf/proto`  declares `revProtoTypes` independently for each differently resolved dependency and doesn't fail. The issues caused by this one can be only detected with tests.

**Comment by jayconrod** [comment]
@morozov Which specific packages in `github.com/golang/protobuf` are you seeing that with? Gazelle has special cases for these libraries:

* `github.com/golang/protobuf/jsonpb`
* `github.com/golang/protobuf/descriptor`
* `github.com/golang/protobuf/ptypes`

**Comment by morozov** [comment]
@jayconrod it's `github.com/golang/protobuf/ptypes`, we're using Gazelle 0.11.0. Were those special cases added later?

**Comment by afking** [comment]
I think `@com_github_golang_protobuf//proto` needs special handling as importing calls register functions which mutate global state like in https://github.com/golang/protobuf/blob/master/proto/properties.go#L530 . Getting silent errors.

**Comment by afking** [comment]
Could gazelle take an overload mapping so all generated code instead points at locally vendor libs? We make some changes to vendor code and its not clear how to make external labels loop back to modified vendor libs correctly. Also its difficult maintaining versions between the libraries and compatibility with the go tool.

**Comment by jayconrod** [comment]
@afking That's something I've been meaning to add for a while. #189 is probably the right issue to track for that.

**Comment by afking** [comment]
Thanks @jayconrod that looks like the solution we need. When using vendor I think all code should prefer the vendor version of the library.

**Comment by jayconrod** [comment]
#335 should actually add a special case. The `# gazelle:resolve` directive added in #326 can be used to override the special case.

I haven't added a special case for `golang.org/x/net/context`, which is another implicit dependency added by the `go_grpc` compiler. I *think* it's safe to have multiple copies of that, though it's obviously better not to. I'd prefer as few special cases as possible though.

**Comment by afking** [comment]
@jayconrod thanks for the quick fix. A solution I came up with was to define the protoc compilers locally as:
```
go_proto_compiler(
    name = "go_grpc",
    options = ["plugins=grpc"],
    visibility = ["//visibility:public"],
    deps = [
        "//vendor/github.com/golang/protobuf/proto:go_default_library",
        "//vendor/golang.org/x/net/context:go_default_library",
        "//vendor/google.golang.org/grpc:go_default_library",
        # WELL_KNOWN_TYPE_RULES
        "//vendor/github.com/golang/protobuf/ptypes/any:go_default_library",
        "//vendor/google.golang.org/genproto/protobuf/api:go_default_library",
        "//vendor/github.com/golang/protobuf/protoc-gen-go/plugin:go_default_library",
        "//vendor/github.com/golang/protobuf/protoc-gen-go/descriptor:go_default_library",
        "//vendor/github.com/golang/protobuf/ptypes/duration:go_default_library",
        "//vendor/github.com/golang/protobuf/ptypes/empty:go_default_library",
        "//vendor/google.golang.org/genproto/protobuf/field_mask:go_default_library",
        "//vendor/google.golang.org/genproto/protobuf/source_context:go_default_library",
        "//vendor/github.com/golang/protobuf/ptypes/struct:go_default_library",
        "//vendor/github.com/golang/protobuf/ptypes/timestamp:go_default_library",
        "//vendor/google.golang.org/genproto/protobuf/ptype:go_default_library",
        "//vendor/github.com/golang/protobuf/ptypes/wrappers:go_default_library",
    ],
)
```
and then fork gazelle to remove all special handling of imports for protocs. This seems to work well for us and could maybe be adopted for the grpc vendored case?

**Comment by jayconrod** [comment]
@afking I don't expect to support the gRPC vendored case directly in Gazelle. There's too much complication and too much risk of conflicts between different vendored copies of a library.

That being said, I would like to add an extension mechanism to Gazelle to allow users to select which `go_proto_compiler` to use. Not sure what that would look like. It may require more of a "plugin" than a configuration mechanism, as there are a lot of dependency resolution rules that would have to be changed.
