### ISSUE TITLE
# gazelle:include directive?

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel-gazelle#221]
This might have an obvious solution that I am missing, but is there a way that I can direct gazelle to only consider certain directories and their sub-directories and exclude everything else?

For us, our repo root is also our `GOPATH`, and if any user or tool runs `go get`, then package sources are installed within our repo (but ignored by our VCS). We want gazelle to ignore these directories but can not compile an exhaustive list of what packages might get installed here.

Pristine repo:
```
go/src/github.com/grailbio/...
go/src/grail.com/...
go/src/vendor/...
```

Dirty repo:
```
go/src/github.com/grailbio/...  # <- we want gazelle to include this.
go/src/github.com/... # we want gazelle to ignore everything else.
go/src/grail.com/... # <- we want gazelle to include this.
go/src/vendor/... # <- we want gazelle to include this.
go/src/... # <- we want gazelle to ignore everything else.
```

**Comment by jayconrod** [comment]
There's not a simple, fully general way to do this yet. It would be useful to have more control (using globs maybe) over which files are included and excluded.

For this case, I think you could pass a list of directories to the `gazelle` rule that you want to be updated.

```
gazelle(
    name = "gazelle",
    command = "fix',
    extra_args = [
        "go/src/github.com/grailbio",
        "go/src/grail.com",
        "go/src/vendor",
    ],
```

Gazelle will still recurse through the entire repository, indexing libraries in build files, but it will only generate or update build files in those directories.

**Comment by siddharthab** [comment]
Thank you for your prompt response.

Unfortunately, this did not work for me. gazelle still generated BUILD files for these packages outside of version control, and updated existing BUILD files to depend on these packages, and not the ones from the vendor directory.

**Comment by jayconrod** [comment]
It sounds like something might be going wrong with the `extra_args`, but in any case, that doesn't seem like the best solution to your problem.

I'll look into adding a `# gazelle:include` directive, since that does seem to be the best solution to this problem. Currently, Gazelle is undergoing a large refactoring in order to support multiple languages. I'll working on adding this after that refactoring is complete.

**Comment by siddharthab** [comment]
Thank you, a more specialized version would be if gazelle somehow became git (or some other VCS) aware, and could ignore files ignored by git. But that is perhaps not a good design.

**Comment by JensRantil** [comment]
Hi, I can verify that
```
gazelle(
    name = "gazelle",
    command = "update',
    extra_args = [
        "directory/with/go/application",
    ],
)
```
worked for me. It _only_ generated files in `directory/with/go/application` and ignored all other directories.

**Comment by siddharthab** [comment]
Thanks. Maybe I was doing something wrong. After Go modules, we don't need the include directive as much so the directory path should be sufficient.

**Comment by JensRantil** [comment]
@siddharthab Would it make sense to close this issue then? Or is it still relevant for others you think?

**Comment by siddharthab** [comment]
I will leave that to the repo maintainers to decide.

**Comment by jayconrod** [comment]
I'm glad that worked. I'll close this, since it seems like this problem can be solved with existing features.

**Comment by jschaf** [comment]
I ran into this. Generally, I want to exclude all testdata, so I have a top-level exclude in my BUILD file, like so:

    # gazelle:exclude **/testdata/

However, sometimes I want gazelle to update a testdata directory explicitly.  An `include` directive would be useful for that usecase.

**Comment by Whoaa512** [comment]
I'd like to open the discussion back up on supporting this. We have a large code base with lots of handwritten BUILD.bazel files, and we'd like to incrementally adopt the auto-formatting. 

Would you accept a PR to add this functionality? If so, how do you think gazelle should be configured so it's exclude by default and things get included when the directive is added?

**Comment by GabrielGhe** [comment]
For people still needing this functionality, we patched gazelle to make `walkConfig` and it's `ignore` field public.
This allowed us to create our own `include` directive.

This is the main change, but all the functions that use this struct have to be updated as well:

```diff
diff --git walk/config.go walk/config.go
index bf23a6e..1b49084 100644
--- walk/config.go
+++ walk/config.go
@@ -38,20 +38,20 @@ import (
 // may be set in one directory and used in another. Excludes work on
 // declared generated files, so we can't just stat.
 
-type walkConfig struct {
+type WalkConfig struct {
 	excludes []string
-	ignore   bool
+	Ignore   bool
 	follow   []string
 	loadOnce sync.Once
 }
 
 const walkName = "_walk"
 
-func getWalkConfig(c *config.Config) *walkConfig {
-	return c.Exts[walkName].(*walkConfig)
+func GetWalkConfig(c *config.Config) *WalkConfig {
+	return c.Exts[walkName].(*WalkConfig)
 }
 
-func (wc *walkConfig) isExcluded(rel, base string) bool {
+func (wc *WalkConfig) isExcluded(rel, base string) bool {
 	if base == ".git" {
 		return true
 	}
@@ -75,7 +75,7 @@ func (wc *walkConfig) isExcluded(rel, base string) bool {
 type Configurer struct{}
 
 func (*Configurer) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
-	wc := &walkConfig{}
+	wc := &WalkConfig{}
 	c.Exts[walkName] = wc
 	fs.Var(&gzflag.MultiFlag{Values: &wc.excludes}, "exclude", "pattern that should be ignored (may be repeated)")
 }
```
