### ISSUE TITLE
Gazelle and vendor/ producing very long build times

### ISSUE THREAD

**Issue by kwiesmueller** [bazelbuild/bazel-gazelle#227]
Hey there,
we are evaluating bazel right now and encountered an issue with the first go project we are trying to migrate.
When generating everyhting using bazel and gazelle
```
gazelle(
    name = "gazelle",
    external = "vendored",
    prefix = "bitbucket.org/seibert-media/events",
)
```
we get immense build times, as this project is using parts of the google api library which seems to be heavy. Others are using kubernetes go-client as well which I suspect gets even worse then.

The builds work themselves through a lot of external/com_google_protobuf actions until they finally arive at our own code, which for now is very small.

Locally it wouldn't be so much of an issue as the caching seems to work, but as we are using Google Container Builder we get those durations on every build.

Is the solution here really to use remote chaching or are we using gazelle wring somehow?

**Comment by kwiesmueller** [comment]
Any input?

**Comment by jayconrod** [comment]
Sorry for not commenting on this earlier. This is related to bazelbuild/rules_go#1531, correct?

I think you're using Gazelle correctly. Gazelle will only run on your host machine (both in your local repository and when setting up remote `go_repository` rules declared in WORKSPACE). It won't run on the execution machines, and it shouldn't do anything to affect remote caching.

**Comment by kwiesmueller** [comment]
Ok, we haven't tried remote caching since then. I guess it will be okay to close this for now as we are already enlisted for Bazel on Cloud Build Beta and if we get the issue there again I will reopen.
Sorry for taking so long.
