### ISSUE TITLE
Vendor package visibility doesn't translate

### ISSUE THREAD

**Issue by afking** [bazelbuild/bazel-gazelle#229]
Vendor code BUILD files don't rewrite package visibility to be local to the vendor path. For example in the https://github.com/grpc-ecosystem/grpc-gateway 

```
package(default_visibility = ["//protoc-gen-swagger:__subpackages__"])
```

remains under `/vendor/github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/genswagger/BUILD.bazel` causing `is not visible from target` errors.

**Comment by jayconrod** [comment]
This is working as intended. In general, Gazelle should not modify handwritten parts of build files. Gazelle doesn't emit `package` declarations, so this is considered handwritten.

In general, I'd recommend against vendoring projects with build files. Build files frequently contain absolute paths and labels that don't make sense when they're moved to a vendor directory.

* Use external repositories e.g., `go_repository` if you can.
* You may find [`cmd/move_labels`](https://github.com/bazelbuild/bazel-gazelle/tree/master/cmd/move_labels) helpful for vendoring. It attempts to rewrite labels in build files after a directory is moved, and it was written to help with vendoring.
* If a repository is buildable with `go build` anyway, it may be better just to delete the build files and regenerate them with Gazelle.

**Comment by afking** [comment]
@jayconrod great thanks for the quick response.

**Comment by bweston92** [comment]
I'm currently getting a similar issue with mgo:

Error:
```
ERROR: /workspace/vendor/gopkg.in/mgo.v2/bson/BUILD.bazel:3:1: target '//vendor/gopkg.in/mgo.v2/internal/json:go_default_library' is not visible from target '//vendor/gopkg.in/m
go.v2/bson:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

Rule visibility is set to:
```
visibility = ["//src/vendor/gopkg.in/mgo.v2:__subpackages__"],
```

Seems whenever someone has a `internal` package it fails.

**Comment by bweston92** [comment]
There is no symbolic link, however now I have just moved my vendor folder into `src` it all works fine.
