### ISSUE TITLE
Allow some way to prioritise one file over another

### ISSUE THREAD

**Issue by Naatan** [bazelbuild/bazel-gazelle#237]
The `# keep` option is great, but unfortunately it does not have any effect on the order of the item. It seems gazelle will reorder `srcs` values each time it is called. Problem is execution order sometimes matters in Go. I need a way to say "this file should be the first entry". At the moment the only option I see is to exclude the relevant directory from gazelle and manually define my rule.

Example:

```
    srcs = [
        "locale-packr.go",  # keep
        "locale.go",
    ],
```

After I run gazelle the result is:

```
    srcs = [
        "locale.go",
        "locale-packr.go", # keep
    ],
```

I need locale-packr.go to be first.

**Comment by jayconrod** [comment]
I think this adds complexity without adding much value. I'd rather not implement it if the problem can be solved another way.

Are you able to build this with `go build` or `go get`? I think the Go toolchain compiles files in sorted order unless you are compiling a package with all source files specified on the command line.

What do you think about renaming files so the sorted order is the correct order? Something like `aa-locale-packr.go`?

If all else fails, you can mark the whole `srcs` attribute with a `# keep` comment above. Gazelle won't add, remove, or sort `srcs`, but it will still update `deps` and other attributes.

**Comment by Naatan** [comment]
This does indeed work with `go build`, I can into it when converting a build to bazel. Note you can easily reproduce it just [by using packr](https://github.com/gobuffalo/packr). The filename is decided by packr and is in the format of `<package>-packr.go`.

I think perhaps this isnt so much an enhancement as much as it is a bug in that gazelle does not appear to apply the same load order to files that `go build` does.

**Comment by jayconrod** [comment]
You're right, this is actually a bug.

Gazelle uses [buildifier](https://github.com/bazelbuild/buildtools/tree/master/buildifier) internally to format build files before writing them out. One of the transformations buildifier applies is sorting string lists. The sorting algorithm is intended to work with labels as well as source files, so it's not strictly lexicographic.

Buildifier has some functionality that lets you control this. Groups of strings in a list with an intervening blank line are sorted separately. And you can write "# do not sort" above a group to prevent it from being sorted. Not sure if that's documented anywhere, but the code is in [rewrite.go](https://github.com/bazelbuild/buildtools/blob/master/build/rewrite.go).

Unfortunately, when Gazelle uses buildifier through its library, we don't get that behavior. I'm not exactly sure why yet, but it *is* a bug.
