### ISSUE TITLE
update-repos doesn't update dependencies in WORKSPACE

### ISSUE THREAD

**Issue by JohnnyQQQQ** [bazelbuild/bazel-gazelle#238]
I tried bazel today to build my golang project. Somehow the update-repo command doesn't work for me.

I used this command for adding gin to the WORKSPACE file:
```bazel run //:gazelle -- update-repos github.com/gin-gonic/gin```

Output: 

```
INFO: Analysed target //:gazelle (1 packages loaded).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/linux_amd64_stripped/gazelle_script.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.221s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
```

After that I saw now changes and the build fails as gin is missing. Any hints?

I uploaded the mini-project I'm using on github https://github.com/JohnnyQQQQ/bazel-demo

**Comment by jayconrod** [comment]
It looks like you're actually using an old version of the `gazelle` macro from `@io_bazel_rules_go`. This is deprecated and will be removed fairly soon. You should load that macro from `@bazel_gazelle` instead. Here's a patch:

```
diff --git a/BUILD b/BUILD
index 05ac3d4..359e57a 100644
--- a/BUILD
+++ b/BUILD
@@ -1,4 +1,5 @@
-load("@io_bazel_rules_go//go:def.bzl", "gazelle", "go_binary", "go_library")
+load("@bazel_gazelle//:def.bzl", "gazelle")
+load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
 
 gazelle(
     name = "gazelle",
```

**Comment by jayconrod** [comment]
I've filed #239 to make this update automatic. Been meaning to do that for a while.

**Comment by JohnnyQQQQ** [comment]
@jayconrod thanks for your explanation. I fixed it locally and tested it again, somehow I got an error on  for the same command

```
bazel run //:gazelle -- update-repos github.com/gin-gonic/gin
INFO: Analysed target //:gazelle (0 packages loaded).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle.bash
INFO: Elapsed time: 0.207s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: exit status 129
```

If found this issue regarding the same problem https://github.com/bazelbuild/bazel-gazelle/issues/222

I can run `git ls-remote https://github.com/gin-gonic/gin HEAD` without any problems and get the current HEAD commit as output. I'm running ubuntu 16.04 with bazel 0.14.1

I updated the repo on github.

**Comment by jayconrod** [comment]
I suspect the old version of the script may have issues with propagating runfiles (in this case, the gazelle binary). Does the problem go away after `bazel clean --expunge`?

**Comment by JohnnyQQQQ** [comment]
@jayconrod I tried with `bazel clean --expunge` but it didn't change the outcome, it's still throwing an 129 error code.

**Comment by Globegitter** [comment]
I am seeing the same issue, running on bazel 0.15.0rc3, Ubuntu 16.04 and the latest release gazelle and rules_go, I get:

```
bazel run //:gazelle -- update-repos google.golang.org/grpc
INFO: Analysed target //:gazelle (0 packages loaded).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle.bash
INFO: Elapsed time: 0.216s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: exit status 129
```

**Comment by jayconrod** [comment]
Hmm, this is really weird. I haven't been able to reproduce this. It seems like Ubuntu 16.04 might be a common factor.

Would either of you be willing to post a gist with the output of the command below? 129 is a strange exit code, and I'd like to know exactly where it's coming from.

```
strace -f -e trace=process bazel run //:gazelle -- update-repos github.com/gin-gonic/gin
```

**Comment by jayconrod** [comment]
Thanks! This part of the indicates that git is exiting with code 129.

```
[pid 24676] execve("/usr/bin/git", ["git", "ls-remote", "--", "https://github.com/gin-gonic/gin", "HEAD"], [/* 83 vars */] <unfinished ...>
[pid 24670] <... clone resumed> child_stack=0, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = 24676
[pid 24676] <... execve resumed> )      = 0
[pid 24670] waitid(P_PID, 24676,  <unfinished ...>
[pid 24676] arch_prctl(ARCH_SET_FS, 0x7f199b5d6700) = 0
[pid 24676] exit_group(129)             = ?
[pid 24676] +++ exited with 129 +++
```

You said you were able to run that command directly without any trouble. Is there anything in your environment that would affect git? Bazel may add, remove, and change environment variables (the `-s` flag should show you what it's doing though). Anything else unusual like a proxy or local configuration that it wouldn't see if it were executing inside the Bazel execroot?

**Comment by JohnnyQQQQ** [comment]
I'm using z-shell. I'm Not sure If this might be the Problem but sometimes it cause some trouble. I'll investigate when I'm home.

**Comment by JohnnyQQQQ** [comment]
I just tested the whole thing in the normal bash terminal and it also failed. What I saw from the trace is that the command that is executed seems to be `git ls-remote -- https://github.com/gin-gonic/gin HEAD` which doesn't work. The command without the `--` works
```
git ls-remote https://github.com/gin-gonic/gin HEAD
1f59bad84b577735b27a1ee855f01ed2f50cd88b	HEAD
```

I think it's this part of the code 
https://github.com/bazelbuild/bazel-gazelle/blob/aec2916dd291b7e4be54e191e1df5389fe5ecf40/internal/repos/remote.go#L275

**Comment by Globegitter** [comment]
Ah yes that was it - git on Ubuntu 16.04 is `2.7.4` and that only supports `git ls-remote https://github.com/gin-gonic/gin HEAD` but not `git ls-remote -- https://github.com/gin-gonic/gin HEAD`, upgrading to the latest git fixes the issue.
