### ISSUE TITLE
Proto target names are not generated based on the last package identifier

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel-gazelle#277]
According to documentation:

> Rule names are generated based on the last run of identifier characters in the package name. For example, if the package is "foo/bar/baz", the proto_library rule will be named baz_proto.

This is causing the deps to generate a reference to `:baz_proto`, but the actual target was `:foo_bar_baz_proto`.

Failing test here: https://github.com/prestonvanloon/bazel-gazelle/commit/7f14663fc76627eff9087bd553a77d47dc0cfaf0

**Comment by jayconrod** [comment]
This is true, but only in the `package` mode. I definitely prefer this behavior over the default behavior, but I don't want to break everyone by changing rule names. So `package` mode is opt-in for now.

Clarified documentation in #279 (meant to close this issue).
