### ISSUE TITLE
update-repos -from_file=Gopkg.lock does not generate proper rules

### ISSUE THREAD

**Issue by zllak** [bazelbuild/bazel-gazelle#288]
When using `update-repos -from_file=Gopkg.lock`, the output in the WORKSPACE is not valid.
It ends up generating `go_repository` rules with a `remote`, but without a `vcs`, which makes gazelle error when running.

I'm trying to find a fix and will do a pull request. If you have any advice on where and how you want to do it, do not hesitate.

**Comment by robfig** [comment]
Sorry for the lack of reply. If this is still an issue, please provide more detail, or a reproducer. Thanks
