### ISSUE TITLE
Import repository rules from vendoring tools

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#29]
(Migrated from bazelbuild/rules_go#1082)

Gazelle should be able to transcribe lock files from popular vendoring tools like dep into repository rules in WORKSPACE. These tools produce lock files, which contain import paths and commit ids for each remote repository. It should be straightforward to generate repository rules from these.

* We should understand lock file formats of a few popular tools. dep will be first. Support for more tools can be added on demand.
* The import functionality should be available via a new command. For example:

```
gazelle migrate-deps Gopkg.lock
```

* Gazelle may initially add `go_repository` rules for imported dependencies. However, it is likely we will deprecate `go_repository` soon, so Gazelle should add `git_repository` and `http_archive` rules with pre-generated build files.
  * There isn't a viable replacement for `go_repository` yet. `new_git_repository` and `new_http_archive` only accept a single flat build file, which can be difficult to maintain and causes migration problems for repositories that eventually migrate to Bazel. We need replacements for these rules that can overlay a tree of build files on a downloaded repository.
* Gazelle should not add new rules if an existing rule checks out the same repository. The import command must be idempotent. If dependencies change or are updated in the lock file, Gazelle should update rules in place when possible (and report an error otherwise).
* Gazelle may not be able to remove dependencies that were removed from the lock file.

**Comment by robfig** [comment]
Gazelle supports Go Modules
