### ISSUE TITLE
external: not working as advertised

### ISSUE THREAD

**Issue by zllak** [bazelbuild/bazel-gazelle#294]
The `external` mode does not work as advertised.
From the documentation, we expect it to always use imports as external, `@com_github...`.
But when we have defined the go_repository in the WORKSPACE, if the library is also in the `vendor` directory, the `@com_github...` won't be used, and we will end up using the `//vendor/github.com/...`.

**Comment by zllak** [comment]
Ok, saw #204, but still, the documentation of `external` is VERY misleading, and it's actually a really weird behavior, because it clearly states that dependences WILL BE resolved using the WORKSPACE definitions.

**Comment by jayconrod** [comment]
Reopening this issue as a documentation bug.
