### ISSUE TITLE
Gazelle doesn't know about @gogo_special_proto

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel-gazelle#298]
This causes the following code to be generated:
```
proto_library(
    name = "myproto_proto",
    srcs = ["myproto.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//github.com/gogo/protobuf/gogoproto:gogoproto_proto",
    ],
)
```

**Comment by jayconrod** [comment]
At the moment, Gazelle has no support for gogo, so you may need to run with the `# gazelle:proto disable` directive and write the `proto_library` and `go_proto_library` rules by hand.

I think gogo support would be useful, but currently, there are several other projects that are higher priority (particularly editor integration and better platform support).

**Comment by steeve** [comment]
Thanks jay. I'm guessing having gazelle understand that `github.com/gogo/protobuf/gogoproto/gogoproto.proto` should be replaced by `@gogo_special_proto//github.com/gogo/protobuf/gogoproto` would be a bit too coupled ?

**Comment by jayconrod** [comment]
I'm fine with Gazelle having knowledge about gogo, but there needs to be a holistic strategy. If gogo is being used, we need to resolve imports of Well Known Types to `go_proto_library` rules that use one of the gogo `compilers`. Plus we need cases for any other standard packages associated with gogo. We need to have a strategy for dealing with conflicts involving other `go_proto_library` rules with different `compilers`.

**Comment by steeve** [comment]
Well, `@gogo_special_proto//github.com/gogo/protobuf/gogoproto` is just a definitions file for proto attributes, so in theory it is possible to include/use it with the standard proto go generator without issue.
It really is about finding the proto file.

Currently, when depending on WKTs, gazelle properly makes the `proto_library` depend on the proto file in `@com_google_protobuf` and lets the plugin generate the `.pb.go`, which I think it a good thing rather than depending on the `ptypes/XXX` package.

**Comment by jayconrod** [comment]
I feel like adding a special case for this would create an expectation that gogo is better supported in Gazelle than it currently is. I'd rather launch gogo support as a complete feature.

I also don't think `@gogo_special_proto` should continue to exist as a repository rule. I don't think there's any good reason for it to be outside of the `@com_github_gogo_protobuf` repository.

**Comment by steeve** [comment]
True indeed.
I could path the gogo overlay to add a proto_library for `gogo.proto`.

The issue though is that Gazelle will still try to generate a rule for a local file, and fail.

For now this + gogo compiler is working as expected.

**Comment by bartle-stripe** [comment]
Another option is to add a couple `gazelle:resolve` directives:
```
# gazelle:resolve proto github.com/gogo/protobuf/gogoproto/gogo.proto @gogo_special_proto//github.com/gogo/protobuf/gogoproto
# gazelle:resolve proto go github.com/gogo/protobuf/gogoproto/gogo.proto @com_github_gogo_protobuf//gogoproto:go_default_library
```

**Comment by jayconrod** [comment]
Closing this issue. Gazelle won't support gogoprotobuf natively. I think it's better to add support in a separate language extension if needed.
