### ISSUE TITLE
Gazelle uses the wrong naming convention for go_grpc_library

### ISSUE THREAD

**Issue by nclinger** [bazelbuild/bazel-gazelle#30]
For a grpc proto files gazel generates the following build target:
```
go_grpc_library(
    name = "helloworld_go_proto",
    importpath = "builds/examples/protobuf",
    proto = ":helloworld_proto",
    visibility = ["//visibility:public"],
)
```

However, I believe the standard for naming is \<proto file name\>_\<lang\>_grpc, thus this should be:
```
go_grpc_library(
    name = "helloworld_go_grpc",
    importpath = "builds/examples/protobuf",
    proto = ":helloworld_proto",
    visibility = ["//visibility:public"],
)
```

Fyi, this seems to correctly work when the file only contains a grpc service definition without any messages definitions.

**Comment by jayconrod** [comment]
Gazelle is a bit out-of-sync with rules_go on proto rules. `go_grpc_library` is now just a wrapper for `go_proto_library`. Gazelle should generate:

```
go_proto_library(
    name = "helloworld_go_proto",
    compiler = "@io_bazel_rules_go//proto:go_grpc",
    importpath = "build/examples/protobuf",
    proto = ":helloworld_proto",
    visibility = ["//visibility:public"],
)
```

#8 is the main tracking issue for this.

I'd prefer not to generate rules with different names depending on the compiler plugin, so I'm closing this as WAI. At some point, Gazelle may be able to update rules with names that differ from Gazelle's regular conventions (#17). Not sure how that would apply to proto rules yet, but it might have the same effect.
