### ISSUE TITLE
go_repository: support module proxies

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#307]
As described in [Module proxy protocol](https://golang.org/cmd/go/#hdr-Module_proxy_protocol).

**Comment by linzhp** [comment]
Would this mean that `go_repository` will first try downloading from module proxies before falling back to git checkout?

**Comment by jayconrod** [comment]
Yes

**Comment by jayconrod** [comment]
Fixed in #450
