### ISSUE TITLE
Unable to import kubernetes client; k8s.io/client-go/kubernetes

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel-gazelle#327]
I'm not sure how to explain this issue; I'm not sure exactly what the issue is yet.

I'm trying to use `k8s.io/client-go/kubernetes` and I'm having many issues due to the "k8s.io" aspect of imports. It seems that gazelle doesn't understand that k8s.io/apimachinery is within the same project for a build file within k8s.io/apimachinery? 

```
/home/preston/.cache/bazel/_bazel_preston/2bf51e8690558a83a0a0514ab422fd4b/external/io_k8s_apimachinery/pkg/apis/meta/v1beta1/BUILD.bazel:15:1: no such package '@io_k8s_apimachinery//k8s.io/apimachinery/pkg/runtime/schema': BUILD file not found on package path and referenced by '@io_k8s_apimachinery//pkg/apis/meta/v1beta1:v1beta1_go_proto'
```
To reproduce, add `k8s.io/client-go/kubernetes` as an import, use gazelle to `update-repos`, manually add the transitive dependencies (is there a better way?), and you'll eventually get stuck where the generated build files to not properly reference relative imports because `k8s.io` renaming (I think?).

**Comment by jayconrod** [comment]
I tweaked the WORKSPACE file a little bit to disable proto rule generation. Here's what I have:

```
go_repository(
    name = "io_k8s_client_go",
    build_file_proto_mode = "disable_global",
    commit = "a5d40177db184c504978c4b08350ac9e367042b0",
    importpath = "k8s.io/client-go",
)

go_repository(
    name = "io_k8s_apimachinery",
    build_file_proto_mode = "disable_global",
    commit = "5ae511e0ed34ac0fbf6e17340df5605372591d00",
    importpath = "k8s.io/apimachinery",
)

go_repository(
    name = "com_github_google_gofuzz",
    commit = "24818f796faf91cd76ec7bddd72458fbced7a6c1",
    importpath = "github.com/google/gofuzz",
)
```

Then this works:

```
bazel build @io_k8s_apimachinery//pkg/apis/meta/v1beta1:go_default_library
```

Most (all?) of the Kubernetes .proto files are not buildable with Bazel because the Bazel `proto_library` does not let you set import base directories. There is a Bazel feature request at bazelbuild/bazel#3867, but until that's implemented, you won't be able to build Kubernetes .proto files since they have `import k8s.io/...`. So with Gazelle / `go_repository`, you'll need to use the `disable_global` proto mode.

If you're seeing a break in another target after disabling proto rule generation, please update, and I'll try to figure out what's going on.

**Comment by jayconrod** [comment]
>  use gazelle to update-repos, manually add the transitive dependencies (is there a better way?)

To answer this specific question, no, `update-repos` doesn't have a mechanism to add repositories transitively yet. That's something I'd like to add. If you have a go.mod file or Gopkg.lock, you can import it with `gazelle update-repos -from_file go.mod`. That will update existing `go_repository` rules and add new ones if needed.

**Comment by prestonvanloon** [comment]
Thanks @jayconrod. I've created a minimal example to demonstrate the issue here: https://github.com/prestonvanloon/rules_gazelle_issue_327

Do you have any suggestions for a temporary workaround for generating the protos? 
Forking the project and checking in the pb.go files maybe?

Thanks again.

Current error is: 
```
no such package '@io_k8s_api//authentication/v1': The repository could not be resolved and referenced by '@io_k8s_client_go//kubernetes/typed/authentication/v1:go_default_library'
ERROR: Analysis of target '//:go_default_library' failed; build aborted: no such package '@io_k8s_api//authentication/v1': The repository could not be resolved
INFO: Elapsed time: 0.311s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by jayconrod** [comment]
The target `//:project` builds after adding this rule to WORKSPACE:

```
go_repository(
    name = "io_k8s_api",
    build_file_proto_mode = "disable_global",
    commit = "a191abe0b71e00ce4cde58af8002aa4c1a8bb068",
    importpath = "k8s.io/api",
)
```

WORKSPACE needs to list all transitive dependencies, not just direct dependencies.

> Do you have any suggestions for a temporary workaround for generating the protos?
> Forking the project and checking in the pb.go files maybe?

Did you mean forking `k8s.io` projects? I think the .pb.go files are already checked in there. Or did you mean the project you're building? Checking in .pb.go files is probably your best option until that Bazel issue is fixed. I guess patching the imports in those k8s.io proto files repositories might work, too. The k8s.io protos can't be built by Bazel as-is.

**Comment by prestonvanloon** [comment]
Ha, yes. This resolves my issue. Originally I was trying to build from tagged release 8.0.0, but I've build from HEAD (as shown in your example and in mine) and things are working more nicely now.

Thanks for the help. I'll go ahead and close this since the underlying issue seems to be tracked elsewhere. :)

**Comment by achew22** [comment]
I just ran into this issue. Now that https://github.com/bazelbuild/bazel/issues/3867 is closed, is there an issue where you're tracking making `build_file_proto_mode = "disable_global",` unnecessary?

**Comment by vbence** [comment]
Hi I'm pretty sure I've got the same error, but the suggested workaround does not seem to work for me
```
bazel build cmd/...
ERROR: /home/bence/.cache/bazel/_bazel_bence/1edfb4299156a8f7bf51ffc94c5318b7/external/io_k8s_api/core/v1/BUILD.bazel:18:17: no such package '@io_k8s_api//k8s.io/apimachinery/pkg/runtime': BUILD file not found in directory 'k8s.io/apimachinery/pkg/runtime' of external repository @io_k8s_api. Add a BUILD file to a directory to mark it as a package. and referenced by '@io_k8s_api//core/v1:v1_go_proto'
ERROR: Analysis of target '//cmd/podstats:go_default_library' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.239s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @io_k8s_utils; fetching
```

```
bazel build @io_k8s_api//k8s.io/apimachinery/pkg/runtime:go_default_library
ERROR: Skipping '@io_k8s_api//k8s.io/apimachinery/pkg/runtime:go_default_library': no such package '@io_k8s_api//k8s.io/apimachinery/pkg/runtime': BUILD file not found in directory 'k8s.io/apimachinery/pkg/runtime' of external repository @io_k8s_api. Add a BUILD file to a directory to mark it as a package.
WARNING: Target pattern parsing failed.
ERROR: no such package '@io_k8s_api//k8s.io/apimachinery/pkg/runtime': BUILD file not found in directory 'k8s.io/apimachinery/pkg/runtime' of external repository @io_k8s_api. Add a BUILD file to a directory to mark it as a package.
INFO: Elapsed time: 0.133s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

An in my WORKSPACE I've got
```
go_repository(
    name = "io_k8s_apimachinery",
    build_file_proto_mode = "disable_global",
    importpath = "k8s.io/apimachinery",
    sum = "h1:pOGcbVAhxADgUYnjS08EFXs9QMl8qaH5U4fr5LGUrSk=",
    version = "v0.18.3",
)
```
```
