### ISSUE TITLE
go_repository: $HOME/.gitconfig does not take effect

### ISSUE THREAD

**Issue by yaozongyou** [bazelbuild/bazel-gazelle#330]
I have a git config:
`git config --global url./path/to/local/github_mirror/.insteadOf https://github.com/`
but this config does not work for go_repository. go_repository still fetch repo from github.com.

Instead if git is configed using --system, it works.

**Comment by jayconrod** [comment]
#331 should fix this, but note that you'll have to run `bazel clean --expunge` for changes in any .gitconfig to take effect.

**Comment by yaozongyou** [comment]
It works, thanks.
