### ISSUE TITLE
FR: Customize default visibility with directives

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel-gazelle#342]
Setting clear code boundaries in a large monolith repository is difficult. In a native go world, one can use `internal/` importpath to make a package only usable by its own siblings. This approach is supported by gazelle as well, which will generate proper `visibility` attributes in BUILD files.

However, this approach comes with a few issues:

- Refactor is expensive.  To make a package public, it must be moved out of its own directory to make go compiler happy.
- Code is deeply nested.  To actually create private packages, `internal/` must be added everywhere.

As a comparison, the bazel's approach is simpler.  We can easily make a package public or whitelisted for other packages with `visibility` and `package_group`. In a pure bazel workspace, this can be done by nesting multiple go packages in a single directory and use `package(default_visibility)` instead, but there is no way to set such option for go directory layouts. 

Therefore it would be nice to add new directives to change the default visibility settings for generated BUILD files.

**Comment by jayconrod** [comment]
Sorry for the slow response. I'm still catching up on issues after BazelCon.

I'd prefer not to implement this. Gazelle's main job is mapping Go conventions to Bazel build files. `internal` directories are the primary way to express visibility in Go, and following that convention keeps Gazelle simple and keeps Go projects predictable.

That said, it should be easy to make your own visibility decisions, and Gazelle should not fight you on this. [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer) is a command line tool that is very useful for making batch modifications to large numbers of build files. That's probably the best way to make visibility changes. If you've added `package(default_visibility = ...)` to a build file already, Gazelle won't generate `visibility` attributes. It also won't replace `visibility` attributes in rules that have them already.

**Comment by ashi009** [comment]
Sounds fair. Thanks!
