### ISSUE TITLE
update-repos to automatically add subdependencies

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-gazelle#362]
Running `bazel run //:gazelle -- update-repos github.com/path/package` adds the `go_repository` definition of that dependency to the `WORKSPACE` file, but it is sometimes quite cumbersome to manually have to add all sub-dependencies. It would be nice if there was some way of automatically adding all sub-dependencies. No matter if it is via the `bazel run //:gazelle -- update-repos ...` command of if even having a new command `bazel run //:gazelle -- update-repos automatic` that can analyse the code and add all deps and subdeps automatically.

**Comment by jayconrod** [comment]
I'm going to de-dup this against #56, which describes the original idea for the feature.

I'd definitely like Gazelle to be able to do this, but it's a pretty significant amount of work. It would be fairly easy for Gazelle to add / update rules for your direct dependencies, but cloning those repositories and collected all the transitive dependencies is quite a bit more work. We're also going to need to sort out whether to include test dependencies and dependencies that are unreachable from targets in your repository.

As a workaround, I think the easiest thing to do now is create a `go.mod` file (`go mod init example.com/repo; go mod tidy`) and then import it with `bazel run //:gazelle -- update-repos -from_file=go.mod`.
