### ISSUE TITLE
Generate dependencies on :foo_go_proto instead of :go_default_library

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#388]
Hi, I am trying to figure out the best way to use Gazelle in this scenario:

```
//src/...  # contains java and protobufs. gazelle:prefix alpha
//gocode/src/corp/... # contains go code. gazelle:prefix corp
```

For example:
```
# contains :foo_java_proto and :foo_go_proto rules, and other java rules
# These are generated by a wrapper rule we have around rules_proto
//src/com/corp/foo/BUILD 
//src/com/corp/foo/foo.proto 

 # uses //src/com/corp/foo:foo_go_library
//gocode/src/corp/bar/bar.go
```

When running gazelle on the `//gocode/src/corp` directory tree, it generates a dependency on `//src/com/corp/foo:go_default_library` instead of `...:foo_go_proto`, and I was looking for advice on the best way to make it work out. We wrap this library, which my understanding is the most modern and recommended one: 
https://github.com/stackb/rules_proto

I see these options:
1. Create a `go_default_library` wrapper library for all our `foo_go_proto` rules
2. Manually fix the gazelle-generated dependencies, and have it be a thing that developers generally just have to do by hand. 
3. Get gazelle:resolve directives to work and add one for each .proto file.

The problem with 1 is that it will require some manual fixup when there are multiple protos in one package. But at least it's done per proto instead of per caller, so this is an attractive option.

The problem with 2 is that it adds an ongoing tax to development. I'm also not sure what concrete mechanism I can use to have Gazelle not add the `go_default_libraries` back in future runs (adding a `keep` directive on the correct import doesn't prevent it)

For 3, I was unable to get resolve directives to work. I tried both adding this directive in the build file next to the proto:
```
# gazelle:resolve proto go profile.proto //src/com/corp/profile:profile_go_proto
```

and this one in the BUILD file of the calling package:
```
# gazelle:resolve proto go //src/com/corp/profile/profile.proto //src/com/corp/profile:profile_go_proto
```
but neither one changed the result. Even if I got them to work, I would want to somehow generate them with the macro we're using rather than by hand, but since they are a comment it seems like that's probably impossible.

My understanding is that we are using the rule naming convention recommended by `rules_proto`, so I also thought it might make sense for gazelle to support this case a bit better, but I'm not sure what feature addition would cause it to work seamlessly. I also didn't know if there was some way to have Bazel notice that the file it needed was included in an existing bazel target and depend on that one instead.

Thanks for any advice!
Rob

**Comment by jayconrod** [comment]
What do your `go_proto_library` targets look like? Could you post an example of one of them? rules_go and Gazelle don't directly support proto rules other than those defined by Bazel and rules_go, but Gazelle will index `go_proto_library` targets regardless of how `go_proto_library` is defined.

What do your imports from .go files in the corp directory look like? If the whole repository is being indexed by Gazelle, and the import strings in the .go file match the `importpath` attributes in the `go_proto_library` rules, Gazelle should emit the correct dependencies. Are there any other libraries with the same `importpath` that might conflict? Are there any visibility restrictions (i.e., a `vendor` or `internal` parent directory)?

Also, how exactly are you invoking Gazelle? I just want to verify that it's indexing library rules in the whole repository.

If you end up needing `gazelle:resolve` directives, it's probably best to add them to the root build file. They apply in the directory where they appear and in subdirectories (so if you have them in `//src`, they won't affect `//gocode`). Also, as I understand, you just want to map imports from  .go files to the right `go_proto_library` targets. That should be written as:

```
# gazelle:resolve go corp/profile //src/com/corp/profile:profile_go_proto
```

**Comment by robfig** [comment]
Here's the rules we're using, a usage of the rules, the results of the macro expansion, and an example Go file importing them:
https://gist.github.com/robfig/f37d8c1450688ca3323c84cc2a6a4ea2

Responding to your questions/observations:
- It sounds like the problem might be that we don't use a rule called `go_proto_library` directly. 
- Generally, there are no visibility restrictions. I believe all of our protos are public.
- We use glock today to manage dependencies, so they exist under `//gocode/src/github.com/...`, perhaps something to gazelle:ignore. We use `external` dependency mode, and import a file of go_repository definitions in WORKSPACE. I added this to the gist
- Conflicts - We do have protos generated outside of bazel under //gocode/src/alpha/; I'll add an ignore directive for Gazelle to avoid that. I don't think that's the problem though, because it generated the right path to the package (`//src/com/corp/profile`) just using the wrong target name.
- Invoking - I'm running gazelle as `bazel run //:gazelle -- gocode/src/corp`

Thanks for looking into this!

**Comment by jayconrod** [comment]
Oops, I missed your response to this last week. Sorry for the delay.

> It sounds like the problem might be that we don't use a rule called go_proto_library directly.

That sounds like an issue. In general, Gazelle processes files at the syntax level. It doesn't evaluate anything, so rules declared inside a macro won't be visible. It can't tell the difference between rules and macros though, so if you had a macro named `go_proto_library`, it would try and update that. There isn't currently any way for Gazelle to treat a rule as if it were another kind of rule.

> We use glock today to manage dependencies, so they exist under //gocode/src/github.com/..., perhaps something to gazelle:ignore. We use external dependency mode, and import a file of go_repository definitions in WORKSPACE. I added this to the gist

If you want to prevent Gazelle from indexing a directory tree, use `# gazelle:exclude gocode/src` in your root build file. `# gazelle:ignore` prevents Gazelle from *updating* a build file, but it will still index libraries in there and make them available for dependency resolution.

**Comment by robfig** [comment]
I'll keep an eye on that PR and take a look when it's merged. Thanks for the guidance.

**Comment by robfig** [comment]
FYI, here's what ended up working.

This change to gazelle:
https://github.com/bazelbuild/bazel-gazelle/compare/master...robfig:master

Results in this test case working:
https://github.com/robfig/gazelle-language-test
