### ISSUE TITLE
autogazelle's echo "done running autogazelle" >&1 possibly interferring with query

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-gazelle#389]
We do stuff like `output=$(bazel query <something>)` and then use that output to decide some logic, e.g. what tests to run etc. and because of the echo that autogazelle add our subsequents bazel commands are then trying to query/build `'//:done, //:running //:autogazelle`. It is quite easy to fix by either removing the `echo` or not running autogazelle on `query` but thought it is worth opening a ticket for this as maybe there is another elegant solution.

**Comment by jayconrod** [comment]
This should echo to stderr, not stdout. I think that's a bug. I'll fix that today.

autogazelle does need to run on `query` though, since `query` relies on correct build files.
