### ISSUE TITLE
update-repos: `gazelle: error parsing "go.mod": exec: "go": executable file not found in $PATH`

### ISSUE THREAD

**Issue by fsenart** [bazelbuild/bazel-gazelle#392]
With the following setup:

```bzl
# WORKSPACE

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.3/rules_go-0.16.3.tar.gz"],
    sha256 = "b7a62250a3a73277ade0ce306d22f122365b513f5402222403e507f2f997d421",
)
http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.15.0/bazel-gazelle-0.15.0.tar.gz"],
    sha256 = "6e875ab4b6bf64a38c352887760f21203ab054676d9c1b274963907e0768740d",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
gazelle_dependencies()
```

```bzl
# BUILD

load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/example/project
gazelle(name = "gazelle")
```

```
# go.mod
# intentionally left empty
```

And while inside the [Bazel Docker Container](https://docs.bazel.build/versions/master/bazel-container.html):

```sh
docker run --rm -it -e USER=$(id -u) -u $(id -u) -v $PWD:/exp -v /tmp/exp:/.cache -w /exp --entrypoint=/bin/bash l.gcr.io/google/bazel:0.19.2
```

When I perform the following command:

```sh
bazel run //:gazelle -- update-repos -from_file=go.mod
```

I get the following error:

```
gazelle: error parsing "go.mod": exec: "go": executable file not found in $PATH
```

---

I don't know the project's internals but my investigations led me to [repo/modules.go#L136](https://github.com/bazelbuild/bazel-gazelle/blob/master/repo/modules.go#L136l) where `$GOROOT` is not set which may be explained by the fact that [internal/gazelle.bash.in#L58](https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/gazelle.bash.in#L58) is not called since [here](https://github.com/bazelbuild/bazel-gazelle/commit/04a7472f63731d38bd6ba4032ac83568809c8a7b#diff-a276da92f6630b72008d149f91b93e49L102).

**Comment by jayconrod** [comment]
Yep, we really should be calling `set_goroot`. I wonder how long that's been broken? Thanks for reporting.

Once #393 is merged, you'll need to add a `module` statement at least to the `go.mod` for it to parse correctly.
