### ISSUE TITLE
Support source directives in imported Gopkg.toml files

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#411]
See [source](https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md#source) from the dep documentation. `source` directives specify a replacement for a module. The replacement may be an import path or a URL. Either way, we should convert this to `remote` and `vcs` attributes in `go_repository`.

In the case of an import path, we should resolve it to a remote and VCS using `golang.org/x/tools/go/vcs`, as fetch_repo would do.

In the case of a URL, there's no specified way to determine what VCS to use. URLs usually start with `https://`, which is used by several VCSs.

**Comment by jayconrod** [comment]
Related #289

**Comment by robfig** [comment]
Closing - dep is no longer relevant
