### ISSUE TITLE
Including the workspace name in deps?

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel-gazelle#420]
Hello,

Is it possible for the rules generated by gazelle to include the current workspace name. For example, "@my_workspace_name//some/dep:go_default_library" instead of "//some/dep:go_default_library".

It will help avoid warnings like the below when I build across multiple local repositories:
```
GoLink: warning: package "some/dep" is provided by more than one rule:
    @my_workspace_name//some/dep:go_default_library
    //some/dep:go_default_library
Set "importmap" to different paths in each library.
This will be an error in the future.
```

Thank you.

**Comment by siddharthab** [comment]
I can explain my setup to you and then perhaps you can shine some light for me on what should happen.

```
go/src/grail.com <- our internal module (1)
go/src/github.com/grailbio/... <- modules that we open source on github but maintain in our monorepo (2)
go/src/github.com/... <- other modules that we have locally forked (3)
@com_github_x_y <- go_repository workspaces that we import from our go.mod (4)
```

For (1) and (2), we specify `gazelle:prefix` in our main workspace for each of the modules. Their build files are maintained by running `bazel run //:gazelle` in the main workspace.

For (3), we define `local_repository` workspaces such that gazelle's external mode resolutions while executing to create our `go_repository` workspaces in (4) continues to be valid. We have replace directives for them in our go.mod file. All the modules in (3) are `gazelle:exclude` from our main workspace, and we run gazelle separately in each of them whenever we change something there.

Our deviation from an expected setup is that in (2), we do not specify `local_repository` workspaces because we would like to use the same bazel cache, etc. when building from within the directories in (2). We have used a multiple workspace setup for these before and it created friction for our developers. If we do define `local_repository` workspaces for these, then everything will work smoothly.

But because we are not doing what is expected, rules_go gets confused when the same target is referenced in the `deps` attribute as `//go/src/github.com/grailbio/base/simd` (in our main module) and as `@grail//go/src/github.com/grailbio/base/simd` (in a module from (3)).

**Comment by jayconrod** [comment]
Ok, I think I understand your setup, but I have a few questions:

* Where are the WORKSPACE files and what are their names? I think there should be one in the root directory and one in each go/src/github.com/... directory (except grailbio).
* Are the build files in (2) published? Do they refer to internal labels? I'm assuming no.

The important thing here is that as far as both Bazel and Gazelle are concerned, each target is defined in exactly one workspace, and each workspace should have the same understanding of where the workspace boundaries are and what the workspace names are. Each workspace should have a WORKSPACE file at the top with a `workspace(name = "something_unique")` declaration. Gazelle doesn't understand `local_repository` declarations, but if you prevent Gazelle from recursing across workspace boundaries with `# gazelle:exclude`, it should work.

**Comment by jayconrod** [comment]
I'm not sure where that error is coming from though. I created a small example, but it didn't show this error.

* Workspace `localrepos` (`example.com/localrepos`) is in the root directory. It has a main package and a library, `lib`.
* Workspace `fork` (`example.com/fork`) is in the `fork` directory. It has a library that depends on `@localrepos//lib:go_default_library`.
* The main package in the main repo depends on `@fork//:go_default_library`.

I hacked some of the dependency resolution rules with `# gazelle:resolve`. That wouldn't scale in a large repo, but it worked for a quick hack like this.

```
-- WORKSPACE --
workspace(name = "localrepos")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "7be7dc01f1e0afdba6c8eb2b43d2fa01c743be1b9273ab1eaf6c233df078d705",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.5/rules_go-0.16.5.tar.gz"],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "7949fc6cc17b5b191103e97481cf8889217263acf52e00b560683413af204fcb",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.16.0/bazel-gazelle-0.16.0.tar.gz"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

local_repository(
    name = "fork",
    path = "fork",
)

-- BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix example.com/localrepos
# gazelle:exclude fork
# gazelle:resolve go example.com/fork @fork//:go_default_library

gazelle(name = "gazelle")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "example.com/localrepos",
    visibility = ["//visibility:private"],
    deps = ["@fork//:go_default_library"],
)

go_binary(
    name = "localrepos",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

-- main.go --
package main

import "example.com/fork"

func main() {
	fork.Foo()
}

-- lib/BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["lib.go"],
    importpath = "example.com/localrepos/lib",
    visibility = ["//visibility:public"],
)

-- lib/lib.go --
package lib

func Foo() {}

-- fork/BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix example.com/fork
# gazelle:resolve go example.com/localrepos/lib @localrepos//lib:go_default_library
gazelle(name = "gazelle")

go_library(
    name = "go_default_library",
    srcs = ["fork.go"],
    importpath = "example.com/fork",
    visibility = ["//visibility:public"],
    deps = ["@localrepos//lib:go_default_library"],
)

-- fork/WORKSPACE --
workspace(name = "fork")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "7be7dc01f1e0afdba6c8eb2b43d2fa01c743be1b9273ab1eaf6c233df078d705",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.16.5/rules_go-0.16.5.tar.gz"],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "7949fc6cc17b5b191103e97481cf8889217263acf52e00b560683413af204fcb",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.16.0/bazel-gazelle-0.16.0.tar.gz"],
)

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

local_repository(
    name = "localrepos",
    path = "..",
)

-- fork/fork.go --
package fork

import "example.com/localrepos/lib"

func Foo() { lib.Foo() }
```

**Comment by siddharthab** [comment]
Thank you so much Jay for making an example. I could have done this for you. 😄 

You need to make one change in your example to see the warning. In your main.go, you need to depend on lib directly as well. So,
```
-- main.go --
package main

import "example.com/fork"
import "example.com/localrepos/lib"

func main() {
	lib.Foo()
	fork.Foo()
}

-- BUILD.bazel --
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix example.com/localrepos
# gazelle:exclude fork
# gazelle:resolve go example.com/fork @fork//:go_default_library

gazelle(name = "gazelle")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "example.com/localrepos",
    visibility = ["//visibility:private"],
    deps = [
        "@fork//:go_default_library",
        "//lib:go_default_library",
    ],
)

go_binary(
    name = "localrepos",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
```

**Comment by jayconrod** [comment]
Got it, reproduced.

I think this is a bug in Bazel, and I've opened bazelbuild/bazel#7099. I discussed this with @dkelmer. She fixed some namespacing bugs related to loading .bzl files. She said it's possible she missed a code path, but if it turns out this is related to the way the main workspace and external workspaces are treated differently within Bazel, it may be a difficult issue to fix.

**Comment by siddharthab** [comment]
Thank you so much for looking into it.

If it turns out to be a difficult issue to fix, it will be nice to reference each target in a consistent way with gazelle. So each dep gets prefixed with the workspace name. That way, these conflicts won't arise. This can be a user knob if you prefer.

**Comment by jayconrod** [comment]
I'd rather not support this in Gazelle. Fundamentally, this is a bug in Bazel. It may be necessary to work around this (either short term or long term, depending on how difficult the fix is), but I don't think Gazelle is the right place for that workaround. Outside of Gazelle-generated rules, there is still a lot of opportunity to trigger this bug. There's also risk of other build file maintenance tools like Buildifier "fixing" this for you (though I don't think that's something Buildifier does right now).

Instead, my advice would be to avoid references from `local_repository` into the main repository more systematically. There are a couple ways this could work (but both may require large-scale changes to build files).

1) Your main workspace could include all of your modified open source code. So in your earlier description, 1, 2, and 3 would be in the same workspace. `local_repository` would not be used to separate 3 anymore.
2) Your main workspace could include almost nothing. Everything would be split into smaller `local_repositories` that could reference each other freely.

**Comment by siddharthab** [comment]
That's fair. We are doing something unexpected, so it does not make sense for gazelle to have a workaround.

You can close this issue if you want to. The issue in bazel should be enough to track this.

Thank you Jay for going the extra mile and coordinating with the bazel team on this. It's very rare to see this level of commitment in open source projects. :-)
