### ISSUE TITLE
Force Gazelle to output files called BUILD instead of BUILD.bazel

### ISSUE THREAD

**Issue by marpaia** [bazelbuild/bazel-gazelle#425]
Howdy! Thanks for such a great project! I was wondering if I could force gazelle to output files called `BUILD` instead of `BUILD.bazel`? I read up on and understand the motivation for using `BUILD.bazel`, but the problems the rename aims to solve (collisions with other things named `build` on case-insensitive filesystems, etc) are not problems for me, so I'd like to continue using `BUILD` if possible.

**Comment by marpaia** [comment]
I see. It was not clear to me that the flags for `fix` and `update` would work for running the initial Gazelle command. I see that I can now do `bazel run //:gazelle -- --build_file_name BUILD` and that will do the trick. Thanks @achew22!

**Comment by marpaia** [comment]
I wonder, is there a way I can set this as a default?

**Comment by achew22** [comment]
@marpaia, in the documentation for the [bazel rule](https://github.com/bazelbuild/bazel-gazelle#bazel-rule) it has an argument titled `extra_args` with the docstring of `A list of extra command line arguments passed to Gazelle.` I believe this will achieve the end you want.

**Comment by marpaia** [comment]
Yes, that's perfect! Thanks!
