### ISSUE TITLE
Run gazelle in a subdirectory of the workspace

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel-gazelle#427]
We are making use of the `gazelle` rule, so invoking `bazel run //:gazelle` and it would be nice if there was a way to invoke gazelle in a subdirectory of the workspace. More specifically I want to make use of the output_runner of bazel-watcher: there are not much docs on that but see https://github.com/bazelbuild/bazel-watcher/pull/134 for the basic idea.

So what I would want to do here is, whenever we get the `GoCompile: missing strict dependencies:` error I will look at the next line, get the path of the source file and just want to run gazelle in the first directory within the workspace. It would be even nicer if we could get the path to the package in the error message and run gazelle just there but given our monorepo directory structure that should already work quite well.

So one way I could imagine it is via a flag: `bazel run //:gazelle -- fix --cwd=./app` and then gazelle takes that relative to the `BUILD_WORKSPACE_DIRECTORY`.

**Comment by jayconrod** [comment]
Gazelle already accepts positional arguments that indicate where to run. When Gazelle is run via `bazel run //:gazelle`, there is a bash script that jumps to the workspace root directory before executing the Gazelle binary, so paths are interpreted relative to there. Does that solve the problem?

Note that if `-index=true` (the default), Gazelle will read build files in all directories, but will only update build files in the directories you ask for. Also, if `-r=true` (also default), subdirectories will also be updated.

Also, you might be interested in [autogazelle](https://github.com/bazelbuild/bazel-gazelle/tree/master/cmd/autogazelle)? Sounds like you are trying to solve a similar problem.

**Comment by Globegitter** [comment]
Thanks for that will give it a try - yes we have been trying out autogazelle and it has been working really well, but I have heard some of our devs complaining about each bazel command taking a bit longer now (especially for non-go projects), and I am not sure if it is working a 100% nicely together with bazel-watcher at all times. Either way, we are starting to evaluate this different approach and see how that compares in terms of dev experience.
