### ISSUE TITLE
LTS of vendor strategy ?

### ISSUE THREAD

**Issue by dan-compton** [bazelbuild/bazel-gazelle#429]
Will vendor mode ever be deprecated or is a permanent fixture in the tooling?  We have constant issues with vendor mode and gazelle replacing references to protobuf-related libraries (pulled in by glide which is a potential place to fix this), along with invocations of gazelle -vendor across our codebase (as in the context of go generate for goadesign specs).

Does the gazelle project intend to honor the vendor directory indefinitely, or is the plan to reduce functionality down to pulling in dependencies from glide.yaml gopkg.lock etc into the workspace.  It would be an excellent forcing function from my perspective if that were the case.

**Comment by jayconrod** [comment]
Gazelle will continue to generate rules for the vendor directory as long as the Go SDK supports it. Lots of large projects need to be buildable both with the standard Go toolchain and Bazel (especially during migration periods), so this will be necessary for the foreseeable future.

Certainly there are a lot issues around protos though. Vendored protos and proto libraries cause problems and conflicts. Gazelle tries to avoid these when it can, and we have special dependency resolution rules for well known types and googleapis targets.

**Comment by dan-compton** [comment]
Thanks for the feedback!
