### ISSUE TITLE
Go build failing with weird path issue

### ISSUE THREAD

**Issue by zaccari** [bazelbuild/bazel-gazelle#432]
First - just want to thank you for creating this tool, it has been a pure joy to work with. I originally posted here https://github.com/bazelbuild/rules_go/issues/1921 but I believe it might be related to how I ran `gazelle` in my project. When I attempt to build my go service, I'm getting this error:

```
GoCompile: error running compiler: exit status 2
/private/var/tmp/_bazel_michael/6b577be22076903abd179ce929d06cd5/execroot/charybdis/vendor/google.golang.org/api/option/option.go:163:54: cannot use "bitbucket.org/accelecon/charybdis/vendor/google.golang.org/api/internal".NewPoolResolver(int(w), o) (type *"bitbucket.org/accelecon/charybdis/vendor/google.golang.org/api/internal".PoolResolver) as type "google.golang.org/grpc/naming".Resolver in argument to grpc.RoundRobin:
	*"bitbucket.org/accelecon/charybdis/vendor/google.golang.org/api/internal".PoolResolver does not implement "google.golang.org/grpc/naming".Resolver (wrong type for Resolve method)
		have Resolve(string) ("bitbucket.org/accelecon/charybdis/vendor/google.golang.org/grpc/naming".Watcher, error)
		want Resolve(string) ("google.golang.org/grpc/naming".Watcher, error)
```

Here's what the `BUILD.bazel` file looks like for `google.golang.org/api/option/option.go`:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "credentials_go19.go",
        "credentials_notgo19.go",
        "option.go",
    ],
    importmap = "bitbucket.org/accelecon/charybdis/vendor/google.golang.org/api/option",
    importpath = "google.golang.org/api/option",
    visibility = ["//visibility:public"],
    deps = [
        "//vendor/golang.org/x/oauth2:go_default_library",
        "//vendor/golang.org/x/oauth2/google:go_default_library",
        "//vendor/google.golang.org/api/internal:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
    ],
)

```

Is it possible `gazelle` has created a `BUILD.bazel` somewhere in my project with an incorrect path? It seems to find `"google.golang.org/grpc/naming".Watcher`, just in the wrong folder.

**Comment by zaccari** [comment]
So the issue appears to be with how the `BUILD.bazel` file was generated for `google.golang.org/api/internal`:

```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "creds.go",
        "pool.go",
        "settings.go",
    ],
    importmap = "bitbucket.org/accelecon/charybdis/vendor/google.golang.org/api/internal",
    importpath = "google.golang.org/api/internal",
    visibility = ["//visibility:public"],
    deps = [
        "//vendor/golang.org/x/oauth2:go_default_library",
        "//vendor/golang.org/x/oauth2/google:go_default_library",
        "//vendor/google.golang.org/grpc/naming:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
    ],
)
```

Replacing the dep `"//vendor/google.golang.org/grpc/naming:go_default_library"` with `"@org_golang_google_grpc//naming:go_default_library"` got things working.

**Comment by jayconrod** [comment]
It sounds like you already figured this out, but this issue comes up when vendored types leak into the public API of external repos. Most vendoring tools encourage this unfortunately, so it's best to go 100% external repos (excluding vendor directories) or 100% vendored. If you're using `go_proto_library`, you implicitly are using the external gRPC, so that may limit your choices.

You can exclude vendor directories in external repositories retrieved with `go_repository` by adding `build_extra_args = ["-exclude=vendor"]`.

**Comment by zaccari** [comment]
Awesome. Thank you for the explanation!

**Comment by dhiller** [comment]
> ... Replacing the dep `"//vendor/google.golang.org/grpc/naming:go_default_library"` with `"@org_golang_google_grpc//naming:go_default_library"` got things working.

@zaccari @jayconrod thanks for investigation! 

We ran into the same issue. While  trying to fix it like above we noticed that this fix is overwritten every time you update your dependencies.

Using [# gazelle:resolve](https://github.com/kubevirt/project-infra/pull/146/commits/da43481c08d0120587854ef83e5fa266f9b2536f#diff-0ea22445d900db774c8deb00f4a4df55R4) like described [here](https://github.com/bazelbuild/bazel-gazelle#id8) fixed this permanently for us. Please let me know if there are any issues. Thanks!
