### ISSUE TITLE
Language extensions for gazelle

### ISSUE THREAD

**Issue by vitarb** [bazelbuild/bazel-gazelle#438]
## Introduction

Code generation process takes IDL files as an input and after applying code generator produces code that can later be used under unique import path in libraries, binaries and tests. There are numerous combinations of codegen configurations that require producing different variants of code for the same set of IDLs. Supporting them requires running code generation multiple times and providing results as different go libraries. We would need to update gazelle in order to generate separate build rules for different configurations, each of resulting go_library rules would have different import path and may have different dependencies.

## Use cases

- Compiling same IDL files using different code generators. There are numerous thrift compilers and there is development of proto v2 happening on the branch. It's possible that users would want to implement their own extensions or code generators too.
- Compiling same IDL files using incompatible sets of plugins. Certain plugins are not designed to be compatible with each other. One such example is gogoproto vs plain proto, there is a bunch of other examples in thrift ecosystem.
- Some projects may go as far as to define custom DSLs and code generators that are not generally available to the community.
- Users of gazelle may need to be able to generate custom build rules for things like integration testing, documentation, etc.
- Requiring [multiple prefixes](https://github.com/bazelbuild/bazel-gazelle/issues/437) and custom dependencies for different user owned code generation plugins.

## Language abstraction

Language abstraction in gazelle provides a way to implement custom logic that takes package metadata as an input and produces build rules as an output. It should be generic enough to support various scenarios for creating rules that run code generation with only limitation that code needs to be part of gazelle.

## Proposal

We would like to be able to develop custom build rule generation logic outside of gazelle and have a mechanism that would load and execute these extensions in gazelle. We suggest using [plugin](https://golang.org/pkg/plugin) feature available in Go to compile custom Language implementations into shared object (.so) files and pass them to gazelle. Gazelle will then load plugins in runtime and will execute them along with other natively supported languages.

I believe that having this feature would enable a lot of possibilities and customizations that would not otherwise be possible without forking or patching gazelle.

Do you see value in adding language extensions based on go plugins into gazelle? 
If yes let's work together formalizing interaction model between extensions and gazelle and see if we can help contribute this improvement.

**Comment by ianthehat** [comment]
Plugins are only supported on Linux and MacOS, and not very well on those. The combination of limitations and absence of Windows support make them a terrible fit for this kind of proposition...
I would suggest you look into using starlark instead, especially as that is the language that bazel rules are written in, and is thus a language rule writers are already steeped in.
There is an implementation of [starlark in go](https://github.com/google/starlark-go/) that would fit naturally into gazelle.

**Comment by vitarb** [comment]
Glad to hear that you are open to adding this feature in principal, I'm sure we can work out implementation details and choose optimal technology.

I'm not going to defend Go plugins much as they seem a bit immature and I agree that Starlark does seem like a better option on paper as it provides hermetic execution environment and shields us from platform specific issues.

My main concern though is that if we take Starlark route we would need to collect and pass all information that may potentially be needed inside of the plugin, which may limit what we can do.

For example our thrift processing requires parsing thrift files and reading service names in order to generate all build rules. If we go with Starlark based design we would need to write implementation of thrift parser in starlark or pre-parse it inside of gazelle and pass information to the plugin. Both options look pretty bad to me.

Do you see any way to get around this?

**Comment by jayconrod** [comment]
Agree with Ian's concerns about plugins, but it's not really clear to me that they're necessary. The list of extensions you need would be known at build time, right?

It seems like this problem is solved by [`gazelle_binary`](https://github.com/bazelbuild/bazel-gazelle/blob/master/extend.rst#gazelle-binary). That rule lets you build a custom Gazelle binary with a list of language extensions. It essentially generates a file that goes in the main package, then builds a regular Go binary from that. You can reference custom binaries from the [`gazelle`](https://github.com/bazelbuild/bazel-gazelle#bazel-rule) rule via the `gazelle` attribute.

**Comment by vitarb** [comment]
Nice, that should work perfectly for us!

I've initially misunderstood the concept and thought that languages parameter can only be used to enable/disable existing ones.

Being able to define custom go libraries and have them compiled into gazelle's binary is exactly what I wanted.

We would probably need to think about defining boundaries for these language extensions and triggering conditions especially as it comes to autogazelle and incremental execution. 

For now we should be good though, thanks!
