### ISSUE TITLE
Problem with uppercase letters in the repository name

### ISSUE THREAD

**Issue by sustrik** [bazelbuild/bazel-gazelle#441]
I am using following external dependencies:

```
go_repository(
    name = "com_github_pierrec_lz4",
    importpath = "github.com/pierrec/lz4",
    commit = "08c27939df1bd95e881e2c2367a749964ad1fceb"
)
go_repository(
    name = "com_github_pierrec_xxHash",
    importpath = "github.com/pierrec/xxHash",
    commit = "a0006b13c722f7f12368c00a3d3c2ae8a999a0c6"
)
```
Despite repo xxHas existing I get an error:

```
no such package '@com_github_pierrec_xxhash//xxHash32'
```

Changing the uppercase H to lowecase one helps -- in a way. The package is dowloaded. However, library lz4 which dependes on xxHash won't build:

```
GoCompile: missing strict dependencies:
	.../external/com_github_pierrec_lz4/lz4.go: import of "github.com/pierrec/xxHash/xxHash32"
Known dependencies are:
	github.com/pierrec/xxhash/xxHash32
```

**Comment by jayconrod** [comment]
Currently, when Gazelle runs within `go_repository`, it doesn't read any information from the main workspace or from other external repositories. So when it resolves an import in an external repository, it will use the default name for that repo, ignoring customized names in WORKSPACE.

You should be able to fix this by changing the name of the `go_repository` to `com_github_pierrrec_xxhash` (all lower case). This is the default name that `gazelle update-repos` would generate. Make sure not to change the `importpath` though. It's important that this matches the strings that other packages use to import packages in that repository.

```
go_repository(
    name = "com_github_pierrec_lz4",
    commit = "473cd7ce01a1113208073166464b98819526150e",
    importpath = "github.com/pierrec/lz4",
)

go_repository(
    name = "com_github_pierrec_xxhash",
    commit = "be086f0f67405de2fac6bc563bf8d0f22fa2a6b2",
    importpath = "github.com/pierrec/xxHash",
)
```

**Comment by sustrik** [comment]
That helped. Thanks!
