### ISSUE TITLE
Option to generate cc_proto_library, java_proto_library, java_lite_proto_library

### ISSUE THREAD

**Issue by peter-edge** [bazelbuild/bazel-gazelle#452]
It would be nice if there was the option to generate the built-in [cc_proto_library](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_proto_library), [java_proto_library](https://docs.bazel.build/versions/master/be/java.html#java_proto_library), and [java_lite_proto_library](https://docs.bazel.build/versions/master/be/java.html#java_lite_proto_library) rules.

For example, given the following already-generated rule:

```
proto_library(
    name = "bazv1_proto",
    srcs = [
        "job_api.proto",
        "hello.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//uber/proto/foo/bar/v1:barv1_proto",
        "//uber/proto/schema/gis/v1:gisv1_proto",
        "@com_google_protobuf//:timestamp_proto",
    ],
)
```

It would be nice to be able to generate:

```
cc_proto_library(
    name = "cc_bazv1_proto",
    deps = [":bazv1_proto"],
    visibility = ["//visibility:public"],
)

java_proto_library(
    name = "java_bazv1_proto",
    deps = [":bazv1_proto"],
    visibility = ["//visibility:public"],
)

java_lite_proto_library(
    name = "java_lite_bazv1_proto",
    deps = [":bazv1_proto"],
    visibility = ["//visibility:public"],
)
```

This could open up a can of forms, for example people might want options to generate rules from https://github.com/stackb/rules_proto, however I think keeping it to this for now would be justifiable, since these rules are built-in.

This shouldn't be overly difficult, and should be opt-in, not opt-out. These rules might actually be best done as separate `language.Language` impls entirely that depend on the `proto` language being present, but this gets into a whole other issue that should be filed separately, namely it would be nice to be able to dynamically select the language list (including `proto` and `go`), and define dependencies between languages. Even nicer would be to have each rule X rule-config be it's own "language" with defined deps between them.

In lieu of making these separate languages, which might be overkill for something this simple, these could just be added as flags to the `proto` language. If you'd like, I'm happy to work on a PR for this.

Slightly related to https://github.com/bazelbuild/bazel-gazelle/issues/138 if things are being tackled but not dependent.

**Comment by jayconrod** [comment]
I think [Extending Gazelle](https://github.com/bazelbuild/bazel-gazelle/blob/master/extend.rst) is the right way to handle generating rules for additional languages. `language/proto` should remain language-neutral, but it should provide enough information for other extensions to generate the right rules.

I think it's best for extensions to be written outside of the bazel-gazelle repository. I'm not familiar enough with the subtleties in these rules to be able to review PRs or fix bugs that are reported here.

I'm happy to answer questions though, and I'll consider language-neutral framework changes if they're necessary.

**Comment by peter-edge** [comment]
These are all built in to bazel, no different than `proto_library` (see the above links) - there isn't any nuance here, and since they depend on the `proto` language, ie they need to depend on the `proto_library` rules, where the naming logic is within this repository, it would prove difficult to do this without some work. Can we keep this open to track this?

Alternatively it's a simple add

**Comment by jayconrod** [comment]
`cc_library` and `java_library` are also built into Bazel, but I'd give the same advice on a feature request to support to them -- I think they should be developed as separate extensions in separate repositories. I don't have bandwidth to maintain them here.

And again, the `language/proto` extension should provide enough information to other extensions to generate rules. For example, `go_proto_library` rules are generated by `language/go` using imports and options extracted from .proto files by `language/proto`.

**Comment by peter-edge** [comment]
OK fair enough - I'll explore this and keep you up to date if you're interested. Thanks for the quick response! Appreciate it

**Comment by alokpr** [comment]
Any update on this? I see a `gazelle:lang` directive but not sure if that is related to this issue.
