### ISSUE TITLE
Gazelle ignored imports on generated proto sources

### ISSUE THREAD

**Issue by stevewolter** [bazelbuild/bazel-gazelle#453]
When I generate a proto source, e.g. with a genrule, gazelle will ignore its imports when generating dependencies for the rule.

**Comment by jayconrod** [comment]
It's not feasible for Gazelle to do this. Gazelle can't build generated files, since that would make Gazelle a much heavier tool, and it would raise a lot of issues with multiple concurrent runs of Bazel.

Instead, you can add `deps` manually and add `# keep` comments to ensure they're not removed.
