### ISSUE TITLE
Configure how Gazelle handles testdata directories

### ISSUE THREAD

**Issue by blico** [bazelbuild/bazel-gazelle#456]
Currently, when generating `go_test` rules Gazelle will set `data = glob(["testdata/**"])` if there is a `testdata` directory present in the package, as long as the `testdata` directory does not contain any buildable code. When a `testdata` directory contains buildable code and is used by a `go_test` rule, you must exclude the directory from Gazelle and manually populate the `data` attribute. An example of this case in Gazelle can be found here: https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/BUILD.bazel#L4

Given that by default [Go ignores directories named testdata](https://golang.org/cmd/go/#hdr-Test_packages), Gazelle should support this use case with minimal resistance. 

One solution would be to create a `#gazelle:go_test_data_dir` directive, this would tell Gazelle to not generate build files for a directory if its name matches the directive value, and to populate the `data` attribute of any `go_test` rules with a matching directory name in their package. When the directive is not set, Gazelle will treat the `testdata` directory like any other directory.

**Comment by jayconrod** [comment]
Sorry for the latency -- it's been a really busy week.

Just to explain why this works the way it does: Go ignores directories named `testdata` when expanding wildcards (e.g., `go test ./...`), but you are allowed to have importable packages named `testdata`, and people do that. So we try to guess whether `testdata` is actually a package or just data based on whether there are buildable .go files or BUILD.bazel files.

This directive seems like it would be useful for repositories that have a lot of `testdata` directories with buildable Go code that should be treated as data, but that seems like a very narrow use case. Could you say more about when this would be needed? I'd rather not have a feature for this if it can be solved with another general-purpose mechanism (e.g., adding `// +build ignore` to test files).

**Comment by blico** [comment]
No worries, and thanks for the additional information on `testdata`.

Our repo contains no cases of `testdata` that are actually meant to be built. However the number of `testdata'`s with go code is small, so for now I will close this issue. In the future if it becomes a common pattern within our repo, I may reopen the issue.
