### ISSUE TITLE
bazel_gazelle does not use commit hash specified in go_repository rule

### ISSUE THREAD

**Issue by jiachenwang** [bazelbuild/bazel-gazelle#457]
I am upgrading [ESP](https://github.com/cloudendpoints/esp) to newer version Bazel (from 0.5.4 to 0.21.0). I use bazel_gazelle for golang dependencies. I find a problem that bazel_gazelle does not use commit hash specified in go_repository. For example, this rule in repositories.bzl:
```
go_repository(
        name = "org_golang_google_grpc",
        commit = "a02b0774206b209466313a0b525d2c738fe407eb",
        importpath = "google.golang.org/grpc",
    )
```
commit id (a02b0774206b209466313a0b525d2c738fe407eb) is [grpc-go v1.18.0](https://github.com/grpc/grpc-go/releases/tag/v1.18.0), but v1.15.0 is downloaded:
`cat  bazel-test_go_repo/external/org_golang_google_grpc/version.go` outputs: `const Version = "1.15.0"`. Also, running command like `bazel build @org_golang_google_grpc//interop/grpc_testing/...` or `bazel sync` ouputs log:
```
INFO: Repository rule 'org_golang_google_grpc' returned: {"remote": "https://github.com/grpc/grpc-go", "commit": "8dea3dc473e90c8179e519d91302d0597c0ca1d1", "shallow_since": "2018-09-11", "init_submodules": False, "verbose": False, "strip_prefix": "", "patches": [Label("@io_bazel_rules_go//third_party:org_golang_google_grpc-gazelle.patch"), Label("@io_bazel_rules_go//third_party:org_golang_google_grpc-android.patch")], "patch_tool": "patch", "patch_args": ["-p1"], "patch_cmds": [], "name": "org_golang_google_grpc"}
```
Looks like it is using  commit `8dea3dc473e90c8179e519d91302d0597c0ca1d1`.
To reproduce this problem:
- create a folder name `test_go_repo`
- put attached files like this:
```
.
├── test
│   └── grpc
│       ├── BUILD
│       ├── interop-client.go
│       └── repositories.bzl
└── WORKSPACE
```
- run `bazel build @org_golang_google_grpc//interop/grpc_testing/...` or `bazel sync`

Sample files attached: [test_go_repo.zip](https://github.com/bazelbuild/bazel-gazelle/files/2903158/test_go_repo.zip)

**Comment by jayconrod** [comment]
`go_repository` *does* check out the specific tag or commit you give it.

I think what's happening here is that `go_rules_dependencies` declares the repository `org_golang_google_grpc` first, and your later declaration in `grpc_go_repositories` does not override it. If you declare `org_golang_google_grpc` before calling `go_rules_dependencies`, you should get the version you want. [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies) has more information.
