### ISSUE TITLE
map_kind directive results in panic on BUILD-less package

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#469]
I found a NPE in the map_kind code through usage, and I'd like your thoughts on how best to solve it. 

It records the usage of mapped kinds associated with the `*rule.File`, but there is none on packages that lack a BUILD.bazel file. 
https://github.com/robfig/bazel-gazelle/commit/7a00eca71ce067ff3936b40df5844be0a82891ad

The f.Pkg does not appear to be easily accessible without a `*rule.File`.  We could use the relative path instead?

**Comment by jayconrod** [comment]
> The f.Pkg does not appear to be easily accessible without a *rule.File. We could use the relative path instead?

That should work. `MappedKind` can accept `rel string` instead of `f *rule.File`. They should always be the same (when `f` is non-nil).
