### ISSUE TITLE
go_repository: minimal module compatibility

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#477]
When cmd/go runs in GOPATH mode, it has a feature called [minimal module compatibility](https://github.com/golang/go/wiki/Modules#how-are-v2-modules-treated-in-a-build-if-modules-support-is-not-enabled-how-does-minimal-module-compatibility-work-in-197-1103-and-111). Unmodularized code (without a go.mod) is allowed to import packages at post-v2 versions without the major version suffix. This is a case where packages may have multiple import paths.

We should support this in `go_repository` and in rules_go.

**Comment by blico** [comment]
@jayconrod We are currently blocked by this, any thoughts on how to implement?

I was thinking we could add an option `-go_gopath_mode` that `go_repository` will pass to Gazelle whenever we are not in full [module mode](https://github.com/golang/go/wiki/Modules#when-do-i-get-old-behavior-vs-new-module-based-behavior). 

When Gazelle is in module mode, `go_gopath_mode` will tell Gazelle to remove the /vN from import paths during external dependency resolution.

AFAIK this is the only work that would be needed [minimal module compatibility](https://github.com/golang/go/wiki/Modules#how-are-v2-modules-treated-in-a-build-if-modules-support-is-not-enabled-how-does-minimal-module-compatibility-work-in-197-1103-and-111) :
> The entirety of the logic is – when operating in GOPATH mode, an unresolvable import statement containing a /vN will be tried again after removing the /vN if the import statement is inside code that has opted in to modules (that is, import statements in .go files within a tree with a valid go.mod file).

**Comment by jayconrod** [comment]
Implementing this is going to be complicated. I think a change in rules_go will be needed because a package may be imported with a path that's different from its import path. That's not currently allowed. I'm hoping that won't require a new attribute: maybe we can just look through all the provided `deps` for something that's similar to what we want but with an extra `/vN` somewhere.

If that works out, Gazelle dependency resolution could probably do the same thing. I'd rather not add any new flags or directives if it can be avoided.

This may take some time to implement. You may be able to workaround this by patching the .go files before running Gazelle (which unfortunately means `go_repository` will not be useful). [Updating dependencies](https://github.com/bazelbuild/rules_go/wiki/Updating-dependencies) describes the workflow for updating rules_go dependencies, which takes this approach (`go_repository` cannot be used there). [mod](https://github.com/marwan-at-work/mod) is a tool for bulk-rewriting imports to different module versions that may help generate a patch.

**Comment by blico** [comment]
We decided to work around this by always disabling `--experimental_module_mode` for now.

I did get a basic version of this feature working in rules_go, if anyone else needs the work here is my branch:
https://github.com/blico/rules_go/tree/modMode
