### ISSUE TITLE
Directive to reference macros from WORKSPACE

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#483]
#480 will add the ability for `update-repos` to write repository rules to a macro in a separate .bzl file.

Gazelle currently reads repository rules declared in WORKSPACE in order to discover custom repository names and known prefixes. This information is used for dependency resolution. If repositories are declared in a macro, this information will no longer be available (though #132 would be a useful escape hatch).

We should have a directive that tells Gazelle to look for repository rules in a macro in a .bzl file. It should be possible to repeat this directive, since there may be multiple macros.

```
# gazelle:repository_macro repos.bzl%go_repositories
```

This is mainly useful for the `fix` and `update` commands, but bonus points if `update-repos` can update repository rules in the corresponding macros without additional command line arguments instead of writing copies to WORKSPACE.

**Comment by ifoox** [comment]
Hi Jay, do you intend to make a release of Gazelle with this included any time soon? (I see the last release is from Feb).

**Comment by jayconrod** [comment]
Soon, yes. #477 is the main release blocker. I've gotten sidetracked with some toolchain compatibility issues in new versions of Bazel, but I expect to come back to this soon.
