### ISSUE TITLE
go_repository: support replace in module mode

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#488]
`go_repository` should support a `replace` directive, to be used in module mode.

```
go_repository(
    name = "com_example_mod",
    importpath = "example.com/mod",
    replace = "github.com/example/forked",
    version = "v1.2.3",
    sum = "h1:abcdef",
)
```

This would be analogous to module `replace` directives in `go.mod` files. We would retrieve the module named in the `replace` directive, at the specified `version`, with the specified `sum`. The original `importpath` would be the prefix for the purpose of generating build files and resolving dependencies.

**Comment by jayconrod** [comment]
Note that `replace` directives with file paths will not be supported. As long as indexing is enabled and the prefix is set correctly in the replacement directory, those should not need additional support. #475 will set the prefix automatically when encountering a `go.mod` file.

**Comment by steeve** [comment]
Is `fetchModule` (or `go mod download`) aware of possible replacement ?

**Comment by jayconrod** [comment]
It shouldn't need to be. We just need to `go mod download` the replacement using `fetch_repo`, then run Gazelle with the replaced `importpath` as the prefix.

**Comment by loeffel-io** [comment]
is there any way to ignore the `replace` statements?
