### ISSUE TITLE
Support to generate go.mod/go.sum from WORKSPACE

### ISSUE THREAD

**Issue by TennyZhuang** [bazelbuild/bazel-gazelle#491]
sometimes we need better IDE support, or just want to use go tools during develop, so that we need all the dependency, and all the info go.sum/go.mod required is written in Bazel WORKSPACE already. Is it possible to add a rule to generate a go.mod/go.sum file from WORKSPACE?

**Comment by jayconrod** [comment]
Sorry, I don't think supporting this would be feasible. We support importing `go.mod` and `go.sum` files into WORKSPACE, but not the other way around.

`go_repository` rules support modules, but repositories aren't required to be modules. We also don't do anything with version requirements and minimum version selection. So it's likely that we'd end up with files that don't make sense or aren't buildable.

We are planning to improve tool support to make that less of a pain point, but I can't promise any specific timeline right now.
