### ISSUE TITLE
update-repos: add go_repository rules in module mode

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#505]
New `go_repository` rules should be added in module mode (with `version` and `sum`) set.

Existing `go_repository` rules that aren't in module mode should probably still be updated to `master`.

**Comment by TennyZhuang** [comment]
It seems that it's not a trivial work to get the latest pseudo version from the repo, and here is no a simple API to do this. Do you think that vendoring the golang official mod internal implementation (what the goproxy.io do [here](https://github.com/goproxyio/goproxy/blob/c8a38458f30c5fc42bef89f0c2b5616dc465ab39/pkg/proxy/proxy.go#L117)) to call `modfetch.Repo.Latest()` simply is reasonable?

**Comment by jayconrod** [comment]
I'm not sure how this will work yet. We might just send `list` and `latest` requests to `GOPROXY` so we don't have to download a whole git repository (which is sometimes needed for `latest`).
