### ISSUE TITLE
Feature request: Debugging for index importpaths

### ISSUE THREAD

**Issue by GauntletWizard** [bazelbuild/bazel-gazelle#508]
I have several libraries that are generated from macros that don't seem to be recognized in the gazelle index. For example, I have generated library:

```
Thomass-MBP:bar ted$ bazel query //go/api:go_default_library --output build
# /Users/ted/go/src/gitlab.com/foo/bar/go/api/BUILD.bazel:4:1
go_library(
  name = "go_default_library",
  visibility = ["//visibility:public"],
  generator_name = "go_default_library",
  generator_function = "wire_library",
  generator_location = "go/api/BUILD.bazel:4",
  srcs = ["//go/api:grpc.go", "//go/api:http.go", "//go/api:server.go", "//go/api:wire.go", "//go/api:go_default_library_wirerunner_"],
  deps = [...],
  importpath = "gitlab.com/foo/bar/go/api",
)
```

The generating skylark macro can be found at https://github.com/GauntletWizard/wire/blob/bazel/skylark/rule.bzl#L66

However, after running gazelle, rules import of "gitlab.com/foo/bar/go/api" are replacing the dep "//go/api:go_default_library" with "@com_gitlab_foo_bar/go/api". This happens for two different macros, though at some earlier time in development (Possibly when the skylark import was from the same workspace...) these macros did work.

I'd like some way to dump the index to see if these are simply not making it in, or if they're being misnamed, or... what. Additionally, if you spot anything wrong with the skylark macro, I'd love to fix it.

**Comment by jayconrod** [comment]
This isn't actually expected to work. Gazelle knows about rules by parsing and examining the syntax tree of build files. It doesn't run `bazel query`, and it doesn't evaluate Starlark, so it won't know what rules are declared inside a macro.

You could use `# gazelle:resolve` directives in your top-level build file to explicitly declare your `wire_library` rules for dependency resolution. See [Directives](https://github.com/bazelbuild/bazel-gazelle#directives) for more info. Does that work for you?

I'm not sure how feasible it is to automatically generate `wire_library`, but if you have a lot of those, writing a Gazelle extension might be another option.

**Comment by GauntletWizard** [comment]
Ah, That makes sense. `# gazelle:resolve` directives have worked so far, though they are somewhat unwieldy. I'm also using `# gazelle:map_kind` for some libraries, and these are working - They're still named `go_default_library`, however, some of my wire_libraries are multiple build configurations for a target (i.e. I have a `production_library` go_library rule that's embedded in a `production_binary` go_binary, `local_library` wired to a `local_binary`, etc). 

At this point, it's only a couple deep. but I'll look into writing an extension or perhaps a buildozer rule that manages that section of my root BUILD file.
