### ISSUE TITLE
gazelle handles multiple test packages poorly

### ISSUE THREAD

**Issue by AustinSchuh** [bazelbuild/bazel-gazelle#515]
https://github.com/golang/net/tree/master/bpf

If you look at instruction_test.go, you will see it's in the bpf package.  The rest of the tests are in the bpf_test package.  This results in a build time error.

I can edit the test code, but I'd really rather not since it's part of the standard package.

What's the recommended solution?

**Comment by jayconrod** [comment]
You're getting an error like `conflicting package heights 12 and 9 for path "golang.org/x/net/bpf"`, right? Unfortunately, this is a known issue. Closing as a dup of bazelbuild/rules_go#1877.

Normally `go_test` does support a mix of internal and external test source files. However, I think in this case, the external package imports some other packages that import the package under test. `go build` says we should recompile all those packages to depend on the internal test package instead. Those semantics are hard to map to Bazel. We could use an aspect, but it would make tests very expensive to build if we always did so. We'd probably need an explicit flag or something on `go_test` rules with this problem.
