### ISSUE TITLE
update-repos is overriding modules that have replace directives

### ISSUE THREAD

**Issue by blico** [bazelbuild/bazel-gazelle#521]
In our `go.mod` file we have something like this:
```
require (
        github.com/bar v0.0.0-00010101000000-000000000000
	github.com/foo v1.4.0
)
replace github.com/bar/v0.0.0-00010101000000-000000000000 => github.com/foo v1.4.0
```
Gazelle calls `go list -m -json all` in order to discover relevant modules. When I call `go list -m all` with the `go.mod` file above I see the following output:
```
github.com/bar v0.0.0-00010101000000-000000000000 => github.com/foo v1.4.0
github.com/foo v1.4.0
```

With the current logic in `modules.go`, the first module listed (with the replace directive) will be overridden by the second module because they have the same import path. This results in update-repos generating the `go_repository` rule without a `replace` attribute. 

Before fixing this in Gazelle, I just want to make sure that it is expected for `go list -m all` to list the same import path twice.

**Comment by jayconrod** [comment]
That's expected behavior for `go list -m all`.

This needs to be fixed in Gazelle.
