### ISSUE TITLE
"gazelle: multiple rules" error with go modules and indirect import of github.com/grpc-ecosystem/grpc-gateway

### ISSUE THREAD

**Issue by dxj910804** [bazelbuild/bazel-gazelle#528]
I'm facing this problem when building a project which *indirectly* depends on github.com/grpc-ecosystem/grpc-gateway via "go modules"

gazelle: multiple rules (@example_project//vendor/github.com/grpc-ecosystem/grpc-gateway/internal:internal_go_proto and @example_project//vendor/github.com/grpc-ecosystem/grpc-gateway/internal:go_default_library) may be imported with "github.com/grpc-ecosystem/grpc-gateway/internal" from @example_project//vendor/github.com/grpc-ecosystem/grpc-gateway/runtime:go_default_library

The project uses bazelle-gazelle e443c54b396a236e0d3823f46c6a931e1c9939f2
bazelbuild/rules_go 2eb16d80ca4b302f2600ffa4f9fc518a64df2908

I believe this error resulted in  missing strict dependencies:
vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go: import of "github.com/grpc-ecosystem/grpc-gateway/internal

A fix tried is to add # gazelle:resolve go github.com/grpc-ecosystem/grpc-gateway/internal //internal:internal_go_proto but it didn't work out. 

Need some help here.

Note that github.com/grpc-ecosystem/grpc-gateway uses bazel.

**Comment by jayconrod** [comment]
I wouldn't normally recommend vendoring a Bazel project. The build files can require a lot of adjustment. It's better to reference them through external repository rules.

What is `example_project`? Is it a `go_repository`? You may be able to use `build_extra_args = ["-exclude=vendor"]` to avoid generating build files for the vendor directory. You can change the proto mode that way, too.

I can't help much more without an example.

**Comment by dxj910804** [comment]
"example_project" is just an anonymized placeholder.

Here are the steps we are using to setup bazel build for this project.

        go mod vendor (<= did this step since //vendor dependencies everywhere!)
        bazel run //:gazelle
        bazel run //:gazelle -- update-repos -from_file=go.mod

        bazel build //...
        bazel test //...

Top-level BUILD.bazel as this:
# gazelle:proto disable_global

In our go.mod, we have as an indirect dependency:
        github.com/grpc-ecosystem/grpc-gateway v1.9.0 // indirect

**Comment by jayconrod** [comment]
I wasn't able to reproduce this.

Could you try deleting build files from vendor (`find vendor -name BUILD.bazel -delete`), then running Gazelle again? I'm guessing that `# gazelle:proto disable_global` was added to your top-level build file after `go_proto_library` rules were already generated. In that mode, Gazelle assumes existing `go_proto_library` rules are hand-written, and it leaves them alone.

**Comment by alecthomas** [comment]
FYI I had the exact same problem and @jayconrod 's suggestion fixed it for me.

**Comment by dxj910804** [comment]
thanks and we enabled sandbox_debug flag then find all the dependencies including the same file, added exclude vendor flag for these packages and solved the problem.

**Comment by nrvnrvn** [comment]
@jayconrod hi!

I have found that in order to avoid this issue one should run something like this: 
```bash 
go mod verify
go mod tidy -v
go mod vendor
find vendor -name BUILD.bazel -delete
bazel run //:gazelle
```

`go mod vendor` fetches BUILD.bazel files for the `grpc-gateway` and as you've mentioned leaves them alone.

I wonder if this whole `find vendor -name BUILD.bazel -delete` is safe and whether gazelle should leave existing vendored `BUILD.bazel` files alone or not...

**Comment by alexeldeib** [comment]
+1, vendoring fixes this for me.

**Comment by alexeldeib** [comment]
Actually, I found that a combination of `build_file_proto_mode = "disable",` on some deps and `build_extra_args = ["-exclude=src"],` on a particularly troublesome package got it working without vendoring.

**Comment by vvrpradeep** [comment]
It might be a dumb question, can you please tell me where to include the above parameters?

**Comment by jayconrod** [comment]
@vvrpradeep Those attributes can be added to a `go_repository` rule like this:

```
go_repository(
    name = "org_golang_google_grpc",
    build_file_proto_mode = "disable",
    build_extra_args = ["-exclude=src"],
    importpath = "google.golang.org/grpc",
    sum = "h1:IZl7mfBGfbhYx2p2rKRtYgDFw6SBz+kclmxYrCksPPA=",
    version = "v1.18.0",
)
```

See [go_repository documentation](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository) for supported attributes.
