### ISSUE TITLE
Extract canonical import path from .go files

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#53]
Migrated from bazelbuild/rules_go#874

See https://golang.org/doc/go1.4#canonicalimports

Go implementation: [`findImportComment`](https://github.com/golang/go/blob/46c5856f6dfcc76e00f753387ea3dc276de2b28e/src/go/build/build.go#L933)

**Comment by psalaberria002** [comment]
I worked around it by adding `# gazelle:repository go_repository name=io_opentelemetry_go_otel_exporters_otlp importpath=io.opentelemetry/go/otel/exporters/otlp/internal` in my WORKSPACE.

**Comment by purkhusid** [comment]
I'm hitting the same issue when trying to use OpenTelemetry packages. Are ther any known workarounds?

**Comment by psalaberria002** [comment]
> I'm hitting the same issue when trying to use OpenTelemetry packages. Are ther any known workarounds?

I think it got fixed for us when we upgraded to the latest version.
```
$ cat go.mod | grep opent
        go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin v0.40.0
        go.opentelemetry.io/otel v1.14.0
        go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.14.0
        go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.14.0
        go.opentelemetry.io/otel/sdk v1.14.0
        go.opentelemetry.io/otel/trace v1.14.0
        github.com/opentracing/opentracing-go v1.2.0 // indirect
        go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.14.0 // indirect
        go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.14.0 // indirect
        go.opentelemetry.io/proto/otlp v0.19.0 // indirect
```

**Comment by jayconrod** [comment]
This issue shouldn't be relevant anymore now that `GOPATH` is mostly dead.

It was referring specifically to comments like this:

```
package otlpconfig // import "go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig"
```

Before Go modules, the `go` tool checked that if the canonical import path was set, it matched the directory within `$GOPATH`. It was possible to download a package to the wrong path manually or by using a non-canonical path that mapped to the same repository like `github.com/open-telemetry/opentelemetry-go`.

This issue was meant to add that feature to Gazelle, but since `GOPATH` is basically deprecated, and modules don't support canonical import paths (the module path in `go.mod` serves that purpose), this feature isn't needed.
