### ISSUE TITLE
How to tell gazelle not to gen go_test?

### ISSUE THREAD

**Issue by linuxerwang** [bazelbuild/bazel-gazelle#531]
When importing 3rd-party libraries, we sometimes don't care about the tests in those libraries while they might introduce extra dependencies. Is it possible to instruct gazelle not to generate targets like "go_test" and "go_binary"?

Thanks!

**Comment by jayconrod** [comment]
No way to do this at the moment, but it would be a useful feature, especially in `go_repository`.

#16 is probably the right issue to follow.
