### ISSUE TITLE
gomod_repository

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel-gazelle#539]
I've made a small rule for our of our internal repo, and I find nice it very nice to interact with:
```python
def _gomod_repository_impl(repository_ctx):
    repository_ctx.file("WORKSPACE", "workspace(name = \"{name}\")\n".format(
        name = repository_ctx.name,
    ))
    gazelle = repository_ctx.path(repository_ctx.attr._gazelle)
    gomod = repository_ctx.path(repository_ctx.attr.gomod)
    cmd = [
        gazelle,
        "update-repos",
        "-from_file=%s" % gomod,
        "-to_macro=repositories.bzl%{name}".format(
            name = repository_ctx.name,
        ),
    ]
    repository_ctx.execute(cmd)
    repository_ctx.file("BUILD.bazel", "exports_files([\"repositories.bzl\"])")

gomod_repository = repository_rule(
    _gomod_repository_impl,
    attrs = {
        "gomod": attr.label(
            mandatory = True,
        ),
        "_gazelle": attr.label(
            default = "@bazel_gazelle_go_repository_tools//:bin/gazelle",
        ),
    },
)
```

Basically, it levereages `to_macro` into a repository rule and thus generate the deps directly, without doing a `bazel run`.

The end UX is as follow:
```python
load("//:gomod_repository.bzl", "gomod_repository")

gomod_repository(
    name = "go_deps",
    gomod = "//:go.mod",
)

load("@go_deps//:repositories.bzl", "go_deps")

go_deps()
```

The only remaining problem is for `# gazelle:repository_macro` to understand the full path somehow:
```python
# gazelle:repository_macro @go_deps//:repositories.bzl%go_deps
```

**Comment by jayconrod** [comment]
Thanks for posting this, interesting use case.

I'd rather not integrate this into Gazelle though. The circularity between WORKSPACE and repository rules that read WORKSPACE and files within themselves seems pretty confusing, and I think it would be hard to support. I think it's better to have repository rules somewhere static, especially those that need some hand-modification.

Other people may be interested in this though. Maybe post to the bazel-go-discuss mailing list?

**Comment by steeve** [comment]
Will do! My main idea was to have one single file for dependencies, rather than two `go.mod and WORKSPACE`

**Comment by Globegitter** [comment]
I think this is very useful - maybe this snippet could be added to the https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst document and linked from the main readme to actually make it discoverable for other users who could be interested. WDYT?
