### ISSUE TITLE
Advice requested - Merging srcs in multi-file targets

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#553]
I was hoping to get a bit of advice to help my work on the js language module. It generates a rule per file, and I want to support the scenario of merging the generated rules into an existing rule that has a superset of its srcs. 

For example, given this existing BUILD file
```
closure_js_library(
    name = "multifile",
    srcs = ["file1.js", "file2.js"],
)
```

I generate rules like
```
        closure_js_library(
            name = "file1",
            srcs = ["file1.js"],
            visibility = ["//visibility:public"],
            deps = [
                "//:i18n",
                "@io_bazel_rules_closure//closure/library/string",
            ],
        )

        closure_js_library(
            name = "file2",
            srcs = ["file2.js"],
            visibility = ["//visibility:public"],
            deps = [
                "//ui:widget",
                "@io_bazel_rules_closure//third_party/closure/library/dojo/dom:query",
            ],
        )
```

and would like to merge them into the existing rule:
```
        closure_js_library(
            name = "multifile",
            srcs = [
                "file1.js",
                "file2.js",
            ],
            visibility = ["//visibility:public"],
            deps = [
                "//:i18n",
                "//ui:widget",
                "@io_bazel_rules_closure//closure/library/string",
                "@io_bazel_rules_closure//third_party/closure/library/dojo/dom:query",
            ],
        )
```

I got close by adding a MatchSubsetOfAttrs to the KindInfo, applied to "srcs" for these rules:
```
	"closure_js_library": {
		MatchSubsetOfAttrs: []string{"srcs"},
		NonEmptyAttrs: map[string]bool{
			"deps": true,
			"srcs": true,
		},
		ResolveAttrs: map[string]bool{"deps": true},
	},
```

.. and the obvious implementation in merger.go:match, and the generated rules successfully matched the existing rule. However `rule.MergeRule` replaces the destination rule's attr with the source rule's, so it doesn't work for this use case. The `deps` in the resulting rule are the `deps` from one of the generated rules, not both of them. 

In other words, I end up with this rule, which is so close:
```
        closure_js_library(
            name = "multifile",
            srcs = [
                "file1.js",
                "file2.js",
            ],
            visibility = ["//visibility:public"],
            deps = [
                "//ui:widget",
                "@io_bazel_rules_closure//third_party/closure/library/dojo/dom:query",
            ],
        )
```

The only recourse I can see that avoids making invasive changes to Gazelle is to do all of this processing in `GenerateRules` and emit the rules that I want directly. That feels like opting out of the mechanisms that Gazelle provides for this stuff, but it could be the right move for a non-core language module.

Is that what you'd recommend, or is there another path that I'm missing?

Thanks!

**Comment by jayconrod** [comment]
I'm sorry for not responding to this earlier. I remember typing out a response, but it doesn't look like I actually sent it.

How exactly would the rules for individual files be combined into a single rule? Is that something the user does (and after that, Gazelle updates the combined rule), or is this in response to a directive? Also, is this a one time change, or is it valid for a build file to be in either state (or perhaps both)?

I think the simplest thing is to make source files and directives the source of truth for the generator. From #560, it seems complicated to examine existing rules directly. So maybe there could be a directive indicating whether rules for individual files or all files should be emitted?

If you need to change from one state to the other, the `Fix` method is probably the best place to do that. It can make arbitrary transformations to the build file before `GenerateRules` is called. You can make more or less aggressive changes depending on whether the `fix` or `update` command is used.

**Comment by robfig** [comment]
Thanks for your input! I ended up being able to do a good enough job in GenerateRules, I think. At least, no one has complained.
