### ISSUE TITLE
go_repository: cannot read outside of the repository directory

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#555]
`go_repository` uses `ctx.read` to read the main WORKSPACE file in versions of Bazel that support it. This is not actually allowed.

Caused by #550
Related #529

**Comment by excavador** [comment]
Confirm. Can not switch to bazel 0.27.0 because of this problem

**Comment by excavador** [comment]
Same issue with 0.26.1
Last workable version: 0.25.3

**Comment by excavador** [comment]
Sorry for noise, it is not related to bazel version.
It's problem with new version of gazelle

**Comment by jayconrod** [comment]
Fixed by #559
