### ISSUE TITLE
map_kind - apply inverse mapping to `rule.File` passed to `GenerateRules`

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#560]
While working on the JS language module, I noticed something which may be a bug in `map_kind`. However, I don't think it's relevant for the Go rules, so I wasn't sure the best way to contribute a fix upstream or if you'd even be interested in it. 

One of the design goals of `map_kind` was to keep the Language  ignorant of any mappings that were applied. However, in order to properly handle existing rules (related to #553) I recently updated the JS rules to use the existing rules as the main driver:
https://github.com/robfig/bazel-gazelle/commit/fbf6b1a8cbf400f95dcda474761d28cd8819a18b?diff=split#diff-fef136f01d97a0693b00b19c199f6cbaL28

The above commit does not work properly with mapped kinds because the rules it produces are already of the mapped kind, and the conditional that loads that information into the MetaResolver does not happen:
https://github.com/bazelbuild/bazel-gazelle/blob/master/cmd/gazelle/fix-update.go#L285

As a result, `mrslv.Resolver` returns nil later on:
https://github.com/bazelbuild/bazel-gazelle/blob/master/cmd/gazelle/fix-update.go#L331

Here's the fix, which adds a copy & inverse mapping step before calling GenerateRules:
https://github.com/robfig/bazel-gazelle/commit/dd45a04c733425594cd3a6c6ee78a7e32c3a606a

My impression is that the Go rules do not suffer from the same issue, and I have not run into this in practice with them.

I wanted to confirm that this is how it should work, and I also wanted to ask if you have any idea how to trigger this behavior with the Go rules so that I could write a test for it to include in the PR.

**Comment by jayconrod** [comment]
I have mixed feelings about this one. On the one hand, I agree with the goal of keeping languages ignorant of `map_kind`. On the other hand, I think if we move forward with this change, I think it's going to get really complicated, and it's going to be very hard to avoid introducing bugs.

I see a few potential problems in robfig@dd45a04. It's not clear what happens or should happen if many kinds are mapped onto one. I think one kind will be picked randomly as the inverse (subject to map iteration order). Also, in general, it's not safe to make shallow copies of rules or files. We end up with multiple references to mutable structures, which is error-prone.

Is there a way to solve this in the JS extension without relying too heavily on the form of existing rules? I'll re-read and comment on #553 but let me know if there's anything else I'm missing to understand the use case.

**Comment by robfig** [comment]
Sorry for the long silence, but I'm looking at cleaning up our implementation now. I think this inverse mapping is important to work well with manually authored rules.  For example, if someone creates a rule that groups 3 files together, I rely on the inverse map_kind to recognize that those source files are part of a library, so that Gazelle correctly updates that rule's deps or resolves the symbols that it provides.

The best workarounds I can see:
- map_kind in the language module - get the map_kind configuration in the language's GenerateRules and use it to know what rule name to look for. 
- Heuristic - assume that any non-filegroup rule, perhaps matching a pattern like 'library$', is a JS library and treat it like that if a JS source file appears in srcs. 

I suppose the former isn't so bad, and it would allow us to start using upstream again. I suppose I'll proceed in that direction, unless you have other guidance. I do think that this will come up in any languages that Gazelle is applied to that aren't as simple as Go's model of one library rule per package. I'm also assuming that it's common to wrap the generated rules in a macro using map_kind, but perhaps I'm off base there and it's not as common as I thought.

Anyway, if you have any last thoughts on this issue, please let me know. I'll close in the meantime. 

Happy holidays and thank you for your work on Gazelle & Go/Bazel ecosystem!
