### ISSUE TITLE
bazel build //:gazelle and I failed cannot to fetch repository

### ISSUE THREAD

**Issue by sword0307** [bazelbuild/bazel-gazelle#567]
I follow the go-sample and I failed of  `An error occurred during the fetch of repository 'org_golang_x_tools'`.
This is the error log.INFO: Call stack for the definition of repository 'org_golang_x_tools' which is a git_repository (rule definition at /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/bazel_tools/tools/build_defs/repo/git.bzl:252:18):
 - /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/io_bazel_rules_go/go/private/repositories.bzl:237:9
 - /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/io_bazel_rules_go/go/private/repositories.bzl:38:5
 - /Users/sword0307/go/src/bazel/WORKSPACE:16:1
ERROR: An error occurred during the fetch of repository 'org_golang_x_tools':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "/private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning org_golang_x_tools:
+ cd /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external
+ rm -rf /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools
+ git clone '--shallow-since=1551386336 +0000' https://go.googlesource.com/tools /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools
Cloning into '/private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
+ git clone https://go.googlesource.com/tools /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools
Cloning into '/private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
ERROR: /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/io_bazel_rules_go/go/tools/builders/BUILD.bazel:55:1: no such package '@org_golang_x_tools//go/analysis': Traceback (most recent call last):
        File "/private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "/private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning org_golang_x_tools:
+ cd /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external
+ rm -rf /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools
+ git clone '--shallow-since=1551386336 +0000' https://go.googlesource.com/tools /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools
Cloning into '/private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools'...
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
+ git clone https://go.googlesource.com/tools /private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools
Cloning into '/private/var/tmp/_bazel_sword0307/28e65313e00e12f102f602de75e3db54/external/org_golang_x_tools'...
I tried to handle this via vpn but failed.

**Comment by jayconrod** [comment]
The relevant error seems to be:

```
fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
```

Are you able to access that repository outside of Bazel?

**Comment by sword0307** [comment]
> The relevant error seems to be:
> 
> ```
> fatal: unable to access 'https://go.googlesource.com/tools/': Failed to connect to go.googlesource.com port 443: Operation timed out
> ```
> 
> Are you able to access that repository outside of Bazel?

**Comment by sword0307** [comment]
@jayconrod But when I use vpn which host is in America,I still  meet the same  error.How can I do ?Wish your help!

**Comment by sword0307** [comment]
In fact,I can see the code via vpn but I cannot to get aceess to the repository?I don't know why?

**Comment by jayconrod** [comment]
Sorry, I can't help debug VPN and network issues. It doesn't seem like there's a bug in Bazel or Gazelle here, so I'll close this issue.
