### ISSUE TITLE
Compatibility release needed

### ISSUE THREAD

**Issue by siddharthab** [bazelbuild/bazel-gazelle#571]
0.17.0 does not build with bazel 0.27.1 because there are various upgrades needed. The latest commit however works fine. A new release tag would guide people into using a commit with all the compatibility fixes. Thank you!

**Comment by jayconrod** [comment]
Working on it. rules_go needs a release first.

**Comment by siddharthab** [comment]
Thanks. master seems to not work for imports like `v.io/v23/context`. I will add a test case in a PR.
