### ISSUE TITLE
update-repos should add version/commit select

### ISSUE THREAD

**Issue by weixiao-huang** [bazelbuild/bazel-gazelle#604]
while using
```
bazel run //:gazelle update-repos github.com/someone/pkg
```
it will try to fetch the latest version (see [code here](https://github.com/bazelbuild/bazel-gazelle/blob/master/repo/remote.go#L44)) and cannot select specified version.
However, since go modules can use `go edit` to specify version for go packages as `go edit -require=path@version` (see [go edit documentation](https://golang.org/cmd/go/#hdr-Edit_go_mod_from_tools_or_scripts)), I think gazelle's update-repos should support such feature as 
```
bazel run //:gazelle update-repos github.com/someone/pkg@version
```
Therefore I open https://github.com/bazelbuild/bazel-gazelle/pull/595 to support this.

**Comment by jayconrod** [comment]
Thanks for opening an issue for this. I think this will probably work when `update-repos` eventually supports multiple languages. Each language extension can interpret the string after `@` for each argument however it needs to. I was thinking we might also want something like `-attr key=value` to set specific attributes afterward, but let's not worry about that in this issue.
