### ISSUE TITLE
go_repository: Use cached build_config file

### ISSUE THREAD

**Issue by blico** [bazelbuild/bazel-gazelle#611]
From the `build_config` attribute for the [`go_repository`](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository) rule:
> A file that Gazelle should read to learn about external repositories before generating build files. This is useful for dependency resolution. For example, a go_repository rule in this file establishes a mapping between a repository name like golang.org/x/tools and a workspace name like org_golang_x_tools. Workspace directives like # gazelle:repository_macro are recognized.
By default, Gazelle reads the WORKSPACE file in the main workspace. This means that go_repository rules are re-evaluated when WORKSPACE changes. Their content should still be fetched from a local cache, but build files will be regenerated. If this is not desirable, build_config may be set to a less frequently updated file or None to disable this functionality.

It is not ideal to re-evaluate every `go_repository` rule whenever there is a `WORKSPACE` change. Especially because many `WORKSPACE` changes have no effect on the rule's output.

We can instead create a repository rule, which generates a macro file containing only the metadata that Gazelle cares about. Each `go_repository` rule can then depend on the generated file rather than `WORKSPACE`, meaning they will only need to be re-evaluated when the generated file changes. The generated file can reside in the Bazel cache, meaning it doesn't need to be checked into the repository.

I have a working implementation on a [personal branch](https://github.com/blico/bazel-gazelle/tree/go_repository_list), but wanted to hear your opinion before sending out a PR.

**Comment by jayconrod** [comment]
Sounds good to me. I guess the generated config file would look like `WORKSPACE` but would only contain `go_repository` rules with `name` and `importpath` set, plus any Gazelle directives?
