### ISSUE TITLE
CGO dependencies.

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/bazel-gazelle#613]
Is there a way I can specify the dependencies for CGO to use?

For example how we have `go_repository` is there a way for me to get ` C library and then make my `go_library` use it as a dependency?

I don't really want to install the library on the host as it will no longer be in the projects control in regards to versioning.

What I am trying to fix:

```
ERROR: /app/vendor/gopkg.in/mgo.v2/internal/sasl/BUILD.bazel:3:1: CGoCodeGen //vendor/gopkg.in/mgo.v2/internal/sasl:go_default_library%linux_amd64%cgo_codegen failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder cgo -sdk external/go_sdk -installsuffix linux_amd64 -src ... (remaining 27 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/tmp/srcdir489197267/sasl.go:15:11: fatal error: 'sasl/sasl.h' file not found
 #include <sasl/sasl.h>
          ^~~~~~~~~~~~~
1 error generated.
cgo: error running subcommand: exit status 2
```

**Comment by jayconrod** [comment]
C dependencies can be complicated, and in general, there's not a good way for Gazelle to figure out what they should be automatically. Gazelle will translate some `#cgo` directives into `copts` and `clinkopts` attributes, but these almost always require some manual intervention. `cdeps` in particular needs to be set explicitly.

The simplest thing here is probably 1) fetch the library with `http_archive`, 2) use the `patches` attribute in `http_archive` to add hand-written build files, defining a `cc_library`, 3) reference the `cc_library` in `cdeps` of any `go_library` that needs it.

**Comment by bweston92** [comment]
Thanks for taking the time to respond, will see if I can get it working that way.
