### ISSUE TITLE
Gazelle does not update visibility attribute when it is already set

### ISSUE THREAD

**Issue by scrye** [bazelbuild/bazel-gazelle#614]
If the `visibility` attribute is already set, Gazelle will not try to update it. This will cause building to fail if some other package attempts to import the one with restricted `visibility`, even though the import is valid from Go's point of view.

This scenario can happen when a Go package lives in an `internal` directory, as the `visibility` attribute is automatically restricted to the parents when Gazelle runs. If the package folder is moved out of `internal`, the `visibility` attribute in the Bazel build stays set when Gazelle runs again; this happens for both `update` and `fix` commands. Attempting to build a package that depends on the moved one then fails.

An example repo of the failing build state is available [here](https://github.com/scrye/gazelle-test). To reproduce, run `test.sh`.

Manually deleting the Bazel file of the moved package, or manually deleting the `visibility` attribute makes a rerun of Gazelle fix the problem.

This was tested with gazelle release 0.18.1, rules_go release 0.19.1 and Bazel 0.26.1.

**Comment by jayconrod** [comment]
This is working as intended. Gazelle has a [list of attributes](https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/kinds.go) on each rule it considers to be mergeable. Mergeable attributes can be replaced and overwritten by Gazelle; non-mergeable attributes may be set if they're not set already, but they won't be updated or overwritten once they're present.

`visibility` is a non-mergeable attribute. People often like to restrict visibility of packages beyond what the Go command allows with `internal` subdirectories.

> Manually deleting the Bazel file of the moved package, or manually deleting the visibility attribute makes a rerun of Gazelle fix the problem.

This is the best thing to do. If you have a large number of packages to move, consider using [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer) to remove or set `visibility` attributes as a bulk update.
