### ISSUE TITLE
Gazelle handles sub-modules strangely when using external deps

### ISSUE THREAD

**Issue by fejta** [bazelbuild/bazel-gazelle#623]
https://github.com/kubernetes/test-infra/blob/67acd530bd3419a370acecfd6121e3735bc1b4ae/go.mod#L10

Includes a:

* github.com/Azure/go-autorest v11.1.0+incompatible

Which results in a `go_repsitory` when using update-repos

```python
    go_repository(
        name = "com_github_azure_go_autorest",
        build_file_generation = "on",
        build_file_proto_mode = "disable",
        importpath = "github.com/Azure/go-autorest",
        sum = "h1:9DfMsQdUMEtg1jKRTjtkNZsvOuZXJOMl4dN1kiQwAc8=",
        version = "v11.1.0+incompatible",
    )
```

However gazelle generates the following deps:

```python
        "@com_github_azure_go_autorest_autorest//:go_default_library",
        "@com_github_azure_go_autorest_autorest//azure:go_default_library",
        "@com_github_azure_go_autorest_autorest_adal//:go_default_library",
```

When there is an import like:
https://github.com/kubernetes/test-infra/blob/67acd530bd3419a370acecfd6121e3735bc1b4ae/kubetest/azure.go#L43

`"github.com/Azure/go-autorest/autorest/azure"`

I suspect this is because HEAD of master defines a new module in `github.com/Azure/go-autorest/autorest`
https://github.com/Azure/go-autorest/blob/master/autorest/go.mod

However this module does not exist at v11.1.0:

https://github.com/Azure/go-autorest/tree/v11.1.0/autorest

So the correct dep here are:
```python
      "@com_github_azure_go_autorest//autorest:go_default_library",
        "@com_github_azure_go_autorest//autorest/azure:go_default_library",
        "@com_github_azure_go_autorest//autorest/adal:go_default_library",
```

Any why `gazelle update-repos` and `gazelle fix` do different things here and more importantly can we get `gazelle fix` to use the correct dep?

**Comment by fejta** [comment]
This seems hard to resolve because some of this repos imports have this problem:
```console
ERROR: /usr/local/google/home/fejta/.cache/bazel/_bazel_fejta/c229eee16670a3bb15d65c08362dcf5d/external/io_k8s_client_go/plugin/pkg/client/auth/azure/BUILD.bazel:3:1: no such package '@com_github_azure_go_autorest_autorest//azure': The repository '@com_github_azure_go_autorest_autorest' could not be resolved and referenced by '@io_k8s_client_go//plugin/pkg/client/auth/azure:go_default_library'
```

FYI you can repo this (and see what I'm doing) by checking out the https://github.com/fejta/test-infra/commits/bazel repo and `bazel test //...`

**Comment by fejta** [comment]
Sorry, use https://github.com/fejta/test-infra/commits/jay

**Comment by jayconrod** [comment]
I wasn't able to get too deep into this, but I think I have a fix for you. Try adding this line to WORKSPACE:

```
# gazelle:repository_macro repos.bzl%go_repositories
```

When Gazelle resolves an import to a label, it looks for a library in the current workspace that provides that import (for Go, a `go_library` or `go_proto_library` with the same `importpath`). If there is no such library, it looks for a `go_repository` rule in `WORKSPACE` with an `importpath` that is a prefix of the import. If there is no rule, it uses `go list` to find the name of the module that package belongs to.

The issue here is that all the `go_repository` rules are declared in a macro outside of WORKSPACE, so they're not getting indexed. So Gazelle calls `go list`, and that reports a different answer than what you need.

`# gazelle:repository_macro` tells Gazelle to index `go_repository` rules in a function defined in another function, in addition to repositories in WORKSPACE. It can be repeated. You should find that Gazelle is also much faster when using this, since it shouldn't need to run `go list`. As an added benefit, `gazelle update-repos` will update those rules in place. You can use the `-to_macro` argument to append new rules to that function as well.

**Comment by fejta** [comment]
Nice, makes a lot of sense! Let me try it out later today and get back to you.

**Comment by fejta** [comment]
This works nicely, thanks!

**Comment by fejta** [comment]
Things mostly work, but I'm still seeing some odd behavior:

`go build github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources` compiles whereas `bazel build @com_github_azure_azure_sdk_for_go//services/resources/mgmt/2018-05-01/resources:go_default_library` gives me a `com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:113:20: future.Done undefined (type *CreateOrUpdateByIDFuture has no field or method Done)` error.

This doesn't make sense, both go.mod and repos.bzl show (and matching sums):
* github.com/Azure/azure-sdk-for-go v21.1.0+incompatible
* github.com/Azure/go-autorest v11.1.0+incompatible

And the lines of code are:
* Function https://github.com/Azure/azure-sdk-for-go/blob/v21.1.0/services/resources/mgmt/2018-05-01/resources/models.go#L113
* Struct def, showing embedded azure.Future
https://github.com/Azure/azure-sdk-for-go/blob/v21.1.0/services/resources/mgmt/2018-05-01/resources/models.go#L105-L107
* Future.Done() method def https://github.com/Azure/go-autorest/blob/v11.1.0/autorest/azure/async.go#L92

So as best as I can tell (and this is how it worked when using vendored deps) this should build (and does build when using vendored deps aka master)

```console
$ go build github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources
fejta-macbookpro:test-infra fejta$ bazel build @com_github_azure_azure_sdk_for_go//services/resources/mgmt/2018-05-01/resources:go_default_library
INFO: Analyzed target @com_github_azure_azure_sdk_for_go//services/resources/mgmt/2018-05-01/resources:go_default_library (1 packages loaded, 14 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/BUILD.bazel:3:1: GoCompilePkg external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/darwin_amd64_stripped/go_default_library%/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2018-05-01/resources.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src ... (remaining 47 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: error running subcommand: exit status 2
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:113:20: future.Done undefined (type *CreateOrUpdateByIDFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:141:20: future.Done undefined (type *CreateOrUpdateFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:175:20: future.Done undefined (type *DeleteByIDFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:197:20: future.Done undefined (type *DeleteFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:549:20: future.Done undefined (type *DeploymentsCreateOrUpdateAtSubscriptionScopeFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:578:20: future.Done undefined (type *DeploymentsCreateOrUpdateFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:607:20: future.Done undefined (type *DeploymentsDeleteAtSubscriptionScopeFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:629:20: future.Done undefined (type *DeploymentsDeleteFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:936:20: future.Done undefined (type *GroupsDeleteFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:1124:20: future.Done undefined (type *MoveResourcesFuture has no field or method Done)
/private/var/tmp/_bazel_fejta/436df7e80b7a8ba049d812837a328382/sandbox/darwin-sandbox/4574/execroot/io_k8s_test_infra/external/com_github_azure_azure_sdk_for_go/services/resources/mgmt/2018-05-01/resources/models.go:1124:20: too many errors
Target @com_github_azure_azure_sdk_for_go//services/resources/mgmt/2018-05-01/resources:go_default_library failed to build
```

(or just `bazel build //kubetest/...`)

Thoughts?

**Comment by fejta** [comment]
BTW updated repo is still at https://github.com/fejta/test-infra/commits/jay

And hmm, from the diff it looks like we still have the sub repos, let me see if I can debug this

**Comment by fejta** [comment]
Well deleting `com_github_azure_go_autorest_autorest` etc from repos.bzl and then rerunning gazelle fixed things. I wonder why it is doing that though?

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/pull/14036
