### ISSUE TITLE
Stable resolution of importpath to repo name mappings

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel-gazelle#631]
We've been chasing this cow around the field for a while with #529 and #132 and #602, and it just fell on me today in a way that more precisely illustrates the problem we are trying to solve. I believe I now have a workable design for solving the remaining cases.

I have a repo which provides a go library. This library depends on the kubernetes client libraries, which use a vanity domain: k8s.io/client-go is https://github.com/kubernetes/client-go. Types from these libraries form part of my interface, so users of my library will end up importing them for temporary variables. I'm also running without direct internet access so the network lookups to k8s.io fail, and gazelle's static heuristics interpret "import k8s.io/client-go/plugin/pkg/client/auth" as @io_k8s_client_go_plugin//pkg/client/auth, which is broken. In order for this to generate correct rules, gazelle needs to see an explicit mapping in the form of a go_repository rule. (The networking tangle is its own mess, but for the purposes of this discussion, let's just accept it as axiomatic that sometimes we're going to need gazelle to see the contents of go_repository rules in order to get name resolution right)

Users of this repo will call a foo_deps() function that I provide to get the dependencies they need, which includes go_repository rules for all the many kubernetes client libraries. If those users then import the library I provide and run gazelle themselves, it will generate incorrect dependencies on the k8s.io packages, because it can't see those go_repository rules.

There is currently nothing those users can do to get gazelle to read the go_repository rules, because they are in a foreign repo. Copying every such foo_deps function into a local .bzl file for gazelle:repository-macro file is combinatorially-hard and an intolerable layering violation.

(Description of the problem ends here. If this is too abstract to understand, I can attempt to create an instance of this problem on github for inspection)

So, what can we do about this? The only plausible way to extract all the go_repository rules in the repo rules is to run bazel query (which has its own bug: https://github.com/bazelbuild/bazel/issues/7855) or bazel sync --experimental_repository_resolved_file. We cannot reasonably do either of these from within any repo rule or build action. There is only one time that we could plausibly collect this data: during a "bazel run :gazelle" invocation.

This leads us to the first important idea of this design:

> The gazelle() rule should extract the complete set of repo name mappings that it discovers and write them to a file in the repo, so that it can be used later by other rules.

For the moment, let's say that it writes the file //:.gazelle-repos.bzl and the contents are something which gazelle:repository-macro could consume. Let's also assume that this file is loaded by default for gazelle() and go_repository rules, without needing a gazelle:repository-macro directive. Since the gazelle() rule both reads and writes this file, it will behave like go.sum and accumulate name resolutions that it finds across multiple invocations. In the general case it may be necessary to accumulate resolutions from running gazelle in several environments, if the WORKSPACE file has sufficiently complex conditionals in it, but this is within the scope of things we can ask the repo maintainer to handle, since they're responsible for introducing that sort of complexity.

Once we're doing that, it becomes reasonable to have the gazelle() macro call genquery() and pass the output to the gazelle binary for transcription into .gazelle-repos.bzl. Bootstrapping tangles can still be created by sufficiently devious users, but those same users can resolve them by manually adding entries to .gazelle-repos.bzl.

Now we've got as far as having a file committed to every gazelle-using repo which records the name resolutions that it might need. The second important idea to making this design work is:

> The go_repository() rule should include .gazelle-repos.bzl from the downloaded source in the mappings that it uses for running gazelle on that repo, with the one from the root repo taking precedence when names conflict.

Now we have a reasonably automated setup: each repo maintainer has a mostly-automatically-maintained .gazelle-repos.bzl file, and if somebody runs go_repository on that repo again, it should give the same results without the caller needing to do additional work. Callers can still override the name resolution in order to swap out a dependency, and get this behaviour automatically if they override the dependency in their own WORKSPACE file and run gazelle there. Critically, a repo maintainer now has a plausible mechanism to ship name resolutions to users of their repo, without the user having to do any additional work.

Once we have all of that, the desired behaviour should be correct-by-default with the routine workflow of running gazelle() rules, and the need to manually specify gazelle:repository-macro directives might go away entirely. #132 is encompassed by manually editing the file, but we would not expect people to do this routinely. WDYT?

**Comment by asuffield** [comment]
@jayconrod Opinions?

**Comment by asuffield** [comment]
Bump - this is an ongoing nuisance which I'd quite like to fix, but I don't want to send a PR for something this intrusive without some agreement on direction first.

**Comment by jayconrod** [comment]
Reading through this again, it seems like a significant structural change. In particular, I absolute don't want to deal with `genquery` or any recursive invocations of bazel. It seems like there should be a smaller solution to this problem.

We already distill the WORKSPACE file down to a configuration file in `go_repository_config` (#615). If #132 were implemented, those directives would go in there, too. If #602 were implemented, that configuration file would be the only source of information for external dependency resolution: we would not go out to the network. Do those issues cover everything?

**Comment by asuffield** [comment]
Not quite - we still have the underlying problem with recursive dependencies that just never make it into WORKSPACE in any form, and the author of the WORKSPACE file being stuck with figuring out everybody else's _deps functions to write gazelle:repository lines for things which are only used transitively.

However, that does bring us a lot closer. I need to run it over again in my head in detail, but I think the missing piece is one of the ideas from my (long) writeup reworked for these new developments: have go_repository also extract the WORKSPACE file from the archive it downloaded (with generate_repo_config) and load both configs into the gazelle invocation for this repo. That way names from both WORKSPACE files are available, and the eventual user doesn't need to flatten all the _deps functions they call into gazelle:repository lines.

**Comment by asuffield** [comment]
No, that's still not quite enough - the gnarliest case is this one:

repo A is some pure go code (k8s.io/api and friends)
repo B is a starlark repo which wraps them in a k8s_deps() function to import all the right things
repos C..Z are applications that want to call the function from repo B and not have to worry about all the k8s deps

To handle this scenario we'll want a way to inherit names from another repo, possibly transitively.

**Comment by jayconrod** [comment]
Unfortunately, managing transitive dependencies is inherently difficult in Bazel. Bazel doesn't evaluate WORKSPACE files of dependencies, and it's always up to each repo author to come up with a flat list of dependencies. [`bazel sync`](https://blog.bazel.build/2018/07/09/bazel-sync-and-resolved-file.html) was an attempt to solve this problem. [bazel-federation](https://github.com/bazelbuild/bazel-federation) is another (though only for rules).

Because Bazel doesn't evaluate WORKSPACE files in external repos, I don't think Gazelle should read them. Rules declared there could contradict rules from the main WORKSPACE, for example if a module has split into submodules and now needs to be pulled in as multiple `go_repository` rules. That would lead to a lot of confusion and bugs.

**Comment by asuffield** [comment]
The bazel-federation case is actually closest to the one that I keep struggling with, so let's try unpacking it from that angle.

Assume that bazel-federation provides a starlark function that calls go_repository() a bunch of times. As a user of bazel-federation, I call this function, and when gazelle runs it can't see any of those rules in my WORKSPACE file.

I can work around this by copying all the rules from bazel-federation into my own WORKSPACE, but this largely defeats the point of having bazel-federation. What I really want is a way for bazel-federation to export those names, and let me import them. With the current iteration, there's nothing I can do to get names from an external repo.

**Comment by jayconrod** [comment]
Does `--experimental_repository_resolved_file` solve that case actually? It writes a .bzl file with information about all declared repositories. That could be converted into a file with `# gazelle:repo` directives, or a `# gazelle:repository_resolved` directive could be added to make Gazelle look for such a file.

**Comment by asuffield** [comment]
It's been a while, but I've had a new idea for tackling this space, after studying how go_repository_config works. See what you make of this one:

Teach go_repository_config to support multiple input files, and merge their results together.

Then I can handle dependencies by passing several parameters to go_repository_config, and solve the rest of the problem in starlark. Expected usage would be something like:

```
load("@some_repo//:deps.bzl", "some_deps", some_gazelle_config="GAZELLE_CONFIG")

some_deps()
go_repository_config(deps = [some_gazelle_config])
```

If I have several input repos like this, and there's no underlying incompatibility in their dependencies, everything would just work. What do you think about this one?

**Comment by jayconrod** [comment]
`go_repository_config` already reads multiple input files: WORKSPACE and local files mentioned in `# gazelle:repository_macro` directives. It also recognizes `# gazelle:repository` directives in those files.

What more is needed?

Constraints here are that Gazelle won't read files in external repositories and won't execute Starlark code or run Bazel commands. So pointing `# gazelle:repository_macro` to a function defined in another repo won't work, but you could write a program outside of Gazelle to generate such a file locally.

**Comment by asuffield** [comment]
Right, and multiple external repositories is the big thing I was thinking of handling via go_repository_config: I want to take definitions from a few repos, merge them all, and feed them to gazelle - exactly the same pattern of collapsing down inputs into a single file. It also gives us the maybe-useful feature of being able to go more than one hop (gazelle doesn't follow repository_macro directives in files referenced via repository_macro, as far as I can tell).

I have a crude demo spliced together where I just cat a bunch of them together in a repository rule, which seems to be doing what I want.

**Comment by jayconrod** [comment]
I'm closing this issue because I don't think there's a way forward.

Bazel's rules for repository rule evaluation and overriding are [really complicated](https://stackoverflow.com/a/60656122/1891). Resolving conflicts between rules with the same names is difficult to predict, so I think keeping a flat WORKSPACE is best, or at most, one level of repository macros. I think keeping multiple level of repository macros is too hard to support, and given the constraints mentioned above, Gazelle can't do it effectively.
