### ISSUE TITLE
import `proto_library` from `rules_proto` is not supported

### ISSUE THREAD

**Issue by moruowait** [bazelbuild/bazel-gazelle#638]
### What version of gazelle are you using?

0.18.2

### What version of rules_go are you using?

0.19.2

### What version of Bazel are you using?

Build label: 0.29.1

### What operating system and processor architecture are you using?

Darwin

### What did you do?

rerun gazelle on a BUILD.bazel file which contains native import `proto_library`

### What did you expect to see?

should load `proto_library` from `rules_proto` like `load("@rules_proto//proto:defs.bzl", "proto_library")` 

### What did you see instead?

imported native `proto_library`

Native proto_library has DEPRECATED: https://docs.bazel.build/versions/master/be/protocol-buffer.html#proto_library and it becomes an incompatible change in bazel 0.29.0.

**Comment by Yannic** [comment]
I'll submit a fix for this shortly.
