### ISSUE TITLE
Gazelle erroring on relative path replace directives

### ISSUE THREAD

**Issue by cwaeland** [bazelbuild/bazel-gazelle#650]
### What version of gazelle are you using?

0.18.1

### What version of rules_go are you using?

0.19.0

### What version of Bazel are you using?

0.28.1

### Does this issue reproduce with the latest releases of all the above?

I believe so.

### What operating system and processor architecture are you using?

macOS / x64

### What did you do?

With a go.mod file like the following: 

```
module github.com/foo/bar

go 1.12

require (
	baz.com v0.0.0
)

replace baz.com => ./build-support/baz
```

### What did you expect to see?

I was hoping to see the same behavior as I do with absolute paths.  Namely:

`gazelle: go_repository does not support file path replacements for compass.com -> /Users/cwaeland/development/foo/build-support/baz`

### What did you see instead?

I get the following output:

```
go: parsing build-support/baz/go.mod: open /private/var/folders/s6/tpqlfq494czcv34zgzwm4vy40000gp/T/gazelle-temp-gomod900090332/build-support/baz/go.mod: no such file or directory
go: error loading module requirements
gazelle: error parsing "go.mod": exit status 1
```

I thought this would have been covered by https://github.com/bazelbuild/bazel-gazelle/issues/407 but it doesn't seem to be.

**Comment by ebracho** [comment]
Would an acceptable solution to this be to copy all go.mod files from the repo to the temp dir?

**Comment by jayconrod** [comment]
@ebracho `gazelle update-repos -from_file=go.mod` should reject go.mod files with file replacements. They can't be supported in `go_repository`, so there's no correct way to import them.

**Comment by ebracho** [comment]
> Ideally, go.mod should only contain direct dependencies. However, if a dependency hasn't migrated to modules, its dependencies may need to be specified as // indirect.

I see, thanks for clearing that up.

> Are you copying all modules into the monorepo or just a few forked modules? You'll need go_repository rules for anything that's not checked in.

We’re still evaluating approaches, but the plan is to remove all external modules from the repo except for the ones we’ve forked and modified. Before modules we were vendoring with `gvt` and generating `BUILD.bazel` files with gazelle. 

Ideally we want to continue supporting builds with both the Go tool chain and bazel, and would also like to avoid long import paths for forked modules.

**Comment by sagikazarmark** [comment]
A common use case for path replaces is exposing a portion of a repository as a separate module for others to consume and using it in the main repo as well.

A common example is an API package that provides a contract between the server and the clients.

I agree that it shouldn't need a `go_repository` rule, but it should still work with gazelle. It should detect and ignore path replacements, but still copy the files to the build dir.

**Comment by dragonsinth** [comment]
Would a patch to use `-mod=readonly` on the list call be accepted?  The `go mod download` doesn't seem to take this as an argument.

**Comment by jayconrod** [comment]
@dragonsinth Sure I'd take a PR for that.

I believe `go mod download` command, as it is used here, will not modify `go.sum` since it's invoked with explicit arguments. So with `go list -mod=readonly`, it should no longer be necessary to copy `go.mod` to a temporary directory, and that code can be removed.

**Comment by dragonsinth** [comment]
Sweet, submitted #912
