### ISSUE TITLE
Regen std_package_list?

### ISSUE THREAD

**Issue by whilp** [bazelbuild/bazel-gazelle#652]
### What version of gazelle are you using?

0.18.1

### What version of rules_go are you using?

0.19.3

### What version of Bazel are you using?

```
$ bazel version
Build label: 0.29.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Aug 28 14:34:45 2019 (1567002885)
Build timestamp: 1567002885
Build timestamp as int: 1567002885
```

### Does this issue reproduce with the latest releases of all the above?

Yep.

### What operating system and processor architecture are you using?

```
$ uname -a
uname -a
Linux ba182f744dde 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### What did you do?

Attempted to update from go 1.12.9 to 1.13.1 while using vendored dependencies, including some that transitively depend on the `ed25519` that was formerly under `golang.org/x/crypto` but entered the stdlib in 1.13.

### What did you expect to see?

Build success.

### What did you see instead?

Fails to build because gazelle doesn't know ed25519 is in the stdlib now.

### Other info

`std_package_list.go` does not appear to have been updated lately:

https://github.com/bazelbuild/bazel-gazelle/blob/b65fc45778ad97a3710f64679279ff41d18fd5b8/language/go/std_package_list.go#L17-L22

Perhaps we just need to regen this w/ a 1.13 toolchain?

Here's ed25519:

https://github.com/golang/crypto/blob/34f69633bfdcf9db92f698f8487115767eebef81/ed25519/ed25519.go#L5-L8

**Comment by liggitt** [comment]
Did #658 actually address the specific issue noted? I also am seeing incorrect BUILD files generated for `crypto/ed25519`, and #658 didn't add stdlib [`crypto/ed25519` packages](https://github.com/golang/go/tree/release-branch.go1.13/src/crypto/ed25519) that are in go1.13

**Comment by jayconrod** [comment]
Hmm, you're right. Not sure what went wrong.
