### ISSUE TITLE
Gazelle generated BUILD files resolution

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/bazel-gazelle#656]
### What version of gazelle are you using?

v0.18.2

### What version of rules_go are you using?

v0.19.3

### What version of Bazel are you using?

v0.28

### What did you do?

With the following in my `go.mod`

```
require (
	cloud.google.com/go v0.45.1
	cloud.google.com/go/pubsub v1.0.1
)
```

After I run Gazelle with `-from-file` and `-to_macro` I expected to see a rule for `cloud.google.com/go/pubsub` as `@com_google_cloud_go_pubsub` but only the following was generated.

```
    go_repository(
        name = "com_google_cloud_go",
        importpath = "cloud.google.com/go",
        sum = "h1:lRi0CHyU+ytlvylOlFKKq0af6JncuyoRh1J+QJBqQx0=",
        version = "v0.45.1",
    )
```

Howver when I compile my code because of Gazelle using `@com_google_cloud_go//pubsub` instead of `@com_google_cloud_go_pubsub` I get

```
ERROR: /Users/bweston/**/queue/BUILD.bazel:3:1: no such package '@com_google_cloud_go//pubsub': BUIL
D file not found in directory 'pubsub' of external repository @com_google_cloud_go and referenced by '//**/queue:go_default_
library'
ERROR: Analysis of target '//**/embeds:deployment' failed; build aborted: no such package '@com_google_cloud_go//pubsub': BUILD file no
t found in directory 'pubsub' of external repository @com_google_cloud_go
```

**Comment by bweston92** [comment]
So from what I can tell they point to 2 different git repositories.

- `https://cloud.google.com/go?go-get=1` => `https://github.com/GoogleCloudPlatform/gcloud-golang`
- `https://cloud.google.com/go/pubsub?go-get=1` => `https://github.com/googleapis/google-cloud-go`

However if I manually add

```
    go_repository(
        name = "com_google_cloud_go_pubsub",
        importpath = "cloud.google.com/go/pubsub",
        sum = "h1:W9tAK3E57P75u0XLLR82LZyw8VpAnhmyTOxW9qzmyj8=",
        version = "v1.0.1",
    )
```

and then run Gazelle again it generates a correct BUILD file that works with the desired dep.

However because of an internal package `cloud.google.com/go/internal` used in the build fails because of visibility.

```
ERROR: /var/lib/jenkins/.cache/bazel/_bazel_jenkins/979524fa5084bc875cc3360d67a07c93/external/com_google_cloud_go_pubsub/BUILD.bazel:3:1: in go_library rule @com_google_cloud_go_pubsub//:go_default_library: target '@com_google_cloud_go//internal/optional:go_default_library' is not visible from target '@com_google_cloud_go_pubsub//:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /var/lib/jenkins/.cache/bazel/_bazel_jenkins/979524fa5084bc875cc3360d67a07c93/external/com_google_cloud_go_pubsub/BUILD.bazel:3:1: in go_library rule @com_google_cloud_go_pubsub//:go_default_library: target '@com_google_cloud_go//internal/version:go_default_library' is not visible from target '@com_google_cloud_go_pubsub//:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

**Comment by bweston92** [comment]
Above solutions works fine with `--nocheck_visibility` however this isn't desired.

**Comment by jayconrod** [comment]
Could you try upgrading to Gazelle at `master`? There have been a lot of fixes for multi-module repositories lately. The visibility issue in particular was #619. It's probably about time to tag a new release.

I tried the following:

* Created a WORKSPACE using tip versions of rules_go and Gazelle and these [proto dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#proto-dependencies).
* Created a go.mod as you described and imported it with `bazel run :gazelle -- update-repos -from_file=go.mod -to_macro=deps.bzl%go_deps`.
* Added to WORKSPACE:

```
# gazelle:repository_macro deps.bzl%go_deps
load("//:deps.bzl", "go_deps")

go_deps()
```

* Built pubsub with `bazel build @com_google_cloud_go_pubsub//:go_default_library`.

That seems to work.

**Comment by bweston92** [comment]
Using master works! thanks.
