### ISSUE TITLE
Missing dependency on cross repos

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel-gazelle#665]
### What version of gazelle are you using?

0.19.0

### What version of rules_go are you using?

0.20.1

### What version of Bazel are you using?

1.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS / amd64

### What did you do?

Let's take 2 repos: `@A` and `@B`

I'm running gazelle on `@A`.

`A/one` imports `B/two`
`B/two` imports `A/three`

When trying to build, bazel fails with a classic:
```
compilepkg: missing strict dependencies: import of "github.com/xxx/a/three"
```

If I look at the generated `BUILD.bazel` file, I see that `github.com/xxx/a/three` is missing.

I tried to fiddle with resolve directives, but it didn't work...

**Comment by jayconrod** [comment]
Are both repositories declared in your WORKSPACE file or in a file declared by `# gazelle:repository_macro` directive? If there are `go_repository` rules, Gazelle will figure this out automatically. But you can also declare other things with `# gazelle:repository` now. [Directives](https://github.com/bazelbuild/bazel-gazelle#directives) has the syntax details for both.

**Comment by steeve** [comment]
Yes, one (`@A`) is the one from which I'm running bazel, the "main" one. I'll check the directive! Thank you
