### ISSUE TITLE
go_repository_tools seemingly incompatible with alpine linux

### ISSUE THREAD

**Issue by mrmeku** [bazelbuild/bazel-gazelle#670]
### What version of rules_go are you using?
v0.20.2

### What version of gazelle are you using?
v0.19.0

### What version of Bazel are you using?
1.0.0

### Does this issue reproduce with the latest releases of all the above?
Yep! That's upgrading to bazel 1.1.x does not help

### What operating system and processor architecture are you using?
Alpine linux (latest release)

### Any other potentially useful information about your toolchain?
Nope, this is just about bootstrapping a workspace to use gazelle (which invokes `go_repository_tools`) 

### What did you do?
Use the following workspace file:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "b9aa86ec08a292b97ec4591cf578e020b35f98e12173bbd4a921f84f583aebd9",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.20.2/rules_go-v0.20.2.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.20.2/rules_go-v0.20.2.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains()

http_archive(
    name = "bazel_gazelle",
    sha256 = "41bff2a0b32b02f20c227d234aa25ef3783998e5453f7eade929704dcff7cd4b",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/v0.19.0/bazel-gazelle-v0.19.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.19.0/bazel-gazelle-v0.19.0.tar.gz",
    ],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()
```

And try `bazel build ...`
### What did you expect to see?
Successful build

### What did you see instead?
```
INFO: Call stack for the definition of repository 'bazel_gazelle_go_repository_tools' which is a go_repository_tools (rule definition at /jenkins/.cache/bazel/_bazel_jenkins/dae8a8559bd21d49ade8cbe4a5251560/external/bazel_gazelle/internal/go_repository_tools.bzl:110:23):
10:14:13  - /jenkins/.cache/bazel/_bazel_jenkins/dae8a8559bd21d49ade8cbe4a5251560/external/bazel_gazelle/deps.bzl:68:5
10:14:13  - /jenkins/workspace/WORKSPACE:35:1
10:14:13 ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':
10:14:13    list_repository_tools_srcs: env: ‘/jenkins/.cache/bazel/_bazel_jenkins/dae8a8559bd21d49ade8cbe4a5251560/external/go_sdk/bin/go’: No such file or directory
```

I'm not sure why this is happening but I imagine this might be an issue with linking? This issue seemed like it could be releated: https://github.com/bazelbuild/rules_go/issues/2042

**Comment by jayconrod** [comment]
Maybe I'm missing something, but it doesn't seem like Bazel runs on Alpine linux. The released binary depends on some symbols like `secure_getenv` that aren't in libc on there.

Do you have a Dockerfile or something that can help me reproduce this?
