### ISSUE TITLE
//language/go/gen_std_package_list:gen_std_package_list target is not visible

### ISSUE THREAD

**Issue by dududko** [bazelbuild/bazel-gazelle#676]
### What version of gazelle are you using?

v0.19.1

### What version of rules_go are you using?

v0.20.2

### What version of Bazel are you using?

1.2.1

### Does this issue reproduce with the latest releases of all the above?

yes

### What operating system and processor architecture are you using?

not related to this issue

### What did you do?

I try to build bazel-gazelle with option `--all_incompatible_changes` to see if gazelle uses some deprecated code which may cause a broken build in the future.

```
bazel build //... --all_incompatible_changes --incompatible_no_implicit_file_export=false --incompatible_disallow_struct_provider_syntax=false --incompatible_use_platforms_repo_for_constraints=false
```

### What did you expect to see?

Successful build

### What did you see instead?

```
➜ bazel build //...
WARNING: Option 'incompatible_tls_enabled_removed' is deprecated: No-op. See #8061 for details.
ERROR: ~/bazel-gazelle/language/go/BUILD.bazel:9:1: in std_package_list rule //language/go:std_package_list: target '//language/go/gen_std_package_list:gen_std_package_list' is not visible from target '@io_bazel_rules_go//go/private:rules/rule.bzl'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//language/go:std_package_list' failed; build aborted: Analysis of target '//language/go:std_package_list' failed; build aborted
INFO: Elapsed time: 0.116s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

**Comment by jayconrod** [comment]
Thanks for reporting. I think #677 will work around this issue, but there is a deeper problem here with the `go_rule` wrapper. I've opened bazelbuild/rules_go#2302 to track that.
