### ISSUE TITLE
bazel build //:gazelle fails when workspace file is named WORKSPACE.bazel instead of WORKSPACE

### ISSUE THREAD

**Issue by cdelguercio** [bazelbuild/bazel-gazelle#678]
### What version of gazelle are you using?

v0.19.1

### What version of rules_go are you using?

v0.20.2

### What version of Bazel are you using?

1.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Ubuntu 19.10 x86_64

### What did you do?

I ran bazel build //:gazelle, and it fails only when my Bazel workspace file is named WORKSPACE.bazel. Renaming the file fixes the issue. From the Bazel docs: "Bazel also supports WORKSPACE.bazel file as an alias of WORKSPACE file. If both files exist, WORKSPACE.bazel will take the priority."

### What did you expect to see?

Extracting Bazel installation...
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/xxx/.cache/bazel/_bazel_xxx/19290186472e4c15bae74e9b7d943605/command.profile.gz'
INFO: Analyzed target //:gazelle (58 packages loaded, 6671 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 28.258s, Critical Path: 3.83s
INFO: 34 processes: 34 linux-sandbox.
INFO: Build completed successfully, 47 total actions

### What did you see instead?

Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'bazel_gazelle_go_repository_config' which is a go_repository_config (rule definition at /home/xxx/.cache/bazel/_bazel_xxx/19290186472e4c15bae74e9b7d943605/external/bazel_gazelle/internal/go_repository_config.bzl:57:24):
 - /home/xxx/.cache/bazel/_bazel_xxx/19290186472e4c15bae74e9b7d943605/external/bazel_gazelle/deps.bzl:77:5
 - /home/xxx/xxx/WORKSPACE.bazel:26:1
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_config':
   Not a regular file: /home/xxx/xxx/poker/WORKSPACE
ERROR: /home/xxx/.cache/bazel/_bazel_xxx/19290186472e4c15bae74e9b7d943605/external/bazel_gazelle/language/go/BUILD.bazel:30:1: no such package '@org_golang_x_sync//errgroup': no such package '@bazel_gazelle_go_repository_config//': Not a regular file: /home/xxx/xxx/WORKSPACE and referenced by '@bazel_gazelle//language/go:go_default_library'
ERROR: Analysis of target '//:gazelle' failed; build aborted: no such package '@org_golang_x_sync//errgroup': no such package '@bazel_gazelle_go_repository_config//': Not a regular file: /home/xxx/xxx/WORKSPACE
INFO: Elapsed time: 6.390s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (40 packages loaded, 460 targets c\
onfigured)
    Fetching @local_config_cc; Restarting.
    Fetching @org_golang_x_sync; Restarting.
    Fetching @com_github_pmezard_go_difflib; Restarting.
    Fetching @com_github_bazelbuild_buildtools; Restarting.
    Fetching @com_github_pelletier_go_toml; Restarting.
    Fetching @org_golang_x_tools; Restarting.

**Comment by HALtheWise** [comment]
This can be worked around by changing the `gazelle_dependencies` line in your `WORKSPACE.bazel` to read
```
gazelle_dependencies(go_repository_default_config = "@//:WORKSPACE.bazel")
```

There is a separate problem deriving from Gazelle's attempt to automatically determine the root of the workspace, which I'm pursuing in #764

**Comment by joneshf** [comment]
It looks like this was closed a few days ago, but It's not clear whether this was fixed or not.

The workaround posted above only works if your workspace is the only one using `gazelle_dependencies`. If you transitively  depend on something else that uses `gazelle_dependencies`, you get the same error. An example of this is `rules_k8s`, it uses `gazelle_dependencies` directly, and also depends on `rules_docker` which uses `gazelle_dependencies`.

To be clear in my question: was this fixed recently and now dependents of `gazelle` need to be updated to get the fix?

**Comment by flolu** [comment]
This issue still present!

**Comment by fwfurtado** [comment]
> This issue still present!

You can replace  `gazelle_dependencies()` with `gazelle_dependencies(go_repository_default_config = "//:WORKSPACE.bazel")`
