### ISSUE TITLE
`proto_library` for `go_repository`

### ISSUE THREAD

**Issue by bjchambers** [bazelbuild/bazel-gazelle#681]
### What version of gazelle are you using?

0.19.1

### What version of rules_go are you using?

0.20.2

### What version of Bazel are you using?

1.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Ubuntu, AMD Ryzen

### What did you do?

Attempted to add https://github.com/mwitkow/go-proto-validators to my `go.mod` and use it.

I also attempted various combinations, such as using an `http_archive` and hand-writing the desired BUILD file, but it seemed like it was being overwritten.

### What did you expect to see?

A BUILD file for the external dependency that exposes a `proto_library` I can depend on, allowing me to import it in my own `*.proto` files.

### What did you see instead?

The library itself is loadable, but the BUILD file doesn't expose the `validator.proto` file, so it cannot be imported.

```load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "helper.go",
        "validator.pb.go",
    ],
    importpath = "github.com/mwitkow/go-proto-validators",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_gogo_protobuf//proto:go_default_library",
        "@com_github_gogo_protobuf//protoc-gen-gogo/descriptor:go_default_library",
    ],
)

```

**Comment by jayconrod** [comment]
`com_github_mwitkow_go_proto_validators` is one of the repositories declared by `go_rules_dependencies`. It uses pre-generated build files with proto rule generation disabled.

You can [override](https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies) the dependency by declaring the repository before calling `go_rules_dependencies` like this. 

```
go_repository(
    name = "com_github_mwitkow_go_proto_validators",
    importpath = "github.com/mwitkow/go-proto-validators",
    sum = "h1:F6LFfmgVnfULfaRsQWBbe7F7ocuHCr9+7m+GAeDzNbQ=",
    version = "v0.2.0",
)

go_rules_dependencies()

go_register_toolchains()

gazelle_dependencies()
```

**Comment by bjchambers** [comment]
Thanks --  I had definitely missed that!

I've tried to override it with a `go_repository` rule configured to produce a `proto_library` rule as well as a `new_git_repository` rule with a hard-coded `build_file_content`, and it still seems to be getting a `BUILD.bazel` configured by the patch from `go_rules_dependencies`.

Here's what I've tried:

```
# First attempt: go_repository
#go_repository(
#    name = "com_github_mwitkow_go_proto_validators",
#    importpath = "github.com/mwitkow/go-proto-validators",
#    version = "v0.2.0",
#    sum = "h1:F6LFfmgVnfULfaRsQWBbe7F7ocuHCr9+7m+GAeDzNbQ=",
#    build_file_proto_mode = "default",
#)

# Second attempt: new_git_repository
new_git_repository(
    name = "com_github_mwitkow_go_proto_validators",
    remote = "https://github.com/mwitkow/go-proto-validators",
    commit = "d70d97bb65387105677cb21cee7318e4feb7b4b0",
    shallow_since = "1568733758 +0100",
    build_file_content = """
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@io_bazel_rules_go//go:def.bzl", "go_library")

proto_library(
  name = "proto_library",
  srcs = glob(["*.proto"]),
  visibility = ["//visibility:public"],
  deps = ["@com_google_protobuf_wkt//:descriptor_proto"],
)
go_proto_library(
    name = "go_proto_library",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "github.com/mwitkow/go-proto-validators",
    proto = ":proto_library",
    visibility = ["//visibility:public"],
)
go_library(
    name = "go_default_library",
    srcs = [
        "helper.go",
    ],
    deps = [
        ":go_proto_library",
    ]
    importpath = "github.com/mwitkow/go-proto-validators",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_gogo_protobuf//proto:go_default_library",
        "@com_github_gogo_protobuf//protoc-gen-gogo/descriptor:go_default_library",
    ],
)
    """,
)

go_rules_dependencies()
```

It almost seems like the override isn't working, but I'm not sure how to confirm / diagnose that.

**Comment by jayconrod** [comment]
`new_git_repository` and other native Bazel repository rules have different override behavior that I don't completely understand. They've been deprecated for a while, so I'd recommend using `git_repository` in `@bazel_tools//tools/build_defs/repo:git.bzl` instead.

**Comment by bjchambers** [comment]
FWIW, `new_git_repository` is also from `@bazel_tools//tools/build_defs/repo:git.bzl`.

I gave using `git_repository` from there a shot, and it still doesn't seem to work. I added a patch based on the one used for https://github.com/bazelbuild/rules_go/blob/master/third_party/com_github_mwitkow_go_proto_validators-gazelle.patch, but edited to add a `proto_library`.

I'm wondering if the override behavior isn't working -- I see that `rules_go` has a check of whether a rule exists in the [`native.existing_rules`](https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl#L204) map which is (I think) what causes `go_rules_depenencies()` to avoid defining the same rule. Is it possible that the `git_repository` rule in the WORKSPACE is declaring it with a different name (for instance, I see it declared in `external/com_github_mwitkow_go_proto_validators`, so maybe it's not showing up in `native.existing_rules()`)?

(Most recent attempt below)

I changed to use `git_repository` in my `WORKSPACE`:
```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "com_github_mwitkow_go_proto_validators",
    remote = "https://github.com/mwitkow/go-proto-validators",
    commit = "d70d97bb65387105677cb21cee7318e4feb7b4b0",
    shallow_since = "1568733758 +0100",
    patches = ["//third_party:com_github_mwitkow_go_proto_validators-build.patch"],
    patch_args = ["-p1"],
)

go_rules_dependencies()

go_register_toolchains()

gazelle_dependencies()

go_repositories()
```

The patch:
```
diff -urN a/BUILD.bazel b/BUILD.bazel
--- a/BUILD.bazel	1969-12-31 19:00:00.000000000 -0500
+++ b/BUILD.bazel	2019-10-05 15:46:11.320601008 -0400
@@ -0,0 +1,32 @@
+load("@rules_proto//proto:defs.bzl", "proto_library")
+load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
+load("@io_bazel_rules_go//go:def.bzl", "go_library")
+
+proto_library(
+  name = "proto_library",
+  srcs = glob(["*.proto"]),
+  visibility = ["//visibility:public"],
+  deps = ["@com_google_protobuf_wkt//:descriptor_proto"],
+)
+go_proto_library(
+    name = "go_proto_library",
+    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
+    importpath = "github.com/mwitkow/go-proto-validators",
+    proto = ":proto_library",
+    visibility = ["//visibility:public"],
+)
+go_library(
+    name = "go_default_library",
+    srcs = [
+        "helper.go",
+    ],
+    deps = [
+        ":go_proto_library",
+    ]
+    importpath = "github.com/mwitkow/go-proto-validators",
+    visibility = ["//visibility:public"],
+    deps = [
+        "@com_github_gogo_protobuf//proto:go_default_library",
+        "@com_github_gogo_protobuf//protoc-gen-gogo/descriptor:go_default_library",
+    ],
+)
diff -urN a/examples/BUILD.bazel b/examples/BUILD.bazel
--- a/examples/BUILD.bazel	1969-12-31 19:00:00.000000000 -0500
+++ b/examples/BUILD.bazel	2019-10-05 15:46:11.320601008 -0400
@@ -0,0 +1,19 @@
+load("@io_bazel_rules_go//go:def.bzl", "go_library")
+
+go_library(
+    name = "go_default_library",
+    srcs = [
+        "enum.pb.go",
+        "enum.validator.pb.go",
+        "nested.pb.go",
+        "nested.validator.pb.go",
+        "uuid.pb.go",
+        "uuid.validator.pb.go",
+    ],
+    importpath = "github.com/mwitkow/go-proto-validators/examples",
+    visibility = ["//visibility:public"],
+    deps = [
+        "//:go_default_library",
+        "@com_github_golang_protobuf//proto:go_default_library",
+    ],
+)
diff -urN a/plugin/BUILD.bazel b/plugin/BUILD.bazel
--- a/plugin/BUILD.bazel	1969-12-31 19:00:00.000000000 -0500
+++ b/plugin/BUILD.bazel	2019-10-05 15:46:11.320601008 -0400
@@ -0,0 +1,16 @@
+load("@io_bazel_rules_go//go:def.bzl", "go_library")
+
+go_library(
+    name = "go_default_library",
+    srcs = ["plugin.go"],
+    importpath = "github.com/mwitkow/go-proto-validators/plugin",
+    visibility = ["//visibility:public"],
+    deps = [
+        "//:go_default_library",
+        "@com_github_gogo_protobuf//gogoproto:go_default_library",
+        "@com_github_gogo_protobuf//proto:go_default_library",
+        "@com_github_gogo_protobuf//protoc-gen-gogo/descriptor:go_default_library",
+        "@com_github_gogo_protobuf//protoc-gen-gogo/generator:go_default_library",
+        "@com_github_gogo_protobuf//vanity:go_default_library",
+    ],
+)
diff -urN a/protoc-gen-govalidators/BUILD.bazel b/protoc-gen-govalidators/BUILD.bazel
--- a/protoc-gen-govalidators/BUILD.bazel	1969-12-31 19:00:00.000000000 -0500
+++ b/protoc-gen-govalidators/BUILD.bazel	2019-10-05 15:46:11.320601008 -0400
@@ -0,0 +1,19 @@
+load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
+
+go_library(
+    name = "go_default_library",
+    srcs = ["main.go"],
+    importpath = "github.com/mwitkow/go-proto-validators/protoc-gen-govalidators",
+    visibility = ["//visibility:private"],
+    deps = [
+        "//plugin:go_default_library",
+        "@com_github_gogo_protobuf//proto:go_default_library",
+        "@com_github_gogo_protobuf//protoc-gen-gogo/generator:go_default_library",
+    ],
+)
+
+go_binary(
+    name = "protoc-gen-govalidators",
+    embed = [":go_default_library"],
+    visibility = ["//visibility:public"],
+)
diff -urN a/test/gogo/BUILD.bazel b/test/gogo/BUILD.bazel
--- a/test/gogo/BUILD.bazel	1969-12-31 19:00:00.000000000 -0500
+++ b/test/gogo/BUILD.bazel	2019-10-05 15:46:11.320601008 -0400
@@ -0,0 +1,7 @@
+load("@io_bazel_rules_go//go:def.bzl", "go_test")
+
+go_test(
+    name = "go_default_test",
+    srcs = ["validator_test.go"],
+    deps = ["@com_github_stretchr_testify//assert:go_default_library"],
+)
diff -urN a/test/golang/BUILD.bazel b/test/golang/BUILD.bazel
--- a/test/golang/BUILD.bazel	1969-12-31 19:00:00.000000000 -0500
+++ b/test/golang/BUILD.bazel	2019-10-05 15:46:11.320601008 -0400
@@ -0,0 +1,7 @@
+load("@io_bazel_rules_go//go:def.bzl", "go_test")
+
+go_test(
+    name = "go_default_test",
+    srcs = ["validator_test.go"],
+    deps = ["@com_github_stretchr_testify//assert:go_default_library"],
+)
```

**Comment by bjchambers** [comment]
I also tried using `http_archive`, but had the same observation. Interestingly, even though I didn't specify the `sha256`, I didn't receive a warning about it. This makes me wonder if something is causing the rule in `go_rules_dependencies` to take effect and over-write my own attempts.

**Comment by jayconrod** [comment]
`go_rules_dependencies` shouldn't declare it again if it's already declared with the same name. To debug, maybe call a function at the end of WORKSPACE that prints the contents of `native.existing_rules`? It gives a `dict` that describes all the rules that have been declared so far.

**Comment by bjchambers** [comment]
I think I figured out what is happening by editing the `go_rules_dependencies` rules to log (1) what it was finding and (2) fail if it didn't find my expected dependency. Based on the stack trace, I realized it was first being found as absent due to `rules_docker`:

I was also pulling in the [`docker/java:image.bzl`](https://github.com/bazelbuild/rules_docker/blob/master/java/image.bzl), and *that* repository rule includes the [`go_rules_dependencies`](https://github.com/bazelbuild/rules_docker/blob/master/repositories/go_repositories.bzl#L25). This was happening before my overrides, so it wasn't "winning" and generating the source. 

Thanks for the patience and the help!

**Comment by jayconrod** [comment]
Glad you got it sorted out!
