### ISSUE TITLE
How do I make gazelle not generate go imports for descriptor-only proto libraries?

### ISSUE THREAD

**Issue by v3n** [bazelbuild/bazel-gazelle#682]
### What version of gazelle are you using?

`0.19.1`

### What version of rules_go are you using?

`v0.20.3`

### What version of Bazel are you using?

`0.29.1`

### Problem

I've got a proto library that includes a descriptor-only protobuf. There is no corresponding go-library for the proto as it's all generated.

In my proto, I have:
```proto
import "validate/validate.proto"
```

In my root BUILD file, I have the following, which has stopped gazelle from overwriting the dependency in the binary.
```python
# gazelle:resolve proto validate/validate.proto @com_github_envoyproxy_protoc_gen_validate//validate:validate_proto
```

The BUILD file for the proto library looks like:
```python
proto_library(
    name = "x_proto",
    srcs = [
        "release.proto",
        "versions.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_envoyproxy_protoc_gen_validate//validate:validate_proto",
    ],

go_proto_library(
    name = "x_go_proto",
    compilers = [
        "//tools/protoc-gen-gogocustom:gogocustom_proto",
        "//tools/protoc-gen-validate:gogo_gen_validate",
    ],
    proto = ":x_proto",
    visibility = ["//visibility:public"],
    deps = [

    ],
)
```

Gazelle insists on adding `//validate:go_proto_library` to the deps for x_go_proto. How do I tell it that `@com_github_envoyproxy_protoc_gen_validate//validate:validate_proto` does not resolve to any Go libraries?

**Comment by jayconrod** [comment]
This seems like a level of customization Gazelle isn't really well-suited to deal with. Maybe add a `# keep` comment either above the `deps` attribute or the entire `go_proto_library` rule? That will tell Gazelle to leave them alone.

**Comment by v3n** [comment]
That's a reasonable option. While it's not my favorite, considering that we're adding this for pretty much every proto file we've got, it's better than just disabling Gazelle.
