### ISSUE TITLE
Feature Request: flag to limit languages processed

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#687]
I have the following scenario:
- I have a Gazelle binary that composes rules for JS, Go, and Proto
- I want to process only Go rules under some/path
- I want to process only JS rules under other/path.

Right now, there's no way to do that. If I run this Gazelle binary against our Go codebase, it will produce undesirable rules for any JS files checked in there. 

I want to propose a new flag, `--lang`, which is a comma separated list of languages. It defaults to empty string, which has no effect. 

It would be implemented as a flag in `updateReposConfigurer`, filtering based on `language.Language.Name()`. 

```
func updateRepos(args []string) error {
	cexts := make([]config.Configurer, 0, 2)
	cexts = append(cexts, &config.CommonConfigurer{}, &updateReposConfigurer{})
	kinds := make(map[string]rule.KindInfo)
	loads := []rule.LoadInfo{}
	for _, lang := range languages {
		// filter here
		loads = append(loads, lang.Loads()...)
		for kind, info := range lang.Kinds() {
			kinds[kind] = info
		}
	}
```

I *think* that's all it would take, although I haven't tested it out.

If this sounds good to you, I'll put together a PR. 

Thanks!

**Comment by jayconrod** [comment]
How are you invoking Gazelle usually?

This seems reasonable for people invoking Gazelle manually (without `bazel run`). Also useful for people passing additional arguments to `bazel run`.

For people using the `gazelle` rule only, you'd need multiple `gazelle` rules, so it's possible to also have multiple `gazelle_binary` rules with different sets of languages. This proposal seems a little redundant with that capability, though still useful.

**Comment by robfig** [comment]
I'm invoking it via bazel rules. I guess the real reason I'm interested in this feature is that Gazelle logs errors on unrecognized directives. Running it for Go logs ~20 lines about JS directives that it doesn't recognize.

**Comment by jayconrod** [comment]
Ah, that makes sense. That does seem like a good reason to have a `-lang` flag.

It should probably be a flag in `config.CommonConfigurer` rather than `updateReposConfigurer` since it would need to be understood by all subcommands.

**Comment by robfig** [comment]
Sorry for the delay -- PR is up. I also added it as a directive, because I recall you saying that flags should generally be overridable by directives. I can remove one or the other if you prefer, either mechanism works for my use case.
