### ISSUE TITLE
importing multiple modules from cloud.google.com/go fails

### ISSUE THREAD

**Issue by smparkes** [bazelbuild/bazel-gazelle#689]
### What version of gazelle are you using?

https://github.com/bazelbuild/bazel-gazelle/commit/33ccc50dcd2d0b9d8937bc8497fa13505bd7a665

### What version of rules_go are you using?

https://github.com/bazelbuild/rules_go/commit/5e69779e3fe39126bf4fc14912bc766ada10efec

### What version of Bazel are you using?

2.0.0-homebrew

### Does this issue reproduce with the latest releases of all the above?

Those are the latest (pre)releases ..

### What operating system and processor architecture are you using?

macos

### What did you do?

In `go.mod` I have

```
	cloud.google.com/go v0.51.0 // indirect
	cloud.google.com/go/storage v1.5.0 // indirect
```
I use `bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=repositories.bzl%go_repositories -prune=true` to generate the macro file:

```
    go_repository(
        name = "com_google_cloud_go_storage",
        importpath = "cloud.google.com/go/storage",
        sum = "h1:RPUcBvDeYgQFMfQu1eBMq6piD1SXmLH+vK3qjewZPus=",
        version = "v1.5.0",
    )
    go_repository(
        name = "com_google_cloud_go",
        importpath = "cloud.google.com/go",
        sum = "h1:PvKAVQWCtlGUSlZkGW3QLelKaWq7KYv/MW1EboG8bfM=",
        version = "v0.51.0",
    )
```
In the generated `BUILD.bazel`, the deps show as
```
        "@com_google_cloud_go//civil:go_default_library",
        "@com_google_cloud_go//storage:go_default_library",
```

### What did you expect to see?

A successful build ...

### What did you see instead?

`... BUILD.bazel:3:1: no such package '@com_google_cloud_go//storage': BUILD file not found in directory 'storage' of external repository @com_google_cloud_go. Add a BUILD file to a directory to mark it as a package. and referenced by ...`

### Comments

There is no `storage` directory in the `com_google_cloud_go` repo. I'm not actually sure why not ... how those modules are getting published is beyond my experience ... the github releases seem to have everything.

On the off chance it was the right thing to do, I changed the dep to
```
        "@com_google_cloud_go_storage//:go_default_library",
```
This does try to get further but fails for visibility (different repo but visibility is supackages only)
```
5a62dcd7d003251df94bdf4c74decb98/external/com_google_cloud_go_storage/BUILD.bazel:3:1: in go_library rule @com_google_cloud_go_storage//:go_default_library: target '@com_google_cloud_go//internal:go_default_library' is not visible from target '@com_google_cloud_go_storage//:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
```
If I force all the `go_repository`s to a single git sha (the latest in that repo) it works, though that has negative side effects: I really don't want to lose the caching ...

**Comment by jayconrod** [comment]
This sounds similar to #665. Do you have a comment like this in your `WORKSPACE`? Try adding it if not.

```
# gazelle:repository_macro repositories.bzl%go_repositories
```

**Comment by smparkes** [comment]
Tried adding the directive. No change.

Not sure this is the same as #665, which looks like cross (and cyclic ...) dependences(?) There may be overlap, though.

There are two different modules here. The twist is that but one is a prefix of the other, i.e., the second is nested(ish) within the first.

The modules are
* cloud.google.com/go
* cloud.google.com/go/storage

The zip file pulled from the pkg source for `cloud.google.com/go` does not have the files for `cloud.google.com/go/storage`.

The macro file has both `go_repository`s defined but the generated `BUILD.bazel` file does not generate the correct repo reference for the nested `storage` repo: it references the parent repo and then just specs the nested path. Those files don't exist in that repo.

Generating the correct reference in the build files seems like it might be fairly straightforward (haven't looked yet ...)

The issue that's more of a mystery to me is the visibility issue: the build files in the parent repo are only visible to the parent repo and so builds from the separate but abstractly nested repo don't have permissions (though they do reference correctly.) Not sure if this is addressable (aside from eliminating the restricted visibility ...)

**Comment by jayconrod** [comment]
Could you post an example that reproduces this? Ideally a small test repo that includes `WORKSPACE`, and the .bzl file containing the macro.

The visibility issue was #619. It was fixed a while ago. Several people have reported similar issues then, and they've mostly turned out to be configuration issues like #665. So I want to make sure that's not the case here, and if not, it would be useful to have a debuggable example.

**Comment by smparkes** [comment]
Ack

**Comment by smparkes** [comment]
Confirmed that a simple example works. Working on reducing our real code to something minimal.

**Comment by smparkes** [comment]
This shows the problem, though in a slightly different behavior than our production code base, so I'm not sure it's the exact problem. I'm not sure if it will help narrow things down ...

https://github.com/smparkes/gazelle-test

If I check this out and simply `bazel run //:gazelle`, I get
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["gcs.go"],
    importpath = "github.com/ascend-io/gazelle/utils",
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_cloud_go//storage:go_default_library",
        "@org_golang_x_net//context:go_default_library",
    ],
)
```
if I do a `go mod init` and run the same `gazelle` command, I get
```
load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["gcs.go"],
    importpath = "github.com/ascend-io/gazelle/utils",
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_cloud_go_storage//:go_default_library",
        "@org_golang_x_net//context:go_default_library",
    ],
)
```
We do have a `go.mod` in production and we do use it to create macros but we still get the problem. But our `go.mod` in production is pretty big.

Not sure if this helps narrow down the code path that we might be hitting?

**Comment by smparkes** [comment]
Meh ... deleted the last comment since the test runs in a different module mode. Working on a test that uses module-aware mode ...

**Comment by jayconrod** [comment]
Just to help explain what's happening (or supposed to be happening):

When Gazelle starts, it reads `WORKSPACE` or a configuration file generated from `WORKSPACE`. It builds an index of `go_repository` rules, mapping import paths (like `cloud.google.com/storage`) to workspace names (`com_google_cloud_storage`). When Gazelle resolves imports in source files to Bazel dependencies, it uses this table. So if something is being resolved to `@com_google_cloud_go//storage:go_default_library`, it probably means this index is not being built properly. That's why the `# gazelle:repository_macro` directives in `WORKSPACE` are important: they tell Gazelle what other files to look in.

Additionally, when Gazelle is generating `visibility` attributes for rules in external workspaces, it uses this index to find what packages might need to import an `internal` package.

**Comment by smparkes** [comment]
Thanks. That's helpful.

I've been seeing some inconsistent behavior so I'm working on confirming that all the versions of things are consistent. I'm wondering if I somehow got an old version of the code in play (which I don't believe should happen but ...)

I'll update here when I know more. I'd say there's no action until I'm able to track down the inconsistency.

I can either close this when/if I track that down or we can close this now and I'll repopen when/if necessary ...

**Comment by smparkes** [comment]
I seemed to get things working but then got pulled off on some [rules_scala](https://github.com/bazelbuild/rules_scala) support issues before I could get the go changes into production. So while I'm not 100% sure it was my error, I think chances are better than half that it was me so I'm going to close this as my error for now. I'll reopen if I can replicate.

BTW, thanks, @jayconrod, for the all the [bazel blog posts](https://www.jayconrod.com/tags/bazel). I can't overstate how helpful they've been in doing work in `rules_scala`.

**Comment by cherryland** [comment]
Some of the Google Cloud API modules are released into standalone packages, while others are part of the monorepo. They are all part of the same monorepo at [github.com/googleapis/google-cloud-go](https://github.com/googleapis/google-cloud-go).

[cloud.google.com/go/**logging**](https://github.com/googleapis/google-cloud-go)
```
go_repository(
    name = "com_google_cloud_go_logging",
    importpath = "cloud.google.com/go/logging",
)
```
[cloud.google.com/go/**bigquery**](https://github.com/googleapis/google-cloud-go)
```
go_repository(
    name = "com_google_cloud_go_logging",
    importpath = "cloud.google.com/go/bigquery",
)
```

You can find a list of standalone packages at [googleapis/google-cloud-go/README.md](https://github.com/googleapis/google-cloud-go/README.md)

All other modules are part of the monorepo and need to be imported differently

[cloud.google.com/go/**profiler**](https://github.com/googleapis/google-cloud-go)
[cloud.google.com/go/**civil**](https://github.com/googleapis/google-cloud-go)
... etc

```sh
go_repository(
    name = "com_google_cloud_go",
    importpath = "cloud.google.com/go",
)
```

**Comment by cherryland** [comment]
Some of the Google Cloud API modules are released into standalone packages, while others are part of the monorepo at [github.com/googleapis/google-cloud-go](https://github.com/googleapis/google-cloud-go).

[cloud.google.com/go/**logging**](https://github.com/googleapis/google-cloud-go)
```
go_repository(
    name = "com_google_cloud_go_logging",
    importpath = "cloud.google.com/go/logging",
)
```
[cloud.google.com/go/**bigquery**](https://github.com/googleapis/google-cloud-go)
```
go_repository(
    name = "com_google_cloud_go_bigquery",
    importpath = "cloud.google.com/go/bigquery",
)
```

You can find a list of standalone packages at [googleapis/google-cloud-go/README.md](https://github.com/googleapis/google-cloud-go/README.md)

All other modules are part of the monorepo and need to be imported differently

[cloud.google.com/go/**profiler**](https://github.com/googleapis/google-cloud-go)
[cloud.google.com/go/**civil**](https://github.com/googleapis/google-cloud-go)
... etc

```sh
go_repository(
    name = "com_google_cloud_go",
    importpath = "cloud.google.com/go",
)
```

**Comment by jordancharest** [comment]
@smparkes How did you fix it? I am running into this exact issue with the cloud storage package

**Comment by smparkes** [comment]
I don't really remember. As best as I can recall, it had to do with getting `go.mod`, `go.sum` and the go repository file created by gazelle back into known good/repeatable states. IIRC, those things were getting messed up by a series of operations as I was trying to put together the overall build. I think I went back to a clean state and added things in the correct order and the result was stable. But as I said, we never did put this into production ...
