### ISSUE TITLE
Feature request: flag to disable network access

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel-gazelle#700]
Gazelle will reach out to remote endpoints when resolving imports from outside the well-known domains set. This can be disabled per-domain using the `--known_import` flag, but this list of known imports must be kept up to date. If the developer doesn't notice a reference to some external domain, this behavior can result in slow or unreliable builds.

It would be nice if Gazelle had a flag that totally disabled network access. In that case it should fail fast if it would have tried to look at the network for something.

**Comment by jayconrod** [comment]
I'm going to consolidate this issue with #499. Not a duplicate, but I think this would make sense in the same situations as "strict mode".

Note that `# gazelle:repository name=foo importpath=bar` in WORKSPACE is a better replacement for `-known_import` on the command line, but there's still a problem with the list being out of date.

**Comment by jmillikin-stripe** [comment]
We want the ability to turn off network egress without pulling in a bunch of arbitrary unknown behavioral changes implied by a "strict mode" flag.
