### ISSUE TITLE
gazelle add grpc compilers attributes on non grpc protos

### ISSUE THREAD

**Issue by asv** [bazelbuild/bazel-gazelle#702]
### What version of gazelle are you using?
0.19.1

### What version of rules_go are you using?
0.19.9

### What version of Bazel are you using?
1.2.1

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

Linux asmirnov 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### What did you do?

1. Create simple .proto:

```protobuf
syntax = proto3;

package bug;

message Foo {
  string service = 1;
}
```

2. Run bazel run //:gazelle

### What did you expect to see?

The `compilers` attribute should not be present in `go_proto_library` if the source .proto does not contain `service` definitions.

### What did you see instead?
BUILD.bazel file contains attribute `compilers = ["@io_bazel_rules_go//proto:go_grpc"]` in go_proto_library definition.

**Comment by asv** [comment]
I am ready to prepare a PR that solves this problem: https://github.com/asv/bazel-gazelle/commit/c8239e752d18d6df604ae9ba3dfe75b9d11f948d

**Comment by jayconrod** [comment]
Thanks for reporting. I'd be happy to take a PR for this.
