### ISSUE TITLE
Conflict when using 2 proto compilers in same pacakge.

### ISSUE THREAD

**Issue by bweston92** [bazelbuild/bazel-gazelle#710]
### What version of gazelle are you using?

0.20

### What version of rules_go are you using?

0.21

### What version of Bazel are you using?

v2.0.0

### What did you do?

I have rules to create a gRPC package that Gazelle is doing. However I also use another rule in the same package to build a grpc-gateway package.

### What did you expect to see?

Being able to build the `go_default_library` with both of the rules.

### What did you see instead?

That there is a conflict.

```
_/cosmic/bazel-out/k8-fastbuild/bin/api/introducers/v1/linux_amd64_static_pure_stripped/introducers_go_proto%/cosmic/api/introducers/v1/introducers.pb.go:31:6: Introducer redeclared in this block
        previous declaration at _/cosmic/bazel-out/k8-fastbuild/bin/api/introducers/v1/linux_amd64_static_pure_stripped/api_gateway_library%/cosmic/api/introducers/v1/introducers.pb.go:31:6
_/cosmic/bazel-out/k8-fastbuild/bin/api/introducers/v1/linux_amd64_static_pure_stripped/introducers_go_proto%/cosmic/api/introducers/v1/introducers.pb.go:66:5: xxx_messageInfo_Introducer redeclared in this block
        previous declaration at _/cosmic/bazel-out/k8-fastbuild/bin/api/introducers/v1/linux_amd64_static_pure_stripped/api_gateway_library%/cosmic/api/introducers/v1/introducers.pb.go:66:5
```

## Files

The following is what Gazelle will generate and products the above errors.

```
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@build_stack_rules_proto//github.com/grpc-ecosystem/grpc-gateway:gateway_swagger_compile.bzl", "gateway_swagger_compile")
load("//tools/grpc_utils:gateway_grpc_library.bzl", "gateway_grpc_library")

proto_library(
    name = "introducers_proto",
    srcs = ["introducers.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//api/internalwkt:internalwkt_proto",
        "@com_google_protobuf//:empty_proto",
        "@com_google_protobuf//:timestamp_proto",
        "@go_googleapis//google/api:annotations_proto",
    ],
)

gateway_swagger_compile(
    name = "api_swagger",
    deps = [":introducers_proto"],
)

gateway_grpc_library(
    name = "api_gateway_library",
    importpath = "cosmic/api/introducers/v1",
    deps = [
        ":introducers_proto",
    ],
    libdeps = [
        "//api/internalwkt:go_default_library",
    ],
)

go_proto_library(
    name = "introducers_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "cosmic/api/introducers/v1",
    proto = ":introducers_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//api/internalwkt:go_default_library",
        "@go_googleapis//google/api:annotations_go_proto",
    ],
)

go_library(
    name = "go_default_library",
    srcs = ["introducers.pb.gw.go"],
    embed = [
        ":api_gateway_library",  # keep
        ":introducers_go_proto",
    ],
    importpath = "cosmic/api/introducers/v1",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golang_protobuf//proto:go_default_library",
        "@com_github_grpc_ecosystem_grpc_gateway//runtime:go_default_library",
        "@com_github_grpc_ecosystem_grpc_gateway//utilities:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//grpclog:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
    ],
)
```

Bu if I change the rule `go_default_library` to this it works.

```
go_library(
    name = "go_default_library",
    embed = [
        ":api_gateway_library",  # keep
    ],
    importpath = "cosmic/api/introducers/v1",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golang_protobuf//proto:go_default_library",
        "@com_github_grpc_ecosystem_grpc_gateway//runtime:go_default_library",
        "@com_github_grpc_ecosystem_grpc_gateway//utilities:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//grpclog:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
    ],
)
```

I did try and tell `api_gateway_library` not to generate the gRPC file and it couldn't build because of missing dependencies.

Any help would be appreciated.

**Comment by jayconrod** [comment]
Not sure how I can help with this? It sounds like `api_gateway_library` and `introducers_go_proto` are generating files with the same definitions (possibly equivalent files), and the compiler is rejecting them.

Listing one of the libraries in `deps` instead of `embed` probably won't work because they all have the same `importpath` and the linker will only be able to use one of them.

Do all of these need to build as standalone targets?

**Comment by bweston92** [comment]
No but when I run Gazelle it will make the rules for go_proto_library and update go_library

**Comment by jayconrod** [comment]
Gazelle can't always generate buildable rules in the presence of manual customizations. Gazelle can't know what `api_gateway_library` will do.

**Comment by bweston92** [comment]
Is there a way I can ignore rules in the directory?

I tried exclude but it doesn’t populate other rules that rely on the packages in the excluded directory correctly iirc

**Comment by jayconrod** [comment]
Do you mean is there a way to prevent a rule from being generated (the `go_proto_library` rule I guess)? There's not a general way to do that, but you could disable proto rule generation here with `# gazelle:proto disable`.

You could also prevent Gazelle from updating that build file with a `# gazelle:ignore` directive. Rules in the file should still be indexed for dependency resolution.

**Comment by bweston92** [comment]
Adding `# gazelle:ignore` at the top of the Bazel files I do not want to be modified by Gazelle does exclude them from being resolved in other packages.

Example error:
```
Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
        .../execroot/cosmic/gateways/identities/pkg/app/authentication/authentication.go:import of "cosmic/api/gateways/identities/v1"
```

The moment I remove the ignore directive, run Gazelle again it includes the dependency but has errors due to duplicates.

Is this not intended behaviour?

To be honest I thought it would ignore building but would still allow resolving.

**Comment by jayconrod** [comment]
Gazelle should index library rules in build files that are ignored. The code that does that is [here](https://github.com/bazelbuild/bazel-gazelle/blob/071c8d00482fc8e4dc65c451c5d41411631280c1/cmd/gazelle/fix-update.go#L277): `update` is `false` for files that shouldn't be modified.

The import may be unresolvable for another reason (multiple targets with the same import; directory is excluded...) or maybe there's a bug?

**Comment by bweston92** [comment]
Ok I just setup an example and that ignore worked fine when generating a BUILD file else where, must be something else that is causing the issue.

Will see if I can suss it out.

Thanks for your help.
