### ISSUE TITLE
Something drops the '@' when invoking Gazelle through Bazel

### ISSUE THREAD

**Issue by smeder** [bazelbuild/bazel-gazelle#719]
### What version of gazelle are you using?

0.20.0

### What version of rules_go are you using?

0.22.0

### What version of Bazel are you using?

I've tried various, including 2.1.1

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS 10.14.6/x86_64

### What did you do?

bazel run //:gazelle -- update-repos  k8s.io/client-go@v0.16.6

### What did you expect to see?

I expected to have the call update the relevant go_repository stanza in my WORKSPACE file

### What did you see instead?

Got the following error:
bazel run //:gazelle -- update-repos  k8s.io/client-go@v0.16.6          
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:gazelle (57 packages loaded, 6807 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /private/var/tmp/_bazel_sam.meder/729bb5577d184ddba441b233464e71bd/sandbox
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 14.998s, Critical Path: 0.21s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: finding module version and sum for k8s.io/client-go@v0.16.6@latest: exit status 1: go: finding k8s.io/client-go v0.16.6@latest
go: finding k8s.io/client-go v0.16.6@latest

Note that this works when invoked directly via gazelle:

./bin/gazelle update-repos  k8s.io/client-go@v0.16.6

Almost seems that something in the chain drops or replaces '@'. Unclear whether this is a gazelle or bazel issue.

**Comment by jayconrod** [comment]
I couldn't reproduce this. Could you post a minimal workspace file that reproduces this? Is there already a rule for `k8s.io/client-go`? What happens if you delete it first?

**Comment by smeder** [comment]
There already is a rule for client-go, but deleting it doesn't change the outcome. Let me work on putting together a smaller example - it will be a few days though.

**Comment by smeder** [comment]
Ok, when I tried to put together that minimal project I ended up finding our issue. We were magically fixing the version of gazelle/io_bazel_rules_go to a rather old version (it was pretty hidden). Once I removed that things started working. Thanks for your response!
