### ISSUE TITLE
Imports in generated proto files

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel-gazelle#721]
We have a rule to generate proto files from thrift files. From the thrift files, we can infer the imports of the generated proto files. However, the proto extension doesn't have that information. How do we generate the `deps` of the `proto_library`?

One possible way is to create a Gazelle extension to execute after proto extension. It reads the thrift files and amends the `deps` of `proto_library`. Any better way?

**Comment by jayconrod** [comment]
I think an extension is the best approach. It could read thrift files and generate both `proto_library` targets (with correct `deps`) and targets that generate `.proto` files. The `language/proto` extension would probably not need to do anything.

Currently, there's a backchannel for one extension to pass information about target imports to another extension. In [`language/proto/generate.go`](https://github.com/bazelbuild/bazel-gazelle/blob/90b7d7252af13b3003f5a6820a3830d0700c8ecb/language/proto/generate.go#L215), the proto extension sets the private attribute `config.GazelleImportsKey` to a list of proto imports. `language/go` translates those into `deps` for `go_proto_library`. So a Thrift extension might also need to do that for `go_proto_library` rules generated from it.
