### ISSUE TITLE
Matching proto_library with its srcs

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel-gazelle#725]
`proto_library` targets are [resolved](https://github.com/bazelbuild/bazel-gazelle/blob/master/language/proto/resolve.go#L35) using its `srcs`. So in that sensee, `srcs` are like `importpath` of `go_library`. If there is an existing `proto_library` rule in the same BUILD.bazel file that has the same `srcs` as the one just generated, Gazelle should update the existing rule instead of adding a new `proto_library`.

### What version of gazelle are you using?

92bc7b03d768a3581bd9bdd30d5e3635bbf854da

### What version of rules_go are you using?

c5a0b28c495edc83ec80477e1c8addf631f156a6

### What version of Bazel are you using?

2.0

### Does this issue reproduce with the latest releases of all the above?

It should

### What operating system and processor architecture are you using?

macOS, amd64

### What did you do?

* rename an existing `proto_library` previously generated by Gazelle
* run Gazelle

### What did you expect to see?

Gazelle should not generate a new `proto_library`

### What did you see instead?

Gazelle generates a new `proto_library`

**Comment by jayconrod** [comment]
Seems reasonable, probably not just for `proto_library`, but any rule that asks for it.

Rule matching is implemented in [`merger.Match`](https://github.com/bazelbuild/bazel-gazelle/blob/83b2dc564469ef341d2e84f358ebf24ffa003a71/merger/merger.go#L198). The function will first attempt to match a generated rule with an existing rule using its name and kind. If the name doesn't match anything but there are other rules with the same kind, it will use `MatchAttrs` from the rule kind to find a matching rule.

`MatchAttrs` currently only supports string attributes like `importpath`. It would be reasonable to extend that to string lists though. A rule could match if it had at least one source file in common. It would still be an error if more than one rule matched.
