### ISSUE TITLE
Generated proto files in subpackage

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel-gazelle#727]
To avoid mixing with regular proto files, some rules may want to generate proto files in virtual subpackage like this:

```python
# gazelle:prefix example.com/foo

some_rule(
  name = "gen_proto",
  out = "bar/generated.proto",
)

proto_library(
  name = "bar_proto",
  srcs = ["bar/generated.proto"],
)

proto_library(
  name = "foo_proto",
  srcs = ["regular.proto"],
)
```

In that case, can we make the import path of the `go_proto_library` to be `example.com/foo/bar`?

**Comment by jayconrod** [comment]
Normally, `go_proto_library` will use the import path specified with `option go_package` in the .proto file. The Go extension doesn't actually read the `.proto` file though. The proto extension attaches metadata by setting the hidden attribute `language/proto.PackageKey` to a `language/proto.Package` struct.

I think the best way to handle this is for a separate extension to generate `proto_library` rules that have this metadata attached. The Go extension should understand that.

**Comment by linzhp** [comment]
Yeah, I am aware of [goProtoImportPath](https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/package.go#L193-L204) that look up `go_package` before calling `inferImportPath`.  We can copy the logic of `inferImportPath`, append it with subdirectory and assign it go `go_package`. Or maybe make `inferImportPath` an exported method?

**Comment by jayconrod** [comment]
Exporting `inferImportPath` would probably be fine. Its signature should be `func InferImportPath(c *config.Config, rel string) string` so that we don't need to export `goConfig`.

**Comment by ekleiner** [comment]
I am implementing an extension which generates proto_library and need ProtoConfig.StripImportPrefix and ProtoConfig.ImportPrefix
