### ISSUE TITLE
Handling proto files that are consumed by existing proto_library rules

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel-gazelle#731]
I kind of shooting myself in the foot by #720. Now proto extension generates a proto_library for all generated proto files. After discussion in #727, we decided to write our own extension to generate a proto_library for each proto file because they need to compile into different Go libraries. So we no longer need Gazelles's proto extension to do that anymore.

Should I revert #720, or should I do something like #643 for proto?

**Comment by linzhp** [comment]
Or should I have go extension to generate `go_proto_library` whenever there is a `proto_library`? Basically removing [this if statement](https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/generate.go#L395-L399)

**Comment by jayconrod** [comment]
If you don't need `language/proto` to generate `proto_library` rules for generated .proto files anymore, it's probably best to roll back #720. Either behavior seems reasonable to me, but doing less is probably better, especially if it's getting in the way for you.

About `go_proto_library`, that `if` statement is necessary when proto rule generation is disabled. Not sure what you need here exactly. Do you want to generate `go_proto_library` for some `proto_library` rules but not others?

**Comment by linzhp** [comment]
> About go_proto_library, that if statement is necessary when proto rule generation is disabled. Not sure what you need here exactly. Do you want to generate go_proto_library for some proto_library rules but not others?

An alternative is to disable proto_library generation in Gazelle's default proto extension. Our private extension doesn't honor `# gazelle:proto`, so it would continue to generate proto_library. The if that `if` statement is removed, Go extension can generate `go_proto_library` whenever there is a `proto_library`, whether it is handwritten or generated by our private extension.

Reverting #720 is probably the simplest solution here.
