### ISSUE TITLE
fetch_repo doesn't handle git repositories with submodules

### ISSUE THREAD

**Issue by mplzik** [bazelbuild/bazel-gazelle#732]
### What version of gazelle are you using?

0.20.0

### What version of rules_go are you using?

0.22.1

### What version of Bazel are you using?

2.1.0

### Does this issue reproduce with the latest releases of all the above?

To my best knowledge, these are the latest versions, apart from bazel, which has had different issues when upgrading 2.2.0.

### What operating system and processor architecture are you using?

Linux/amd64

### What did you do?

Tried to use Bazel/rules_go/gazelle to build a (otherwise functional) golang project that uses `github.com/google/go-jsonnet` (which is a git repo using submodules). This was done by creating a Bazel workspace and trying to use gazelle to generate BUILD files and import the necessary repositories. After that, I tried to build the target using `bazel build //...`

See the attached archive with Bazel workspace.
[gazelle-bug.tar.gz](https://github.com/bazelbuild/bazel-gazelle/files/4350223/gazelle-bug.tar.gz)

### What did you expect to see?

A correctly compiled target.

### What did you see instead?

Compilation error on go-jsonnet's side:

```
$ bazel build //...
ERROR: /home/whatever/.cache/bazel/_bazel_whatever/2746597193d878897e28c5186b213b4b/external/com_github_google_go_jsonnet/astgen/BUILD.bazel:3:1: no such package '@com_github_google_go_jsonnet//cpp-jsonnet/stdlib': BUILD file not found in directory 'cpp-jsonnet/stdlib' of external repository @com_github_google_go_jsonnet. Add a BUILD file to a directory to mark it as a package. and referenced by '@com_github_google_go_jsonnet//astgen:dumpstdlibast'
ERROR: Analysis of target '//:go_default_library' failed; build aborted: no such package '@com_github_google_go_jsonnet//cpp-jsonnet/stdlib': BUILD file not found in directory 'cpp-jsonnet/stdlib' of external repository @com_github_google_go_jsonnet. Add a BUILD file to a directory to mark it as a package.
INFO: Elapsed time: 3.191s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 49 targets configured)
```

**Comment by jayconrod** [comment]
It looks like the `go_repository` rule for `go-jsonnet` will run in module mode. By default, it downloads a .zip file from the Go module proxy. That .zip file won't include submodules.

```
go_repository(
    name = "com_github_google_go_jsonnet",
    importpath = "github.com/google/go-jsonnet",
    sum = "h1:lEUXTDnVsHu+CLLzMeWAdWV4JpCgkJeDqdVNS8RtyuY=",
    version = "v0.15.0",
)
```

`go_repository` does support cloning Git repositories directly, but it doesn't support submodules.

However, this repository already has `WORKSPACE` and `BUILD.bazel` files, so maybe it's just better to use `git_repository` instead of `go_repository`.

```
# gazelle:repository go_repository name=com_github_google_go_jsonnet importpath=github.com/google/go-jsonnet
git_repository(
    name = "com_github_google_go_jsonnet",
    commit = "70a6b3d419d9ee16a144345c35e0305052c6f2d9",
    init_submodules = True,
    remote = "https://github.com/google/go-jsonnet",
    shallow_since = "1581289066 +0100",
)
```

The `# gazelle:repository` directive here is optional. It will speed up Gazelle's dependency resolution.

**Comment by mplzik** [comment]
Indeed, this seems to work; thanks a lot! :) In the meanwhile, Since the release archives don't contain the `cpp-jsonnet/stdlib` as well, it probably makes sense to report this as a bug to the go-jsonnet maintainers.
