### ISSUE TITLE
Can gazelle generate go_tool_library?

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/bazel-gazelle#747]
### What version of gazelle are you using?

0.22.0

### What version of rules_go are you using?

0.22.2

### What version of Bazel are you using?

2.1.1

### Does this issue reproduce with the latest releases of all the above?

N/A

### What operating system and processor architecture are you using?

linux amd64

### What did you do?

I'm trying to use github.com/securego/gosec as a third_party dependency via workspace go_repository in a go_tool_library analyzer. The problem I have is that gazelle only generates the go_default_library's which cause a dependency loop on nogo. 

My question is: is there a way to direct gazelle to generate go_tool_library in addition to go_default_library?

### What did you expect to see?

N/A

### What did you see instead?

N/A

**Comment by achew22** [comment]
Can you use

```
# gazelle:map_kind from_kind to_kind to_kind_load
```

and map it to a `go_tool_library` directly? If you need both a `go_tool_library` and a `go_library` you could make a macro that creates both of those and map the `to_kind` to the macro.

**Comment by prestonvanloon** [comment]
Where would I put that directive? I tried this
```starlark
go_repository(
    name = "com_github_securego_gosec",
    importpath = "github.com/securego/gosec",
    sum = "h1:rq2/kILQnPtq5oL4+IAjgVOjh5e2yj2aaCYi7squEvI=",
    version = "v0.0.0-20200401082031-e946c8c39989",
    # gazelle:map_kind go_library go_tool_library @io_bazel_rules_go//go:def.bzl
)
```

But it seems the rules are still go_library.

```
bazel query @com_github_securego_gosec//... --output=label_kind
go_test rule @com_github_securego_gosec//rules:go_default_test
go_test rule @com_github_securego_gosec//output:go_default_test
go_binary rule @com_github_securego_gosec//cmd/tlsconfig:tlsconfig
go_library rule @com_github_securego_gosec//cmd/tlsconfig:go_default_library
go_binary rule @com_github_securego_gosec//cmd/gosecutil:gosecutil
go_library rule @com_github_securego_gosec//cmd/gosecutil:go_default_library
go_binary rule @com_github_securego_gosec//cmd/gosec:gosec
go_library rule @com_github_securego_gosec//cmd/gosec:go_default_library
go_library rule @com_github_securego_gosec//output:go_default_library
go_test rule @com_github_securego_gosec//:go_default_test
go_library rule @com_github_securego_gosec//testutils:go_default_library
go_library rule @com_github_securego_gosec//rules:go_default_library
go_library rule @com_github_securego_gosec//:go_default_library
```

**Comment by achew22** [comment]
I'm terribly sorry, I didn't understand something about this. Let me revise.

In [`go_repository`](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository) there is a parameter called `build_extra_args`. I was expecting you would be able to use a flag to include that directive, but now that I am reading the docs it doesn't look like that's possible.

@jayconrod do you have any idea on the next way direction to go here? Is the correct move to use patch to replace or to add a flag to gazelle allowing you to pass in directives?

**Comment by jayconrod** [comment]
`go_repository` has an attribute `build_directives` that you can use to pass in a list of directives. Gazelle will act as if they were in the root build file when running. That's probably the way to go here.

Gazelle won't support `go_tool_library` though. I'd like to get rid of `go_tool_library` (bazelbuild/rules_go#2374). `nogo` should be able to depend on regular `go_library` targets that are built in a configuration that doesn't use `nogo`. That would eliminate the circular dependency without needing the repetition we currently have.

Closing this issue just to say this won't be supported. Happy to continue discussion though.

**Comment by prestonvanloon** [comment]
Thanks @jayconrod. Looking forward to your transitional rules rewrite!
