### ISSUE TITLE
Test running gazelle rule in another workspace

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#75]
Test should:

* Create a new workspace with a WORKSPACE file, BUILD.bazel file, and some trivial source files, using the recommended boilerplate code.
* `bazel run //:gazelle`
* `bazel build` a newly generated `go_binary` rule.

This test should work similarly to rules_go integration tests (see [bazel_tests.bzl](https://github.com/bazelbuild/rules_go/blob/master/tests/bazel_tests.bzl)).

**Comment by achew22** [comment]
I have done something like this in the iBazel project. I opted to just use sh_library in my examples but the same logic applies.

https://github.com/bazelbuild/bazel-watcher/blob/a2ceacd14ddf2cb7e1afe718f181441cc95162b3/e2e/simple/simple_test.go#L19-L31

It also has the added bonus of allowing you to verify against multiple versions of Bazel in unison by passing in a set of versions.

**Comment by jayconrod** [comment]
@achew22 Thanks, that looks promising.
