### ISSUE TITLE
Workspace root detection fails when "WORKSPACE.bazel" used

### ISSUE THREAD

**Issue by HALtheWise** [bazelbuild/bazel-gazelle#764]
In a Bazel workspace using the `WORKSPACE.bazel` filename instead of plain `WORKSPACE`, Gazelle is unable to discover the root of the repository.

```
gazelle: -repo_root not specified, and WORKSPACE cannot be found: file does not exist
```

The issue seems to be in [`internal/wspace/finder.go`](https://github.com/bazelbuild/bazel-gazelle/blob/master/internal/wspace/finder.go), where it assumes that the `WORKSPACE` file must always be named exactly that.

Either this file could hard-code the two legal names for WORKSPACE files, or it could become a configurable option like BUILD file names are. 

I wanted to open this up for discussion before making a PR.

Note that this is similar to, but not the same as, #678, which possibly indicates there needs to be some testing for this scenario.

### What version of gazelle are you using?
v0.19.1

### What version of rules_go are you using?
v0.21.0

### What version of Bazel are you using?
2.0.0

### Does this issue reproduce with the latest releases of all the above?
Yes

**Comment by jayconrod** [comment]
I'd be happy to take a PR that fixes this.

It shouldn't need to be a configurable option, since Gazelle never creates a WORKSPACE file. Just detect whichever one is there.
