### ISSUE TITLE
DEBUG warnings generated importing `github.com/apache/thrift`

### ISSUE THREAD

**Issue by smparkes** [bazelbuild/bazel-gazelle#766]
### What version of gazelle are you using?

`master`

### What version of rules_go are you using?

`master`

### What version of Bazel are you using?

`3.1.0` (and `3.0.0`)

### What operating system and processor architecture are you using?

`linux` `x86_64`

### What did you do?

We depend on `github.com/xitongsys/parquet-go` which depends on `github.com/apache/thrift/lib/go/thrift`. Gazelle creates a reasonable looking `go_repository`:
```
    go_repository(
        name = "com_github_apache_thrift",
        importpath = "github.com/apache/thrift",
        sum = "h1:pODnxUFNcjP9UTLZGTdeh+j16A8lJbRvD3rOtrk/7bs=",
        version = "v0.12.0",
    )
```

### What did you expect to see?

No warnings ...

### What did you see instead?

The build seems to work but Gazelle gives a debug warning:
```
DEBUG: /.cache/bazel/_bazel_/f49c05caa546fa66f935cfc83be54142/external/bazel_gazelle/internal/go_repository.bzl:184:13: com_github_apache_thrift: gazelle: finding module path for import thrift: exit status 1: can't load package: package thrift is not in GOROOT /.cache/bazel/_bazel_/f49c05caa546fa66f935cfc83be54142/external/go_sdk/src/thrift)
```
and then 29 lines of the form
```
gazelle: finding module path for import thrifttest: exit status 1: can't load package: package thrifttest is not in GOROOT /.cache/bazel/_bazel_s/f49c05caa546fa66f935cfc83be54142/external/go_sdk/src/thrifttest)
```

Not sure if this is something we should be worried about/can avoid?

**Comment by jayconrod** [comment]
It looks like this happens because `github.com/apache/thrift` has a bunch of invalid packages in the `test` directory (or rather, packages that are only valid if you set `GOPATH` to that directory). There are a lot of imports of `"thrifttest"` for example.

You should be able to work around this by adding `build_extra_args = ["-exclude=test"]` to the `com_github_apache_thrift` rule.

**Comment by smparkes** [comment]
Thanks for the quick response and appologies for letting this sit idle. Switching between lots of tasks ...

Exactly the right solution, though they also have tests in `lib/go/test/tests` so I ended up with
```
    go_repository(
        name = "com_github_apache_thrift",
        build_extra_args = [
            "-exclude=test",
            "-exclude=tutorial",
            "-exclude=lib/go/test",
        ],
        importpath = "github.com/apache/thrift",
        sum = "h1:pODnxUFNcjP9UTLZGTdeh+j16A8lJbRvD3rOtrk/7bs=",
        version = "v0.12.0",
    )

```
