### ISSUE TITLE
Disable proto rule generation by default in vendor

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#77]
Original issue: bazelbuild/rules_go#1219, bazelbuild/rules_go#1022

Vendored .proto files rarely compile without modification in Bazel. If a vendored proto A imports another vendored proto B, the import path in A must be adjusted manually to include a "vendor" prefix. Bazel `proto_library` assumes all proto import paths are relative to the root of a repository. There's currently no way to adjust import paths via `proto_library`.

Since working `proto_library` rules can't be generated for vendored protos in most cases, Gazelle should not attempt to do so by default. We should automatically disable proto rule generation when entering a vendor directory.

Proto rule generation can be explicitly turned on by adding a directive like the one below to a build file. The directive applies to the build file's package and subdirectories.

```
# gazelle:proto default
```

**Comment by mattmoor** [comment]
So a complementary argument for why this should not be necessary...

The contents of `vendor/` is likely dependencies compatible with traditional Go vendoring (`go get`, `godep`, `dep`, `glide`, ...), which means that even if there are `.proto` files, that the code they generate must have been checked in to be compatible with the standard (non-Bazel) tooling.
