### ISSUE TITLE
resolve: support cross-language dependency resolution in extensions

### ISSUE THREAD

**Issue by blico** [bazelbuild/bazel-gazelle#771]
Currently, Autogazelle always passes `-index=false` to Gazelle as a way to keep Gazelle runs fast. Therefore for the dependency resolution of custom-named rules, you must use `# gazelle:resolve` directives within the repo's root bazel file.

Due to the large size of our repo and the number of rules we have that require an index to be resolved, it would not be feasible for us to maintain a top-level bazel file with all of the needed `# gazelle:resolve` directives.

I believe we could get around this issue if Gazelle was able to take in a pre-calculated rule index to use for dependency resolution. Autogazelle could generate the index during its initial run on the entire repo and then pass in the generated index to subsequent gazelle runs. Each run would also need to update the index to reflect any changes within the supplied directories.

Before digging too deep, I was wondering if this idea sounds good to you and if there are any gotchas you may be aware of?

**Comment by jayconrod** [comment]
I think this could work in theory, depending on how big the index is. The important thing is that Gazelle can run quickly in a few directories that have changed, and if the index is serialized in some format where specific imports can be looked up quickly (without needing to read the entire index), that could work.

I'm not sure how compatible this would be with extensions. Index entries are rule objects that may contain information only in memory, so some information may be lost if only labels are serialized.

In any case, this would be a pretty complicated implementation, and it would make Gazelle more complex. I can't commit to designing, implementing, or reviewing this right now.

**Comment by blico** [comment]
I was able to get a prototype of this idea working for our repository, and I would consider the change to be fairly simple and non-invasive (no public APIs are modified and only `fix-update.go` and `index.go` have changes). 

Rather than serializing the entire index, I only serialized `ImportSpec` => `label` mappings. When there is a cache hit, a rule object is created by parsing the build file of the given label. Also, the normal index is still created for any dirs in which Gazelle is running on, and it takes priority over the cached index, ensuring that stale data won't be used as long as all changed paths are included in the Gazelle run.

The change is compatible with all 8 of our custom extensions, and I can't think of a scenario where it would not work with an extension.

If that is enough to convince you to review the change I can polish my change and put out a PR.

**Comment by blico** [comment]
Thank you for your help here.

I do like the idea of avoiding indexing altogether. To rely on consistent naming conventions in our repo, we would likely need to modify the Go extension's dependency resolution logic, or less ideally fork the Go extension.

To elaborate, we have several Gazelle extensions for code generators that generate go importable rules, each with a different naming convention. Go code that imports these rules rely on the Go extension's use of indexing for dependency resolution. Without indexing, the Go extension would need to be able to resolve by attempting to match an import to a naming convention.

Without going into too many specifics, I think a general enough solution would be to add the ability to allow extensions to register custom dependency resolution logic within here: https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/resolve.go#L181

Besides that, features to manage a list of ` # gazelle:resolve` directives would also be very helpful because resolve directive could be used as a fallback while we migrate our repository to consistent naming conventions.

**Comment by jayconrod** [comment]
I opened #817 to track expanding the `replace` directive.

Making this kind of dependency resolution extensible is an interesting idea. So you'd maybe have an extension with a method like:

```
ResolveImport(c *Config, ix *RuleIndex, rc *repo.RemoteCache, imp resolve.ImportSpec, from label.Label) label.Label
```

and that would be able to provide custom dependency resolution logic for other languages. For example, the `language/proto` extension could use that to provide known dependencies for imports of certain proto packages from Go code instead of having that logic in Go as it is now.

**Comment by blico** [comment]
Exactly. To avoid breaking `language.Language` we could define a new interface 
`MetaLanguage`, with some function like `OtherResolvers() map[string]ResolveImport`.

To avoid breaking `language.Resolve`, `RuleIndex` could keep track of all `ResolveImport` mappings, and `RuleIndex` could be used by extensions to retrieve a list of other resolvers that have registered to its language.

Maybe there is a better way I am not thinking of, or this change is worthy of breaking some APIs?

**Comment by jayconrod** [comment]
One of my regrets with `language.Language` is that it's a big monolithic interface. It would have been better for it not to embed `config.Config` and `resolve.Resolver`. Extensions could implement any subset of those interfaces. Changing that now would be a breaking change, and I'd rather not make breaking changes now, but I should probably start making a list of things like that to change before `v1.0.0`.

Anyway, I think adding a new optional interface for extensions to implement is the right want to proceed with this. Let's call it `resolve.CrossResolver`. I'll sketch out a bit more what I'm thinking.

```
type CrossResolver interface {
  CrossResolve(c *Config, ix *RuleIndex, rc *repo.RemoteCache, imp ImportSpec, lang string) []resolve.FindResult
}
```

The `CrossResolve` method would take an import (for example, `ImportSpec{Lang: "proto", Imp: "google/protobuf/any.proto"}`) and the language of the rule being resolved (for example, `"go"`) and would return a list of matching targets, according to some logic. For example, the `language/proto` extension could use the proto mode in `c` to resolve the import to either `@io_bazel_rules_go//proto/wkt:any_go_proto` or `@com_github_golang_protobuf//protobuf/ptypes/any:go_default_library`.

When the `RuleIndex` is created in `fix-update.go`, extensions that implement `CrossResolver` would be added. When `RuleIndex.FindRulesByImport` is called, that would call `CrossResolve` methods if there are no other results in the index.

Note that when indexing is disabled, the index is still used, but we just don't add libraries to it. So `CrossResolver` implementations would have a bigger role to play.

Would that design work for you? It's complicated, and something is probably missing.

**Comment by blico** [comment]
SGTM. Not sure if you want a new issue for the `CrossResolver` implementation, or if we should repurpose this one for it.

**Comment by jayconrod** [comment]
Let's repurpose this one to preserve the discussion.
