### ISSUE TITLE
External Go module is not visible from go_binary() target

### ISSUE THREAD

**Issue by themacguffinman** [bazelbuild/bazel-gazelle#774]
### What version of gazelle are you using?
v0.20.0

### What version of rules_go are you using?
v0.22.4

### What version of Bazel are you using?
```
Build label: 3.1.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Apr 30 13:16:41 2020 (1588252601)
Build timestamp: 1588252601
Build timestamp as int: 1588252601
```

### Does this issue reproduce with the latest releases of all the above?
Yes

### What operating system and processor architecture are you using?
```
Linux 5.6.11-arch1-1 #1 SMP PREEMPT Wed, 06 May 2020 17:32:37 +0000 x86_64 GNU/Linux
```

### What did you do?
1. created a new empty repo with Go and Gazelle rules loaded in `WORKSPACE`
2. declared the `gazelle()` rule in top-level `BUILD.bazel` file
3. created a top-level `go.mod` file that looks like this:
```
module github.com/themacguffinman/gazelle_module_visibility_test

go 1.14

require (
	sigs.k8s.io/kind v0.8.0
)
```
4. generate `go_repository()` rules from `go.mod` file by running this command:
```
bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=go_modules.bzl%go_modules
```
5. create a `deploy/BUILD.bazel` file with a `go_binary()` rule that uses the external go module, the build file looks like this:
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "kind",
    embed = ["@io_k8s_sigs_kind//:go_default_library"],
    visibility = ["//visibility:public"],
)
```
6. run the target we defined in the previous step:
```
bazel run //deploy:kind
```

Note: you can clone https://github.com/themacguffinman/gazelle_module_visibility_test and skip to step 6

### What did you expect to see?
`//deploy:kind` should have successfully compiled and executed.

### What did you see instead?
```
Starting local Bazel server and connecting to it...
ERROR: /home/josh/Documents/gazelle_module_visibility_test/deploy/BUILD.bazel:3:1: in go_binary rule //deploy:kind: target '@io_k8s_sigs_kind//:go_default_library' is not visible from target '//deploy:kind'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//deploy:kind' failed; build aborted: Analysis of target '//deploy:kind' failed
INFO: Elapsed time: 14.985s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (110 packages loaded, 7214 targets configured)
FAILED: Build did NOT complete successfully (110 packages loaded, 7214 targets configured)
```

Note: it works if I run the target with visibility checks disabled:
```
bazel run --nocheck_visibility //deploy:kind
```

**Comment by jayconrod** [comment]
It looks like `@io_k8s_sigs_kind//:go_default_library` is a `main` package: a library that exists only to be embedded in a `go_binary` or `go_test` in the same directory. Is that intentional? It can't be imported by other packages, so it doesn't have public visibility.

rules_go has no restriction on embedding packages across directories, but Gazelle tries to follow conventions from the `go` command as much as possible, so it's stricter about one package per directory. So from the Gazelle side, this is working as intended.

Why embed the library like this though? Unless you have other sources or dependencies to build in, an `alias` might work better.

**Comment by themacguffinman** [comment]
Ah, thank you for the suggestion and explanation, I was able to get it working with `alias()`. I didn't have a good understanding of how these rules work and fit together so I reached for `go_binary()`.

For any onlookers, what I did was examine the generated build file:
```

**Comment by aw185176** [comment]
One use case for this is packaging external binaries (kind, godoc, etc) into your own container images.  Since the package main isn't visible, we cant define `go_image` for things like `@io_k8s_sigs_kind//:go_default_library`
