### ISSUE TITLE
go_repository: error resolving latest version of module

### ISSUE THREAD

**Issue by pierretasci** [bazelbuild/bazel-gazelle#775]
### What version of gazelle are you using?

v0.20.0

### What version of rules_go are you using?

v0.22.4

### What version of Bazel are you using?

2.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Works when I run locally on Mac, breaks when I run in an Alpine Linux container

### What did you do?

Create a go project that depends on https://github.com/tektoncd/pipeline v0.11.2 and kubernetes v1.17.2.

*go.mod*
```go
go 1.13

require (
	...
	github.com/tektoncd/pipeline v0.11.2
        ...
	k8s.io/api v0.17.2
	k8s.io/apimachinery v0.17.2
	k8s.io/client-go v0.17.2
)

replace (
	k8s.io/api => k8s.io/api v0.16.5
	k8s.io/apimachinery => k8s.io/apimachinery v0.16.5
	k8s.io/client-go => k8s.io/client-go v0.16.5
	k8s.io/code-generator => k8s.io/code-generator v0.16.5
	k8s.io/gengo => k8s.io/gengo v0.0.0-20190327210449-e17681d19d3a
)
```

Note the replacements needed because Tekton uses an older version of Kubernetes. There was a breaking change in a dependency of Kubernetes called `gnostic` (a path was renamed). This means our older version of Kubernetes that we are using expects an `importpath` of `github.com/googleapis/gnostic/OpenAPIv2` and that is what Gazelle produces when running locally. I then mount this repository as a volume on an Alpine container and install Bazel and run a test.
### What did you expect to see?

For the test to succeed as it does locally.

### What did you see instead?

```bash
go: downloading github.com/googleapis/gnostic v0.4.1
go: extracting github.com/googleapis/gnostic v0.4.1
can't load package: package github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest (v0.4.1) found, but does not contain package github.com/googleapis/gnostic/OpenAPIv2
DEBUG: /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/bazel_gazelle/internal/go_repository.bzl:184:13: io_k8s_apimachinery: gazelle: finding module path for import github.com/googleapis/gnostic/OpenAPIv2: exit status 1: can't load package: package github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest (v0.4.1) found, but does not contain package github.com/googleapis/gnostic/OpenAPIv2
```

It is trying to download gnostic v0.4.1 even though my repository rules specifies v0.3.1:

```
go_repository(
        name = "com_github_googleapis_gnostic",
        importpath = "github.com/googleapis/gnostic",
        sum = "h1:WeAefnSUHlBb0iJKwxFDZdbfGwkd7xRNuV+IpXMJhYk=",
        version = "v0.3.1",
 )
```

Something is resolving differently on Linux than on Mac because a completely clean repository will succeed locally but not in the container. I think there is some flaky logic in how dependencies are resolved.

**Comment by jayconrod** [comment]
Sorry for the slow response. Last week was a very busy week, and I'm still catching up.

Where exactly is the `com_github_googleapis_gnostic` repository declared? Is it in `WORKSPACE` or in a function somewhere else? If it's somewhere else, do you have a `# gazelle:repository_macro` directive in `WORKSPACE` pointing to that location?

From the error message, it sounds like this came up when the `go_repository` rule for `io_k8s_apimachinery` was evaluated. When Gazelle is invoked in `go_repository`, it's given a configuration file derived from `WORKSPACE` that lists `go_repository` rules and their `importpaths`. That lets Gazelle resolve Go imports to Bazel labels without going out to the network.

It sounds like this configuration file is incomplete. If Gazelle didn't find a `go_repository` rule for `github.com/googleapis/gnostic`, it will use `go list` to find a module for that.

Related #454, #499

**Comment by pierretasci** [comment]
No worries, thanks for getting back to me!

So I fixed the issue based on a hunch from your comment above but the reason is still confusing.

To answer your questions...`gnostic` is not a direct or indirect dependency of my `go.mod` but it is imported transiently by multiple K8s packages. Therefore it does show up in a `repository_macro` I use which does have `gnostic` listed in there.

Your comment made me realize that perhaps when running in a container, it isn't picking up on my macro and therefore using `go list`. I remembered that there is a gazelle directive I can put in my WORKSPACE file to tell it about my macro (even though I am already loading the macro). I added that in, ran it in the container, and it resolved correctly!

Now what is confusing to me is why this worked locally without the macro before. I would think that if it needed the macro to properly resolve, it would always need that whether I was running on my dev machine or in a new container. Any thoughts?

**Comment by jayconrod** [comment]
> Now what is confusing to me is why this worked locally without the macro before. I would think that if it needed the macro to properly resolve, it would always need that whether I was running on my dev machine or in a new container. Any thoughts?

The behavior in the container is what I would expect: if it can't find something, it should go out to the network, and that should fail if the package was removed upstream. But you should see the same behavior both locally and in the container, given the same set of files. I wouldn't expect platform-specific behavior here. Hard to say more without knowing more about the workspace and the specific commands being run.

**Comment by pierretasci** [comment]
I figured. From a clean local workspace, I run:

```bash
go mod tidy -v
bazel run //:gazelle -- update-repos -from_file=go.mod -to_macro=go-deps.bzl%go_local_deps -proto disable_global -prune=true -build_file_generation=on;
bazel run //:gazelle -- update
```
to produce all of the `go_repository` rules and the `BUILD.bazel` files. I think I might have generated this project before there was a dependency on this directive because I don't remember it being there when I set this up.

Anyways, if I then run a `bazel test //...` it passes.
If I spin up a container with Bazel installed and my repo mounted as a volume and run `bazel test //...` it would have failed obviously without the addition of the directive.

Hope that helps!

**Comment by jayconrod** [comment]
I'll close this issue since it sounds like this is working with the `# gazelle:repository_macro` directive. I'm still a little surprised it would work without the directive. Perhaps an odd interaction between Bazel's cache, Go's module cache, and container volume mapping, but I don't have bandwidth to hunt it down.

The `# gazelle:repository_macro` directive was introduced shortly after the `-to_macro` flag (maybe in the same release, actually). It's required, but it's very easy to forget, so in `v0.21.0` (released last week), `-to_macro` adds the directive automatically if it's missing.
