### ISSUE TITLE
Not able to build github.com/chai2010/webp

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel-gazelle#776]
The repository `github.com/chai2010/webp` includes a C library. "go build" succeeds because the 
repository has all necessary C dependencies. However, "bazel build" fail due to misconfiguration generated by Gazelle.

### What version of gazelle are you using?

7e93b118efcdfe63f43057a88711762e0b5d7267

### What version of rules_go are you using?

280a1ed6be5a3c085aeb4ca72564b066cba64e62

### What version of Bazel are you using?

3.0.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Darwin amd64

### What did you do?

```bash
git clone github.com:linzhp/bazel_examples.git
cd bazel_examples
git checkout 7a11b0c697cd0c024a770d05973f6f4f844f7153
bazel build //gazelle/webp
```

### What did you expect to see?

Build succeed

### What did you see instead?
```
ERROR: /private/var/tmp/_bazel_zplin/1b23f78923ad6c0028e8aab1a0a6d5fb/external/com_github_chai2010_webp/BUILD.bazel:3:1: GoCompilePkg external/com_github_chai2010_webp/go_default_library.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_chai2010_webp/capi.go -src external/com_github_chai2010_webp/cgo.go -src ... (remaining 277 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/private/var/tmp/_bazel_zplin/1b23f78923ad6c0028e8aab1a0a6d5fb/sandbox/darwin-sandbox/94/execroot/__main__/external/com_github_chai2010_webp/capi.go:24:10: fatal error: 'webp.h' file not found
#include "webp.h"
         ^~~~~~~~
1 error generated.
compilepkg: error running subcommand: exit status 2
Target //gazelle/webp:webp failed to build
```

**Comment by jayconrod** [comment]
Sorry for the slow response. Last week was a busy week, and I'm still catching up.

This is probably not something that Gazelle can support. Packages that use cgo with files that span more than one directory almost always require handwritten rules.

One way to build this would be to have at least one `cc_library` rule that includes the necessary headers in its `hdrs` attribute. Not sure if that should be in the `internal/include` directory, or `internal/libwebp-1.0.2`, both, or somewhere else. `@com_github_chai2010_webp//:go_default_library` should depend on that library via a `cdeps` attribute. Gazelle won't generate `cdeps` attributes, since it can't reliably guess what's needed.

Alternatively, since all the `.c` files are copied into the same directory, `internal/include/webp.h` could be added to the `go_library` `srcs` attribute. That makes sense for this one specific case, but it would break if there were any other `BUILD.bazel` files in the way.

**Comment by barbu110** [comment]
hi there @linzhp - sorry for tagging - have you ever been able to overcome the issue?

**Comment by linzhp** [comment]
We disabled the build file generation for that repository, manually wrote build targets for it, and apply a patch like this:
```
diff --git a/BUILD.bazel b/BUILD.bazel
new file mode 100644
index 0000000..6c6321c
--- /dev/null
+++ b/BUILD.bazel
@@ -0,0 +1,58 @@
+load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
+
+filegroup(
+  name = "libwebpsrcs",
+  srcs = glob([
+        "internal/libwebp-1.0.2/**/*.c",
+        "internal/src/webp.c",
+       ]),
+  visibility = ["//visibility:public"],
+)
+
+filegroup(
+  name = "libwebphdrs",
+  srcs = glob([
+        "internal/libwebp-1.0.2/**/*.h",
+        "internal/include/webp.h",
+       ]),
+  visibility = ["//visibility:public"],
+)
+
+filegroup(
+    name = "gosource",
+    srcs = glob([
+        "*.go",
+       ], exclude = ["*_test.go"]),
+    visibility = ["//visibility:public"],
+)
+
+cc_library(
+  name = "cclib_webp",
+  srcs = [":libwebpsrcs"],
+  hdrs = [":libwebphdrs"],
+  copts = [
+        "-Iexternal/com_github_chai2010_webp/internal/include",
+        "-Iexternal/com_github_chai2010_webp/internal/libwebp-1.0.2",
+        "-Iexternal/com_github_chai2010_webp/internal/libwebp-1.0.2/src",
+        "-Wno-pointer-sign -DWEBP_USE_THREAD",
+  ],
+  linkopts = [ "-lm" ],
+  visibility = ["//visibility:public"],
+)
+
+go_library(
+    name = "go_default_library",
+    srcs = [":gosource", ":libwebpsrcs", ":libwebphdrs"],
+    cgo = True,
+    cdeps = [":cclib_webp"],
+    importpath = "github.com/chai2010/webp",
+    visibility = ["//visibility:public"],
+    copts = [
+        "-Iexternal/com_github_chai2009_webp/internal/include",
+        "-Iexternal/com_github_chai2010_webp/internal/libwebp-1.0.2",
+        "-Iexternal/com_github_chai2010_webp/internal/libwebp-1.0.2/src",
+        "-Iexternal/com_github_chai2010_webp",
+        "-Wno-pointer-sign -DWEBP_USE_THREAD",
+    ],
+
+)
```

**Comment by barbu110** [comment]
Oh that’s very smart! Was already looking into something like module patching, but this seems cleaner. Thank you!
  
On Tue, Jun 18, 2024 at 23:20, Zhongpeng Lin - notifications at github.com ***@***.***&gt; wrote:  We disabled the build file generation for that repository, manually wrote build targets for it, and apply a patch like this:
diff --git a/BUILD.bazel b/BUILD.bazel
new file mode 100644
index 0000000..6c6321c
--- /dev/null
+++ b/BUILD.bazel
@@ -0,0 +1,58 @@
***@***.***_bazel_rules_go//go:def.bzl", "go_library", "go_test")
+
+filegroup(
+  name = "libwebpsrcs",
+  srcs = glob([
+        "internal/libwebp-1.0.2/**/*.c",
+        "internal/src/webp.c",
+       ]),
+  visibility = ["//visibility:public"],
+)
+
+filegroup(
+  name = "libwebphdrs",
+  srcs = glob([
+        "internal/libwebp-1.0.2/**/*.h",
+        "internal/include/webp.h",
+       ]),
+  visibility = ["//visibility:public"],
+)
+
+filegroup(
+    name = "gosource",
+    srcs = glob([
+        "*.go",
+       ], exclude = ["*_test.go"]),
+    visibility = ["//visibility:public"],
+)
+
+cc_library(
+  name = "cclib_webp",
+  srcs = [":libwebpsrcs"],
+  hdrs = [":libwebphdrs"],
+  copts = [
+        "-Iexternal/com_github_chai2010_webp/internal/include",
+        "-Iexternal/com_github_chai2010_webp/internal/libwebp-1.0.2",
+        "-Iexternal/com_github_chai2010_webp/internal/libwebp-1.0.2/src",
+        "-Wno-pointer-sign -DWEBP_USE_THREAD",
+  ],
+  linkopts = [ "-lm" ],
+  visibility = ["//visibility:public"],
+)
+
+go_library(
+    name = "go_default_library",
+    srcs = [":gosource", ":libwebpsrcs", ":libwebphdrs"],
+    cgo = True,
+    cdeps = [":cclib_webp"],
+    importpath = "github.com/chai2010/webp",
+    visibility = ["//visibility:public"],
+    copts = [
+        "-Iexternal/com_github_chai2009_webp/internal/include",
+        "-Iexternal/com_github_chai2010_webp/internal/libwebp-1.0.2",
+        "-Iexternal/com_github_chai2010_webp/internal/libwebp-1.0.2/src",
+        "-Iexternal/com_github_chai2010_webp",
+        "-Wno-pointer-sign -DWEBP_USE_THREAD",
+    ],
+
+)
