### ISSUE TITLE
gazelle_binary and cfg = "host"

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#782]
In order to test the closure_js language module, I take the same approach as //cmd/gazelle/integration_test.go and run Gazelle on a temp directory using your testtools package. However, unlike the integration tests in gazelle's repo, I have no choice but to execute the binary. 

Right now I accomplish that by including it in the data attribute
https://github.com/robfig/rules_closure/blob/dev/gazelle/closure_js/BUILD.bazel#L44-L46

and building a path to it:
https://github.com/robfig/rules_closure/blob/dev/gazelle/closure_js/integration_test.go#L448-L451

However, I didn't see a good way to build the path in a platform-independent fashion. 

It seems like this is a good use case for specifying `cfg = "host"` on the gazelle binary, but there was no way to do that via gazelle_binary. Is that the right way to solve this, and are you open to a PR adding that pass-through, or perhaps a kwargs that passes through to the go_binary?

**Comment by jayconrod** [comment]
There are a couple ways to do this. [How do I access go_binary executables from go_test?](https://github.com/bazelbuild/rules_go#how-do-i-access-go_binary-executables-from-go_test) has some examples.

* Pass the location of the binary via an argument with a `$(location :binary)` expansion.

```
go_test(
    name = "go_default_test",
    srcs = [...],
    data = [":gazelle_js"],
    args = ["-gazelle=$(location :gazelle_js)"],
)
```

* Use the [`bazel.FindBinary`](https://pkg.go.dev/github.com/bazelbuild/rules_go/go/tools/bazel?tab=doc#FindBinary) function. It searches for a binary with the given name in a Bazel package. There are some known issues with this function, but I think it will work in this case.

Normally, another option would be to set the binary's `out` attribute to get a predictable output location, but `gazelle_binary` doesn't have an `out` attribute.

Setting `cfg = "host"` may cause problems. The binary should be built in the same configuration as the test. For example, if you were testing using remote execution, the execution service might not be able to run host binaries.

**Comment by robfig** [comment]
Makes sense, thank you for those links! I hadn't seen them before.

**Comment by robfig** [comment]
Actually, quick follow-up. `$(location :gazelle_js)` returns the workspace-relative path, "gazelle/closure_js/darwin_amd64_stripped/gazelle_js". In order to access it, I have to prefix it with "../..", e.g. `path.Join("../..", *gazellePath)`. That works ok, but it breaks if the package gets moved or refactored. I couldn't think of any way to make that work in a position-independent way though. Any ideas?

**Comment by jayconrod** [comment]
You might need to set `rundir = "."` on the `go_test` rule. That will prevent the `go_test` binary from changing into the package directory before running tests.

(This is the result of a mismatch between how Blaze runs tests within Google and how `go test` runs tests. Blaze runs everything in the workspace root directory. `go test` runs tests in package directories. Bazel starts `go_test` binaries in the workspace root directory, but the `go_test` implementation changes to the package directory to simulate what `go test` does.)

**Comment by robfig** [comment]
Perfect, thank you!
