### ISSUE TITLE
Adding grpc-ecosystem/grpc-gateway fails with go_default_library_gen target

### ISSUE THREAD

**Issue by rytswd** [bazelbuild/bazel-gazelle#788]
### What version of gazelle are you using?

v0.20.0

### What version of rules_go are you using?

v0.22.2

### What version of Bazel are you using?

v3.1.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

macOS Catalina v10.15.4, x86_64

### What did you do?

Added `"github.com/grpc-ecosystem/grpc-gateway/runtime"` as a dependency.
The full repro of contrived minimal setup is https://github.com/rytswd/simple-bazel/tree/issue/bazelbuild/bazel-gazelle/grpc-gateway-error

`WORKSPACE`

```
workspace(name = "com_github_rytswd_simple_bazel")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

### ---- http_archive ----------------------------------------------------- ###
# Go
# Ref: https://github.com/bazelbuild/rules_go#setup
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "142dd33e38b563605f0d20e89d9ef9eda0fc3cb539a14be1bdb1350de2eda659",
    urls = [
        "https://github.com/bazelbuild/rules_go/releases/download/v0.22.2/rules_go-v0.22.2.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.22.2/rules_go-v0.22.2.tar.gz",
    ],
)

# Gazelle
# Ref: https://github.com/bazelbuild/bazel-gazelle#setup
http_archive(
    name = "bazel_gazelle",
    sha256 = "d8c45ee70ec39a57e7a05e5027c32b1576cc7f16d9dd37135b0eddde45cf1b10",
    urls = [
        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.20.0/bazel-gazelle-v0.20.0.tar.gz",
    ],
)

# Protobuf
http_archive(
    name = "com_google_protobuf",
    sha256 = "9748c0d90e54ea09e5e75fb7fac16edce15d2028d4356f32211cfa3c0e956564",
    strip_prefix = "protobuf-3.11.4",
    urls = ["https://github.com/protocolbuffers/protobuf/archive/v3.11.4.zip"],
)
### ---- end of http_archive                                                ###
### ----------------------------------------------------------------------- ###

### ---- Load Go dependencies --------------------------------------------- ###
load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "go_repository")
load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

# Override depenedency of `googel.golang.org/genproto`
# Ref: https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#overriding-dependencies
go_repository(
    name = "org_golang_google_genproto",
    build_file_proto_mode = "disable_global",
    importpath = "google.golang.org/genproto",
    sum = "h1:MRHtG0U6SnaUb+s+LhNE1qt1FQ1wlhqr5E4usBKC0uA=",
    version = "v0.0.0-20200331122359-1ee6d9798940",
    # commit = "c50568487044f7393f957c36b91edbf731220cba",
)

go_repository(
    name = "com_github_golang_protobuf",
    build_file_proto_mode = "disable_global",
    importpath = "github.com/golang/protobuf",
    sum = "h1:+Z5KGCizgyZCbGh1KZqA0fcLLkwbsjIzS4aV2v7wJX0=",
    version = "v1.4.2",
)

# As per the above reference, this should be called after `go_repository` calls
go_rules_dependencies()

go_register_toolchains()
### ---- end of Go deps                                                     ###
### ----------------------------------------------------------------------- ###

### ---- Setup Gazelle ---------------------------------------------------- ###
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()

# gazelle:repo bazel_gazelle

### ---- end of Gazelle setup                                               ###
### ----------------------------------------------------------------------- ###

# Below lines are auto-generated by running the following command:
#   bazel run gazelle -- update-repos -from_file=go.mod --build_file_proto_mode=disable_global

# Gazelle generated go_repository lines...
```

### What did you expect to see?

```
$ bazel run simple-bazel
INFO: Analyzed target //:simple-bazel (112 packages loaded, 1082 targets configured).
INFO: Found 1 target...
Target //:simple-bazel up-to-date:
  bazel-bin/darwin_amd64_stripped/simple-bazel
...
hello
```

### What did you see instead?

```
bazel run simple-bazel                                                                    
ERROR: (snip).../external/com_github_grpc_ecosystem_grpc_gateway/runtime/BUILD.bazel:5:1: no such target '@com_github_golang_protobuf//descriptor:go_default_library_gen': target 'go_default_library_gen' not declared in package 'descriptor' (did you mean 'go_default_library'?) defined by (snip).../external/com_github_golang_protobuf/descriptor/BUILD.bazel and referenced by '@com_github_grpc_ecosystem_grpc_gateway//runtime:go_default_library'
ERROR: (snip).../external/com_github_grpc_ecosystem_grpc_gateway/runtime/BUILD.bazel:5:1: no such target '@com_github_golang_protobuf//jsonpb:go_default_library_gen': target 'go_default_library_gen' not declared in package 'jsonpb' (did you mean 'go_default_library'?) defined by (snip).../external/com_github_golang_protobuf/jsonpb/BUILD.bazel and referenced by '@com_github_grpc_ecosystem_grpc_gateway//runtime:go_default_library'
ERROR: Analysis of target '//:simple-bazel' failed; build aborted: Analysis failed
INFO: Elapsed time: 31.438s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (177 packages loaded, 1368 targets configured)
FAILED: Build did NOT complete successfully (177 packages loaded, 1368 targets configured)
```

I'm using `disable_global` flag. I can see that grpc-gateway itself uses Bazel, and https://github.com/grpc-ecosystem/grpc-gateway/blob/v1.14.5/runtime/BUILD.bazel uses `go_default_library_gen` target.

I was checking out https://github.com/bazelbuild/bazel-gazelle/blob/master/language/go/resolve.go#L147, and thought this is the exact case being handled. I suppose it's a configuration mistake, but couldn't easily spot the error, or find any other reference around this.

**Comment by achew22** [comment]
What happens when you change it from a `go_repository` to an `http_archive`? We run `gazelle` in that repo on its own so go_repository shouldn't be necessary at all.

**Comment by jayconrod** [comment]
`github.com/grpc-ecosystem/grpc-gateway` has its own build files, so `go_repository` won't run Gazelle when fetching that repo. You can force it to update the build files by setting `build_file_generation = "on"`. I don't know if that will work for this repo though.

The `go_default_library_gen` targets are missing by the way because the patch `@io_bazel_rules_go//third_party:com_github_golang_protobuf-extras.patch` hasn't been applied to the repository `com_github_golang_protobuf`. You may not need that patch if you're using the `disable_global` proto mode everywhere though.

**Comment by rytswd** [comment]
@achew22 As far as I understand, `go_repository` for "Load Go dependencies" section is there to override the packages used by Gazelle itself. As to the rest of the `go_repository` lines at the bottom (from [this line onward](https://github.com/rytswd/simple-bazel/blob/issue/bazelbuild/bazel-gazelle/grpc-gateway-error/WORKSPACE#L82)), they are auto generated by Gazelle and I was under impression that it's doing some `http_archive` type of dependency resolution under the hood.

@jayconrod I tried both approaches, and the former one seems to have gotten me a bit further.
I thought overriding the BUILD file in `github.com/grpc-ecosystem/grpc-gateway` is the ultimate goal for me (provided the rest of the setup works with it), I tried `build_file_generation = "on"` attribute:

```starlark
go_repository(
    name = "com_github_grpc_ecosystem_grpc_gateway",
    build_file_generation = "on", ## NOTE: This is manually added, other lines were auto generated
    build_file_proto_mode = "disable_global",
    importpath = "github.com/grpc-ecosystem/grpc-gateway",
    sum = "h1:aiLxiiVzAXb7wb3lAmubA69IokWOoUNe+E7TdGKh8yw=",
    version = "v1.14.5",
)
```

This resulted with a different error about some missing dependencies:

```
$ bazel run simple-bazel
INFO: Analyzed target //:simple-bazel (25 packages loaded, 312 targets configured).
INFO: Found 1 target...
ERROR: (snip).../external/com_github_grpc_ecosystem_grpc_gateway/runtime/BUILD.bazel:5:1: GoCompilePkg external/com_github_grpc_ecosystem_grpc_gateway/runtime/darwin_amd64_stripped/go_default_library%/github.com/grpc-ecosystem/grpc-gateway/runtime.a failed (Exit 1) builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src external/com_github_grpc_ecosystem_grpc_gateway/runtime/context.go -src ... (remaining 73 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
        (snip).../sandbox/darwin-sandbox/91/execroot/com_github_rytswd_simple_bazel/external/com_github_grpc_ecosystem_grpc_gateway/runtime/errors.go: import of "github.com/grpc-ecosystem/grpc-gateway/internal"
        (snip).../sandbox/darwin-sandbox/91/execroot/com_github_rytswd_simple_bazel/external/com_github_grpc_ecosystem_grpc_gateway/runtime/handler.go: import of "github.com/grpc-ecosystem/grpc-gateway/internal"
        (snip).../sandbox/darwin-sandbox/91/execroot/com_github_rytswd_simple_bazel/external/com_github_grpc_ecosystem_grpc_gateway/runtime/proto_errors.go: import of "github.com/grpc-ecosystem/grpc-gateway/internal"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //:simple-bazel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 12.975s, Critical Path: 2.56s
INFO: 38 processes: 38 darwin-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

Is there anything else that could be done from Bazel / Gazelle side to handle this missing dependency? Or would this require further input from the repo?

**Comment by rytswd** [comment]
As a side note, as you mentioned, I use `disable_global` everywhere so the patch with `@io_bazel_rules_go//third_party:com_github_golang_protobuf-extras.patch` did not seem to be the main concern here. However, when I tried to use the patch regardless following [dependency override guideline](https://github.com/bazelbuild/rules_go/blob/af0f76b6b85b1a8776be82ee58d6a640c73c2111/go/dependencies.rst#overriding-dependencies), it gave me some error about applying the patches.

```starlark
go_repository(
    name = "com_github_golang_protobuf",
    build_file_proto_mode = "disable_global",
    importpath = "github.com/golang/protobuf",
    patch_args = ["-p1"], ## NOTE: I wasn't sure what this argument was supposed to be 
    patches = ["@io_bazel_rules_go//third_party:com_github_golang_protobuf-extras.patch"],
    sum = "h1:+Z5KGCizgyZCbGh1KZqA0fcLLkwbsjIzS4aV2v7wJX0=",
    version = "v1.4.2",
)
```

As the error is 700+ lines long, I saved it in a file https://github.com/rytswd/simple-bazel/blob/issue/bazelbuild/bazel-gazelle/grpc-gateway-error/issue-note/bazel-gazelle-788/patch-error.md.

**Comment by jayconrod** [comment]
> I tried both approaches, and the former one seems to have gotten me a bit further.
I thought overriding the BUILD file in github.com/grpc-ecosystem/grpc-gateway is the ultimate goal for me (provided the rest of the setup works with it), I tried build_file_generation = "on" attribute:
> ...
> This resulted with a different error about some missing dependencies:
> ...
> Is there anything else that could be done from Bazel / Gazelle side to handle this missing dependency? Or would this require further input from the repo?

I tried this in a test repo. The error messages indicate there are multiple libraries (`go_library` and `go_proto_library`) with the same `importpath`, so Gazelle can't resolve the dependencies.

I think your best bet here is to modify the build files to be the way you want them ahead of time, create a patch, and fetch the repository with `http_archive` using that patch. `go_repository` doesn't support a great deal of customization.

> As a side note, as you mentioned, I use disable_global everywhere so the patch with @io_bazel_rules_go//third_party:com_github_golang_protobuf-extras.patch did not seem to be the main concern here. However, when I tried to use the patch regardless following dependency override guideline, it gave me some error about applying the patches.

I missed that you're using rules_go `v0.22.2` in the description. That patch was intended to be used with `github.com/golang/protobuf@v1.3.3`. The errors are reported because it doesn't apply cleanly to `v1.4.2`. rules_go `v0.23.0` has a patch intended for protobuf `v1.4.1`, so that may be closer to what you want. Some further customization may be needed though.

**Comment by rytswd** [comment]
> I tried this in a test repo. The error messages indicate there are multiple libraries (go_library and go_proto_library) with the same importpath, so Gazelle can't resolve the dependencies.

Thanks for looking into this further, is [grpc-gateway's BUILD.bazel file](https://github.com/grpc-ecosystem/grpc-gateway/blob/db7fbefff7c04877cdb32e16d4a248a024428207/runtime/internal/examplepb/BUILD.bazel) what you are referring to as multiple library with same `importpath`?

It is fair how `go_repository` doesn't support so much customisation. I hope this can be tackled by the grpc-gateway team, and for now, I'll probably just not use this repo given the additional complexity.

> rules_go v0.23.0 has a patch intended for protobuf v1.4.1, so that may be closer to what you want. Some further customization may be needed though.

That did the trick, thanks!
