### ISSUE TITLE
language/go: automatically ignore files with _grpc.pb.go suffix

### ISSUE THREAD

**Issue by johanbrandhorst** [bazelbuild/bazel-gazelle#798]
### What version of gazelle are you using?

v0.21.1

### What version of rules_go are you using?

v0.23.2

### What version of Bazel are you using?

v3.2.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

Generating files using the new official grpc-go protoc plugin `protoc-gen-go-grpc` and ran gazelle on the output folder.

### What did you expect to see?

I expected gazelle to ignore files generated by `protoc-gen-go-grpc`, like it does files generated by `protoc-gen-go` (suffixed with `.pb.go`).

### What did you see instead?

Gazelle generates entries for the generated files in the `go_library`s in the same folder, causing double type definition errors when using the `go_library`.

### Workarounds

It's possible to fix today by adding
```
# gazelle:exclude xxx_grpc.pb.go
```
to the BUILD file manually and rerunning gazelle.

**Comment by jayconrod** [comment]
Adding this directive in the repository's root build file may be a simpler workaround:

```
# gazelle:exclude **_grpc.pb.go
```

More generally, Gazelle should recognize the `suffix` attribute of `go_proto_compiler` and exclude files appropriately when a compiler is in use. That will only work within the same repository though (Gazelle does not read build files in other repositories).

Gazelle should have hard coded support for the APIv1 and APIv2 generators and the gRPC generator when it's ready. rules_go needs support first though (bazelbuild/rules_go#2522).
