### ISSUE TITLE
Single `proto_library`?

### ISSUE THREAD

**Issue by amit-traiana** [bazelbuild/bazel-gazelle#799]
### What version of gazelle are you using?
v0.20.0

### What version of rules_go are you using?
0.21.4

### What version of Bazel are you using?
2.2.0

We have a big project that use multiple languages. Some BUILD files are being manually written, and some use Gazelle. When manually writing BUILD files, we follow the official documentation recommendation: 

`One proto_library rule per .proto file.`

So if I have 3 `.proto` files, each `.proto` file will have it own `proto_library`. Gazelle however, will create a single `proto_library` with all 3 `.proto` files in it. This inconsistency cause confusion among the teams. Lastly we have been struggling with some complex `rules_go` targets we write manually, and we were thinking on adapting the single `proto_library` structure. So I'm wondering why you guys picked a single `proto_library`, if there's a design decision around it we would be aware of that might cause future problems?

Thank you!

**Comment by jayconrod** [comment]
Agreed this should be done, but #138 is the tracking issue, so I'll close this one as a duplicate.

**Comment by amit-traiana** [comment]
Oh. Did a search and missed that issue. Thanks!
