### ISSUE TITLE
Generate go_proto_library with gRPC plugin

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#8]
We currently generate either `go_proto_library` or `go_grpc_library`, depending on whether .proto files have service declarations. `go_grpc_library` is now just a wrapper on `go_proto_library` with the grpc plugin, so we should generate that instead. We'll need to migrate existing instances.

We should avoid merging the `compiler` attribute in proto rules, since developers can set this to something else manually.

**Comment by ashi009** [comment]
I have a working prototype for this, which will generate `go_proto_library` with grpc complier.  However I didn't put much effort in supporting converting exiting `go_grpc_library` to `go_proto_library`.

I think this work needs to be prioritized, as it will allow people to actually benefit from the new `rules_go` release.
