### ISSUE TITLE
language/proto: inferred proto import paths wrong for subfolder roots

### ISSUE THREAD

**Issue by johanbrandhorst** [bazelbuild/bazel-gazelle#805]
### What version of gazelle are you using?

v0.21.1

### What version of rules_go are you using?

v0.23.3

### What version of Bazel are you using?

v3.2.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

Ran `gazelle` on proto hierarchy rooted in subfolder of repo root. Example hierarchy:
```
$ tree 
.
├── BUILD
├── LICENSE
├── proto                           # <- Proto root
│   ├── myorg
│   │   ├── blogs
│   │   │   └── v1
│   │   │       ├── blogs.proto     # <- Imports "myorg/users/v1/users.proto"
│   │   │       └── BUILD           # Has proto_library with deps = ["//myorg/users/v1:v1_proto"],
│   │   └── users                   # which doesn't resolve
│   │       └── v1
│   │           ├── BUILD.bazel
│   │           └── users.proto
├── repositories.bzl
└── WORKSPACE
```

### What did you expect to see?

Expected some way to configure the subfolder as a root for proto import path purposes. I tried setting the `gazelle:proto_import_prefix` directive to both `proto` and the repo url + `proto` and got the same error.

It works if I run

```shell
$ protoc --go_out=paths=source_relative:./proto -I proto ./proto/myorg/blogs/v1/blogs.proto
```

From the root of the repo.

### What did you see instead?

```
$ bazel build //...
ERROR: /root/proto/myorg/blogs/v1/BUILD:5:14: no such package 'myorg/users/v1': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /root/myorg/users/v1 and referenced by '//proto/myorg/blogs/v1:blogs_proto'
ERROR: Analysis of target '//proto/myorg/blogs/v1:blogs_proto' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.567s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 9 targets configured)
```

**Comment by jayconrod** [comment]
In theory, adding this to the root build file should work:

```
# gazelle:proto_strip_import_prefix /myorg
```

This should add `strip_import_prefix = "/myorg"` to generated `proto_library` rules, and it should index them correctly.

It seems like there are a couple bugs with this though. Working on a fix now.

**Comment by johanbrandhorst** [comment]
I assume you mean
```
# gazelle:proto_strip_import_prefix /proto
```
Which unfortunately still didn't work in my testing:
```shell
$ bazel build //proto/...
ERROR: /root/proto/myorg/blogs/v1/BUILD:5:14: no such package 'myorg/users/v1': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /root/myorg/users/v1 and referenced by '//proto/myorg/blogs/v1:blogs_proto'
ERROR: Analysis of target '//proto/myorg/blogs/v1:blogs_proto' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.308s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
```

Using
```
# gazelle:proto_strip_import_prefix /myorg
```
Gave me an error:
```
$ bazel run :gazelle
INFO: Analyzed target //:gazelle (62 packages loaded, 6946 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 1.211s, Critical Path: 0.12s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: invalid proto_strip_import_prefix "/myorg" at proto
```

**Comment by jayconrod** [comment]
Oops, yes, `/proto`.

**Comment by jayconrod** [comment]
Could you try out #806 and see if that fixes the problem?

If not, please post the `proto_library` rules from `proto/myorg/blogs/v1/BUILD.bazel` and `proto/myorg/users/v1/BUILD.bazel`.

**Comment by johanbrandhorst** [comment]
I can confirm that with #806 applied and using
```
# gazelle:proto_strip_import_prefix /proto
```
In a `BUILD` file in the `/proto` directory, the `deps` are created correctly, and `bazel build //proto/...` works :tada:. Great job!

**Comment by johanbrandhorst** [comment]
Can we tidy the `proto_strip_import_prefix` docs a little as part of this fix? If anything I was trying to use `proto_import_prefix` which wasn't helping things at all. It would be good to add this use case as an example.

**Comment by jayconrod** [comment]
Glad to hear it works.

Good point about the documentation. I just pushed another commit that adds a couple examples and mentions the need for a leading slash.
