### ISSUE TITLE
fix-update: only write changed build files to disk

### ISSUE THREAD

**Issue by blico** [bazelbuild/bazel-gazelle#807]
Currently, when `mode=fix` Gazelle unconditionally writes all build files that it visits to disk. Given the size of our repository (~30,000 build files), if Gazelle only writes changed build files back to disk, it would result in a significant performance improvement. A quick prototype shows this would speed up Gazelle runs from the root of our repository by ~20%.

Gazelle already reads every build file it visits into memory, so to implement we could simply cache the original contents of each file and then do a comparison with the final contents before `fixFile` writes out to disk.

If not all users want this feature enabled by default, we could potentially make a new `mode` for it (e.g. `fixOnChange`).

**Comment by jayconrod** [comment]
You can work around this by passing directories as positional arguments. Gazelle will only update build files in those directories (and subdirectories unless `-r=false`).

Skipping the write automatically would be better though. A 20% speedup would be very nice.
