### ISSUE TITLE
Support wildcards in resolve directives

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/bazel-gazelle#817]
This came up in discussion in #771.

Currently, `resolve` directives have two forms:

```
# gazelle:resolve lang import-string dep-string
# gazelle:resolve src-lang dep-lang import-string dep-string
```

We currently don't support any form of wildcard, so if a repository needs to use `resolve` directives for a large number of rules (for example, when using a custom naming convention or a large number of rules in a directory), it needs a large number of `resolve` directives, which can be very repetitively.

We should support some sort of wildcard in the `import-string` which could also appear in the `dep-string`. The simplest and most familiar way to do this would probably be to introduce a `resolve_regexp` directive, where `import-string` is a regular expression, and `dep-string` is something that could be passed to [`regexp.ReplaceAll`](https://pkg.go.dev/regexp?tab=doc#Regexp.ReplaceAll) (with `$1` and so on for matched groups).

**Comment by ChuntaoLu** [comment]
Hey, any update on this issue?
