### ISSUE TITLE
[Question] Resolving imports to generated code

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#821]
We have some custom code generation rules, e.g. 

```python
load("//tools/db:defs.bzl", "database")

database(
    name = "my_db",
    database_hcl = ":db.hcl",
    importpath = "my/db",
)
```

To have Gazelle resolve imports to "my/db", we currently use a `# gazelle:resolve` directive at the root of the sub-tree it's used in. I wanted to confirm that's the effective way, or see if there's a way to have it transparently work for users of the rules. 

The current solution is not onerous, but relatively few engineers are well-versed in Gazelle configuration since it "just works" the vast majority of the time, so it's a bonus if the developer that writes a custom rule can have it work for the callers of the rule with no additional configuration. 

Thanks!

**Comment by jayconrod** [comment]
How are `database` targets generated? If they're written by hand, then `# gazelle:resolve` is the best way to go; Gazelle has no other way to know this is an importable Go library.

If they're generated with an extension, the extension can return a slice including `resolve.ImportSpec{Lang: "go", Imp: "my/db"}` from the `Imports` method when it generates that target.

**Comment by robfig** [comment]
Those rules are written by hand. I'll keep that in mind in case we automate that, though. Thank you!
