### ISSUE TITLE
Support transitive runfiles from language plugins

### ISSUE THREAD

**Issue by greenboxal** [bazelbuild/bazel-gazelle#827]
### What version of gazelle are you using?

```
http_archive(
    name = "bazel_gazelle",
    sha256 = "bfd86b3cbe855d6c16c6fce60d76bd51f5c8dbc9cfcaef7a2bb5c1aafd0710e8",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.21.0/bazel-gazelle-v0.21.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.21.0/bazel-gazelle-v0.21.0.tar.gz",
    ],
)
```

### What version of rules_go are you using?

```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "87f0fb9747854cb76a0a82430adccb6269f7d394237104a4523b51061c469171",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.23.1/rules_go-v0.23.1.tar.gz",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.23.1/rules_go-v0.23.1.tar.gz",
    ],
)
```

### What version of Bazel are you using?

```
Build label: 3.3.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Jun 17 12:59:56 2020 (1592398796)
Build timestamp: 1592398796
Build timestamp as int: 1592398796
```

### Does this issue reproduce with the latest releases of all the above?

Yes.

### What did you do?

Custom languages should be able to depend on other tools, for example, a parser that can extract dependencies from source code. This is especially useful as it's unlikely a Go parser would exist, not mentioning compatibility issues.

Specifying `data` in `go_library` should be enough so runfiles are propagated to the gazelle runner:

```
# language/js/BUILD
go_library(
    name = "go_default_library",
    srcs = [
        "builtin.go",
        "config.go",
        "fileinfo.go",
        "generate.go",
        "generator.go",
        "language.go",
        "resolve.go",
        "resolver.go",
        "utils.go",
        "worker.go",
    ],
    data = [
        "@brex_rules_js//packages/import-parser",
    ],
    importpath = "github.com/brexhq/brex_rules_js/gazelle/language/js",
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_gazelle//config:go_default_library",
        "@bazel_gazelle//label:go_default_library",
        "@bazel_gazelle//language:go_default_library",
        "@bazel_gazelle//language/proto:go_default_library",
        "@bazel_gazelle//repo:go_default_library",
        "@bazel_gazelle//resolve:go_default_library",
        "@bazel_gazelle//rule:go_default_library",
        "@io_bazel_rules_go//go/tools/bazel:go_default_library",
        "@org_golang_x_sync//errgroup:go_default_library",
    ],
)
```

### What did you expect to see?

Runfiles to be available during runtime so the following code works:

```go
import "github.com/bazelbuild/rules_go/go/tools/bazel"
parser, err := bazel.Runfile("brex_rules_js/packages/import-parser/import-parser.sh")
```

### What did you see instead?

Runfiles from the `gazelle_binary` are not merged into `gazelle_runner`.

**Comment by greenboxal** [comment]
Opened #828 as a proposed solution that works.

**Comment by joneshf** [comment]
This looks to have been closed and the [accompanying commit](https://github.com/bazelbuild/bazel-gazelle/commit/ae9e256f5b88f757dd094d999ebf5e2012aa6939) states that it fixes this issue, but I cannot seem to get runfiles to work. I'm supplying a `data` attribute to my `go_library` importing `"github.com/bazelbuild/rules_go/go/tools/bazel"` and calling [`bazel.RunfilesPath`](https://pkg.go.dev/github.com/bazelbuild/rules_go/go/tools/bazel#RunfilesPath), but I end up getting an error when running: `gazelle: could not locate runfiles directory`. Am I missing some other piece, or did this accidentally get closed by the other commit?
