### ISSUE TITLE
Ignoring vendor folders in dependencies

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#833]
Using Gazelle 0.23.2, importing contrib.go.opencensus.io/exporter/prometheus results in a BUILD file that uses its vendor directory, e.g.

```
# external/com_github_prometheus_statsd_exporter/pkg/mapper/BUILD.bazel

go_library(
    name = "go_default_library",
    srcs = [
        "action.go",
        "escape.go",
        "mapper.go",
        "mapper_cache.go",
        "mapper_defaults.go",
        "mapping.go",
        "match.go",
        "metric_type.go",
        "observer.go",
    ],
    importpath = "github.com/prometheus/statsd_exporter/pkg/mapper",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/mapper/fsm:go_default_library",
        "//vendor/github.com/hashicorp/golang-lru:go_default_library",
        "//vendor/github.com/prometheus/client_golang/prometheus:go_default_library",
        "//vendor/github.com/prometheus/common/log:go_default_library",
        "//vendor/gopkg.in/yaml.v2:go_default_library",
    ],
)
```

This results in a panic on startup:
```
panic: proto: duplicate enum registered: io.prometheus.client.MetricType

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
   external/com_github_golang_protobuf/proto/properties.go:458
github.com/prometheus/statsd_exporter/vendor/github.com/prometheus/client_model/go.init.0()
   external/com_github_prometheus_statsd_exporter/vendor/github.com/prometheus/client_model/go/metrics.pb.go:663 +0x332
```

The reason is that the prometheus client includes protobufs, which register their enums in a global registry on init, and so the vendored prometheus client conflicts with our separately imported one.

I believe I can work around this by adding a `-exclude vendor` flag on the go_repository, but I wanted to ask about this behavior. My impression was that the updated behavior with Go Modules is to only use vendor directories if they are on the module that's being built, and it would ignore vendor directories on imported libraries. I think this is different from what it did in GOPATH mode. Assuming I have that right, then I wanted to see if Gazelle's behavior should be updated for consistency.

Cheers

**Comment by robfig** [comment]
Ah, I see the note you have on build_external here
https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go_repository

So I'm sure you've thought of this. Closing

**Comment by jayconrod** [comment]
How is the `go_repository` declared? If it's in module mode (with `version` and `sum`), the vendor directory shouldn't even be presented in the repo directory, and Gazelle shouldn't be able to generate rules that point to it. I'm surprised `build_external` would be needed.

(Well, to be pedantic, the `vendor` directory might be present, but it won't contain any packages).

**Comment by robfig** [comment]
Oh, interesting. I didn't realize that activated module mode. 

We still use a GLOCKFILE as the source of truth and generate rules from that, e.g.:

```
    go_repository(
        name = "com_github_gorilla_websocket",
        commit = "0ec3d1bd7fe50c503d6df98ee649d81f4857c564",
        importpath = "github.com/gorilla/websocket",
    )
```

I'm not sure if I can switch to using version/sum, since GLOCKFILE has just the commit shas. We still use a GLOCKFILE so that Go CLI continues working, since it's more pleasant to use that for development tasks (e.g. running benchmarks) and gopls doesn't support bazel yet afaik.

Thanks for the explanation!
