### ISSUE TITLE
Generate repo-cache friendly `go_repository` using `update-repos`

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel-gazelle#852]
When gazelle generates `go_repository` from `go.mod`, it uses `importpath` and `sum` to identifies an external go module dependency. However, it depends on go toolchain to download those module files, and therefore escaped bazel's repository cache mechanism. When there are network access restrictions or an intranet build is required, this behavior is undesirable.

We used to manually convert those generated rules with `go_repository` rules with tarball URLs and hashes. It would be nice to have gazelle to generate them during `update-repos`.

**Comment by jayconrod** [comment]
`go_repository` stores downloaded modules in a separate workspace, `@bazel_gazelle_go_repository_cache`, to avoid polluting the user's module cache.

It sounds like this is more about configuring the module download though? `go_repository` should respect the environment variables `GOPROXY`, `GONOPROXY`, `GOPRIVATE`, `GOSUMDB`, and `GONOSUMDB`. Others can be added if needed. Changing those should not invalidate the cache though, so you might need to run `bazel clean --expunge` after changing them to verify something can still be downloaded.

Does that solve your problem? I'm probably not going to support generating `go_repository` in HTTP mode with `update-repos`. I think you can accomplish the same things by setting those environment variables though.

**Comment by ashi009** [comment]
What we really want is to have everything cached in repo-cache, and letting CI machines to build without any internet access. We can easily (almost) do that before go module landed, but not so lucky with the current approach.

**Comment by jayconrod** [comment]
Couple things you could do here.

1. You could make a read-only copy of a module cache on disk, then set `GOPROXY` to point to it with a file URL (`GOPROXY=file:///var/modcache/pkg/mod/cache/download`). `go_repository` should "download" modules from that directory and fail if anything's missing.
2. You could stand up an HTTP file server with that same content and set `GOPROXY` to that server's URL.
3. You could set `GO_REPOSITORY_USE_HOST_CACHE=1` in the environment and set `GOPROXY=off`. `go_repository` will use the cache in `$GOPATH/pkg/mod`. This method may be less reliable.

You'll probably want to set `GOSUMDB=off` in all these cases.

**Comment by ashi009** [comment]
I'm reading https://golang.org/ref/mod#tmp_47, is it possible to put those module zip there? then have the go tool to extract them? Which is both repo friendly and go module cache friendly.

**Comment by jayconrod** [comment]
That's what setting `GOPROXY` would do. `go_repository` will download module zip files from that location and extract them into the module cache. `go_repository` itself will not handle zip files directly; it will only do so through `go mod download`.

**Comment by ashi009** [comment]
Sorry I didn't make myself clear. I'm wondering if we can use `ctx.download` to download the module zip directly, which will allow bazel to handle the cache. `GOPROXY` and other environment variables will be captured at the phase of generating the `go_repository` rules.

For instance:

```
    go_repository(
        name = "com_github_yuin_goldmark",
        importpath = "github.com/yuin/goldmark",
        sum = "h1:ruQGxdhGHe7FWOJPT0mKs5+pD2Xs1Bm/kdGlHO04FmM=",
        version = "v1.2.1",
    )
```

Could be:

```
    go_repository(
        name = "com_github_yuin_goldmark",
        importpath = "github.com/yuin/goldmark",
		url = "https://proxy.golang.org/github.com/yuin/goldmark/@v/v1.2.1.zip",
        sha256 = "e07c8cb16aa0b42dc9eaf0f922e25e330af3a39d8e8404c8c6e04bba406aa7b2",
        module = True,
    )
```

Once bazel downloaded the file, the repository rule could populate the module cache with the extracted data.

**Comment by jayconrod** [comment]
> I'm wondering if we can use ctx.download to download the module zip directly, which will allow bazel to handle the cache.

No, sorry. You can accomplish the same thing by setting those environment variables.

**Comment by ashi009** [comment]
Sigh. Guess that I have to set up another cache for this job then.
