### ISSUE TITLE
Gazelle fails to compile code that uses protobuf APIv2 with the "any" protobuf well-known-type

### ISSUE THREAD

**Issue by pjjw** [bazelbuild/bazel-gazelle#858]
Hey, got a codebase where we're straddling using the standard Go build tools and using Bazel. We just switched away from using gogoproto for reasons, and in the process, can no longer build parts of the codebase, specifically anything using the Go import `"google.golang.org/protobuf/types/known/anypb"`. Standard toolchain is fine, but Bazel claims undefined references. It seems like the v2 API we're using is not available.

I'm putting this issue here in Gazelle as this is the topmost tool in the chain, as I'm trusting it to write BUILD files that work, but it seems like there might be parts of the mess that stretch deeper.

I've extracted the minimal set of code that fails into pjjw/anygazelle for easy testing.

Please let me know if I'm doing anything wrong here!

### What version of gazelle are you using?
0.21.1

### What version of rules_go are you using?
0.23.6

### What version of Bazel are you using?
3.3.1, 3.4.1

### Does this issue reproduce with the latest releases of all the above?

Yes. 

### What operating system and processor architecture are you using?

macos catalina x64

### What did you do?

Clone https://github.com/pjjw/anygazelle. Run test.sh

### What did you expect to see?

Expected a successful build, first with the standard go tools, then with Bazel, after a Gazelle run.

### What did you see instead?
```
$ bazel build //... --sandbox_debug                                                                                                                                     08:27:17
INFO: Analyzed target //:go_default_library (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/peter.woodman/src/fuct/BUILD.bazel:24:11: GoCompilePkg go_default_library.a failed (Exit 1) process-wrapper failed: error executing command 
  (cd /private/var/tmp/_bazel_peter.woodman/bdddef2c6de5577d7cdd00baffba8ef0/sandbox/processwrapper-sandbox/115/execroot/__main__ && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    CGO_ENABLED=1 \
    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
    GOARCH=amd64 \
    GOOS=darwin \
    GOPATH='' \
    GOROOT=external/go_sdk \
    GOROOT_FINAL=GOROOT \
    PATH=external/local_config_cc:/bin:/usr/bin \
    SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk \
    TMPDIR=/var/folders/9h/xl_fqf517h1g7wwfv5zz9gw40000gp/T/ \
    XCODE_VERSION_OVERRIDE=11.6.0.11E708 \
  /var/tmp/_bazel_peter.woodman/install/eb682cee8e49c9648bde5ea9374b8a8b/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix darwin_amd64 -src anygazelle.go -arc 'google.golang.org/protobuf/proto=google.golang.org/protobuf/proto=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/proto/go_default_library.a=' -arc 'google.golang.org/protobuf/types/known/anypb=google.golang.org/protobuf/types/known/anypb=bazel-out/darwin-fastbuild/bin/external/org_golang_google_protobuf/types/known/anypb/go_default_library.a=' -importpath github.com/pjjw/anygazelle -p github.com/pjjw/anygazelle -package_list bazel-out/host/bin/external/go_sdk/packages.txt -o bazel-out/darwin-fastbuild/bin/go_default_library.a -gcflags '' -asmflags '')
compilepkg: error running subcommand: exit status 2
/private/var/tmp/_bazel_peter.woodman/bdddef2c6de5577d7cdd00baffba8ef0/sandbox/processwrapper-sandbox/115/execroot/__main__/anygazelle.go:13:14: undefined: anypb.UnmarshalNew
Target //:go_default_library failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.176s, Critical Path: 0.06s
INFO: 0 processes.
```

**Comment by jayconrod** [comment]
The relevant error is:

```
anygazelle.go:13:14: undefined: anypb.UnmarshalNew
```

In rules_go `v0.23.6`, `go_rules_dependencies` declares a dependency on `org_golang_google_protobuf` at `v1.22.0`. The function `UnmarshalNew` is not defined in that version.

If you want to use a newer version, see [Overriding dependencies](https://github.com/bazelbuild/rules_go/blob/master/go/dependencies.rst#overriding-dependencies).

In general, each minor release of rules_go updates the default set of dependencies. Minor releases go out roughly every quarter, and the next release should be some time this month.

**Comment by pjjw** [comment]
thanks for the tip! didn't realize this was special-cased, thought gazelle was handling it entirely. really saved me some time, thank you again!
