### ISSUE TITLE
Gazelle over eagerly prune compilers list in go_proto_library

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/bazel-gazelle#86]
When multiple compilers are specified for a proto, gazelle removes them.

I assume the fix here would be adding `# keep` to the end of additional compilers.  Is this an intended behavior?

```
go_proto_library(
    name = "repo_go_proto",
    compilers = [
        "@io_bazel_rules_go//proto:go_grpc",
        "@io_bazel_rules_go//proto:go_grpc_gateway",
    ],
    importpath = "example.com/repo",
    proto = ":repo_proto",
    visibility = ["//visibility:public"],
)
```

becomes

```
go_proto_library(
    name = "repo_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "example.com/repo",
    proto = ":repo_proto",
    visibility = ["//visibility:public"],
)
```

**Comment by jayconrod** [comment]
This should probably work differently. `compilers` should probably be a non-mergeable attribute like `visibility`: Gazelle should set if needed when not present, but it shouldn't change a value that's already there.

The intent of making it mergeable initially was to remove the `go_grpc` compiler when service definitions are removed.
