### ISSUE TITLE
Using mod version in update-repos command results in always asking for latest version.

### ISSUE THREAD

**Issue by entersb** [bazelbuild/bazel-gazelle#878]
### What version of gazelle are you using?

0.18.1

### What version of rules_go are you using?

0.19.1

### What version of Bazel are you using?

2.2.0

### Does this issue reproduce with the latest releases of all the above?

No, but it reproduces all other sort issue that simple change of gazelle version cannot help with.

### What operating system and processor architecture are you using?

Linux Mint 19.2, x86.

### What did you do?

I am trying to use specific version for grpc. When I run `bazelisk run //:gazelle -- update-repos google.golang.org/grpc@1.27.0`.

### What did you expect to see?

Successfully update version to specific one.

### What did you see instead?

```
INFO: Analyzed target //:gazelle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 0.171s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: finding module version and sum for google.golang.org/grpc@1.27.0@latest: exit status 1: go: finding google.golang.org/grpc 1.27.0@latest
go: finding google.golang.org/grpc 1.27.0@latest

```

**Comment by jayconrod** [comment]
This doesn't reproduce in the latest version of Gazelle, and 0.18.x is no longer supported.

You said this reproduces other issues that aren't resolved by upgrading Gazelle. What are they? What's blocking you from upgrading?

**Comment by entersb** [comment]
Thanks for your answer.

I managed to upgrade to latest gazelle version.

Some grpc modules where misbehaving but using correct version (in this case `google.golang.org/grpc@1.29.1`) solve all issues I got with initial try.

Some other modules had issue too with go1.13+ but managed to solve those too.

I am closing this issue as not relevant any more.
