### ISSUE TITLE
go_naming_convention_extern -> go_naming_convention_external

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/bazel-gazelle#886]
https://github.com/bazelbuild/bazel-gazelle#directives says the directive name is `gazelle:go_naming_convention_extern` but its `go_naming_convention_external` in code.

```
gazelle: ....../BUILD.bazel: unknown directive: gazelle:go_naming_convention_extern
```

**Comment by jayconrod** [comment]
Thanks, fixed.
