### ISSUE TITLE
Error: 'NoneType' value has no field or method 'libs' on 0.22.0

### ISSUE THREAD

**Issue by johanbrandhorst** [bazelbuild/bazel-gazelle#896]
### What version of gazelle are you using?

0.22.0

### What version of rules_go are you using?

0.22.4

### What version of Bazel are you using?

3.5.0

### Does this issue reproduce with the latest releases of all the above?

Unknown, cannot update `rules_go` due to #780

### What operating system and processor architecture are you using?

Linux amd64

### What did you do?

I ran
```
bazel run //:gazelle
```

### What did you expect to see?

No error

### What did you see instead?

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //:gazelle (1 packages loaded, 0 targets configured)
ERROR: /root/.cache/_grpc_gateway_bazel/external/bazel_gazelle/cmd/gazelle/BUILD.bazel:4:15: in gazelle_binary rule @bazel_gazelle//cmd/gazelle:gazelle: 
Traceback (most recent call last):
	File "/root/.cache/_grpc_gateway_bazel/external/bazel_gazelle/cmd/gazelle/BUILD.bazel", line 4
		gazelle_binary(name = 'gazelle')
	File "/root/.cache/_grpc_gateway_bazel/external/bazel_gazelle/internal/gazelle_binary.bzl", line 57, in _gazelle_binary_impl
		go.binary(go, <4 more arguments>)
	File "/root/.cache/_grpc_gateway_bazel/external/io_bazel_rules_go/go/private/actions/binary.bzl", line 41, in go.binary
		go.archive(go, source)
	File "/root/.cache/_grpc_gateway_bazel/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 114, in go.archive
		emit_compilepkg(go, <10 more arguments>)
	File "/root/.cache/_grpc_gateway_bazel/external/io_bazel_rules_go/go/private/actions/compilepkg.bzl", line 62, in emit_compilepkg
		go.stdlib.libs
'NoneType' value has no field or method 'libs'
ERROR: Analysis of target '//:gazelle' failed; build aborted: Analysis of target '@bazel_gazelle//cmd/gazelle:gazelle' failed
```
See https://app.circleci.com/pipelines/github/grpc-ecosystem/grpc-gateway/1182/workflows/9c697a61-2d00-4dc4-a76f-5c8e79ca57c6/jobs/15221 for full logs, and https://github.com/grpc-ecosystem/grpc-gateway/pull/1325 for full context of updates.

**Comment by jayconrod** [comment]
Sorry for the slow response. It's been a very busy week. #906 should fix this.

**Comment by jayconrod** [comment]
#780 is fixed now, too. Let me know if anything else is blocking you.

**Comment by johanbrandhorst** [comment]
How can I best test a pre-release version? I tried using
```
http_archive(
    name = "bazel_gazelle",
    sha256 = "4374742f5782d1a957f8059bf325f1f062a21b3724957633f33b64bd04cf469b",
    urls = [
        "https://github.com/bazelbuild/bazel-gazelle/archive/19c48642ee1f021814846655e78e3cee7871d3e2.tar.gz",
    ],
)
```
But it gave me an error:
```
$ bazel build //:gazelle
ERROR: error loading package '': Every .bzl file must have a corresponding package, but '@bazel_gazelle//:deps.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
INFO: Elapsed time: 0.045s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by jayconrod** [comment]
The archives generated by GitHub have an extra top-level directory, so you'll need to add:

```
    strip_prefix = "bazel-gazelle-19c48642ee1f021814846655e78e3cee7871d3e2",
```

**Comment by johanbrandhorst** [comment]
I can confirm that
```
http_archive(
    name = "bazel_gazelle",
    sha256 = "4374742f5782d1a957f8059bf325f1f062a21b3724957633f33b64bd04cf469b",
    strip_prefix = "bazel-gazelle-19c48642ee1f021814846655e78e3cee7871d3e2",
    urls = [
        "https://github.com/bazelbuild/bazel-gazelle/archive/19c48642ee1f021814846655e78e3cee7871d3e2.tar.gz",
    ],
)
```
Fixes the issue with `bazel build //:gazelle`. Thanks! As a sidenote, v1 of the grpc-gateway is going to have to stay on `rules_go` `v0.22.4` since it's the last version using the golang/protobuf APIv1 stack and we've committed to not changing that, so I understand that upgrading `bazel_gazelle` will eventually lead to an incompatibility down the line.

**Comment by jayconrod** [comment]
> As a sidenote, v1 of the grpc-gateway is going to have to stay on rules_go v0.23.8 since it's the last version using the golang/protobuf APIv1 stack and we've committed to not changing that, so I understand that upgrading bazel_gazelle will eventually lead to an incompatibility down the line.

I'm worried about this. rules_go v0.22.x is no longer maintained and is not receiving Go security updates. What's blocking the upgrade exactly?

rules_go v0.23.x and later declare repositories for both `com_github_golang_protobuf` (APIv1) and `org_golang_google_protobuf` (APIv2). The APIv1 version is a wrapper around APIv2, so it should be safe to use both APIs in a mixed project. `go_proto_library` generates code using APIv1, so that code should be backward and forward compatible.

**Comment by johanbrandhorst** [comment]
We can't upgrade to golang/protobuf v1.4.2 without breaking out external interface (which uses the proto.Message interface). It is also somewhat compatible with gogo/protobuf, something which is impossible with golang/protobuf v1.4.2. The gateway project therefore decided to stay on 1.3.x for v1 and move to implement v2 ASAP. Most of that work is done, and we'll be tagging a stable v2 release as soon as `protoc-gen-go-grpc` is stable (probably in reality as soon as bazel allows us to use a stable version of it).
