### ISSUE TITLE
go_repository dependency parsing not working for most importpath ending with "/v2"

### ISSUE THREAD

**Issue by MewX** [bazelbuild/bazel-gazelle#900]
### What version of gazelle are you using?
v0.22.0 (latest)

### What version of rules_go are you using?
v0.24.1

### What version of Bazel are you using?
v3.5.0

### Does this issue reproduce with the latest releases of all the above?
Yes, reproducable.

### What operating system and processor architecture are you using?
Debian/Ubuntu

### What did you do?

Adding this repository (one of the most popular go cli libs):

```
go_repository(
    name = "urfav_cli",
    importpath = "github.com/urfave/cli/v2",
    # Get hash via: go mod download -json github.com/urfave/cli/v2@v2.2.0
    sum = "h1:JTTnM6wKzdA0Jqodd966MVj4vWbbquZykeX1sKbe2C4=",
    version = "v2.2.0",
)
```

### What did you expect to see?
Building successfully.

### What did you see instead?

```
$ bazel build :kantv
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: /home/mewx/.cache/bazel/_bazel_mewx/9f92c5f8031c909d96e57ce5cd0c7096/external/urfav_cli/BUILD.bazel:3:11: no such package '@com_github_cpuguy83_go_md2man_v2//md2man': The repository '@com_github_cpuguy83_go_md2man_v2' could not be resolved and referenced by '@urfav_cli//:cli'
ERROR: Analysis of target '//:kantv' failed; build aborted: Analysis failed
INFO: Elapsed time: 49.686s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (41 packages loaded, 6941 targets configured)
```

### Reason
Dependency declared in go.mod file is like this:

```
module github.com/urfave/cli/v2

go 1.11

require (
	github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
	...
)
```

Recursively, the go.mod in cpuguy83/go-md2man/v2 looks like this:

```
module github.com/cpuguy83/go-md2man/v2

go 1.11

require (
	...
	github.com/russross/blackfriday/v2 v2.0.1
	github.com/shurcooL/sanitized_anchor_name v1.0.0 // indirect
)
```

### Mitigation

**This is what we shouldn't do.**

Adding these missing `/v2` libraries manually:

```
# This module is explicitly referenced by urfav_cli.
go_repository(
    name = "go-md2man",
    importpath = "github.com/cpuguy83/go-md2man/v2",
    sum = "h1:EoUDS0afbrsXAZ9YQ9jdu/mZ2sXgT1/2yyNng4PGlyM=",
    version = "v2.0.0",
)

# This module is explicitly referenced by go-md2man.
go_repository(
    name = "blackfriday",
    importpath = "github.com/russross/blackfriday/v2",
    sum = "h1:lPqVAte+HuHNfhJ/0LC98ESWRz8afy9tM/0RK8m9o+Q=",
    version = "v2.0.1",
)

# This module is explicitly referenced by go-md2man.
# If not present, getting this error:
# > The repository '@com_github_shurcool_sanitized_anchor_name' could not be resolved and referenced by '@blackfriday//:blackfriday'
go_repository(
    name = "sannitized_anchor_name",
    importpath = "github.com/shurcooL/sanitized_anchor_name",
    sum = "h1:PdmoCO6wvbs+7yrJyMORt4/BmY5IYyJwS/kOiWx8mHo=",
    version = "v1.0.0",
)
```

Sample projectd: https://github.com/MewX/KanTV-downloader-cli/blob/master/WORKSPACE#L39-L61

**Comment by MewX** [comment]
I checked with go build recommendations: https://blog.golang.org/v2-go-modules

These 3rd party libraries didn't follow the best practices.

However, I believe these non-standard go modules are the majoirity in open source communities (even with 14k+ stars).

I wonder if Gazelle should use the information from `go mod download`.

**Comment by jayconrod** [comment]
You need a `go_repository` declaration for each module that provides packages needed to build your targets; direct dependencies aren't enough. Each `go_repository` only fetches one module, and `go_repository` ignores `go.mod` files.

You don't need to write those manually though. The command below should generate or update `go_repository` declarations for each module in the build list.

```
bazel run :gazelle -- update-repos -from_file=go.mod
```

**Comment by MewX** [comment]
I see. Thanks for the command!

It turned out I didn't understand the mechanism correctly.
