### ISSUE TITLE
language/go: generated library name same as source file name

### ISSUE THREAD

**Issue by asv** [bazelbuild/bazel-gazelle#903]
### What version of gazelle are you using?

v0.22.0

### What version of rules_go are you using?

v0.24.1

### What version of Bazel are you using?

v3.3.1 (but on v3.5.0 also reproduced)

### Does this issue reproduce with the latest releases of all the above?

I only tried on the latest release.

### What operating system and processor architecture are you using?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

```
$ uname -a
Linux asmirnov 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### What did you do?

repro repo: https://github.com/asv/rules_go_cycle_bug

```
$ bazel build //pkg/pubsub/...
```

### What did you expect to see?

A successfully completed build command.

### What did you see instead?

```
$ bazel build //pkg/pubsub/...
ERROR: /home/asmirnov/.cache/bazel/_bazel_asmirnov/7dba41bc404cf3230b6d76cff81a3467/external/com_github_nats_io_stan_go/BUILD.bazel:3:11: in go_library rule @com_github_nats_io_stan_go//:stan.go: cycle in dependency graph:
    //pkg/pubsub:go_default_library
    @com_github_nats_io_stan_go//:go_default_library
.-> @com_github_nats_io_stan_go//:stan.go [self-edge]
`--
This cycle occurred because of a configuration option
ERROR: Analysis of target '//pkg/pubsub:go_default_library' failed; build aborted
INFO: Elapsed time: 0.149s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 2 targets configured)
```

**Comment by jayconrod** [comment]
The generated library looks like this:

```
go_library(
    name = "stan.go",
    srcs = [
        "stan.go",
        "sub.go",
    ],
    importpath = "github.com/nats-io/stan.go",
    visibility = ["//visibility:public"],
    deps = [
        "//pb",
        "@com_github_nats_io_nats_go//:nats.go",
        "@com_github_nats_io_nuid//:nuid",
    ],
)
```

They have a source file with the same name as the last component of their import path, so Bazel can't distinguish between the library name and the source file name.

We should adjust the naming convention to replace dots with underscores in target names.
