### ISSUE TITLE
doc: add minimum supported Go version to README

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/bazel-gazelle#917]
v0.22.0 seems to work but not v0.22.1

### What version of gazelle are you using?

v0.22.1

### What version of rules_go are you using?

v0.23.4

### What version of Bazel are you using?

3.5.0

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS 10.15.6 (19G2021)

### What did you do?

Followed instructions in the README.

### What did you expect to see?

gazelle succeeds

### What did you see instead?

$ bazel run //:gazelle
INFO: Repository bazel_gazelle_go_repository_tools instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule go_repository_tools defined at:
  /private/var/tmp/_bazel_gar/29372927b20ca936dc9ab48a0d65e05d/external/bazel_gazelle/internal/go_repository_tools.bzl:117:38: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_tools':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_gar/29372927b20ca936dc9ab48a0d65e05d/external/bazel_gazelle/internal/go_repository_tools.bzl", line 103, column 13, in _go_repository_tools_impl
		fail("failed to build tools: " + result.stderr)
Error in fail: failed to build tools: # github.com/bazelbuild/bazel-gazelle/language/go
src/github.com/bazelbuild/bazel-gazelle/language/go/modules.go:200:6: undefined: errors.As
ERROR: /private/var/tmp/_bazel_gar/29372927b20ca936dc9ab48a0d65e05d/external/bazel_gazelle/cmd/gazelle/BUILD.bazel:10:11: no such package '@com_github_pmezard_go_difflib//difflib': no such package '@bazel_gazelle_go_repository_config//': no such package '@bazel_gazelle_go_repository_tools//': failed to build tools: # github.com/bazelbuild/bazel-gazelle/language/go
src/github.com/bazelbuild/bazel-gazelle/language/go/modules.go:200:6: undefined: errors.As
 and referenced by '@bazel_gazelle//cmd/gazelle:gazelle_lib'
ERROR: Analysis of target '//:gazelle' failed; build aborted: Analysis failed

**Comment by jayconrod** [comment]
What version of Go are you using?

`errors.As` was introduced in Go 1.13. The oldest supported version is Go 1.14.

**Comment by mobileink** [comment]
On Tue, Sep 29, 2020 at 9:26 AM Jay Conrod <notifications@github.com> wrote:

> What version of Go are you using?
>
$ go version
go version go1.12.17 darwin/amd64


> errors.As was introduced in Go 1.13. The oldest supported version is Go
> 1.14.
>

Might want to mention that in the README.

Thanks,

G

**Comment by jayconrod** [comment]
The policy comes from [Release Policy](https://golang.org/doc/devel/release.html#policy), which covers Go itself and projects we directly support.

I'll leave this open. Makes sense to put it in the Gazelle README, too.

**Comment by mobileink** [comment]
On Wed, Sep 30, 2020 at 11:06 AM Jay Conrod <notifications@github.com>
wrote:

> Closed #917 <https://github.com/bazelbuild/bazel-gazelle/issues/917> via
> #920 <https://github.com/bazelbuild/bazel-gazelle/pull/920>.
>
Cool.  Newbies will thank you.
