### ISSUE TITLE
keep directives are getting rewritten incorrectly

### ISSUE THREAD

**Issue by kargakis** [bazelbuild/bazel-gazelle#92]
Reproducer:

$ Clone [this](https://github.com/kargakis/test-infra/tree/keep-repro) branch.
$ ./hack/update-bazel.sh
$ git diff

**Comment by jayconrod** [comment]
Here's what I'm seeing when I run the whole script:

```
diff --git a/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD b/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD
index a858efc45..c4f246b7c 100644
--- a/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD
+++ b/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD
@@ -67,8 +67,8 @@ proto_library(
     deps = [
         "//vendor/k8s.io/apimachinery/pkg/runtime:runtime_proto",
         "//vendor/k8s.io/apimachinery/pkg/runtime/schema:schema_proto",
-        "//vendor/k8s.io/apimachinery/pkg/util/intstr:intstr_proto",
-    ], # keep
+        "//vendor/k8s.io/apimachinery/pkg/util/intstr:intstr_proto",  # keep
+    ],
 )
 
 go_proto_library(
```

I think the `# keep` comment is being moved by kazel, not by gazelle. Here's the diff I see when commenting out kazel and only running Gazelle:

```
diff --git a/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD b/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD
index a858efc45..48d76705e 100644
--- a/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD
+++ b/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/BUILD
@@ -68,7 +68,7 @@ proto_library(
         "//vendor/k8s.io/apimachinery/pkg/runtime:runtime_proto",
         "//vendor/k8s.io/apimachinery/pkg/runtime/schema:schema_proto",
         "//vendor/k8s.io/apimachinery/pkg/util/intstr:intstr_proto",
-    ], # keep
+    ],  # keep
 )
 
 go_proto_library(
```

cc @mikedanese Any idea what might cause this?

**Comment by ixdy** [comment]
I think this is a bug in the buildifer library we are using, which is probably about a year old or so.

We recently transitioned kubernetes/repo-infra to dep, which also updated the buildifier dependency (to https://github.com/bazelbuild/buildtools/commit/1a9c38e0df9397d033a1ca535596de5a7c1cf18f), and the erroneous movement of the keep comment no longer occurs if I use this version.

I'll update the version of kazel we're using.

**Comment by jayconrod** [comment]
@ixdy Sounds good. Gazelle also uses that library, I think at a fairly recent version, so it must be a buildifier bug that was fixed.

I'll close this issue since I don't think there's anything to do on the Gazelle side.
