### ISSUE TITLE
gazelle update-repos could support on-disk replace directives

### ISSUE THREAD

**Issue by dragonsinth** [bazelbuild/bazel-gazelle#921]
### What version of gazelle are you using?

0.22.0

### What version of rules_go are you using?

0.24.2

### What version of Bazel are you using?

3.1.0

### What did you do?

`gazelle update-repos -prune -from_file=go.mod -to_macro=go_repositories.bzl%go_repositories`

### What did you expect to see?

```bzl
    # gazelle:repository go_repository name=com_github_throttled_throttled importpath=github.com/throttled/throttled
    native.local_repository(
        name = "com_github_throttled_throttled",
        path = "go/src/github.com/throttled/throttled",
    )
```

### What did you see instead?

```
gazelle: go_repository does not support file path replacements for github.com/throttled/throttled -> ./go/src/github.com/throttled/throttled
```

###

After a bit of digging, I figured out how to manually setup our on-disk go.mod replace entries with bazel rules.  But I can't think of any reason gazelle update-repos couldn't do this for me?  (It would still be on me to actually add WORKSPACE and BUILD.bazel files to the on-disk dependency, and run gazelle itself within the third party folder.)

**Comment by dragonsinth** [comment]
BTW: totally happy to submit a PR for this idea if it's something that we'd be willing to add.

**Comment by jayconrod** [comment]
Sorry, I'd rather not support this.

It would be easy enough to translate directory `replace` directives to `local_repository` declarations. However, those declarations are unlikely to work automatically since build files won't be generated. I don't think we could really have a complete solution there, and I'd expect a lot of confused users and bug reports. Better to keep things simple: declarations that require manual maintenance should be added manually.

I'm open to changes that would make `local_repository` more ergonomic to use. For example, `update-repos` could suppress the warning about not supporting file path replacements if a `gazelle:repository` directive is already present for that module. If that would be sufficient, let me know.

**Comment by dragonsinth** [comment]
That sounds super reasonable-- especially if the existing `go_repository does not support file path replacements` could point the developer in the right direction!  Trying to figure out the right formulation to do what I needed (correctly) took me quite a lot of struggle.  It's almost certain that anyone dealing with go.mod file replacements will need a formulation of gazelle:repository + local_repository to mimic their existing build.

**Comment by billzhuang** [comment]
@dragonsinth how you fix this issue by "manually setup our on-disk go.mod replace entries with bazel rules." can you share some code?

**Comment by dragonsinth** [comment]
@billzhuang so this issue is super outdated with the advent of `go.work`, which gazelle supports from the standpoint of rule generation.  Let me just detail what this looks like a little for one of my on-disk, forked dependencies, `cloud.google.com/go/datastore`.

So in `go.work`:
```go.work
go 1.18

use (
	./go/src/cloud.google.com/go/datastore
	[...]
```

Then our `WORKSPACE` pulls in a file, `local_repositories.bzl` which contains :
```bzl
# local_repositories installs the necessary on-disk third party repos we reference when building Go code.
def local_repositories():
    # gazelle:repository go_repository name=com_google_cloud_go_datastore importpath=cloud.google.com/go/datastore
    native.local_repository(
        name = "com_google_cloud_go_datastore",
        path = "./go/src/cloud.google.com/go/datastore",
    )
    [...]
```

I originally generated `local_repositories.bzl` from our old `go.mod` `replace` directives with a tiny tool.  There's a TODO to go back and rewrite that script to work against `go.work`, but we haven't really needed to update this in a while.

The `gazelle:repository` directive lets gazelle know that this is the proper repo for `cloud.google.com/go/datastore` so it'll use this for `@com_google_cloud_go_datastore` instead of generating one through `gazelle update-repos`.

The other missing piece is that you have to actually convert your on-disk dependency into a proper bazel workspace.  Within the on-disk repo, I have a stubbed out `WORKSPACE` file:
```bzl
workspace(
    name = "com_google_cloud_go_datastore",
)
```

Then the top level `BUILD.bazel` file looks like this:
```
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

# gazelle:proto disable_global
# gazelle:go_naming_convention import_alias
# gazelle:prefix cloud.google.com/go/datastore

[from here down generated by gazelle]
```

Compile yourself an external `gazelle` binary and then just run `gazelle fix .` within your on-disk repo to actually generate BUILD files, and check them in.

It is NOT important that your 3rd party repo be buildable as its own workspace!

Does not need to work:
```bash
~/project/go/src/cloud.google.com/go/datastore> bazel build //:all
ERROR: Skipping '//:all': while parsing '//:all': error loading package '': Unable to find package for @io_bazel_rules_go//go:def.bzl: The repository '@io_bazel_rules_go' could not be resolved: Repository '@io_bazel_rules_go' is not defined.
```

As long as this works:
```bash
~/project> bazel build @com_google_cloud_go_datastore//:all
INFO: Build completed successfully, 12 total actions
```

**Comment by dragonsinth** [comment]
@billzhuang here, I went ahead and updated our script for `go.work`: https://gist.github.com/dragonsinth/5204cee53950b490c6e646b4da70343b

Give this a whirl and let me know what you think.

**Comment by billzhuang** [comment]
hi @dragonsinth  tks for your help, but I still can not solve my issue, same error can not find the local module.
I created a sample proj [here](https://github.com/billzhuang/bazel-test), can you help to take a look?

**Comment by dragonsinth** [comment]
@billzhuang try this:
```diff
diff --git a/test-cmd/cmd/test/BUILD.bazel b/test-cmd/cmd/test/BUILD.bazel
index 0961341..40b1022 100644
--- a/test-cmd/cmd/test/BUILD.bazel
+++ b/test-cmd/cmd/test/BUILD.bazel
@@ -3,6 +3,7 @@ load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
 go_library(
     name = "test_lib",
     srcs = ["main.go"],
+    deps = ["@testlib_myrepo//log2"],
     importpath = "myrepo/testcmd/cmd/test",
     visibility = ["//visibility:private"],
 )
diff --git a/test-cmd/local_repositories.bzl b/test-cmd/local_repositories.bzl
index 8ebddf8..0fa22bc 100644
--- a/test-cmd/local_repositories.bzl
+++ b/test-cmd/local_repositories.bzl
@@ -1,6 +1,6 @@
 def local_repositories():
-    # gazelle:repository go_repository name=myrepo_testlib importpath=myrepo/testlib
+    # gazelle:repository go_repository name=testlib_myrepo importpath=myrepo/testlib
     native.local_repository(
-        name = "myrepo_testlib",
+        name = "testlib_myrepo",
         path = "../test-lib",
     )
```

The proximal problem is you're missing the dep.  I'm not 100% sure why gazelle didn't gen that dep for you, but it might be that your naming convention is wrong as far as naming the external repo.  Or it might be that you need to use `go.work` instead of go mod replace.
