### ISSUE TITLE
Feature proposal: run 'update-repos' with Bazel rule

### ISSUE THREAD

**Issue by ericnorris** [bazelbuild/bazel-gazelle#929]
It can become difficult to remember the exact incantation required in projects using gazelle's `update-repos` functionality with extra arguments, e.g.

```
bazel run //:gazelle -- update-repos -from_file go.mod -build_file_proto_mode disable_global -to_macro=repositories.bzl%go_repositories -prune=true
```

While the README states: "`update-repos` is not directly supported by the gazelle rule" and suggests something like the above command, I personally prefer the ease of using it as a bazel rule. In projects I've contributed to I've taken to making the following rules in a `scripts/BUILD.bazel` file:

```starlark
gazelle(name = "gazelle")

sh_binary(
    name = "generate-build-files",
    srcs = [":gazelle-runner"],
    args = ["-bazel_run"],
)

sh_binary(
    name = "generate-dependencies",
    srcs = [":gazelle-runner"],
    args = [
        "-bazel_run",
        "update-repos",
        "-from_file go.mod",
        "-build_file_proto_mode disable_global",
        "-to_macro=repositories.bzl%go_repositories",
        "-prune=true",
    ],
)
```

This allows me to then run `bazel run //scripts:generate-build-files` and `bazel run //scripts:generate-dependencies` instead of making a `Makefile` so that I don't have to remember the command.

While this works, it feels a little hacky and could break depending on how you implement the `:gazelle-runner` rule. I'd be open to making a separate `gazelle` rule or changing the current one in order to define this functionality, but wanted to open up an issue first to get thoughts on whether this is worth it and how it should be done.

**Comment by jayconrod** [comment]
A small change to the `gazelle` rule is needed, but something like this could work:

```
gazelle(
    name = "gazelle-update-repos",
    args = [
        "-from_file=go.mod",
        "-to_macro=deps.bzl%go_repositories",
        "-prune",
    ],
    command = "update-repos",
)
```

**Comment by ericnorris** [comment]
Thanks for the speedy response and PR @jayconrod! I'll try it out in my next bazel project.
