### ISSUE TITLE
How to import a package from a directory and another of a subdirectory?

### ISSUE THREAD

**Issue by janiskemper** [bazelbuild/bazel-gazelle#932]
I am using bazel update-repos from_file go.mod. I want to import both "github.com/xx/yy" and "github.com/xx/yy/zz". 

The problem is that for "github.com/xx/yy/zz" there is no additional entry in go.mod, so that no additional go_repository is created, but bazel now complains that there are no dependencies provided for this import. Does anybody have an idea how to solve this problem? 

Thank you in advance!

**Comment by jayconrod** [comment]
Is `github.com/xx/yy/zz` a separate module from `github.com/xx/yy/zz`?

If it's part of the same module, you don't need a separate `go_repository` declaration for it. `gazelle update` should add a dependency like `@com_github_xx_yy//zz` to the library that imports it.

If it's part of a different module, you can add a separate `go_repository` declaration with the command below:

```
bazel run //:gazelle -- update-repos github.com/xx/yy/zz
```

**Comment by janiskemper** [comment]
Thank you very much! ```gazelle update``` was everything I needed... Sorry for this basic question, but I am quite new to this ;)
