### ISSUE TITLE
Gazelle not working on honnef.co/go/tools

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel-gazelle#943]
### What versions are you using?

Bazel 3.5.0
rules_go-v0.24.4
bazel-gazelle-v0.22.2

### What did you do?

I was attempting to compose some go_tool_library rules for staticcheck for the purpose of #578 and found that Gazelle did not appear to run correctly on the repo. 

Repo with WORKSPACE / BUILD.bazel adding Gazelle rule:
https://github.com/robfig/go-tools

To reproduce:
```
$ git clone git@github.com:robfig/go-tools.git
$ cd go-tools
$ bazel run :gazelle
```

Running Gazelle produces error messages like this:
```
module honnef.co/go/tools@latest found (v0.0.1-2020.1.6), but does not contain package honnef.co/go/tools/go/ir
```

It seems like the `go_prefix` must be set incorrectly, but I have it configured like this in //BUILD.bazel:
```
# gazelle:prefix honnef.co/go/tools
```

and I also tried passing it as a command line argument.

The result of this error is that the rules incorrectly treat internal packages as external packages, e.g. 
```
go_tool_library(
    name = "staticcheck",
    srcs = [
        "analysis.go",
        "buildtag.go",
        "doc.go",
        "lint.go",
        "rules.go",
        "structtag.go",
    ],
    importpath = "honnef.co/go/tools/staticcheck",
    visibility = ["//visibility:public"],
    deps = [
        "@co_honnef_go_tools//go/types/typeutil:go_default_library",
        "@co_honnef_go_tools//internal/passes/buildir:go_default_library",
        "@co_honnef_go_tools//internal/sharedcheck:go_default_library",
        "@co_honnef_go_tools//pattern:go_default_library",
        "@co_honnef_go_tools//printf:go_default_library",
    ...
```

I feel like I must be missing something obvious, but I'm not seeing it.. any tips? 

Thank you

**Comment by jayconrod** [comment]
Seems to work after deleting the line:

```
# gazelle:map_kind go_library go_tool_library @io_bazel_rules_go//go:def.bzl
```

The kind mapping is applied before generated targets are added to the index, and since `AddRule` doesn't know about `go_tool_library`, it doesn't appear to be importable.

Tentatively marking as a bug. Mapped kinds should probably be importable if the original kinds were.

**Comment by robfig** [comment]
This is a pretty big gap in the map_kind implementation, apologies for missing it. Uploaded a PR to address it...
