### ISSUE TITLE
walk: add UpdateSubDirsMode

### ISSUE THREAD

**Issue by blico** [bazelbuild/bazel-gazelle#945]
Currently when `--index=false` and `--r=true` [Gazelle visits](https://github.com/bazelbuild/bazel-gazelle/blob/master/cmd/gazelle/fix-update.go#L123-L129) every directory in the repository and updates the passed in directories plus their subdirectories ([`walk.VisitAllUpdateSubdirsMode`](https://github.com/bazelbuild/bazel-gazelle/blob/master/walk/walk.go#L38-L41)).

In this scenario because `--index=false` there is no need to visit the entire repository, which is very expensive in large repos. Gazelle could support a new `walkMode`, `UpdateSubDirsMode` which behaves similarly to [`UpdateDirsMode`](https://github.com/bazelbuild/bazel-gazelle/blob/master/walk/walk.go#L47-L50) except it also updates the subdirectories of the dirs passed into Gazelle. This mode can be enabled when `--index-false` and `--r=true`, or alternatively a new flag could be added to enable this mode (e.g. `--updateSubDirs`).

**Comment by jayconrod** [comment]
I think this is just a bug: no need to introduce new flags.

Adding `walk.UpdateSubdirsMode` seems reasonable.
