### ISSUE TITLE
Is there a way to configure gazelle to use ssh endpoints instead of http?

### ISSUE THREAD

**Issue by danbosnichill** [bazelbuild/bazel-gazelle#946]
### What version of gazelle are you using?

v0.20.0

### What version of rules_go are you using?

v0.23.3

### What version of Bazel are you using?

3.2.0-homebrew

### Does this issue reproduce with the latest releases of all the above?

I didn't see any mention of the improvements in the release notes for v0.20.1 and v0.20.2.

### What operating system and processor architecture are you using?

Mac v10.15.5.   x86-64

### What did you do?

I don't know if this is a bug or a feature request.  Is there a way to get an ssh prefix automatically on the import path?  

Currently developers have to run `git config --global url."git@github.com:".insteadOf "https://github.com/"` to fix this.

gazelle currently generates this:

```
go_repository(
    name = "com_github_promotedai_schema",
    importpath = "github.com/promotedai/schema",
    sum = "h1:GdqB7w0ZRiRf5HSBXrI/dGwrOy12/KnLs2FkfmNmNBM=",
    version = "v0.0.0-20201024035926-be6153f03f6e",
)
```

I'd like gazelle to generate this:

```
go_repository(
    name = "com_github_promotedai_schema",
    importpath = "ssh://git@github.com/promotedai/schema",
    sum = "h1:GdqB7w0ZRiRf5HSBXrI/dGwrOy12/KnLs2FkfmNmNBM=",
    version = "v0.0.0-20201024035926-be6153f03f6e",
)
```

### What did you expect to see?

I expected a flag or argument for gazelle to do this.

### What did you see instead?

No flags.

**Comment by jayconrod** [comment]
Import paths match Go module paths, so they don't say much about how to retrieve a module.

It is possible to fetch a `go_repository` with Git over SSH though. Something like this:

```
go_repository(
    name = "com_github_promotedai_schema",
    importpath = "github.com/promotedai/schema",
    vcs = "git",
    remote = "ssh://git@github.com/promotedai/schema",
    commit = "be6153f03f6e",
)
```

See [`go_repository`](https://github.com/bazelbuild/bazel-gazelle/blob/master/repository.rst#go-repository) for details.

Gazelle won't generate a declaration like that automatically. In most cases, if you want something custom, you need to write it manually.

**Comment by danbosnichill** [comment]
Thanks!

**Comment by danbosnichill** [comment]
How can I get gazelle to ignore these lines or rule?  Gazelle seems to not recognize this syntax and it reverts the code.

**Comment by sluongng** [comment]
> How can I get gazelle to ignore these lines or rule? Gazelle seems to not recognize this syntax and it reverts the code.

Use `# gazelle:ignore` on that line

**Comment by uhthomas** [comment]
For the record, I imagine what you're looking for is https://github.com/bazelbuild/bazel-gazelle#keep-comments

**Comment by robfig** [comment]
Yes, I would use a `# keep` at the end of the line

**Comment by zachwalton** [comment]
Just another +1 for something like a (globally configurable) `ssh=True` flag. We have a monorepo with hundreds of `go_repository` rules referencing internal repos.

Currently we wrap bazel commands with Makefile targets to run:

`git config --global url."git@github.com:".insteadOf "https://github.com/"`

...since it would be cumbersome enough to hand-configure all of them with the suggested workaround that we'd end up extending gazelle to do it if we went that route (plus that route seems to require switching to commits instead of version tags...)

Having some sort of global way to force `go_repository` rules to SSH, in addition to a way to set `GOPRIVATE` which we're currently setting as a `--repo_env` flag, would mean 100% of our Go environment setup is handled by Gazelle.

**Comment by loeffel-io** [comment]
this works great 

```
    go_repository(
        name = "com_github_mindful_hq_global_proto_v2",
        importpath = "github.com/mindful-hq/global-proto/v2",
        remote = "ssh://git@github.com/mindful-hq/global-proto",  # keep
        vcs = "git",  # keep
        commit = "cb1e59d6b6b22bb9ea962bca18039540991a3264",  # keep # v2.8.3
    )
```

but after running gazelle it gets 

```
    go_repository(
        name = "com_github_mindful_hq_global_proto_v2",
        importpath = "github.com/mindful-hq/global-proto/v2",
        remote = "ssh://git@github.com/mindful-hq/global-proto",  # keep
        sum = "h1:5ybe1wUzTYI/ObQA6+Or3mpkLnhN+VAnDvd6BVtLc1I=",
        vcs = "git",  # keep
        version = "v2.8.3",
    )
```

which fails with

```
Error in fail: cannot specify both version and vcs
```

is there a good solution for this?
