### ISSUE TITLE
Expose parsed Go AST to other extensions

### ISSUE THREAD

**Issue by abhinav** [bazelbuild/bazel-gazelle#964]
### What version of gazelle are you using?

9c04579595ec9db9f11d1395e8c6266a3adc3a05

### What version of rules_go are you using?

v0.24.5

### What version of Bazel are you using?

```
Build label: 3.7.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Oct 20 13:31:07 2020 (1603200667)
Build timestamp: 1603200667
Build timestamp as int: 1603200667
```

### Does this issue reproduce with the latest releases of all the above?

Likely.

### What operating system and processor architecture are you using?

macOS, x86_64

### What did you do?

I'm attempting to write a Gazelle extension for a Go code generator.
The extension needs to inspect the Go AST to generate the rules.

### What did you expect to see?

A means of accessing the already-parsed Go AST for the extension to inspect.

### What did you see instead?

The extension had to re-parse the directory of Go files.

---

I was hoping for the [AST parsed by the Go extension](https://github.com/bazelbuild/bazel-gazelle/blob/a2c86baacd1cb24e79320aa7157c25ed7d4090ab/language/go/fileinfo.go#L280) to be made available to other extensions via [private attributes](https://godoc.org/github.com/bazelbuild/bazel-gazelle/rule#Rule.SetPrivateAttr) similar to how the [protobuf extension exposes metadata](https://github.com/bazelbuild/bazel-gazelle/blob/a2c86baacd1cb24e79320aa7157c25ed7d4090ab/language/proto/generate.go#L226). This would be an improvement to the overall runtime for extensions which need to read the AST.

**Comment by jayconrod** [comment]
I'd rather not expose the metadata the Go extension reads from source files. It's an implementation detail that could change over time.

Currently, Gazelle only reads the import declarations from each file. It doesn't read or parse entire files. So that might not even be enough for your use case. The representation of information may change over time as well, if the new build directives or `//go:embed` directives are supported in the future.

**Comment by abhinav** [comment]
Valid points. Thanks.
