### ISSUE TITLE
duplicate go_repository rules are now rejected

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel-gazelle#968]
### What version of gazelle are you using?

0.22.2

### What version of rules_go are you using?

0.25.0

### What version of Bazel are you using?

3.6

As of some recent gazelle version (probably whatever picked up https://github.com/bazelbuild/bazel-gazelle/pull/855), duplicate go_repository rules are rejected in at least some combinations that were previously accepted.

The error will be reported as "multiple rules have the name %s". There turns out to be a range of scenarios where this can occur which are arguably incorrect. I have only partially debugged it so far, so I'm going to be a bit vague about what those scenarios are, but it includes things like:

- The WORKSPACE file includes both repositories defined in external _deps() functions and in go_dependencies.bzl generated by gazelle update-repos
- Some of those repository names match, and the ordering in WORKSPACE has been arranged so that gazelle's definitions override the previous ones.
- gazelle is told to only update go_dependencies.bzl

I believe this scenario should be accepted by gazelle, and currently (at least in some combinations, details TBD) it is rejected. Another similar scenario is where a `# gazelle:repository ` line is overriding something generated in go_dependencies.bzl.

I suspect, but have not yet proved, that this is happening because of the collapsing of definitions into @bazel_gazelle_go_repository_config losing information. Certainly in the cases I'm working on debugging there are two entries in that config which are literal duplicates of each other. My working hypothesis is that generate_repo_config is misinterpreting these scenarios as duplicate rules.

I'll do some more debugging tomorrow, but I figured I'd dump my work so far into this issue in case the problem is immediately obvious to you.

**Comment by jayconrod** [comment]
Gazelle reports this error if there are multiple targets with the same `name` attribute in a file that Gazelle is updating. For `update-repos`, that would be `WORKSPACE` or a macro declared with `# gazelle:repository_macro`. It shouldn't be any other file updated by Gazelle.

This error is definitely necessary: if there are multiple targets with the same name, Gazelle won't know which ones to update or delete. If it's being reported in a situation other than what's intended though, please post more info.

**Comment by asuffield** [comment]
I didn't make a huge amount of progress on debugging it yesterday, but I believe the key detail to understand is:

I'm getting this error about the file `external/bazel_gazelle_go_repository_config/WORKSPACE` containing duplicate entries (and it does).

There's no real concern with gazelle being unable to update that file, and duplicates are notionally fine there - but I suspect the bug is actually in generate_repo_config.

**Comment by jayconrod** [comment]
Hmm, that's probably enough to mark this as a bug. `generate_repo_config` doesn't protect against multiple repositories being declared with the same name. It should.

**Comment by asuffield** [comment]
That would explain it then. I've got some free time tomorrow, I'll try to work out the details. It's not wrong for there to be duplicates in the input of `generate_repo_config`,  but the correct behaviour is probably to simulate what bazel does to pick the right one, which is annoyingly complicated.

**Comment by jayconrod** [comment]
> the correct behaviour is probably to simulate what bazel does to pick the right one, which is annoyingly complicated.

Thanks for looking at this. I'd just say pick the last repo with any given name. It should take precedence over earlier declarations, as long as no labels inside them are resolved, but that's way too complicated for Gazelle to model.
