### ISSUE TITLE
Line seperator of gazelle should be configurable

### ISSUE THREAD

**Issue by JohnnyS318** [bazelbuild/bazel-gazelle#969]
### What version of gazelle are you using?
v0.22.2

### What version of rules_go are you using?
v0.25.0

### What version of Bazel are you using?
[docker.log](https://github.com/bazelbuild/bazel-gazelle/files/5705463/docker.log)

3.7.1

### Does this issue reproduce with the latest releases of all the above?
Yes these are the latest releases until now

### What operating system and processor architecture are you using?
Windows x64 amd64.

### What did you do?
I updated BUILD.bazel files using `gazelle update`.

### What did you expect to see?
Changed BUILD.bazel files should be a unstaged change in git, but already up to date BUILD files should not change

### What did you see instead?
Every BUILD  file was added to the unstaged changes list of git. This is due to the line separator which is was changed to LF by gazelle from CRLF which is the default of Windows. I would like to ask if a configuration for gazelle would be possible to change the applied line seperator.

**Comment by jayconrod** [comment]
Sorry, this is working as intended. Gazelle uses the same library as buildifier to parse and format build files ([github.com/bazelbuild/buildtools/build](https://pkg.go.dev/github.com/bazelbuild/buildtools/build)), and they intentionally canonicalize line endings (bazelbuild/buildtools#914). It looks like gofmt does the same thing as well for go files.
