### ISSUE TITLE
[Question] Emitting a macro call as a dependency

### ISSUE THREAD

**Issue by wolfd** [bazelbuild/bazel-gazelle#978]
### What version of gazelle are you using?
v0.22.0

### What version of rules_go are you using?
v0.24.2

### What version of Bazel are you using?
3.5.0

I'm writing a custom gazelle language extension for Python, and one pattern that all the python pip rule systems use is to hide repository names of installed pip packages behind a call to a `requirement` macro.

```py
load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("@pip3//:requirements.bzl", "requirement")

py_library(
    name = "mylibrary",
    srcs = [
        "__init__.py",
        "fun.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//other/label",
        requirement("numpy"),
    ],
)
```
I was able to make the py_library look correct using the `BzlExprValue` interface:
```go
// RequirementMacroExpr implements gazelle's BzlExprValue interface so that rule.SetAttr can
// write out requirement macros
type RequirementMacroExpr struct {
	pypiName string
}

// BzlExpr gets the starlark AST node for a requirement macro (e.g. `requirement("pypiName")`)
func (req *RequirementMacroExpr) BzlExpr() bzl.Expr {
	return &bzl.CallExpr{
		X:    &bzl.Ident{Name: "requirement"},
		List: []bzl.Expr{&bzl.StringExpr{Value: req.pypiName}},
	}
}
```

I've got the requirement macro call working, _but_ the symbol isn't `load`ed into the build file. I was hoping that `FixLoads` would magically somehow see the identifier and match it to the `rule.LoadInfo` I have for `requirement`, but it seems to only iterate on the rules in a file, which seems reasonable for all existing language plugins.

In essence, I'd like to have gazelle load the `requirement` symbol as it does for rules, but I'm not sure how to do that. Any suggestions? If need be, I would be happy to upstream changes necessary to `merger/fix.go`'s `FixLoads` function.

**Comment by jayconrod** [comment]
I think this would probably work with some modification to `merger.FixLoads`. The main issue is that it just looks at the kinds for top-level rules (call expressions). For this to work, it would need to walk the whole syntax tree looking for calls. That's easy enough with [`build.Walk`](https://pkg.go.dev/github.com/bazelbuild/buildtools/build#Walk). I'd accept a PR that adds that.

Beyond that, I think you'd just need to include `requirement` in the `LoadInfo` for your extension.

**Comment by wolfd** [comment]
I think the right way to solve this is to avoid it altogether. I was mostly through a change that allowed gazelle to sort lists with expressions of this style, but can't really justify the extra complexity there.

My plan is to go down a path that's similar to what gazelle go does with update-repos.
