### ISSUE TITLE
Ability to specify global arguments for go_binary

### ISSUE THREAD

**Issue by astratto** [bazelbuild/bazel-gazelle#98]
Please let me know if this is already possible, but I couldn't find a way to do it.

In my specific scenario, I'd like to be able to configure global `x_defs` that will be passed as attributes of `go_binary` in all the generated `BUILD.bazel`.

The reason for this is that Bazel allows specifying a `--workspace_status_command` to set the variables, but `x_defs` attributes still need to be specified in the various build files.

The idea can be generalized to be able to pass custom overrides that gazelle would then apply to each generated file.

**Comment by jayconrod** [comment]
You can use [buildozer](https://github.com/bazelbuild/buildtools/tree/master/buildozer), which is a general build file modification tool.

Something like this should work (haven't tested, might require some tweaking)

```
$ rules=$(bazel query 'kind(go_binary, //...)')
$ buildozer 'add x_defs A B C' $rules
```

Replace `A B C` with the `x_defs` flags that should be set.

**Comment by ianthehat** [comment]
It's also probable that you don't want to do this.

If you explain what you are trying to achieve I could offer more advice, but it's normally better to have a single library that has the x_def's on it and then depend on that library from all the targets that care about the value, so the x_def is in just one place.

**Comment by astratto** [comment]
Thanks for the replies!

I'm planning on using `x_defs` to add common stamping to sub-projects in a pretty big monorepo.
Stamping a single shared library would be great idea, but there isn't one.

On the positive side, the `x_defs` are going to be common to all the sub-projects.
Also, `BUILD.bazel` files are generated on the fly for those projects, so I would still control everything from one single place.

Any advice is very much appreciated!

**Comment by ianthehat** [comment]
I'm saying make a new package, who's sole job is to hold the stamped values, and make all the other packages use that one to get the values.

The stamping is not done at the time the library is built, it's just propagated up the dependency graph to the place where final linking is done, and then stamping happens there, so it will not cause massive graph rebuilds or anything.

**Comment by astratto** [comment]
Interesting! I'll try that, thanks Ian!

On a related note, do you know if/how stamping in that way can affect remote caching?

**Comment by ianthehat** [comment]
The stamp files count as inputs, if they are different, the cache key will change for the rules that actually apply stamping (so the final binaries or tests)
Because we never apply stamping at the library level, they will never be affected by it and thus get cache hits as per normal.

**Comment by astratto** [comment]
Brilliant! That's what I was expecting, so it's perfect.
I've just tried on a widely shared library and it works.

I'm closing this, thanks!

**Comment by ly0511** [comment]
@astratto  I encountered the same problem, and I also hope that bazel_gazelle can pass custom overrides instead of changing BUILD.bazel. How did you deal with it?
I hope that git commit and tag information can be added to the compilation
