### ISSUE TITLE
'runtime' not declared in package 'runtime' defined by com_github_grpc_ecosystem_grpc_gateway_v2/runtime/BUILD.bazel

### ISSUE THREAD

**Issue by jextrevor** [bazelbuild/bazel-gazelle#980]
### What version of gazelle are you using?

v0.22.3

### What version of rules_go are you using?

v0.25.1

### What version of Bazel are you using?

3.7.2-homebrew

### Does this issue reproduce with the latest releases of all the above?

Yes, I believe these are the latest releases

### What operating system and processor architecture are you using?

Mac OS Catalina (10.15.6), x64

### What did you do?

Attempted to build a go project that depends on github.com/grpc-ecosystem/grpc-gateway/v2/runtime. From what I can tell this is similar to https://github.com/bazelbuild/bazel-gazelle/issues/788 but not quite the same. To update the WORKSPACE, I've been using `bazel run //:gazelle -- update-repos -from_file=go.mod` which adds/updates `go_repository` entries in the WORKSPACE file.

### What did you expect to see?

I expected to see the build finish correctly.

### What did you see instead?

```
ERROR: [redacted]/BUILD:3:11: no such target '@com_github_grpc_ecosystem_grpc_gateway_v2//runtime:runtime': target 'runtime' not declared in package 'runtime' defined by /private/var/tmp/_bazel_[redacted]/68f810b3004981eeee4304146a9267f2/external/com_github_grpc_ecosystem_grpc_gateway_v2/runtime/BUILD.bazel and referenced by '//proto/api:api'
```

Please let me know if I can provide any more info that will be helpful. I'm not the most comfortable/experienced with Bazel/Gazelle.

Thanks!

**Comment by jayconrod** [comment]
You're likely running into the issue described in #890 and #982. `com_github_grpc_ecossytem_grpc_gateway_v2` has its own build files following the `go_default_library` (legacy) naming convention, and that's not known to other repositories (including the main repository).

You may be able to resolve this by adding `build_naming_convention` to that `go_repository` declaration.

```
go_repository(
    name = "com_github_grpc_ecossytem_grpc_gateway_v2",
    build_naming_convention = "go_default_library",
    ...
)
```
