### ISSUE TITLE
go_repository: build_naming_convention not included in configuration file derived from WORKSPACE

### ISSUE THREAD

**Issue by ericnorris** [bazelbuild/bazel-gazelle#982]
### What version of gazelle are you using?

```
v0.22.3
```

### What version of rules_go are you using?

```
v0.24.8
```

### What version of Bazel are you using?

```
bazel version
Build label: 3.3.1- (@non-git)
```

### Does this issue reproduce with the latest releases of all the above?

I believe I have the latest version of `gazelle` at the time of writing; I cannot test with the latest version of `rules_go` at the moment but do not believe that would fix this issue.

### What operating system and processor architecture are you using?

Mac OS X, amd64

### What did you do?

I am writing a [bazel rule](https://github.com/ericnorris/rules_nfpm) for packaging binaries with https://github.com/goreleaser/nfpm, and decided to upgrade to the latest possible version of `rules_go` and `gazelle` given my current `bazel` version.

I ran `bazel test //go/...` within the repository after generating fresh `go_repository` rules and `BUILD.bazel` files with `gazelle`. The `go.mod` dependencies used to generate the `go_repository` rules are:

```
require (
        github.com/alecthomas/kong v0.2.9
        github.com/google/go-cmp v0.5.4
        github.com/goreleaser/nfpm/v2 v2.2.2
        github.com/pkg/errors v0.9.1
)
```

### What did you expect to see?

I expected it to build successfully (and run tests).

### What did you see instead?

```
5989:rules_nfpm enorris$ bazel test //go/...
ERROR: /private/var/tmp/_bazel_enorris/ee9c8349744c26493607e23cdbefccba/external/com_github_goreleaser_nfpm_v2/rpm/BUILD.bazel:3:11: no such target '@com_github_google_rpmpack//:rpmpack': target 'rpmpack' not declared in package '' defined by /private/var/tmp/_bazel_enorris/ee9c8349744c26493607e23cdbefccba/external/com_github_google_rpmpack/BUILD.bazel and referenced by '@com_github_goreleaser_nfpm_v2//rpm:rpm'
ERROR: Analysis of target '//go/internal/cmd/nfpmwrapper:nfpmwrapper' failed; build aborted: Analysis failed
```

### Workaround

I believe this issue is due to a transitive dependency of `nfpm` having its own `BUILD.bazel` file (https://github.com/google/rpmpack/blob/master/BUILD.bazel) and Gazelle is unable to determine what `go_naming_convention` to use. It defaults to `import`, and expects to see a `rpmpack` target, when in reality the `BUILD.bazel` file defines a `go_default_library` target.

I was able to fix this by adding `-build_directives "gazelle:go_naming_convention_external go_default_library"` to my `gazelle update-repos` command arguments, but this doesn't seem like the right solution; I expect (perhaps mistakenly) `gazelle` to either know the external BUILD file's naming convention, or maybe to generate a new one and ignore it. Either way it feels wrong that I would need to explicitly annotate the expected naming convention of my dependencies' dependencies. You're welcome to close this issue if that feeling is misplaced.

This may be related to #980, but I'm not sure.

**Edit:** Originally I had mistakenly thought that adding `-build_directives "gazelle:go_naming_convention_external import_alias"` was what had fixed this problem, but it seems that `gazelle` wasn't actually changing the `build_directives` argument when I changed this parameter and re-ran `update-repos`. This is reproducible for me: adding a `-build_directives` argument with `update-repos`, and then changing the `-build_directives` argument with `update-repos` will leave the generated `go_repository` rules intact. I can file a separate issue for this if needed.

**Comment by jayconrod** [comment]
Sorry, I don't think it's feasible to fix this. If each instance of `go_repository` fetched transitive dependencies, it would slow things down quite a bit. If the naming convention is different than the default, it needs to be declared ahead of time in `WORKSPACE` or in a function referenced by `# gazelle:repository_macro` or in a file referenced by the `go_repository_default_config` parameter to `gazelle_dependencies`. The declaration may be a `go_repository` with `build_naming_convention` set, or it may be a `# gazelle:repository` directive.

#890 is a related issue to set `build_naming_convention` automatically. Not sure if that's feasible; it would make `update-repos` quite a bit slower.

**Comment by ericnorris** [comment]
@jayconrod thanks as always for the quick response.

If I understand correctly (ignoring the current `go_naming_convention_external` directive in the below snippets):

- Gazelle **will** generate a BUILD file for this repository: https://github.com/ericnorris/rules_nfpm/blob/b4bad369fc2f98b1fef6ab74beb6cf30ede8654b/nfpm/go_repositories.bzl#L738-L744
  - when it generates a BUILD file for this repository it will reference `@com_github_google_rpmpack//:rpmpack` by default
- Gazelle **will not** generate a BUILD file for this repository https://github.com/ericnorris/rules_nfpm/blob/b4bad369fc2f98b1fef6ab74beb6cf30ede8654b/nfpm/go_repositories.bzl#L687-L693
  - this BUILD file declares a `go_default_library` target, not an `rpmpack` target

I tried changing `build_naming_convention = "go_default_library",` in the `com_github_google_rpmpack` repository but (not surprisingly) that did not fix the issue, as the `go_repository` for `com_github_goreleaser_nfpm_v2` still doesn't know about that when it is generating its own BUILD file. Setting `build_file_generation = "on",` for `com_github_google_rpmpack` obviously fixed this, because now `gazelle` generates BUILD files in the rpmpack repository with the expected naming convention.

I don't think it is safe for the `com_github_goreleaser_nfpm_v2` repository to assume that its linked repositories will follow the default naming convention; historically the default has been `go_default_library` _without_ any sort of directive, and so I assume most repositories that _do_ contain `BUILD` files will in fact have `go_default_library` targets (my existing projects certainly do).

I think I see what you mean by downloading transitive dependencies, if the `com_github_goreleaser_nfpm_v2` repository downloaded its transitive dependencies it could try to determine their build naming convention mode, but agree that would be untenable.

That being the case, I'm not sure what the answer should be. I worry about a future where I need to explicitly annotate many individual `go_repository` rules with their external build naming conventions, or worse, a (possible?) situation where `com_github_goreleaser_nfpm_v2` depends on two libraries with _different_ build naming conventions and `go_naming_convention_external` does not work.

Is it possible to have some sort of a conditional dependency target, i.e. `import_alias` but in reverse? If `com_github_goreleaser_nfpm_v2` could say "I depend on the `rpmpack` target if it exists, but `go_default_library` if it does not", I believe this would work for past and future repositories.

Appreciate your time working on `gazelle` and `rules_go`, and I'm happy to move the discussion to #890 if that makes more sense.

**Comment by jayconrod** [comment]
> Gazelle will generate a BUILD file for this repository: https://github.com/ericnorris/rules_nfpm/blob/b4bad369fc2f98b1fef6ab74beb6cf30ede8654b/nfpm/go_repositories.bzl#L738-L744
when it generates a BUILD file for this repository it will reference @com_github_google_rpmpack//:rpmpack by default

I think it should reference `@com_github_google_rpmpack//:go_default_library` instead because of the `gazelle:go_naming_convention_external` setting. I didn't verify that, and it's possible I'm missing something though.

> I don't think it is safe for the com_github_goreleaser_nfpm_v2 repository to assume that its linked repositories will follow the default naming convention; historically the default has been go_default_library without any sort of directive, and so I assume most repositories that do contain BUILD files will in fact have go_default_library targets (my existing projects certainly do).

Ideally they should generate targets with the `import_alias` naming convention. That would let their users refer to targets using either convention. Eventually, when no one is using `go_default_library` anymore, they could switch to `import` and delete the aliases.

> That being the case, I'm not sure what the answer should be. I worry about a future where I need to explicitly annotate many individual go_repository rules with their external build naming conventions, or ...

This seems bad but not terrible. It's only necessary for repositories with build files that haven't updated to the new convention. #890 would add those annotations automatically. It might be slow, but if the downloads are cached, it would only be slow the first time.

> Is it possible to have some sort of a conditional dependency target, i.e. import_alias but in reverse? If com_github_goreleaser_nfpm_v2 could say "I depend on the rpmpack target if it exists, but go_default_library if it does not", I believe this would work for past and future repositories.

Sorry, I don't think there's anyway to refer to a target that doesn't exist.

**Comment by ericnorris** [comment]
> I think it should reference @com_github_google_rpmpack//:go_default_library instead because of the gazelle:go_naming_convention_external setting. I didn't verify that, and it's possible I'm missing something though.

You are correct, I was trying to outline what would happen if you pretended the directive wasn't there, to confirm my understanding of what was happening.

> Ideally they should generate targets with the import_alias naming convention. That would let their users refer to targets using either convention. Eventually, when no one is using go_default_library anymore, they could switch to import and delete the aliases.

I agree! But there's probably a decent number of completed projects out there that aren't going to have their BUILD files updated, and will always have `go_default_library`.

> This seems bad but not terrible. It's only necessary for repositories with build files that haven't updated to the new convention. #890 would add those annotations automatically. It might be slow, but if the downloads are cached, it would only be slow the first time.

I don't _think_ #890 would fix that, because the problem is that when generating repository A's BUILD file, gazelle doesn't (can't?) know what repository B's BUILD file's naming convention will be. In my previous comment, when I added the `build_naming_convention` by hand for the `com_github_google_rpmpack` `go_repository` rule, the problem still existed. This would only be fixed if:

- Somehow when generating the BUILD files for repository A, it checked to see that the `go_naming_convention` was for the dependent repository B. Is this possible? I have both repositories defined in my WORKSPACE, so presumably gazelle could figure that out. That would mean adding the `build_naming_convention` by hand for individual repositories would suffice, and I agree that might be not terrible. To be clear this does not work currently, per above.
- If `update-repos` downloaded transitive dependencies, it could then set the `go_naming_convention_external` on repository A, since it could download and determine repository B's naming convention. There may be some conflict though, if repository A depended on two projects with separate build naming conventions... I'm genuinely not sure what would happen there, would the project be unbuildable? I also don't like this option, as we've discussed.

> Sorry, I don't think there's anyway to refer to a target that doesn't exist.

That's a shame! But understood.

---

I think given my understanding, the former point that I raised in the two options seems like a fine solution; if, when generating BUILD files, gazelle could check the dependent `go_repository` rules for what their `build_naming_convention` was (which does not require downloading the dependency), you could manually annotate the naming convention for the projects that include BUILD files. I suppose if `update-repos` downloaded the repository it could then automatically determine the `build_naming_convention` without needing to note it by hand, and then everything goes back to being as automatic as it once was.

A decent chunk of this is abstract, so hopefully I've used the right terminology here and it's clear what I am proposing, let me know if I can clarify anything a bit more.

**Comment by jayconrod** [comment]
(Sorry to be slow to respond; things are busy this week as we resolve release blockers ahead of Go 1.16rc1).

> Somehow when generating the BUILD files for repository A, it checked to see that the go_naming_convention was for the dependent repository B. Is this possible? I have both repositories defined in my WORKSPACE, so presumably gazelle could figure that out. That would mean adding the build_naming_convention by hand for individual repositories would suffice, and I agree that might be not terrible. To be clear this does not work currently, per above.

This is pretty close to what #890 proposes. When you run `gazelle update-repos example.com/mod`, it would download `example.com/mod` (hopefully hitting the cache), then check if there's a build files in the root directory and maybe immediate subdirectories. If there are, it would infer the naming convention in use and set `build_naming_convention` on the updated `go_repository` rule. We have code to infer the naming convention already; it just needs to be adapted.

Other `go_repository` modules with generated build files already resolve dependcies using `build_naming_convention`, so I think that's all that would need to be done.

> If update-repos downloaded transitive dependencies, it could then set the go_naming_convention_external on repository A, since it could download and determine repository B's naming convention. There may be some conflict though, if repository A depended on two projects with separate build naming conventions... I'm genuinely not sure what would happen there, would the project be unbuildable? I also don't like this option, as we've discussed.

To the extent possible, it's important that the naming convention is set on the repository where targets are defined. Repositories where those targets are used shouldn't need to do anything special. Setting `go_naming_convention_external` on each repo could lead to inconsistency.

(To explain a bit more, when `go_repository` invokes Gazelle, it passes in a configuration file derived from the `WORKSPACE` file in the main repo. So it should see `build_naming_convention` for all the other declared `go_repository` modules).

**Comment by ericnorris** [comment]
@jayconrod no worries, I appreciate your time!

> Other go_repository modules with generated build files already resolve dependcies using build_naming_convention, so I think that's all that would need to be done.

This is not the behavior I'm seeing with the latest `rules_go` and `gazelle`, but maybe I am mistaken on what we're talking about.

When I have the below `go_repository` defined:

```
go_repository(
    name = "com_github_google_rpmpack",
    build_naming_convention = "go_default_library",
    importpath = "github.com/google/rpmpack",
    sum = "h1:jyGRCFMyDK/gKe6QRZQWci5+wEUBFElvxLHs3iwO3hY=",
    version = "v0.0.0-20201225075926-0a97c2c4b688",
)
```

I still get the same error:

```
ERROR: /private/var/tmp/_bazel_enorris/ee9c8349744c26493607e23cdbefccba/external/com_github_goreleaser_nfpm_v2/rpm/BUILD.bazel:3:11: no such target '@com_github_google_rpmpack//:rpmpack': target 'rpmpack' not declared in package '' defined by /private/var/tmp/_bazel_enorris/ee9c8349744c26493607e23cdbefccba/external/com_github_google_rpmpack/BUILD.bazel and referenced by '@com_github_goreleaser_nfpm_v2//rpm:rpm'
ERROR: Analysis of target '//go/cmd/nfpmwrapper:nfpmwrapper' failed; build aborted: Analysis failed
```

It seems that the BUILD file for `com_github_goreleaser_nfpm_v2` is not aware of the `build_naming_convention` that I set on `com_github_google_rpmpack`. Am I correct in assuming that this is supposed to work? Your follow-up clarification makes it seem that way, but again, it doesn't seem to work for me.

I am _only_ able to get this to work by setting `go_naming_convention_external` on `com_github_goreleaser_nfpm_v2`.

Now that I've typed this though, I'll note that I have a special case: since I am defining a bazel rule that depends on `rules_go` and `gazelle`, I use `maybe` along with `go_repository` in order to avoid conflicts. See https://github.com/ericnorris/rules_nfpm/blob/b4bad369fc2f98b1fef6ab74beb6cf30ede8654b/nfpm/go_repositories.bzl#L1. I'll try to reproduce a standalone case to confirm this isn't a problem specific to me.

**Comment by jayconrod** [comment]
Ah, ok, I was able to reproduce this. Looks like this is a bug in Gazelle after all; sorry for misleading you.

The configuration file generated from `WORKSPACE` doesn't include the `build_naming_convention` attribute for declared `go_repository` rules. It should.

**Comment by ericnorris** [comment]
Thanks! Good to hear it wasn't something on my end.

With this being fixed, I agree that having `gazelle` try to determine the `build_naming_convention` in `update-repos` is desirable. I'll follow #890 for that.
