### ISSUE TITLE
update-repos: Keep repositories in non-module mode

### ISSUE THREAD

**Issue by tommyknows** [bazelbuild/bazel-gazelle#984]
### What version of gazelle are you using?

`v0.22.3`

### What version of rules_go are you using?

`v0.24.10`

### What version of Bazel are you using?

`3.7.2`

### Does this issue reproduce with the latest releases of all the above?

I haven't tried to be honest, but I'm almost 100% sure it does :-)

### What operating system and processor architecture are you using?

not relevant.

### What did you do?

Depending on `github.com/docker/docker` is a pain - see https://github.com/bazelbuild/bazel-gazelle/issues/902, https://github.com/moby/moby/issues/41503, https://github.com/moby/moby/issues/41191, https://github.com/golang/go/issues/28489 and many more :-)

As described in #902, we're importing github.com/docker/docker, but after fetching the repository, I get issues from transitive dependencies (mostly other docker / moby projects like libnetwork) about the Sirupsen / sirupsen import path. I tried various fixes, nothing worked so far. This issue pollutes our CI output and would break builds (if we would need the dependencies).

The only thing that helped is changing the go_repository of com_github_docker_docker to download through git (by specifying the commit instead of the version & sum) and using build_external = "vendored". Gazelle then appears to be honoring the vendor directory.

However, the issue is that as part of my workflow, I'm running `gazelle update-repos -from_file=go.mod -prune=true`. 
This is a working version of the dependency, before running the command:

```bzl
go_repository(
    name = "com_github_docker_docker",
    build_external = "vendored",
    build_file_proto_mode = "disable_global",
    commit = "8891c58a433a823ce0a65b57efff45f32ee9cb45",  # keep
    importpath = "github.com/docker/docker",
)
```
(I do have `build_file_proto_mode` disabled globally)

After running `update-repos`, Gazelle adds the `sum` and `version` to the repository - breaking the resolution:

```
Error in fail: attribute version: cannot specify both commit and version
```

I understand the general dislike of vendor-directories and I'd be super happy if I wouldn't need to use it either. However, we've spent way too much time on this dependency issue already, for something that technically doesn't break our builds (it just adds 7000 lines of output to our CI pipeline, which is super annoying). 

### What did you expect to see?

Gazelle not touching my `go_repository` definition, allowing me to keep the git mode.

### What did you see instead?

Gazelle changed the Go repository to:
```
go_repository(
    name = "com_github_docker_docker",
    build_external = "vendored",
    build_file_proto_mode = "disable_global",
    importpath = "github.com/docker/docker",
    sum = "h1:vFgEHPqWBTp4pTjdLwjAA4bSo3gvIGOYwuJTlEjVBCw=",
    version = "v20.10.2+incompatible",
    commit = "8891c58a433a823ce0a65b57efff45f32ee9cb45", # keep
)
```

Yes, I know that the issue above is because the commit has the `#keep` attribute set. But downloading it through module-module discards the vendor directory and breaks everything again.

----------
In general, our issue stems from multiple other issues:
- Obviously, Docker and their dependency management
- Gazelle "fixing" the `go_repository` definition, even if I don't want it to
- `update-repos` running `go list -m -json all` (https://github.com/bazelbuild/bazel-gazelle/issues/547) 

I know that the first one will probably never be fixed. The third one may not be an issue at all, but expected behaviour. I don't think that can be changed (?). That's why I'd like to address this through the second option, telling Gazelle not to touch my definition.

**Comment by jayconrod** [comment]
Why not put the `# keep` above the `go_repository` declaration, rather than on a specific attribute? That will prevent Gazelle from modifying it, which sounds like what you want.

Going forward `update-repos`, won't support anything other than module mode, so if you need to fetch something in HTTP or VCS mode, the `go_repository` declaration will need to be written manually.

**Comment by tommyknows** [comment]
Duh, yes that would work. Thanks for the pointer & sorry, completely missed that.

> Going forward update-repos, won't support anything other than module mode, so if you need to fetch something in HTTP or VCS mode, the go_repository declaration will need to be written manually.

I already wrote it manually; or rather I copy-pasted the module-mode definition and replaced it with the commit hash.
Is that what you mean? If so, that's completely okay for me 😄 
(Is there a way to generate the VCS mode declaration for just a single repo with `update-repos`?)

Thanks again - I guess this can be closed then.

**Comment by jayconrod** [comment]
> I already wrote it manually; or rather I copy-pasted the module-mode definition and replaced it with the commit hash.
Is that what you mean? If so, that's completely okay for me 😄

Yep, exactly that.

> Is there a way to generate the VCS mode declaration for just a single repo with update-repos?

Afraid not.

For most modules, if you need a specific commit from the repo, you can do something like `gazelle update-repos example.com/mod@01234abcdef`: the argument is something that could be passed to `go mod download`.

Modules that don't work with that likely need to be fixed upstream. In Go 1.16 (which should be out in a couple weeks), module mode will be enabled by default, so they won't even work with `go build` without some intervention.
