### ISSUE TITLE
Gazelle unable to handle Google's Tink crypto library 

### ISSUE THREAD

**Issue by efagerho** [bazelbuild/bazel-gazelle#993]
### Does this issue reproduce with the latest releases of all the above?

Yes.

### What operating system and processor architecture are you using?

MacOS Big Sur

### What did you do?

I'm trying to use Google's Tink crypto library in a Go project. It looks like Gazelle is not able to handle the package. I've created a minimal repository that reproduces the problem:

https://github.com/efagerho/tinktest

The deps.bzl file contains the go_repository() dependency created by Gazelle. The repository seems to contain two
WORKSPACE files. One in the repository root and another in go/

Making the dependency work seems to require manual intervention, but it's not clear what the fix should be. It looks like go_repository() complains if trying to use strip_prefix to remove the "go" directory.

**Comment by achew22** [comment]
Thanks for the repro repo! Out of curiosity, what is the actual error you're getting and what command are you invoking to receive it?

**Comment by efagerho** [comment]
The following reproduces the problem in my repo:

```
% rm deps.bzl src/BUILD.bazel && touch deps.bzl && gazelle update-repos -from_file=go.mod -to_macro=deps.bzl%go_dependencies && gazelle && bazel build //src/...
ERROR: /Users/edvard.fagerholm/git/tinktest/src/BUILD.bazel:3:11: no such package '@com_github_google_tink//go/keyset': BUILD file not found in directory 'go/keyset' of external repository @com_github_google_tink. Add a BUILD file to a directory to mark it as a package. and referenced by '//src:src_lib'
ERROR: Analysis of target '//src:src_lib' failed; build aborted: Analysis failed
INFO: Elapsed time: 1,614s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 5 targets configured)
    Fetching @local_config_xcode; fetching

```

**Comment by achew22** [comment]
@efagerho did you try just including it as a `git_repository` by chance? It looks like it might already have `BUILD` files that are correct. For example https://github.com/google/tink/blob/master/go/keyset/BUILD.bazel. Also, could you try setting `build_file_generation = False` in your `deps.bzl` and see if that helps? I would have expected the default value of `auto` to fix it, but maybe it didn't.

**Comment by jayconrod** [comment]
Sorry for the delay looking at this. There are a couple problems here.

@efagerho As you pointed out, the Go module in a `go` subdirectory. That means in your `go.mod` file and in your `go_repository` rule need to reference the full module path including that subdirectory (`github.com/google/tink/go`).

As @achew22 points out though, this repository already has Bazel build files, so `go_repository` likely won't work. `git_repository` or `http_archive` may be a better starting point. I tried to get it to build, but they have their own dependencies like the `tink_base` repo, and I'm not sure where those are declared. They have [Go instructions](https://github.com/google/tink/blob/master/docs/GOLANG-HOWTO.md), but they don't cover using Tink as a dependency from your own repo.

I think your best bet is to ask over at that project how this is supposed to work.
